### ISSUE TITLE
[Request] Show card's "swipe animation" when position changed from code

### ISSUE THREAD

**Issue by 207713** [AndreiMisiukevich/CardView#1]
It would be awesome if the cards were animating when we change position from code, just like if a user swiped! :)

Thank you!

**Comment by AndreiMisiukevich** [comment]
@207713 
Validate this feature in the next release (1.2.5)
It will be available in 30-40 minutes on nuget (I've just published new version)

**Comment by 207713** [comment]
@AndreiMisiukevich I have just tested it, it works perfect!
Thank you for your fast work and your time!

**Comment by AndreiMisiukevich** [comment]
I think, I can close this issue
