### ISSUE TITLE
Swiping issues in Android

### ISSUE THREAD

**Issue by Nixon-Joseph** [AndreiMisiukevich/CardView#10]
On android only (so far as I've been able to see). swiping seems to fail sometimes. In testing, I've found that if I do large fast swipes, the image will move over a little, and then stick. If I do large slow swipes, it does a little better, but still doesn't move to the next image. The only consistent way to swipe over is a small quick swipe, maybe half an inch or so (5.5" display).

Andrei suggested [here](https://github.com/AndreiMisiukevich/CardView/issues/9) that I set 'IsPanInCourse' to false, but that didn't seem to make any difference.

Current carousel code
```
public List<SliderImage> CarouselImages { get; set; }
...
var carousel = new PanCardView.CarouselView()
            {
                ItemTemplate = new DataTemplate(() =>
                {
                    var img = new ClickableCachedImage();
                    img.SetBinding(ClickableCachedImage.SourceProperty, "ImageUrl");
                    img.Clicked += Image_Clicked;
                    return new ContentView() { Content = img };
                }),
                //IsPanInCourse = false, // didn't seem to make a difference
            };
```

`SliderImage` is a simple class that essentially just holds a string value of `ImageUrl`, and `ClickableCachedImage` is a class that essentially inherits from `Xamarin.Forms.Image`. Switching to using `Xamarin.Forms.Image`'s doesn't change anything.

If I were to guess, it seems like there are hard constraints on either/both swipe distance, and/or swipe time. And instead of going back to default position when one of those constraints is hit, the carousel just freezes where it is.

Let me know if there's any other information I could provide that could be helpful.

Thanks for the plugin BTW, it's pretty awesome.

**Comment by AndreiMisiukevich** [comment]
@Nixon-Joseph 
One question. Will it work OK, if you use simple contentview? without image at all.

I think, it can be issue of Xamarin's Image realization.. Could you test it pls?
And if it will be OK, i suggest you to install FFImageLoading.. But firstly test it) I will be grateful!

Thanks a lot for feedback, you help me to make it better!)

**Comment by Nixon-Joseph** [comment]
@AndreiMisiukevich I will try using a contentView without an image tomorrow. 

And I'm using FFImageLoading, it's amazing, speeds everything up. My `ClickableCachedImages` extends `CachedImage` from FF.

**Comment by AndreiMisiukevich** [comment]
check pls samples.. is it working better than yours?

**Comment by AndreiMisiukevich** [comment]
@Nixon-Joseph Have you checked it yet?)

**Comment by Nixon-Joseph** [comment]
Sorry, I don't think I'll be able to get to it until Monday. Will try to duplicate your sample code then.

**Comment by AndreiMisiukevich** [comment]
@Nixon-Joseph you may clone my repo and just start sample solution.

**Comment by Nixon-Joseph** [comment]
@AndreiMisiukevich I've cloned the repo, and tried it out. It seems far more stable than what is happening on my app. 

I think I've narrowed down (somewhat) the inconsistency I'm seeing in my carousel. I looks like, if the swipe at any points stop being a full left or right swipe (like if I accidentally also move my finger up or down a certain amount) than it just freezes the images in mid swipe.

This behavior is not in your sample app, so I will look into figuring out what the fundamental differences are.

***EDIT***

I've found where the issue lies. Looks like it's because my carousel is inside of a scrollview. Seems like once my swipe gesture moves too far up or down, the scrollview takes over, and your carousel doesn't seem to detect that. It's probably not sending an end gesture event.

I definitely need my carousel to be inside a scroll, so if this could be fixed, that would be amazing.

If you change line 44 of CarouselSampleView.cs where it sets the Page's Content to the following, you can see the behavior.
```
            Content = new ScrollView() {
                Content = new StackLayout() {
                    Children = {
                        carousel,
                        new BoxView() { HeightRequest = 4000, BackgroundColor = Color.Green }
                    }
                }
            };
```

Screenshot of symptom
![image](https://user-images.githubusercontent.com/10250222/37989629-9bca1b94-31c9-11e8-8d76-4d5e66767be5.png)

**Comment by AndreiMisiukevich** [comment]
@Nixon-Joseph Thanks a lot!
I will dive into this issue and try to create a workaround.

**Comment by AndreiMisiukevich** [comment]
@Nixon-Joseph check samples again..
But use ParentScrollView class instead of ScrollView.. Does it match your expectation?

**Comment by Nixon-Joseph** [comment]
So it seems like it's just a custom renderer on ScrollView that disables the touch intercept if the touch is already working on something? That's a good approach, and that certainly solves the symptom.

Would it be possible to instead only block scrolling over CardsView if the carousel is *currently* being swiped (sideways)? 

I don't like the UI block, as my carousel in my app is roughly half the screen, so that's a large section of screen where you user could try to scroll, and get no feedback.

So how about not setting `LastDownEventHandlerHashCode` on touch down, instead only set it on swipe/sideways movement? Would that work?

Thank you for your help!

**Comment by AndreiMisiukevich** [comment]
@Nixon-Joseph hmm, i tested on iOS simulator and got described behavior
"You aren't able to scroll over cardsview... and this scenario - _user could try to scroll, and get no feedback._"

Do you have another behavior for iOS?
So, can you scroll your ScrollView by swiping over CarouselView for iOS ?? It's strange.. because on simulator I cannot...

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView.Droid/ParentScrollViewRenderer.cs

Looks into this class
Uncomment 24 line and comment 25 line - you will get behavior, which you want.. but it doesn't work on iOS =(

**Comment by AndreiMisiukevich** [comment]
@Nixon-Joseph 
check https://github.com/AndreiMisiukevich/CardView/blob/master/README.md
1.3.8 version should have fix for your issue.
Just use ParentScrollView instead of ScrollView

**Comment by Nixon-Joseph** [comment]
Scrolling vertically on iOS over the carousel seems to work fine for me on emulator and phone. If it matters, my emulators and phone are running iOS 11.2. I'm on the latest xamarin forms and latest visual studio.

And thank you, I pulled your latest commit and the test app seems to be working exactly how I'd expect. 

Great job!

I'll update the package on my main app and give it a go.

**Comment by AndreiMisiukevich** [comment]
Nice) I will be grateful if you set star on this repo :)

**Comment by Nixon-Joseph** [comment]
Seems to work exactly how it should. There is one little thing though. For some reason, when starting a vertical scroll from over the carousel, the image does a quick flicker almost every time. So far have only tested on an emulator, but will test on a real device momentarily.

iOS seems to be fine.

And it's been starred - never knew that was a thing before.

**Comment by AndreiMisiukevich** [comment]
@Nixon-Joseph I'm glad to hear it)
Thanks for your feedback!
