### ISSUE TITLE
Bindable properties of TabViewControl don't work

### ISSUE THREAD

**Issue by AlfredoSolisFrausto** [AndreiMisiukevich/CardView#100]
When I trying bind some value to any Bindable Property of TabViewControl, for example HeaderBackgroundColor or HeaderTabTextFontAttributes, running appears the error: "Cannot assign property {PROPERTY NAME}: Property does not exists, or is not assignable, or mismatching type between value and property". It worked for me adding "static" to bindable properties.

**Comment by AndreiMisiukevich** [comment]
Hi @AlfredoSolisFrausto 
What TabViewControl is ? =)

**Comment by AndreiMisiukevich** [comment]
Oh, you asked me about the sample
Really, don't know, because somebody sent me this sample for reproducing an issue.
It isn't part of cardsView package.

**Comment by AndreiMisiukevich** [comment]
ok, i found the issue

```csharp
public readonly BindableProperty HeaderBackgroundColorProperty = BindableProperty.Create(nameof(HeaderBackgroundColor), typeof(Color), typeof(TabViewControl), Color.Transparent, BindingMode.Default, null, HeaderBackgroundColorChanged);
```
He missed STATIC key word =) (public STATIC readonly) i will fixed it in my sample, thx
