### ISSUE TITLE
How to get the Tap gesture on the Cards ?

### ISSUE THREAD

**Issue by shreyans-wakekar** [AndreiMisiukevich/CardView#102]
**<cv:CarouselView IsCyclical="false" IsVisible="false" IsPanSwipeEnabled="false">
<cv:CarouselView.ItemsSource>
<x:Array Type="{x:Type View}">
<ContentView>
<ContentView.GestureRecognizers>
<TapGestureRecognizer Tapped="Handle_Tapped" /> 
 </ContentView.GestureRecognizers>         
</ContentView>                  
</x:Array>
</cv:CarouselView.ItemsSource>
</cv:CarouselView>

Getting Error : Common Language Runtime detected an invalid program. before build process.
Need Help.**

**Comment by AndreiMisiukevich** [comment]
Whole xaml, please

**Comment by AndreiMisiukevich** [comment]
Because now i don't see any cardI items

**Comment by shreyans-wakekar** [comment]
[xml version.docx](https://github.com/AndreiMisiukevich/CardView/files/2335221/xml.version.docx)

**Comment by AndreiMisiukevich** [comment]
Ok, you can try to add tapGesture to your CarouselView
And determine what items was clicked by checking SelectedIndex

**Comment by rredoh** [comment]
Hi @AndreiMisiukevich can you check it again? Because I tried with TapGesture to CarouselView and it's not working

**Comment by AndreiMisiukevich** [comment]
@rredoh could you please share your code/xaml ?

It's needed to add tapgesture to itemTeplate :) I can help, if you show me code/sample

**Comment by rredoh** [comment]
Here. The [repro](https://github.com/rredoh/CardViewTap)

**Comment by AndreiMisiukevich** [comment]
@rredoh 
Well, there is no bug, you just use wrong BindingContext for tapGesture.
You should bind tapGesture command to parent's command with x:Reference

The first option
```xml
...
<ContentPage x:Name="page">
...
    <TapGestureRecognizer BindingContext="{Binding Source={x:Reference page}, Path=BindingContext}" Command="{Binding Command_ImageTapped}"/>
```

OR

The second option
```xml
...
<ContentPage x:Name="page">
...
    <TapGestureRecognizer Command="{Binding Source={x:Reference page}, Path=BindingContext.Command_ImageTapped}"/>
```

As you wish
