### ISSUE TITLE
Indicators

### ISSUE THREAD

**Issue by shirish8** [AndreiMisiukevich/CardView#103]
Cannot use the indicatorcontrol...
SelectedIndicatorStyle and UnSelectedIndicatorStyle properties...
Can you show an example...where i can change its outline and background color...???

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/issues/54

**Comment by AndreiMisiukevich** [comment]
See this issue

**Comment by shirish8** [comment]
@AndreiMisiukevich  Thank you so much... :)
