### ISSUE TITLE
Issue with Android

### ISSUE THREAD

**Issue by abanoub-labib** [AndreiMisiukevich/CardView#108]
I'm using CardView as carousel component which contains 3 items. each item contains grid with background image. It works well on my S9 only but on other Android devices, the first image is rendered only without others. I don't know yet what is the cause. I changed also the images order, so the problem is not with images.

**Comment by AndreiMisiukevich** [comment]
Hi) could you please create sample for me?
I guess the problem is with your image control.
Have you tried CachedImage ?

**Comment by abanoub-labib** [comment]
@AndreiMisiukevich  Yes true you are right. The issue was in the image and the image control thats why it differes between devices. Thank you

**Comment by AndreiMisiukevich** [comment]
You are welcome
If you like this plugin, you may star 🌟 this repo
