### ISSUE TITLE
Suggestion - not issue

### ISSUE THREAD

**Issue by Nixon-Joseph** [AndreiMisiukevich/CardView#11]
On the CarouselView
It would be nice if ItemTemplate was not required. In my case I have my app's checkout steps are in a carousel, and each page is a different ContentView.
I had to create an ItemTemplate for the carousel for it not to throw an exception.
If your control had a default ItemTemplate of something like:
```
                    new DataTemplate(() =>
                    {
                        var view = new ContentView();
                        view.SetBinding(ContentView.ContentProperty, nameof(ContentView.Content));
                        return view;
                    })
```
Then it would just work by letting you set a list of views to the carousel, without having to define the template.
It took some time to figure out that the missing ItemTemplate was my issue, because the last carousel I used didn't require me to define it, I believe it was doing something similar to this.

**Comment by AndreiMisiukevich** [comment]
Hm.. Why don't you want to use DataTemplateSelector?.. https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/data-templates/selector
OR don't you want to use bindings at all ?

Because in this case, I think it would be right to use it..

**Comment by AndreiMisiukevich** [comment]
If you have infinite count of your views, I suggest you to set IsViewCacheEnabled

**Comment by AndreiMisiukevich** [comment]
@Nixon-Joseph if you want to contribute to this repo, firstly you should fork it, create new branch, then create PR from your repo to mine one =)

But, I can do it myself, as you want)

**Comment by Nixon-Joseph** [comment]
Oh okay. I'll give that a go. I've made one other change too that I think is important. Give me a moment, and I'll try to get the pr to work.

**Comment by AndreiMisiukevich** [comment]
PRs are good)) I like PRs xD

**Comment by Nixon-Joseph** [comment]
Done! :)
