### ISSUE TITLE
Dynamically changing the IndicatorsControl color from the ViewModel

### ISSUE THREAD

**Issue by benazir0** [AndreiMisiukevich/CardView#111]
I want to change the color of the indicator according to the color of the item. If I try to use a value converter that returns cardview style, it doesn't even call the converter.

    <controls:IndicatorsControl SelectedIndicatorStyle="{Binding Item, Converter={StaticResource itemToStyle}}"/>

But if I bind the backgroundcolor only like bellow, it works.

    <controls:IndicatorsControl>
        <controls:IndicatorsControl.SelectedIndicatorStyle>
            <Style TargetType="controls:IndicatorsControl">
                <Setter Property="BackgroundColor"  Value="{Binding item, Converter={StaticResource itemToStyle}}" />
                <Setter Property="HeightRequest" Value="25" />
                <Setter Property="HeightRequest" Value="25" />
            </Style>
        </controls:IndicatorsControl.SelectedIndicatorStyle>
    </controls:IndicatorsControl>

**Comment by AndreiMisiukevich** [comment]
Well, let's investigate it)
Perhaps, you want to debug this view and check, why it doesn't work?)

**Comment by AndreiMisiukevich** [comment]
I would be grateful so much, if you create small sample with reproduction.

**Comment by AndreiMisiukevich** [comment]
Hi
![image](https://user-images.githubusercontent.com/10124814/45589952-51b5aa00-b937-11e8-87b9-5268defef2fd.png)

Everything works fine for me (I tried from code)
Must be the same with xaml (try to clean/rebuild/delete bin/obj)

if you still have this issue, obligatory create sample with reproduction
