### ISSUE TITLE
Issue With Carousel Indicators Direction in RTL

### ISSUE THREAD

**Issue by abanoub-labib** [AndreiMisiukevich/CardView#112]
I'm using a carousel and working on RTL (arabic layout). But there is an issue while swiping from right to left that the indicators dots navigate on the opposite direction.

**Comment by AndreiMisiukevich** [comment]
Hi
Have you set IsRightToLeftFlowDirectionEnabled to true?
Show your xaml/core

**Comment by AndreiMisiukevich** [comment]
@abanoub-labib ...?

**Comment by AndreiMisiukevich** [comment]
Well, try IsRightToLeftFlowDirectionEnabled = true
And let me know, if smth is wrong

**Comment by AndreiMisiukevich** [comment]
@abanoub-labib full xaml please)
Did you add IndicatorsControl as child of carousel ?

**Comment by abanoub-labib** [comment]
<CardsView:CarouselView Grid.Row="0"
                                Grid.RowSpan="5"
                                BackgroundColor="#FF947B66"
                                ItemsSource="{Binding Highlights}"
                                IsRightToLeftFlowDirectionEnabled="True">

            <CardsView:CarouselView.ItemTemplate>
                <DataTemplate>

Content here

</DataTemplate>
            </CardsView:CarouselView.ItemTemplate>

            <CardsViewControls:IndicatorsControl Margin="0,0,0,160"
                                                 UnselectedIndicatorStyle="{StaticResource UnSelectedHighlightsIndicators}" />


        </CardsView:CarouselView>

**Comment by abanoub-labib** [comment]
I just cannot send the full xaml, But the scenario is as I explained
do you get my point? If not I may create you a sample of the problem

**Comment by AndreiMisiukevich** [comment]
Yes, I got it long time ago)
But I tested this flow and it should work correctly.
Well, I will test it again

**Comment by abanoub-labib** [comment]
A workaround is to bind the "IsRightToLeftFlowDirectionEnabled" of the carousel view to the current page flow direction and to set the "IsRightToLeftFlowDirectionEnabled" of the indicators to false.

By setting this, it works fine in both directions.

**Comment by AndreiMisiukevich** [comment]
@abanoub-labib thanks for reply =) Checking now, it seems, that i know the reason

I tested RTL without setting FlowDirection to RTL (i changed only IsRightToLeftFlowDirectionEnabled prop)
