### ISSUE TITLE
Choppy scrolling on iOS

### ISSUE THREAD

**Issue by OKameric** [AndreiMisiukevich/CardView#113]
I'm having an issue when scrolling a page where root element is ParentScrollView and its content is CarouselView. The scrolling is OK on Android but iOS doesn't have that smooth scroll when you swipe up or down on the page. The same issue is also here in the sample: CarouselSampleViewNoTemplate. When you swipe down on green BoxView area the scrolling is working fine but if you swipe (up or down) in upper view where CarouselView is then it's kinda choppy.

I tried playing with VerticalSwipeThresholdDistance property but the behavior is the same. It helps if I set IsPanInteractionEnabled  property to false but then I can't swipe left and right to change selected item in carousel.

**Comment by AndreiMisiukevich** [comment]
Hi @OKameric 
Thanks for your feedback.
Yes, this is known issue. Any ideas how to solve it?

**Comment by AndreiMisiukevich** [comment]
IsPanInteractionEnabled = false is only one solution
Yes, you can't drag and drop your carousel, but can swipe over card and it must show animation.
Isn't it working?

**Comment by AndreiMisiukevich** [comment]
I didn't find any solution, how to pass touch event to parent view.. So panGesture stills touches..(

**Comment by AndreiMisiukevich** [comment]
if you want, you can report a bug for xamarin team.
Perhaps they are able to resolve it

**Comment by OKameric** [comment]
Sorry, I didn't search through closed issues to see that someone else had the same problem. I will try to find some workaround in my layout to accomplish this. 

Btw, thank you for a great library :)

**Comment by AndreiMisiukevich** [comment]
@OKameric thank you)
