### ISSUE TITLE
Weird lines appearing

### ISSUE THREAD

**Issue by LeoJHarris** [AndreiMisiukevich/CardView#114]
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/5468757/45787897-a789a980-bccb-11e8-8b2c-17eb53d985d8.gif)

Hi there, noticing an issue have attached gif:

Part of code is this::

`PanCardView.CarouselView cardsView = new PanCardView.CarouselView()
            {
                ItemTemplate = new DataTemplate(() => new ImageCardItemView()),
                ItemsSource = list,
                SelectedIndex = currentPhotoIndex,
                SlideShowDuration = 3500
            };`

`BackgroundColor = Settings.XeniaBlackThemeColorAlpha;

            _image = new CachedImage
            {
                Aspect = Aspect.AspectFill,
            };

            frame = new Frame()
            {
                Padding = 0,
                CornerRadius = 10,
                HasShadow = false,
                HorizontalOptions = LayoutOptions.Center,
                IsClippedToBounds = true,
                VerticalOptions = LayoutOptions.Center,
                WidthRequest = 300,
                HeightRequest = 300
            };
            _image.SetBinding(CachedImage.SourceProperty, "Source");
            frame.Content = _image;
            Content = frame;`

......

Oddly Im not getting this issue on your sample.. any ideas?

**Comment by AndreiMisiukevich** [comment]
Hi
Probably, you the reason is in Xamarin.Forms
Could you provide fully reproduction?

**Comment by Phenek** [comment]
Is this a video from the simulator?

**Comment by AndreiMisiukevich** [comment]
@Phenek it seems to be a real device
https://play.google.com/store/apps/details?id=com.duapps.recorder&hl=en
But I'm not sure

**Comment by LeoJHarris** [comment]
@AndreiMisiukevich @Phenek Yes using DU Recorder app as the link @AndreiMisiukevich mentioned

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris could you create small sample?
What version of XF do you use?

**Comment by LeoJHarris** [comment]
Xamarin.Forms version I am using is 3.1.0.697729. Small sample to follow soon

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris also what api level does your device use

**Comment by LeoJHarris** [comment]
Have tested on two device 5.1.1 and 7.1.1. Seeing the same issue on both.

**Comment by LeoJHarris** [comment]
@AndreiMisiukevich Will get a sample before the weekend today hopefully, just a bit hands tied atm

**Comment by LeoJHarris** [comment]
I have made a sample repo will submit soon

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris don't forget

**Comment by LeoJHarris** [comment]
[Sample.zip](https://github.com/AndreiMisiukevich/CardView/files/2407093/Sample.zip)

Here you go :)

**Comment by LeoJHarris** [comment]
I copied my own project and stripped out basically everything apart from what was import for the sample. I haven't removed any external .libraries though

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris 
![image](https://user-images.githubusercontent.com/10124814/45919248-f20d5080-be9a-11e8-8bb8-e7c5352b3084.png)


It crashes on start(

**Comment by AndreiMisiukevich** [comment]
Could you please test it on my sample?
https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardViewSample/PanCardViewSample/Views/CarouselSampleXamlView.xaml

I still think that this is xamarin issue (XF 2.5 works fine)

**Comment by amrkamal1993** [comment]
I Have the same issue only in android 
XF 3.1.0.697729

**Comment by AndreiMisiukevich** [comment]
@amrkamal1993 try please with Forms 2.5
I guess, we should create issue for Xamarin team

**Comment by LeoJHarris** [comment]
@AndreiMisiukevich That's a bummer let me check that sample project again. I also think the issue exists in Xamarin.Forms version.

**Comment by LeoJHarris** [comment]
@AndreiMisiukevich Okay

**Comment by LeoJHarris** [comment]
I think we should remove the CircleFrame with just frame then at least the lines disappear, no issues anymore.

Can we not use RoundTransformation in FFLoadingImage package for corner radius without the need of the frame itself?

https://github.com/luberda-molinet/FFImageLoading/wiki/Transformations-Guide#roundedtransformation

What exactly is the issue with the Xamarin Forms Frame?

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris hi
Thanks, i appreciate any help with investigation.

**Comment by thedjnova** [comment]
sorry for my absence but im backkkkk....

I think this will be an issue within the circleframe render. Looks most likely to do with when it overrides the original drawing elements, it is momentarily rendering a regular frame, then it is replacing it with the new frame, then on next render it is doing the same.

Ill take a look into the rendererover weekend and see what I can find.

**Comment by AndreiMisiukevich** [comment]
So, guys
What version of XF broke the Circle frame renderer?
I believe, we can find something new it XF and use reflection for determining current XF version installed on device -)

**Comment by AndreiMisiukevich** [comment]
@Phenek great!) So, we can check for existing FlowDirection property in any view =)

**Comment by AndreiMisiukevich** [comment]
also I think, i should change arrow from label to image
unicode arrow work so bed (align is wrong)

**Comment by AndreiMisiukevich** [comment]
try 1.6.4-pre
