### ISSUE TITLE
Error: Type TabItem not found in xmlns clr-namespace:TabSlide.Controls

### ISSUE THREAD

**Issue by lamvt2306** [AndreiMisiukevich/CardView#115]
I am in this error, Help !
--------------
Page: TabSlide.xaml
-----------
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             xmlns:tv="clr-namespace:TabSlide.Controls" 
             x:Class="CNDEMO.TabSlide">

**Comment by AndreiMisiukevich** [comment]
@lamvt2306 Hi
TabSlide.Controls

It isn't related to CardsView package.
I don't know such namespace
