### ISSUE TITLE
horizontal swipe/pan carousel in listview.Header

### ISSUE THREAD

**Issue by hectorast** [AndreiMisiukevich/CardView#117]
Hello.

I need CarouselView in the header of the listview. In IOS works perfect, but in Android, is too difficult to swipe/pan because listview detect also vertical scroll.
Is posible to avoid vertical scroll of the listview when swipe/pan horizontally?

Thanks.

**Comment by AndreiMisiukevich** [comment]
@hectorast Hi
Have you read https://github.com/AndreiMisiukevich/CardView#workarounds yet?

Try to create listView renderer with the same code https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView.Droid/ParentScrollViewRenderer.cs

**Comment by AndreiMisiukevich** [comment]
Try it and back to me with feedback please =)

**Comment by hectorast** [comment]
Thank for your answer.
But I try all case in workaounds section y didn't work. Probably I'm doing something wrong.
In the other hand I see a probably bug in the carousel. In the ItemTemplate create a Grid with a background image and 2 text with verticalOptions "CenterAndExpand", when swipe heights text are wrong, like actual element (visible) take height from other element in the list.
This problem also happen in sample code, with this modification in section "CarouselSampleXaml.
Can you check this and tell me if I'm doing something wrong?

**Comment by AndreiMisiukevich** [comment]
@hectorast could you please create sample project with that issue?

**Comment by hectorast** [comment]
Here is the example. Is a fork of your project.
https://github.com/hectorast/CardView

**Comment by AndreiMisiukevich** [comment]
@hectorast thanks a lot, i will check it

**Comment by AndreiMisiukevich** [comment]
@hectorast do you want to investigate this issue a little?
I spent a lot of time, but don't see any solution

Any ideas, how to stop scrolling ?

**Comment by AndreiMisiukevich** [comment]
@cyrilcathala very strange issue
Is there a sample?

**Comment by AndreiMisiukevich** [comment]
I'm afraid, you need to use IsPanInteractionEnabled = false
That's only one solution, which i see now :(
