### ISSUE TITLE
Issue when resizing UWP apps

### ISSUE THREAD

**Issue by jonasrembratttetrapak** [AndreiMisiukevich/CardView#119]
There's a problem with rendering in UWP. Here's the repro:

1. Open UWP app and navigate to view containing a `CarouselView`
2. Maximize UWP window
3. Slide to next CarouselView item

= Result: Previous item appears to be partially rendered over the current one.
![screenshot](https://user-images.githubusercontent.com/28783954/46875437-027e6e80-ce3c-11e8-9f4d-fb5e1e83cb1c.PNG)

**Comment by AndreiMisiukevich** [comment]
Hi. thanks for your report
Unfortunately, i don't have a windows PC in my own.

Maybe, somebody wants to investigate this issue, solve and make a PR ?)

**Comment by AndreiMisiukevich** [comment]
try 1.6.4-pre

**Comment by jonasrembratttetrapak** [comment]
I'll check it out ASAP. Thanks!

**Comment by AndreiMisiukevich** [comment]
@jonasrembratttetrapak I'm glad to know it)
If you like this plugin, you may support it by setting STAR 🌟 :)
