### ISSUE TITLE
[Bug Android] Scrolling vertically on ListView, make a swipe out of range.

### ISSUE THREAD

**Issue by Phenek** [AndreiMisiukevich/CardView#125]
Hello There,

I got an issue with Carousel View with two listViews Content, it's just happening on Android

It's literally swipe out of range, when I'm doing a vertical scroll on ListView.
then I just do a click and the List is coming back.
I didn't get this issue on iOS
There a demo:
![Alt Text](https://media.giphy.com/media/iMBdMRfKSinEYdTFYZ/giphy.gif)

If you got any idea where could be the problem, let me know.
regards,

**Comment by AndreiMisiukevich** [comment]
Hi
Try to play with 
1) VerticalSwipeThresholdDistance = 1000
2) SwipeThresholdDistance = 100 
etc.

I need a sample for debugging it, what is causing animation

**Comment by Phenek** [comment]
Yeah I tried
I have not enough time to give you a sample right now.

It's seems to come when I change manually the CarouselView.SelectedIndex then I swipe

**Comment by AndreiMisiukevich** [comment]
@Phenek try it now please
if you want, you can debug, why CurrentView == CurrentBackViews[0].
It seems, that SetupBackViews isn't called sometimes

**Comment by AndreiMisiukevich** [comment]
try 1.6.4

**Comment by Phenek** [comment]
Hey first Thanks,
unfortunately 1.6.4 didn't worked, I still get the issue like in the Gif.
I will investigate why CurrentView == CurrentBackViews[0]
when I got time.

**Comment by AndreiMisiukevich** [comment]
> Hey first Thanks,
> unfortunately 1.6.4 didn't worked, I still get the issue like in the Gif.
> I will investigate why CurrentView == CurrentBackViews[0]
> when I got time.

I think, this issue is related to embedding view only and doesn't affect ItemTemplate approach
