### ISSUE TITLE
UWP crashes with XF 3.3.0.912540 when Sliding

### ISSUE THREAD

**Issue by JTOne123** [AndreiMisiukevich/CardView#126]
With the latest XForms, something crashes when sliding with the next exception 

`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`

**Comment by AndreiMisiukevich** [comment]
@JTOne123 hi) I have no idea, how can we solve it)
I'm sure, we should create an issue for Xamarin.Forms team.

**Comment by AndreiMisiukevich** [comment]
@JTOne123 could you please create this issue for XF team (attach sample)
Because it doesn't look like CardsView bug

**Comment by JTOne123** [comment]
Exception is here 
![image](https://user-images.githubusercontent.com/3457140/47264999-cd53d980-d529-11e8-946a-71aa0ea7e275.png)

It looks like an issue with corner radius that was fixed at 3.3 for UWP

https://github.com/xamarin/Xamarin.Forms/issues/2838

https://github.com/xamarin/Xamarin.Forms/commit/6031bbfb691033680c877bb7da79fc5d6c717299

**Comment by AndreiMisiukevich** [comment]
@JTOne123 amazing! Good job.
What do you think regarding to this issue?
Should we do anything?

**Comment by JTOne123** [comment]
I'm fixed it with the custom frame renderer

```
public class FixFrameRenderer : FrameRenderer
    {
        protected override void UpdateBackgroundColor()
        {
            var backgroundColor = Element.BackgroundColor;
            if (Control != null)
            {
                if (!backgroundColor.IsDefault)
                {
                    Control.Background = backgroundColor.ToBrush();
                }
                else
                {
                     //////Control.ClearValue(BackgroundProperty); ISSUE HERE
                    Control.Background = new Color(0, 0, 0, 0).ToBrush();
                }
            }
        }
    }
```

The issue in Control.ClearValue(BackgroundProperty);

It happens because do not set UnselectedIndicatorStyle and without explicit value background color, the nex XF frame renderer tries to Control.ClearValue and that cause an exception.

Workaround:
Use fixrenderer or set UnselectedIndicatorStyle

**Comment by AndreiMisiukevich** [comment]
Cool 
Let's leave it as is.
