### ISSUE TITLE
In cardsview if the cards are semi transparent then after swiping to left or right the next card will be visible under the current card

### ISSUE THREAD

**Issue by alicint** [AndreiMisiukevich/CardView#128]
try adding a semi transparent card and swipe to any directon partialy and then stay on the original card, the new card will be created under the current card and because current card is semi transparent the next card will be visible under it. I think this is a bug.

**Comment by AndreiMisiukevich** [comment]
@alicint hey, thanks for feedback

How should it work in your opinion? Let's imagine, that you have 1000 cards. It won't be great idea to renderer them on start, will it?

**Comment by alicint** [comment]
yeah definitely I don't mean that it should load all at once, maybe hiding the next card when user isn't swiping yet?

**Comment by AndreiMisiukevich** [comment]
@alicint in this case you are loosing pretty animation.
Well, if you want to customize animation, you may easily achieve it

Inherit these classes:
- https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Processors/BaseCardFrontViewProcessor.cs
- https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Processors/BaseCardBackViewProcessor.cs

And implement your approach (it must be rather easy, set IsVisible = true, only on apply)
