### ISSUE TITLE
Any event handler for SelectedIndex Changed?

### ISSUE THREAD

**Issue by alicint** [AndreiMisiukevich/CardView#129]
It is possible to listen to the SelectedIndex changed when user is swiping with OnUserInteracted but when the selected index is changed programmatically it is not possible to listen to SelectedIndex changes.

**Comment by AndreiMisiukevich** [comment]
@alicint  Hi) thanks for feedback

Have you tried ItemAppearing event ? :)

*if you like this plugin, you may STAR it*

**Comment by AndreiMisiukevich** [comment]
See more info there https://github.com/AndreiMisiukevich/CardView/blob/master/docs/CardsView.md

**ItemAppearing** / **ItemDisappearing** 
or
**ItemAppearingCommand** / **ItemDisappearingCommand**

**Comment by alicint** [comment]
Thanks Andrei, ItemAppearing works. having a SelectedIndexChanged event would be more convenient since thats the common pattern.
And yeah I do like it and have already starred it ;)

**Comment by AndreiMisiukevich** [comment]
@alicint thanks for feedback, but can't agree. This name is unified (ListView use the same) it came from WPF
