### ISSUE TITLE
[Documentation] Create full documentation of this plugin

### ISSUE THREAD

**Issue by AndreiMisiukevich** [AndreiMisiukevich/CardView#13]
Something like this https://github.com/jamesmontemagno/SettingsPlugin/tree/master/docs

**Comment by AndreiMisiukevich** [comment]
I will appreciate any help.
Maybe, somebody wants to start creating of Properties/Description table? =)

**Comment by b099l3** [comment]
Made a start to this, should be able to have a look at #64 

In terms of a GitHub page, are you wanting just the one page for each control your making or to put all the controls under one?

**Comment by AndreiMisiukevich** [comment]
@b099l3 on you wish
I don't know, how it would be more comfortable for developers =)
But I think, now, it's much more better!

Thanks again!

**Comment by AndreiMisiukevich** [comment]
I think, we should leave base information about controls on the main Readme of the project. For more info developers will have to follow the link =)

**Comment by AndreiMisiukevich** [comment]
I think, it can be closed.
For now it is more than enough)
