### ISSUE TITLE
Is it possible to prevent left or right swipe gesture in Carousel control?

### ISSUE THREAD

**Issue by acidbless** [AndreiMisiukevich/CardView#130]
Hi Andrei.
I need to navigate through the collection in a forward direction in the carousel, so the swipe gesture should be restricted in right to left. It seems IsOnlyForwardDirection property is what I need, but the problem is that it does not restrict the left to right gesture. Did I miss something?

**Comment by AndreiMisiukevich** [comment]
@acidbless hi, This is good question, i think, the best solution for you would:

1) Don't use IsOnlyForwardDirection (leave it default)
2) Set IsCyclical = false
3) Handle **ItemDisappearing** event or **ItemDisappearingCommand** and remove disappeared one (Which has got index 0)

So, you will achieve such behavior.

Is everything clear?)
