### ISSUE TITLE
Error - AccessViolation exception on UWP platform

### ISSUE THREAD

**Issue by ZeroByte1987** [AndreiMisiukevich/CardView#131]
I get **AccessViolation** exception on **UWP** when there's more than one image in source collection for **CarouselView**.
CardView version - **1.6.4** (also tested in 1.6.3)
Xamarin.Forms version - **3.3.0**

It seems to work properly on Android and iOS, i.e. this is likely UWP-only issue.

My colleague says it worked some time ago with multiple images, so maybe the problem is with new Xamarin.Forms version.

**Comment by AndreiMisiukevich** [comment]
@ZeroByte1987 yes, i think so too

**Comment by AndreiMisiukevich** [comment]
I don't have Windows PC for testing it. I use Mac

**Comment by AndreiMisiukevich** [comment]
Who wants to debug it ?))

**Comment by ZeroByte1987** [comment]
Oh, seems like this suggestion here fixed the problem.
https://github.com/AndreiMisiukevich/CardView/issues/126

> It happens because do not set UnselectedIndicatorStyle and without explicit value background color, the nex XF frame renderer tries to Control.ClearValue and that cause an exception.
> 
> Workaround:
> Use fixrenderer or set UnselectedIndicatorStyle

Sorry for disturbing you. :)

**Comment by AndreiMisiukevich** [comment]
@ZeroByte1987 don't worry

**Comment by AndreiMisiukevich** [comment]
@amirvenus hi
have you tried this approach https://github.com/AndreiMisiukevich/CardView/issues/126 ?
