### ISSUE TITLE
[Android] ArrowControl require double taps instead of single

### ISSUE THREAD

**Issue by gmwilhelm** [AndreiMisiukevich/CardView#132]
Hello,

i'm playing around with your sample application.

I noticed that in the CarouselSampleXamlView the arrows only react on a double tap. 
Is it possible to set this to a single tap?

Regards,
  Dirk

**Comment by AndreiMisiukevich** [comment]
@gmwilhelm hm, that's strange stuff!
I need to check it
Perhaps you click it too fast, no?

**Comment by AndreiMisiukevich** [comment]
What version forms do you use? Android or iOS ?

**Comment by gmwilhelm** [comment]
Hello,

i tested it on Android, both simulator (Android 6.0) and a real device (Android 8.0), with the forms version 2.5.1.444934 and 3.3.0.912540.

Couldn't test on iOS yet, since i get different errors when i try to compile the sample. but that is a different problem.

**Comment by AndreiMisiukevich** [comment]
@gmwilhelm got it, thanks
I will check on simulator.. but as you can see in source code, I use regular tapgesture

**Comment by AndreiMisiukevich** [comment]
@gmwilhelm i found the reason. Will try to fix today

**Comment by AndreiMisiukevich** [comment]
It will be available in the next release
