### ISSUE TITLE
Handling adding items dynamically

### ISSUE THREAD

**Issue by martinvds81** [AndreiMisiukevich/CardView#133]
Hi,

I have a problems with the view when updating collection. I have created a setup where I can endlessly swipe through dates (disabled the infinite scroll option). So what I did was create a collection with three dates and set the selected index on the middle one. On the `CardsViewItemSwipedHandler` I then handled the right or left swipe and based on that do the following:

**right swipe** (previous date)
1. Add a new date on index 0 and remove the last date

**leftswipe** (nextdate)
1. Add a new date at the end and remove the date on index 0

This seems to be working for the first few swipes but after that the views gets of center (content is not completly shown). Do you have a suggestion how I can solve this ?

Thank you

**Comment by AndreiMisiukevich** [comment]
Hi, if i understood you correctly you want to have 3 active views (3 items)
SelectedIndex = 1 (regular state)
And if you swipe right (you want to make right view as centered - index = 1, remove left one, old centered make as index = 0 and added new one with new index = 2)
Is it correct?

I think you should use ItemAppearing event (and if index = 0 or 2, you recycle views)

**Comment by martinvds81** [comment]
> Hi, if i understood you correctly you want to have 3 active views (3 items)
> SelectedIndex = 1 (regular state)
> And if you swipe right (you want to make right view as centered - index = 1, remove left one, old centered make as index = 0 and added new one with new index = 2)
> Is it correct?
> 
> I think you should use ItemAppearing event (and if index = 0 or 2, you recycle views)
> 
> OR
> 
> Create please small sample for me

Thanks for your reply Andrei,

How do I go about recycling the views? I will setup a sample.

**Comment by AndreiMisiukevich** [comment]
@martinvds81 great. I wait

**Comment by AndreiMisiukevich** [comment]
@martinvds81 don't forget)

**Comment by martinvds81** [comment]
> @martinvds81 don't forget)

I changed the setup yesterday and is seems to be working now. Instead of adding and removing the items in the carousel, they now have some fixed items and enabled cyclic again. In 
the CardsViewItemSwipedHandler I now only register the left or right action and based on that reload the bindable data in the card.

Anway thanks for this control and your help 👍
