### ISSUE TITLE
First and Fourth Page Duplicate ISSUE

### ISSUE THREAD

**Issue by toshitani23** [AndreiMisiukevich/CardView#137]
Hi, I tried to use the "CarouselView" of this Plugin in order to display list of data and everything works fine. However, the only thing that I found some issue is that after every three pages, the next three pages (fourth, fifth, sixth and so on...) unexpectedly duplicate some of the UI Design from the first three pages without touching/changing anything on the current index/page as shown in image(below): 

**THIS IS THE FIRST PAGE**:
![first page](https://user-images.githubusercontent.com/33538394/48048952-149fc280-e1d8-11e8-8b88-488a449bd466.JPG)

**THIS IS THE FOURTH PAGE**:
![fourth page](https://user-images.githubusercontent.com/33538394/48048950-14072c00-e1d8-11e8-9dd2-93ffbd6e3692.JPG)

When I check the 'check icon' in the first page, the fourth page check icon is also being selected.
The second and third page is working fine they are not selected. 

Hoping you can help me with this. Thanks. :)

**Comment by AndreiMisiukevich** [comment]
@toshitani23 

Hi, do you use bindings for managing carousel?
It seems, that bindings doesn't work.. you should clear view each time when they will appear.
hmm..
So, you can try to set **"IsViewCacheEnabled = false"**, but it isn't very good solution.
Or try to subscribe BindingContextChanged in your cards and clear view...
There are a lot of possible fixes/workarounds

It would be great to have small sample with this issue, i will help to figure out.

**Comment by toshitani23** [comment]
Hi @AndreiMisiukevich, thank you for helping me.

Here is the small sample you're requesting.

[CarouselViewDuplicateItem.zip](https://github.com/AndreiMisiukevich/CardView/files/2552508/CarouselViewDuplicateItem.zip)

**Comment by AndreiMisiukevich** [comment]
@toshitani23 i will try to check it today-tomorrow :)

**Comment by AndreiMisiukevich** [comment]
I checked your sample
You don't use bindings properly for storing selected image.

I can create small sample, how to use it .. because it's difficult a little to understand your code :)

**Comment by AndreiMisiukevich** [comment]
[test.zip](https://github.com/AndreiMisiukevich/CardView/files/2558962/test.zip)

I created very similar sample, check it :)
You just need to figure out with your bindings )
