### ISSUE TITLE
Force redraw of card layout

### ISSUE THREAD

**Issue by Luke03** [AndreiMisiukevich/CardView#138]
Hi,
I am trying to build the following functionality:
When a card is tapped it should turn around and show some additional information.
To achieve this I added a TapGestureRecognizer which sets a boolean flag on the data object.
The CardView uses a TemplateSelector which selects between two templates, one for the front-side and one for the back-side of the card. If the boolean flag is true it selects the back-side, otherwise the front-side. My problem is that the TemplateSelector is only called when the card is initially shown. As a workaround I use a PropertyChanged event. When the boolean flag is changed, it sets the ItemSource to an empty list and then back to the actual list. This causes the TemplateSelector to be called again and the correct template is selected. I don't think that is the right way to do it and it also has some minor issues, so is there any way to force a redraw of the currently shown card, so that the TemplateSelector is called again?

**Comment by AndreiMisiukevich** [comment]
Hi, https://github.com/AndreiMisiukevich/CardView/issues/91

The same issue.
I tried to implement such feature, but it causes some errors

In your case i suggest some of next approaches

1) Create template with two layouts and select needed regarding to boolean value
```xml
<DataTemplate>
    <StackLayout IsVisible="{Binding ShouldBeVisible}">
        ...
    </StackLayout>

    <StackLayout>
        ...
    </StackLayout IsVisible="{Binding ShouldNotBeVisible}">
</DataTemplate>
```
2) Or you can use two different carousel view and hide/show when it needed
