### ISSUE TITLE
ImageSource Binding Issue

### ISSUE THREAD

**Issue by vecalion** [AndreiMisiukevich/CardView#140]
Hey Andrei,

I'm looking for some ideas here. I'm putting the CardView control into a real project and getting some binding issues. Let me try to describe:

There are a lot of cards, one of the cards let the user choose a photo from the gallery (so OnDisappearing / OnAppearing fires). When a photo is selected, it's loaded into a property of a type ImageSource. This property is bound to an Image control on the card. 

So the workflow: 
1) User clicks on the button on the card
2) Chooses a photo in the gallery
3) Sees the photo on the card

Issue:
The selected photo often is not displayed. I see that there is some kind of a concurrency issue. When I put breakpoints - it works 100% (the photo is displayed). If there are no breakpoints, 90% it doesn't work. Something is happening when the CardView goes off the screen and back to the screen. 

I wonder if you have any ideas what can be wrong? If not, I'll try to create a simplified sample, but this can take some time.

**Comment by AndreiMisiukevich** [comment]
@vecalion hm, do you use FFImageLoading ?)
If not, try please it. If yes, try to use Xamarin.Forms.Image =)

I think, it can be image loading issue.. also you can try to set new ImageSource it MainThread

```csharp
Device.BeginInvokeInMainThread(() => Image.Source = source));
```

**Comment by AndreiMisiukevich** [comment]
@vecalion if you decide to create repro/sample, could you please do it in your fork repository?
it would be better for debugging :)
But I'm sure, that this is thread issue with Image (FF or regular XF Image)

**Comment by vecalion** [comment]
@AndreiMisiukevich yeap, looks like that. The main thread didn't help. I'll play a bit to get more details and if nothing helps, create a repro project in my fork. Thanks.

**Comment by AndreiMisiukevich** [comment]
@vecalion thanks) 
Btw, do you call PropertyChanged after setting new value ?) Maybe you miss something.. (just hypothesis)

**Comment by vecalion** [comment]
Yep, the PropertyChanged is called.

Here is the repro project (iOS, select the CarouselView Xaml menu item): https://github.com/vecalion/CardView/tree/master/PanCardViewSample

What I found during creation is that it works perfectly if the ImageSource is the property of the card view model. In my case it's a property of a parent view model and is bound like this:

`<Image Source="{Binding Source={x:Reference ThisPage}, Path=BindingContext.SelectedImage}" />`

This causes a concurrency issue. If you uncomment this line or put a breakpoint there everything works:
https://github.com/vecalion/CardView/blob/19b58b95e42b144541b37b20dbe5744761b84212/PanCardViewSample/PanCardViewSample/ViewModels/CardsSampleViewModel.cs#L101

**Comment by AndreiMisiukevich** [comment]
@vecalion and it won't help, right?

```csharp
Device.BeginInvokeInMainThread(() => SelectedImage = ImageSource.FromStream(file.GetStream));
```

**Comment by vecalion** [comment]
Nope, looks like there is an interesting bug here. :)

**Comment by AndreiMisiukevich** [comment]
Does FFImage work wrong in that place as well? @vecalion

**Comment by AndreiMisiukevich** [comment]
@vecalion maybe it's something related to Stream ImageSource ?
What will happen, if we set URI or File Image source instead of Stream?


```csharp
private async Task TakePicture()
        {
            await CrossMedia.Current.Initialize();

            var file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions { CompressionQuality = 50 });

            if (file == null)
            {
                return;
            }

            SelectedImage = "someImage.png"; //or http://someImageUrl.com
        }
```

**Comment by AndreiMisiukevich** [comment]
@vecalion closing for now
because it doesn't seem to be cardView issue
