### ISSUE TITLE
Can we use Stack or Grid as ItemLayout instead of Absolute CoverFlowView? 

### ISSUE THREAD

**Issue by SagarPanwala** [AndreiMisiukevich/CardView#142]
Can we use Stack or Grid as ItemLayout instead of Absolute in CoverFlowView?
I tried to use, but it won't work properly. Sometimes scroll not work , sometime width not calculating properly. I almost spend 1.5 day to make this work butterly. Your help will get me out of trouble.
Thanks

**Comment by AndreiMisiukevich** [comment]
Yes, we can
But background images will be disabled for these controls

Is it ok ?

**Comment by SagarPanwala** [comment]
Sorry don't understand you,
In coverflowview, I want to put stack or grid layout and those can contain
any childview?

Also in the sample, if we change height of items, control functionality got
broke.

**Comment by AndreiMisiukevich** [comment]
Coverflowview is in beta. It isn't stable. And was developed by another guy. It would be better to ask him.

Probably stabl Carousel View would be ok for you..

**Comment by AndreiMisiukevich** [comment]
@SagarPanwala let's go ahead in the original github-ticket 
https://github.com/AndreiMisiukevich/CardView/issues/17

**Comment by Phenek** [comment]
Hello @SagarPanwala ,
For now all items have to get the same Width.

I have to do some rework and add some logics to get them dynamics like 
"HasUnevenRowsProperty" do on ListView. (this will affect performances)

Unfortunately this feature is not implemented for now.

**Comment by AndreiMisiukevich** [comment]
@Phenek Thanks :)

--
_OFFTOPIC: recommend to check https://github.com/AndreiMisiukevich/HotReload_

**Comment by SagarPanwala** [comment]
My concern is let them make , same width, but if I change in sample from
130 to 200, scrolling breaks.

**Comment by SagarPanwala** [comment]
Thanks,

I will be glad if any way I can contribute.
I also need ur help if u can send me ur email or PM me.

**Comment by Phenek** [comment]
For those who want a simple Horizontal list [Here the CollectionView](https://docs.microsoft.com/fr-fr/xamarin/xamarin-forms/user-interface/collectionview)
It will be available in Xamarin.forms 4.0

**Comment by AndreiMisiukevich** [comment]
@Phenek what do you think about future of CardsView controls
Does it make sense to support it at all?)

**Comment by Phenek** [comment]
Regarding this [topic](https://blog.xamarin.com/xamarin-forms-4-0-feature-preview-an-entirely-new-point-of-collectionview/)
There will be a carouselView, I did not try it to get 3 items at the same time.
But the idea of a CardsView and CoverFlowView will not be implemented.

I think CoverFlowView should inherit from CollectionView to get the Velocity scroll, and cause the recycler logic is already implemented. We need just to add some animation when scrolling to get some effects on Items

I think CardsView component can still prosper for a long time

**Comment by AndreiMisiukevich** [comment]
@Phenek good points
