### ISSUE TITLE
Add ThumbnailControl

### ISSUE THREAD

**Issue by stealthcold** [AndreiMisiukevich/CardView#144]
Hi guys!

First of all: thanks for this awesome plugin! 😀

I would like to know if you have some ideas (and if is possible) to change the indicator of the CarouselView, to achieve the same thumbnail style as Syncfusion Rotator control:

![Syncfusion thumbs](https://help.syncfusion.com/xamarin/sfrotator/images/thumbnail.png)

Thanks in advance

**Comment by AndreiMisiukevich** [comment]
Hi @stealthcold 
Very good question.
Yes, you can achieve it yourself
But perhaps it can be great enhancement
-
So, i think, we can create ThumbnailControl
Is it urgent for you? You can try to do it yourself (Add horizontal listView or scrollView with the same ItemsSource etc.)

**Comment by stealthcold** [comment]
Hi @AndreiMisiukevich ,

Would be a nice feature!
Right now I'm trying to combine inside a StackLayout the CarouselView with a CoverFlowView right below. 

My app needs such thing, but I can release without it by now.

Thanks,

**Comment by stealthcold** [comment]
Hey @AndreiMisiukevich,

I had no success with my Stack + Carousel + CoverFlowView idea. ☹️
The CoverFlowView  doesn't have an "ItemTapped" event for me to link with the selectedIndex change of de Carousel. And don't know why, the CoverFlowView got some weird behavior when showing the images from the ItemSource (not scolling correctly and flickering).

Do you plan implement the thumbnails? I'll wait for it.
As I said before, I can release my app without it now.

Thanks,

**Comment by AndreiMisiukevich** [comment]
@stealthcold hi, sorry for delay
Just tried to implement it with ListView -- no luck

I think, you can achieve it with HorizontalScrollView. Just put several items(images) with tapGesture to ScrollView.

I guess it's OK for you, if you don't have 10+ items in carousel.
As for virtualization...hm, i think CollectionView can help.

@Phenek sorry for disturbing :)
Are you still interested in supporting this repo (RE: CoverFlowView)

**Comment by stealthcold** [comment]
@AndreiMisiukevich 

Thanks for the suggestions! I'll take a look! 

Thanks,
