### ISSUE TITLE
[UWP] [XBOX] ParentScrollView does not work with typically scrolling with RS

### ISSUE THREAD

**Issue by JTOne123** [AndreiMisiukevich/CardView#145]
A user isn't able to scroll down with Right Stick (RS) if cursor over the image.

**Comment by AndreiMisiukevich** [comment]
@JTOne123 "IsPanInteractionEnabled = false" as workaround only... )

**Comment by JTOne123** [comment]
I run my app at Xbox console and get that issue, I cannot scroll down the page because of the issue.

The IsPanInteractionEnabled is not the case. The issue at the vertical scrolling.

**Comment by AndreiMisiukevich** [comment]
@JTOne123 yes, but IsPanInteractionEnabled should help, because it disables PanGesture. So, scroll should work.

As for xBox.. not sure, that i am keen to support it :)

**Comment by JTOne123** [comment]
Ideally, you should not support it, the same codebase)

I see your point about PanGesture but ideally, I want to save horizontal swiping.

-

Anyway, I did next renderer and it blocks horizontal swiping in PC but does nothing at Xbox :(
```
    public class ParentScrollViewRenderer : ScrollViewRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<ScrollView> e)
        {
            base.OnElementChanged(e);

            if(e.NewElement != null)
            {
                var carouselView = e.NewElement.Content.FindByName<CarouselView>("carouselView");
                if(carouselView != null)
                {
                    carouselView.IsPanInteractionEnabled = false;
                }
            }
        }
    }
```

**Comment by JTOne123** [comment]
Maybe you can suggest me another idea?

**Comment by AndreiMisiukevich** [comment]
@JTOne123 let's leave it as workaround and close this issue

**Comment by JTOne123** [comment]
It is the workaround at very limited situations like mine.

I guess, the root issue in XF itself.
