### ISSUE TITLE
Images in CarouselView have low quality.

### ISSUE THREAD

**Issue by nimashshz** [AndreiMisiukevich/CardView#146]
Hi,
CarouselView decreases the quality of images.
I set IsViewCacheEnabled to false but didn't worked.
Please help me.

Thanks

**Comment by AndreiMisiukevich** [comment]
@nimashshz hi
It's impossible
What type of image do you use? 
What image control do you use?
What Image Aspect do you use?

Attach the sample please

**Comment by nimashshz** [comment]
Hi, Thanks for reply.
I using JPG image.
I using ffimageloading:CachedImage.
I using AspectFill. (I used all type of Aspect).

I used my image control without CarouselView with same size and Aspect.
I saw the difference of quality between of they.

This is my code:
`<cards:CarouselView x:Name="crvImages" HeightRequest="350" HorizontalOptions="FillAndExpand" FlowDirection="LeftToRight" BackgroundColor="#e73636" IsViewCacheEnabled="False" is>
                            <cards:CarouselView.ItemTemplate>
                                <DataTemplate>
                                    <ContentView>
                                        <ffimageloading:CachedImage Source="{Binding}" Aspect="AspectFill" HorizontalOptions="FillAndExpand"
                                                                    VerticalOptions="FillAndExpand" LoadingPlaceholder="resource://Jewelry.Images.LoadingImages.gif"
                                                                    ErrorPlaceholder="resource://Jewelry.Images.Warning.png" DownsampleToViewSize="true">
                                        </ffimageloading:CachedImage>
                                    </ContentView>
                                </DataTemplate>
                            </cards:CarouselView.ItemTemplate>

                            <controls:LeftArrowControl/>
                            <controls:RightArrowControl/>
                            <controls:IndicatorsControl/>
                        </cards:CarouselView>`

**Comment by AndreiMisiukevich** [comment]
Send this image to me
I will try to reproduce
Also try please with Image from Xamarin

**Comment by AndreiMisiukevich** [comment]
@nimashshz it's VERY strange, if images have lower quality than without carousel, as Carousel -- regular AbsoluteLayout. Let's check

**Comment by AndreiMisiukevich** [comment]
well, if you experience the same issue, try to use Xamarin.Forms.Image instead

**Comment by nimashshz** [comment]
Hi, Thanks for your attention.
I set DownsampleToViewSize="False" of ffimageloading:CachedImage and my problem was solved.

**Comment by AndreiMisiukevich** [comment]
@nimashshz cool!) thanks for feedback :)
