### ISSUE TITLE
macOS and WPF support

### ISSUE THREAD

**Issue by amirvenus** [AndreiMisiukevich/CardView#148]
I was just wondering if there will be any macOS and WPF support as most of my clients only use WPF and macOS version of the apps I create! (Wired right?!)

**Comment by AndreiMisiukevich** [comment]
It should work on these platforms now.. maybe with issues.

**Comment by amirvenus** [comment]
How would I enable it then?

Because it throws Exception even when the app is being started. 

It might be that I need to init it in Delegate or Main.cs files.

**Comment by AndreiMisiukevich** [comment]
Doesn't it work for Mac as well?
I will check.
But as for UWP.. I don't have Windows PC for debugging

**Comment by amirvenus** [comment]
macOS is of higher priority at the moment. 

Please advise what I need to add to the delegate/main.cs file.

**Comment by AndreiMisiukevich** [comment]
@amirvenus let me check it firstly please

**Comment by AndreiMisiukevich** [comment]
@amirvenus i created a sample for Mac
https://github.com/AndreiMisiukevich/CardView/tree/master/PanCardViewSample/MacOS

should work for WPF too
