### ISSUE TITLE
CarouselView.PositionChanging no longer being fired when manually setting CurrentIndex

### ISSUE THREAD

**Issue by Nixon-Joseph** [AndreiMisiukevich/CardView#15]
In version 1.4.0 and 1.4.1 I'm no longer getting any event on `CarouselView.PositionChanging` when manually setting the `CurrentIndex`. Is this intentional?

**Comment by Nixon-Joseph** [comment]
Downgrading to 1.3.9 works. Will use it for now.

**Comment by Nixon-Joseph** [comment]
Nevermind, not getting it on Android in 1.3.9... Just cleaned and rebuilt project, still not getting it. Not sure what's happening, but not certain it's the plugin. Trying some things.

**Comment by Nixon-Joseph** [comment]
Was able to get around it by running the logic I need to manually whenever I update that index, so non-critical.

**Comment by AndreiMisiukevich** [comment]
Hi
Yes, I did it intentionally.
Because I need to differentiate, whether it hand's changing or autonavigating..
So, I added two new categories

AutoNavigationStartedCommand
AutoNavigationStarted //event

AutoNavigationEndedCommand
AutoNavigationEnded //event

**Comment by AndreiMisiukevich** [comment]
It's regarding to one plugin's feature..namely ability to manage prev/next/current card by hands..

Check this class **CardsSampleCustomView** in samples. As you can see, it hasn't got any Items collection. PrevContextProperty/NextContextProperty/CurrentContextProperty manage it.

So.. we need to know exactly if it was autonavigating or swipe gesture, because we need to know, if we should change contexts or no)

Sorry for my English.. but i hope it's clear)

**Comment by Nixon-Joseph** [comment]
Sounds good to me, thanks!

So in your project, the term 'Auto Navigating' is just referring to the index being set manually in the code? 

I had guessed that it meant there were some way to make it automatically start scrolling through the views on a timer.

**Comment by AndreiMisiukevich** [comment]
So in your project, the term 'Auto Navigating' is just referring to the index being set manually in the code?

yes

**Comment by AndreiMisiukevich** [comment]
So, if CurrentIndex changing from ViewModel, autonavigating will start (or just from code) 
OR
If you use "Context Feature"... if you change CurrentContext from code too

**Comment by AndreiMisiukevich** [comment]
I think, i can close this issue.
