### ISSUE TITLE
pancardview disappears on InitializeComponent()

### ISSUE THREAD

**Issue by amirvenus** [AndreiMisiukevich/CardView#153]
Hi,

I have a need to call InitializeComponent() inside the OnAppearing() override but when I do that, it disappears the pancardview I use.

Please advise.

**Comment by AndreiMisiukevich** [comment]
@amirvenus can you provide small sample project?

**Comment by AndreiMisiukevich** [comment]
@amirvenus hi, tested on my sample and it works fine

![image](https://user-images.githubusercontent.com/10124814/50818123-22d4a100-1337-11e9-8e11-e65e085a0579.png)


Can you provide more info? Or it would be better to create reproduction sample.
Seems you missed something on your side :)

**Comment by amirvenus** [comment]
I will provide you with my code later on but in your code if you call InitializeComponent in Constructor as well as on OnAppearing override, you will see what I mean.

**Comment by AndreiMisiukevich** [comment]
oh, okay)
i will check it)

**Comment by AndreiMisiukevich** [comment]
@amirvenus but why you call it twice ?

**InitializeComponent** creates controls and sets up named variables (x:Name)

Are you sure you need to do it twice??

**Comment by amirvenus** [comment]
Thank you for your response and the amazing code! I really love it!

The reason is that imagine I have a Cart icon on top and when taps on it, I PushModalAsync to the Cart page and then user might delete items from the cart and PopModalAsync back to the back that contains the cardsview. 

So far everything is ok, but I will need to refresh the colour binding of that Cart icon so that if there is nothing in the cart, the colour goes back to black. 

The problem is that unless I use Init again on the constructor and OnAppearing() the colour property will not get refreshed (because I don't have a setter in the viewmodel so I can INotifyPropertyChanged it!)

I have tried setting BindingContext to null and then again back to SInglenton.Instance (which is my viewmodel) and it works fine and the cart's colour updates, but it crashes on iOS without any helpful exception!

So that's why I need to call InitializeComponent twice to ensure the Bindings do get refreshed.

**Comment by AndreiMisiukevich** [comment]
hm, you can remove binding and set it again in OnAppearing

```csharp
control.RemoveBinding(BackgroundColorProperty);
control.SetBinding(BackgrounColorProperty, "Path");
```

I am sure it's something too easy :) if you want, i can assist you to solve your problem without calling Initialize method each onAppearing

And i haven't realized what you meant "I don't have a setter in the viewmodel".
How do you bind color to viewModel ? ObservableCollection with converter?

**Comment by amirvenus** [comment]
This is what I have:

`        private ObservableCollection<ProductNew.Obj> _carts = new ObservableCollection<ProductNew.Obj>();
        public ObservableCollection<ProductNew.Obj> Carts {
            get => _carts;
            set
            {
                _carts = value;
                Change(nameof(Carts));
                Change(nameof(CartsColour));
                Change(nameof(TotalCart));
            }
        }

        public Color CartsColour
        {
            get
            {

                if (Carts.Count > 0)
                return Color.SpringGreen;

                return Color.Black;
            }
        }


        public decimal TotalCart
        {
            get
            {
                if (Carts.Count > 0)
                    return Carts.Sum(x => x.ActualPrice);

                return 0.00m;
            }
            set
            {
                TotalCart = value;
                Change(nameof(TotalCart));
            }

        }
`

**Comment by AndreiMisiukevich** [comment]
@amirvenus did it help?

**Comment by amirvenus** [comment]
> @amirvenus did it help?

Thanks I will give that a try and let you know if there problem is still there.

**Comment by AndreiMisiukevich** [comment]
@amirvenus deal
