### ISSUE TITLE
IndicatorsControl visible

### ISSUE THREAD

**Issue by angelru** [AndreiMisiukevich/CardView#154]
Hello, great control...

I have one issue, the control IndicatorsControl only visible when the property ToFadeDuration is higher 0.

I don't understand, How I do for that always visible?

>         <cards:CarouselView HeightRequest="200" ItemsSource="{Binding PhotoItem}">
>             <cards:CarouselView.ItemTemplate>
>                 <DataTemplate>
>                     <ffimageloading:CachedImage HeightRequest="200" Aspect="Fill" DownsampleToViewSize="true" 
> 			                        Source="{Binding .}">
>                     </ffimageloading:CachedImage>
>                 </DataTemplate>
>             </cards:CarouselView.ItemTemplate>
>             <controls:IndicatorsControl  />
>         </cards:CarouselView>

**Comment by AndreiMisiukevich** [comment]
Hi
Have you tried latest version?
What version do you use ?

**Comment by angelru** [comment]
I'm using the lasted version: 1.6.8, 
if add the arrows (left and right) is visible, but only IndicatorsControl not visible

**Comment by AndreiMisiukevich** [comment]
Thanks, I check it

**Comment by AndreiMisiukevich** [comment]
@angelru 

![image](https://user-images.githubusercontent.com/10124814/50958255-564b3300-14d1-11e9-9170-e8d405ec86e8.png)


it's visible for iOS. What platform did you test?

**Comment by angelru** [comment]
I tested in emulator with android 9.0. With physical device with android 8.0 it's visible.

**Comment by AndreiMisiukevich** [comment]
@angelru ok great
Try to play with **WidthRequest** and **HeightRequest** or ```AbsoluteLayout.SetLayoutFlags``` and ```AbsoluteLayout.SetLayoutBounds``` as CardsView/CarouselView is AbsoluteLayout and you can set measure of you indicators yourself, but keep in mind that IndicatorsControl has:
```Margin = new Thickness(0, 20)``` by default

**Comment by AndreiMisiukevich** [comment]
@angelru or probably it's emulator specific issue..
Closing for now. Keep me posted :)

**Comment by AndreiMisiukevich** [comment]
@angelru me too :(

Are you able to play with setting size ?
