### ISSUE TITLE
Style doesn't affect IsCyclical & MoveWidthPercentage properties

### ISSUE THREAD

**Issue by tdoell** [AndreiMisiukevich/CardView#156]
Styles are not applying in the CarouselView class. **Have not tried CardsView**.

This is the style I have been trying to apply.

```xaml
<Style TargetType="panCardView:CarouselView">
    <Setter Property="IsCyclical" Value="False"/>
</Style>
```

In trying this, I have tried to use the style as an `Implicit`, `Explicit` and referencing it by using the `StaticResource` and giving it a `x:Key` to reference the style by. None of the methods of applying a style works.

**P.S.** Styling the `IndicatorControl` does work and works very well.

**P.P.S** Love the package though! Keep up the good work

**Comment by tdoell** [comment]
Looking more into it, it seems like the style is being applied, because I can change the `BackgroundColor` via the style. Since the `IsCyclical` and 2 other properties are being set in the constructor of the `CarouselView` as default values, that will **overwrite** any style applied that modifies any of those 3 properties.

**Comment by AndreiMisiukevich** [comment]
@tdoell nice catch! Thanks for the info.
Hm, how can we solve it? Any ideas?

**Comment by tdoell** [comment]
Some coworkers and I have come up with a solution in a package we have made for work, because we experienced the same issue. I can provide a pull request either this afternoon or in the morning with the proposed fix.

**Comment by AndreiMisiukevich** [comment]
@tdoell it would be interesting to see it.
But it looks like XF issue.

**Comment by AndreiMisiukevich** [comment]
@tdoell i found a workaround - Force set Style's properties

**Comment by tdoell** [comment]
The solution we came up with is to provide an instance method in the `CardsView` class that `CarouselView` or another view can override that provides the default value for the properties.

Then in the **BindableProperty.Create** declarations, you would refer to the bindable instance and call the default value method.

**Example**
```c#
public static readonly BindableProperty IsCyclicalProperty = BindableProperty.Create(nameof(IsCyclical), typeof(bool), typeof(CardsView), defaultValueCreator: (bindable as CardsView).GetIsCyclicalDefaultValue());

private virtual bool GetIsCyclicalDefaultValue() => false;
```

Then the **CarouselView** class could override that method and provide its own default value.

**Comment by AndreiMisiukevich** [comment]
@tdoell cool. Do you want to make PR ?

**Comment by AndreiMisiukevich** [comment]
```csharp
public static readonly BindableProperty MoveWidthPercentageProperty = BindableProperty.Create(nameof(MoveWidthPercentage), typeof(double), typeof(CardsView), defaultValueCreator: b => b.AsCardsView().DefaultMoveWidthPercentage);

        protected virtual double DefaultMoveWidthPercentage => 0.325;
```

**Comment by tdoell** [comment]
Yeah I can make a PR for those 3 properties if you would like. And I can make default value as properties like you just specified with the `DefaultMoveWidthPercentage` example.

Okay I will get to work on that.

**Comment by AndreiMisiukevich** [comment]
@tdoell for those 2 properties :) as the first one wan't designed by me. It's Layout's own. We cannot modify it.
