### ISSUE TITLE
CoverFlow AutoAnimations

### ISSUE THREAD

**Issue by AndreiMisiukevich** [AndreiMisiukevich/CardView#158]
Currently it's impossible to animate CoverFlow items by changing **SelectedIndex** or **SelectedItem**.

Need to adjust

**Comment by AndreiMisiukevich** [comment]
@GabrielSchimidtMylla 
Sorry, what exactly do you mean?

**Comment by GabrielSchimidtMylla** [comment]
@AndreiMisiukevich  I'm sorry, I'm using a more accurate translator: during the ItemAppearing event I would like to access the previous and next view

**Comment by GabrielSchimidtMylla** [comment]
DataTemplate

**Comment by AndreiMisiukevich** [comment]
@GabrielSchimidtMylla 

var index = coverFlowView.SelectedIndex;
var current = coverFlowView.CurrentView;
var next = coverFlowView.Children.FirstOrDefault(x => x.BindingContext == coverFlowView[index+1]);
var prev = coverFlowView.Children.FirstOrDefault(x => x.BindingContext == coverFlowView[index-1]);

Something like this, maybe

**Comment by GabrielSchimidtMylla** [comment]
Thank you for the quick reply, I'll implement
