### ISSUE TITLE
is it possible to override swipe ?

### ISSUE THREAD

**Issue by ldw9981** [AndreiMisiukevich/CardView#16]
i want to distinguish vertical swipe and horizontal swipe.
how can i make cardview worked only when absX is lager than absY  ?
and i want my app use  vertical swipe event.

i wrote code like this . this code work to swipe on UWP but it doesnt work to swipe on Andriod.

namespace PanCardViewSample.Views
{
    public class FlashCardsView : CardsView
    {
        double x, y;
        public FlashCardsView()
        {
            this.IsPanEnabled = false;
            var panGesture = new PanGestureRecognizer();
            panGesture.PanUpdated += OnPanUpdated_FlashCardsView;
            GestureRecognizers.Add(panGesture);
  
        }

        public void OnPanUpdated_FlashCardsView(object sender, PanUpdatedEventArgs e)
        {
            int id = (int)e.StatusType;
            switch (e.StatusType)
            {
                case GestureStatus.Started:
                    x = 0;
                    y = 0;
                    break;
                case GestureStatus.Running:
                    x += e.TotalX;
                    y += e.TotalY;
                    break;

                case GestureStatus.Completed:

                    var absX = Math.Abs(x);
                    var absY = Math.Abs(y);

                    if(absX > absY)
                    {
                        if (x < -20)
                            ProcessGestureLeft();
                        else if (x > 20)
                            ProcessGestureRight();
                    }
                    else
                    {
                        if (y < -20)
                            ProcessGestureUp();
                        else if (y > 20)
                            ProcessGestureDown();
                    }
                    break;
            }
        }

        private void ProcessGestureUp()
        {
            System.Diagnostics.Debug.WriteLine("ProcessGestureUp");
        }

        private void ProcessGestureDown()
        {
            System.Diagnostics.Debug.WriteLine("ProcessGestureDown");
        }
        private void ProcessGestureLeft()
        {
            System.Diagnostics.Debug.WriteLine("ProcessGestureLeft");
            this.CurrentIndex -= 1;
        }

        private void ProcessGestureRight()
        {
            System.Diagnostics.Debug.WriteLine("ProcessGestureRight");
            this.CurrentIndex += 1;
        }
    }
}

**Comment by AndreiMisiukevich** [comment]
Hi, thanks for feedback
So, you want to disable default animation and just handle swipes (vertical and horizontal), don't you?

**Comment by AndreiMisiukevich** [comment]
Check this class https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView.Droid/CardsViewRenderer.cs

Try to create your own renderer which will be extended from that one and write such code

```
public override bool OnInterceptTouchEvent(MotionEvent ev)
{
return true;
}

public override bool OnTouchEvent(MotionEvent e)
{
return true;
}
```

**Comment by ldw9981** [comment]
i tried to understand cross platform swiping in this project and rewrite code. 

`namespace PanCardViewSample.Views
{
    public class FlashCardsView : CardsView
    {
        double accX, accY;
        public FlashCardsView()
        {
            
        }

        protected override void OnTouchStarted()
        {
            accX = 0;
            accY = 0;
        }
        protected override void OnTouchChanged(PanUpdatedEventArgs e)
        {
            var absX = Math.Abs(e.TotalX);
            var absY = Math.Abs(e.TotalY);

            accX += e.TotalX;
            accY += e.TotalY;
        }
        protected override void OnTouchEnded(bool? isSwiped)
        {
            //base.OnTouchEnded(isSwiped);
            var absAccX = Math.Abs(accX);
            var absAccY = Math.Abs(accY);

            var length = Math.Sqrt(absAccX * absAccX + absAccY * absAccY);

            if (length > 30)
            {
                if (absAccX > absAccY)
                {
                    if (accX < 0)
                        ProcessGestureLeft();
                    else if (accX > 0)
                        ProcessGestureRight();
                }
                else
                {
                    if (accY < 0)
                        ProcessGestureUp();
                    else if (accY > 0)
                        ProcessGestureDown();
                }
            }
        }

        private void ProcessGestureUp()
        {
            System.Diagnostics.Debug.WriteLine("ProcessGestureUp");
        }

        private void ProcessGestureDown()
        {
            System.Diagnostics.Debug.WriteLine("ProcessGestureDown");
        }
        private void ProcessGestureLeft()
        {
            System.Diagnostics.Debug.WriteLine("ProcessGestureLeft");
            CurrentIndex -= 1;
        }

        private void ProcessGestureRight()
        {
            System.Diagnostics.Debug.WriteLine("ProcessGestureRight");
            CurrentIndex += 1;
        }
        private void ProcessGestureTap()
        {
            System.Diagnostics.Debug.WriteLine("ProcessGestureTap");            
        }

    }
}`

**Comment by AndreiMisiukevich** [comment]
Thanks, I will look through this.

**Comment by AndreiMisiukevich** [comment]
I checked it
Your realization doesn't consider gesture time..

So

protected override void OnTouchChanged(PanUpdatedEventArgs e)
    {
        var absX = Math.Abs(e.TotalX);
        var absY = Math.Abs(e.TotalY);

        accX += e.TotalX;
        accY += e.TotalY;
    }

It can be very long operation.. but swipe must be rather fast.
So, I think it would be better to leave current solution for detecting swipes.

As for UP/DOWN swipes.. this pack doesn't support it for now.. maybe later.
So, now, you can select horizontal or vertical direction by setting Rotation..
