### ISSUE TITLE
CoverFlowView IsCyclical crash

### ISSUE THREAD

**Issue by InstanceGG** [AndreiMisiukevich/CardView#160]
Setting  IsCyclical to false in the CoverFlowView causes a null exception.

**Comment by AndreiMisiukevich** [comment]
@InstanceGG thank you, i will check it

**Comment by AndreiMisiukevich** [comment]
@InstanceGG could you please provide base sample? Or it is possible to reproduce on test one?

**Comment by InstanceGG** [comment]
[CoverFlowSample.zip](https://github.com/AndreiMisiukevich/CardView/files/2816860/CoverFlowSample.zip)
