### ISSUE TITLE
CoverFlowView next item does not render

### ISSUE THREAD

**Issue by Eldin66** [AndreiMisiukevich/CardView#162]
When I use the Coverflow example the next item on the CoverFlow Carroussel does not render untill I touch the screen. 

Your demo project does not have this issue. Did I forget something?

**Comment by AndreiMisiukevich** [comment]
Hi
Did you copy whole sample ?

**Comment by Eldin66** [comment]
Hi @AndreiMisiukevich 
Yeah, I copy pasted your xaml. Anyway, I upgraded the package to 2.0.1 and it works now. So consider it fixed I guess. Thank you for trying to help!

**Comment by Eldin66** [comment]
Seems like this issue has not been resolved. The issue only happens when there are 4 items or less in the collection. It does not happen with 5 or more items. 

Here is a sample: https://github.com/Eldin66/CoverflowSample

**Comment by AndreiMisiukevich** [comment]
Super, thanks
I will check)

**Comment by AndreiMisiukevich** [comment]
@Eldin66 2.0.2 version :)

**Comment by Eldin66** [comment]
@AndreiMisiukevich Thats fast. Thank you for the amazing work!

**Comment by Hasanajouz** [comment]
I wanted to test card CardFlowView for the first time so i set a small example but i have this issue.
i set the data statically 
and this is what i wrote

<panCardView:CoverFlowView 
                Grid.Row="1"
                PositionShiftValue="90"
                IsCyclical="True"
                SlideShowDuration="3000"
                IsAutoNavigatingAimationEnabled="True"
                IsAutoInteractionRunning="false"
                IsUserInteractionRunning="false"
                SelectedIndex="1"
                >
                <panCardView:CoverFlowView.ItemsSource>
                    <x:Array Type="{x:Type View}">
                        <ContentView Padding="60,0,60,0">
                            <Frame 
                                VerticalOptions="Center"
                                HorizontalOptions="Fill"
                                Padding="0" 
                                HasShadow="false"
                                IsClippedToBounds="true"
                                CornerRadius="10">
                                <forms:CachedImage Source="profile_background.jpg" Aspect="Fill"/>
                            </Frame>
                        </ContentView>
                        <ContentView Padding="60,0,60,0">
                            <Frame 
                                VerticalOptions="Center"
                                HorizontalOptions="Fill"
                                Padding="0" 
                                HasShadow="false"
                                IsClippedToBounds="true"
                                CornerRadius="10">

                                <forms:CachedImage Source="profile_background.jpg" Aspect="Fill"/>
                            </Frame>
                        </ContentView>
                        <ContentView Padding="60,0,60,0">
                            <Frame 
                                VerticalOptions="Center"
                                HorizontalOptions="Fill"
                                Padding="0" 
                                HasShadow="false"
                                IsClippedToBounds="true"
                                CornerRadius="10">

                                <forms:CachedImage Source="profile_background.jpg" Aspect="Fill"/>
                            </Frame>
                        </ContentView>
                    </x:Array>
                </panCardView:CoverFlowView.ItemsSource>
                
            </panCardView:CoverFlowView>

**Comment by Hasanajouz** [comment]
![Annotation 2019-05-05 182643](https://user-images.githubusercontent.com/11570997/57197101-6c3ea100-6f63-11e9-8f29-9737ca65ee4a.jpg)

**Comment by Hasanajouz** [comment]
If I add five items manually it is working fine.
So i think the problem is not fixed if you add the itemsource within xaml

**Comment by AndreiMisiukevich** [comment]
IsAutoInteractionRunning="false"
IsUserInteractionRunning="false"

No need to set them

**Comment by AndreiMisiukevich** [comment]
@Hasanajouz could you please create small sample for me ?

**Comment by Hasanajouz** [comment]
@AndreiMisiukevich of course i will create one and send it as zip file

**Comment by Hasanajouz** [comment]
because i tried to set 
IsAutoInteractionRunning="True"
IsUserInteractionRunning="True"
but nothing changed

**Comment by Hasanajouz** [comment]
[cvtest.zip](https://github.com/AndreiMisiukevich/CardView/files/3145833/cvtest.zip)

@AndreiMisiukevich 
please check this simple solution. with three content views
just run it and swip once
wait it to auto swip and you will notice the bug.
add two more content views. this will not happen.

**Comment by AndreiMisiukevich** [comment]
@Hasanajouz I think I know what is the issue.. I will check

**Comment by AndreiMisiukevich** [comment]
Why don't you want to use ItemTemplate for views creating ?

I presume, this issue will go with it.

**Comment by Hasanajouz** [comment]
yes of course.
but i was just reporting to help you improve the plugin.
Regards.

**Comment by AndreiMisiukevich** [comment]
@Hasanajouz I appreciate it :)

I am just thinking about this issue.. seems it's almost impossible to fix.
Because views are cycled.. and system tries to use the same card from both sides (left, right).. 
Well, you see only 3 cards at the same time, but system works with 5 ones. Because we need to "pre-render" possible next/prev cards. Hope it makes sense

**Comment by AndreiMisiukevich** [comment]
@Hasanajouz yes.. unfortunately it's impossible to fix. Check next sample

[left_card_1]-[left_card_0)-(current_card)-(right_card_0]-[right_card_1]

[] - invisible
() - visible

So, as you can see, at one time we should show current, and two sides cards (also we should pre-render two more cards (from each side)

So, when we don't use ItemTemplate and have only 3 items.. it's impossible to show one View in two places simultaneously.

So, in such cases you should use itemTemplate (DataTemplate/DataTemplateSelector)

Hope it's clear
