### ISSUE TITLE
Default to last item in collection

### ISSUE THREAD

**Issue by modplug** [AndreiMisiukevich/CardView#163]
One thing I would like to see supported is to be able to set SelectedItem to the last item in the collection upon an ItemsSource change or a reset action for INotififyCollectionChanged.

An example would be a collection of months within a year and you want to start at the last month and navigate "backwards in time".

I've actually run into this issue with two apps recently and my "fix" has been to wait until the CarouselView has finished rendering before setting SelectedItem to the last item in the source collection. In reality this is not a fix, just an ugly workaround.

Keep up the good work!

**Comment by AndreiMisiukevich** [comment]
Hi @modplug could you please create small sample for demonstrating this issue?

I think, i understood your point.. but afraid to be wrong.

So, you try to set SelectedItem and ItemsSource simultaneously and it doesn't work, right?

```csharp
new CarouselView
{
   ItemsSource = list,
   SelectedItem = list.Last()
};
```

can you try to work around like:

```
carouselCiew = new CarouselView();
carouselCiew.ItemsSource = list;
//await Task.Delay(5); // and with it too
carouselCiew.SelectedItem = list.Last();

**Comment by AndreiMisiukevich** [comment]
Hey @modplug 

Have you tried it?

```csharp
carouselView.ItemsSource = list;
carouselView.SelectedItem = list.LastOrDefault();
```

**Comment by AndreiMisiukevich** [comment]
There is a problem now.
![image](https://user-images.githubusercontent.com/10124814/52308060-a4523a00-299c-11e9-914a-96d5ffac7d20.png)

We need to know real ItemsSource before setting SelectedItem/SelectedIndex ..

**Comment by AndreiMisiukevich** [comment]
> Hey @modplug
> 
> Have you tried it?
> 
> ```cs
> carouselView.ItemsSource = list;
> carouselView.SelectedItem = list.LastOrDefault();
> ```

I presume, it can be good workaround. Just set properties in proper order.
