### ISSUE TITLE
Coverflow updating itemssource buggy

### ISSUE THREAD

**Issue by Eldin66** [AndreiMisiukevich/CardView#164]
Sorry to bother you again.

When the CoverFlowView ItemsSource gets replaced the view acts really buggy. Sometimes a card stays in view on top of the new cards. Sometimes one stays in view in the previous or next item. Not sure if I am doing something wrong but here is a sample again: https://github.com/Eldin66/CoverFlowRefreshBugSample

**Comment by AndreiMisiukevich** [comment]
ok, thanks, i will check

**Comment by AndreiMisiukevich** [comment]
for now without animation

**Comment by Eldin66** [comment]
Hmm, the bug still happens. After refresh the previous and/or next item gets stuck after a couple swipes.

**Comment by AndreiMisiukevich** [comment]
@Eldin66 with latest version?

**Comment by AndreiMisiukevich** [comment]
@Eldin66 hmm, just updated CardsView to 2.0.3 and tried on iphone simulator https://github.com/Eldin66/CoverFlowRefreshBugSample this sample

Everything works fine, are you sure, you use latest version?

**Comment by Eldin66** [comment]
Yeah I tried it with 2.0.3 also on an iPhone simulator. I'll try it again in a few hours and let you know.

**Comment by Eldin66** [comment]
@AndreiMisiukevich You were right. It did not happen on my sample, however for some reason it did still happen on our app. I cannot figure out why. But, calling clear() on the item collection before assigning new items seems to resolve the issue. Thank you again for your hard work!

**Comment by AndreiMisiukevich** [comment]
@Eldin66 hm.. maybe try to remove bin/obj/packages clean/rebuild/restore and also remove CardsView nuget from proj and add again.. very strange
