### ISSUE TITLE
Question with SetBinding

### ISSUE THREAD

**Issue by anathemus** [AndreiMisiukevich/CardView#167]
Attempting to set the binding of the TextProperty of a Label in this line:

`            slideHeader.SetBinding(Label.TextProperty, "HeaderText");`

Which references the following:

`public class CarouselSampleScrollViewModel
	{
        
		public CarouselSampleScrollViewModel()
		{
            Items = new List<KeyValuePair<string, string>>();
            Items.Add(new KeyValuePair<string, string>("HeaderText", "Track your Coverages"));
            Items.Add(new KeyValuePair<string, string>("HeaderText", "Get Solid Advice"));
            Items.Add(new KeyValuePair<string, string>("HeaderText", "Find Savings Fast"));
        }

		public List<KeyValuePair<string, string>> Items { get; }
	}`

I am getting the correct number of slides (3), but no text is appearing. Any help would be appreciated.

Here are the referenced files:

https://github.com/anathemus/CardViewExperiments/blob/master/PanCardViewSample/PanCardViewSample/ViewModels/CarouselSampleScrollViewModel.cs

https://github.com/anathemus/CardViewExperiments/blob/master/PanCardViewSample/PanCardViewSample/Views/CarouselSampleSrollView.cs

**Comment by AndreiMisiukevich** [comment]
@anathemus hi)
Why do you use **KeyValuePair** ?)
KeyValue pair is instance with 2 properties { Key ; Value; }

So, in you sample, i guess, you should bind to Value

slideHeader.SetBinding(Label.TextProperty, "Value");

**Comment by anathemus** [comment]
Thank you! I'm still learning as a Junior Developer. I understand much better now!
