### ISSUE TITLE
Putting a partial view in a CarouselView doesn't work (PRISM)

### ISSUE THREAD

**Issue by lewcianci** [AndreiMisiukevich/CardView#168]
Hi,

Using Prism 7.5, and trying to put a Partial View in a CarouselView doesn't work.  The page is never navigated to.

I don't know if this is a Prism thing or a CardView thing... I spent a few hours trying to work out why my partial view wouldn't work though.

Attached a repro project.  CarouselView is on the main page with a partial view, and it is supposed to navigate there, but it never gets there. No exception or stack trace or anything.... it just never navigates.

[Prism.PartialViews.zip](https://github.com/AndreiMisiukevich/CardView/files/2886550/Prism.PartialViews.zip)

**Comment by lewcianci** [comment]
I would love to help with this, I see you've attached the "help wanted" flag.  Is there anything I can do?

**Comment by AndreiMisiukevich** [comment]
@lewcianci yep.
It would be awesome if you can debug your issue and find what is wrong.
It's very strange that there is such bug. I don't think it's on CardsView side.. because works fine with Image, CachedImage, ContentView etc.

**Comment by AndreiMisiukevich** [comment]
@lewcianci would you like to help with debugging your case ?)

**Comment by lewcianci** [comment]
I would but I don't know where to start, as the issue lays somewhere between Prism and CardView...

**Comment by AndreiMisiukevich** [comment]
don't see any issues from my side.
probably Partial Views it's something that isn't supported by this lib. Or you should ask Prism DEVs
