### ISSUE TITLE
Slow first appearance if you set the SlideShowDuration

### ISSUE THREAD

**Issue by ssotir** [AndreiMisiukevich/CardView#169]
If you set the SlideShowDuration the the first card takes SlideShowDuration time to appear the first time. You should not delay the first appearance.

**Comment by ssotir** [comment]
If you set the SlideShowDuration the the first card takes SlideShowDuration time to appear the first time. You should not delay the first appearance.

**Comment by AndreiMisiukevich** [comment]
Are you sure, that it works like you described?

**Comment by AndreiMisiukevich** [comment]
1) version of package
2) forms version
3) platform with issue and OS version
4) Sample
please

**Comment by ssotir** [comment]
Yes and to bypass it I've set the SlideShowDuration to lets say 1000 and then to the needed value of 6500. I am using the CoverFlowView. Latest forms 3.5. 

I have it in the XAML : 

<cards:CoverFlowView x:Name="Top10Carousel" PositionShiftValue="120" IsCyclical="True"
                                        BackViewsDepth="2" AreAnimationsEnabled="true" IsAutoInteractionRunning="false"
                                        IsUserInteractionRunning="true" Margin="0,0,0,5"
                                        ItemsSource="{Binding Top10List}" BackgroundColor="White"
                                        SlideShowDuration="700" HeightRequest="140"/>

**Comment by AndreiMisiukevich** [comment]
@ssotir why did you set all these properties?
IsCyclical="True" // true by default
BackViewsDepth="2" // 2 by default
AreAnimationsEnabled="true" // true by default
IsAutoInteractionRunning="false" // You must not set it by yourself... in next release setter will be private
IsUserInteractionRunning="true" // You must not set it by yourself... in next release setter will be private

Remove all them

**Comment by AndreiMisiukevich** [comment]
could you please provide small repro sample?

**Comment by ssotir** [comment]
Well I did a lot of testing with trial and error and those properties were left there. I will prepare it for you

**Comment by ssotir** [comment]
You have right. Something else was the problem. Everything is working fine!!!!! 

Thank you my friend.
