### ISSUE TITLE
Example to Display Previous/Next Items

### ISSUE THREAD

**Issue by zwilkin** [AndreiMisiukevich/CardView#171]
Hello,

Could you please provide documentation on how to properly set up the CoverFlowFiew to display a partial view of the previous/next item and make it seems to transition directly into that item?

When setting this up based on your example, currently, only 1 item is presented each swipe; not like visually represented in this photo...
![image](https://user-images.githubusercontent.com/9438425/53454243-8fddec00-39f4-11e9-89a4-ea1e63ebec6c.png)

**Comment by AndreiMisiukevich** [comment]
@zwilkin hm.
How it's possible?
Did you run my sample project?

**Comment by AndreiMisiukevich** [comment]
It would be great to see small reproduction sample here :)

**Comment by AndreiMisiukevich** [comment]
As for your question:
here is small doc https://github.com/AndreiMisiukevich/CardView/blob/master/docs/CoverFlowView.md

it must be your center view occupy all space.. try to add margins/paddings maybe.
Or just send me your sample :)

**Comment by zwilkin** [comment]
I figured out my issue. I was attempting to adjust the size of the internal frame which visually was working, however I forgot to set a padding on the internal ContentView to allow the previous/next items to "bleed" onto the page.

Amazing library, amazing support, great work man keep it up!

Please feel free to close this thread.

Zach Wilkin
zach@goeis.net | www.goeis.net

(352) 236-4500 Office
(610) 709-4292 Cell
(866) 861-3294 Fax

Executive Information Services, Inc.
1396 NE 20th Avenue, Suite 100
Ocala, FL 34470

________________________________

**Comment by AndreiMisiukevich** [comment]
@zwilkin i'm glad to hear it :)
Thx
