### ISSUE TITLE
Setting SelectedItem indexes to wrong item in Carousel

### ISSUE THREAD

**Issue by Magendanz** [AndreiMisiukevich/CardView#173]
Summary: If I set the SelectedItem (or SelectedIndex, for that matter), the Carousel control will index to the last item displayed, not the new SelectedItem.

I've confirmed that SelectedItem is being set to the correct item and I'm receiving an ItemAppearing event where it's still set correctly.  However, the control just animates back to the previously displayed item, whichever direction that was.

Workaround: You can get the correct item by swiping to an adjacent item and then swiping back.

Version: 2.0.3, tested on Android 8.1 and 9.0 simulator

**Comment by AndreiMisiukevich** [comment]
@Magendanz 

https://github.com/AndreiMisiukevich/CardView/issues/170
https://github.com/AndreiMisiukevich/CardView/issues/172

Are those issues the same?

**Comment by Magendanz** [comment]
No, my problem occurs even if IsCyclical is set to true.

**Comment by AndreiMisiukevich** [comment]
> No, my problem occurs even if IsCyclical is set to true.

is it possible to reproduce on iOS ?

**Comment by Magendanz** [comment]
Yes, it seems the behavior is the same on iOS.

**Comment by AndreiMisiukevich** [comment]
Thanks. I see the reason. I am keen to fix this issue.
Btw, you may use version 2.0.0
Seems, there is no such bug there

**Comment by Magendanz** [comment]
Excellent! Thanks, Andrei!

I'm not in a rush, so I'll probably hold my release until the fix is available.

**Comment by AndreiMisiukevich** [comment]
Check 2.0.4 version please

**Comment by Magendanz** [comment]
> Check 2.0.4 version please
Fixed!  Thanks for the quick turnaround, Andrei!
