### ISSUE TITLE
Default constructor not found for type PanCardView.Controls.IndicatorItemView using Full Linking

### ISSUE THREAD

**Issue by taublast** [AndreiMisiukevich/CardView#175]
CardsView 2.0.5
Forms 3.5.0.16..
tested on Android 6.0:

If i create everything in Xaml only then after full linking, user and sdk,  i get '

> System.MissingMethodException: Default constructor not found for type PanCardView.Controls.IndicatorItemView

'.

```
  <panCardView:CarouselView
                    x:Name="MyCarousel"
                    HorizontalOptions="FillAndExpand"
                    PropertyChanged="OnPropertyChanged_Carousel"
                    HeightRequest="350"
                    ItemsSource="{Binding Images}"
                    VerticalOptions="Start">
                    <panCardView:CarouselView.ItemTemplate>
                        <DataTemplate>
                            <ContentView>
                                    ...
                                </ContentView>
                        </DataTemplate>
                    </panCardView:CarouselView.ItemTemplate>
                    <controls1:LeftArrowControl/>
                    <controls1:RightArrowControl/>
                    <controls1:IndicatorsControl/> 
                </panCardView:CarouselView>
```

Adding a '`var preserveStuff = new IndicatorItemView();`' to somewhere solves this.
Knowing that we already have an added a 'CardsViewRenderer.Preserve()' seems the above line could be added inside the built-in Preserve() method.

**Comment by AndreiMisiukevich** [comment]
Hi
Yes.. would you like to make PR ?

**Comment by AndreiMisiukevich** [comment]
Hope it will be enough

**Comment by jwosty** [comment]
This seems to be cropping back up in an app I'm working on. We're getting an exception along the lines of:

    CardViewExtensions.CreateView (Xamarin.Forms.DataTemplate template)
    System.MissingMethodException: Default constructor not found for type PanCardView.Controls.IndicatorItemView

CardsView 2.6.3
Xamarin.Forms 4.7.0.1179
Android 9.0 (emulator) - API 28

Only happens in Release mode with linking and such enabled.

**Comment by AndreiMisiukevich** [comment]
@jwosty have you added ```CardsViewRenderer.Preserve();``` to MainActivity?
