### ISSUE TITLE
Is it possible to use CardView Nuget package in PanCardViewSample

### ISSUE THREAD

**Issue by AmKum** [AndreiMisiukevich/CardView#176]
I am using Visual Studio 2017 Community version and learning to use CardView.

I have reduced the PanCardViewSample solution to just have 3 projects
1. PanCardViewSample
2. PanCardViewSample.Droid
3. PanCardViewSample.iOS

Removed PanCardView project dependency from PanCardViewSample project.
Removed PanCardView.Droid reference from PanCardViewSample.Droid and PanCardView.iOS reference from PanCardViewSample.iOS project
Added NuGet package "CardView" version 2.0.5 in PanCardViewSample project.
Updated all the other NuGet packages to latest version.

**ISSUE:**
Now when I rebuild (tried multiple time, closed reopened VS2017) the PanCardViewSample solution I get Error:
_CS0246	The type or namespace name 'PanCardView' could not be found (are you missing a using directive or an assembly reference?)	PanCardViewSample.iOS	C:\Try\CardViewMaster\PanCardViewSample\iOS\AppDelegate.cs
CS0103	The name 'CardsViewRenderer' does not exist in the current context	PanCardViewSample.iOS	C:\Try\CardViewMaster\PanCardViewSample\iOS\AppDelegate.cs_

**EXPECTED:**
I followed https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/single-page?pivots=windows and created _TestPCV_ project and then added CardView Nuget package to it. It works fine when I added "using PanCardView.iOS;" and called "CardsViewRenderer.Preserve();" in AppDelegate.cs in _TestPCV.iOS_ project.

**SOME INVESTIGATION**
For _TestPCV_ sln, when building the full solution, it builds PanCardView.dll PanCardView.Droid.dll and PanCardView.iOS.dll 
C:\TestPCV>dir /s Pancardview*.dll
..
 Directory of C:\TestPCV\TestPCV\TestPCV.Android\obj\Debug\81\android\assets
03/17/2019  04:21 PM            79,360 PanCardView.dll
03/17/2019  04:21 PM           104,448 PanCardView.Droid.dll

 Directory of C:\TestPCV\TestPCV\TestPCV.Android\obj\Debug\81\linksrc
03/17/2019  04:21 PM            79,360 PanCardView.dll
03/17/2019  04:21 PM           104,448 PanCardView.Droid.dll

 Directory of F:\TestPCV\TestPCV\TestPCV.iOS\bin\iPhoneSimulator\Debug
03/15/2019  11:27 AM            79,360 PanCardView.dll
03/15/2019  11:29 AM             5,632 PanCardView.iOS.dll

For _PanCardViewSample_ sln it does not builds PanCardView.dll, PanCardView.Droid.dll and PanCardView.iOS.dll. Not sure what could be the issue and would need your help on how to change PanCardViewSample sample that would build the above 3 dlls.

Build Order is
_PanCardViewSample 
PanCardViewSample.iOS 
PanCardViewSample.Droid_

Build dependencies are also set PanCardViewSample project before iOS or Droid projects. PanCardViewSample is added as reference in both PanCardViewSample.Droid and PanCardViewSample.iOS project. 

--Thanks

**Comment by AndreiMisiukevich** [comment]
Hi
Why are you trying to do it?

**Comment by AmKum** [comment]
Wanted to build a sample using the release nuget package. This way I can seamlessly update to newer packages.

I build another project using cardview package and that is giving issues for OnPanUpdate call and I am not getting Completed or Canceled messages. So wanted to start from a Sample and see what could be the issue.

**Comment by AndreiMisiukevich** [comment]
Hm, you can debug without removing source code. Test it with refs. This way you will find the reason

**Comment by AmKum** [comment]
In my other project I am using CardView, NuGet package and it wouldn't be same if I used PanCardViewSample with PanCardView projects ref'd directly.

My assumption is that PanCardView, PanCardView.iOS and PanCardView.Droid projects are released as CardView NuGet package.

**Comment by AndreiMisiukevich** [comment]
Did you call CardsViewRenderer.Preserve ?

**Comment by AmKum** [comment]
Yes I have added that.
**MainActivity.cs**
```
    [Activity(Label = "MyOtherProject", 
              Icon = "@mipmap/icon", 
              Theme = "@style/MainTheme", 
              MainLauncher = true, 
              ScreenOrientation = ScreenOrientation.Portrait, 
              ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            global::Xamarin.Auth.Presenters.XamarinAndroid.AuthenticationConfiguration.Init(this, bundle);
            FFImageLoading.Forms.Platform.CachedImageRenderer.Init(enableFastRenderer: true);
            **CardsViewRenderer.Preserve();**

            global::Xamarin.Forms.Forms.Init(this, bundle);

            LoadApplication(new App());
        }
    }
```


###This to handle On_PanUpdated
**Items.xaml**
```
                        <control:CarouselView.ItemTemplate>
                        ..
                                <Frame.GestureRecognizers>
                                    <PanGestureRecognizer PanUpdated="On_PanUpdated" />
                                </Frame.GestureRecognizers>
                         ..
                        </control:CarouselView.ItemTemplate>

```
**Items.cs**
```
        public async void On_PanUpdated(object sender, PanUpdatedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("On_P: " + e.StatusType.ToString());

            View view = sender as View;
            switch (e.StatusType)
            {
                case GestureStatus.Started:
                    break;
                case GestureStatus.Running:
                    break;
                case GestureStatus.Canceled:
                case GestureStatus.Completed:
                default: // This is not required added to test under debugger 
                    break; // Set Breakpoint here
            }
        }
```

**Comment by AndreiMisiukevich** [comment]
I don't understand your goal
Why do you use pangesture ?

**Comment by AmKum** [comment]
I have a CarouselView control and in that I wanted to do special handling when gesture up or down is done. For left and right default is fine. Using gesture I want to do some calculation for gesture up and down.

**Comment by AndreiMisiukevich** [comment]
@AmKum hmm, https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs#L128

have you tried this event?

https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Enums/UserInteractionStatus.cs

**Comment by AndreiMisiukevich** [comment]
Also you can check my another package
https://github.com/AndreiMisiukevich/TouchEffect

it allows to detect touchStart and touchEnd etc.
