### ISSUE TITLE
Changing slides height

### ISSUE THREAD

**Issue by Snirdude** [AndreiMisiukevich/CardView#180]
Hello Andrei,

Is there a way to size each slide's height according to the content within the slide?
I made a listview within the slide and every slide has different amount of list items within.
Is it possible?

Thank you,
Snir

**Comment by AndreiMisiukevich** [comment]
hmmm, yes, why not?

**Comment by Snirdude** [comment]
I don't understand how to do it because right now the height of the slides stays the same.
When I swipe to a slide with a lot of items, the height is adjusted to the content. However, when I swipe to a slide with less items, the height doesn't adjust, it stays like before.

**Comment by AndreiMisiukevich** [comment]
Do you use in inside listView with recycle elements?
You need to call ForceUpdateSize i guess or use DataTemplateSelector

It's difficult to realize you goal without sample

**Comment by Snirdude** [comment]
Turns out it was something in my code that caused the unwanted behavior.
Thanks anyway for the quick reply.
