### ISSUE TITLE
Issue with CoverFlowView

### ISSUE THREAD

**Issue by IbrahimElshafey** [AndreiMisiukevich/CardView#183]
I have tabs page with two pages the first contains a  `CoverFlowView` that bind to a list in the view model and display a bunch of cards when I navigate to the other tab page and return back to page one the cards in `CoverFlowView`  overlapping on top of each other.

**Note**: the first time the page displayed there is no overlapping, and when I swipe item or tap the `CoverFlowView` it displayed correctly again.

This is the [image](https://drive.google.com/open?id=1zSR3hsk3N3d9r83HCYzWXqhDKvTvIskF) of what I described above.

**Comment by AndreiMisiukevich** [comment]
Hi) thanks for feedback
Could you please provide small sample)? it will help me :)

**Comment by IbrahimElshafey** [comment]
Thanks for your quick response, I'll create a sample and send it tomorrow.

**Comment by IbrahimElshafey** [comment]
When I try to create a sample an exception occurred when try to intilaize `CardsViewRenderer.Preserve();`, here is it:
`{System.TypeInitializationException: The type initializer for 'PanCardView.CardsView' threw an exception. ---> System.ArgumentException: Not a valid default value
Parameter name: defaultValue
  at Xamarin.Forms.BindableProperty..ctor (System.String propertyName, System.Type returnType, System.Type declaringType, System.Object defaultValue, Xamarin.Forms.BindingMode defaultBindingMode, Xamarin.Forms.BindableProperty+ValidateValueDelegate validateValue, Xamarin.Forms.BindableProperty+BindingPropertyChangedDelegate propertyChanged, Xamarin.Forms.BindableProperty+BindingPropertyChangingDelegate propertyChanging, Xamarin.Forms.BindableProperty+CoerceValueDelegate coerceValue, Xamarin.Forms.BindableProperty+BindablePropertyBindingChanging bindingChanging, System.Boolean isReadOnly, Xamarin.Forms.BindableProperty+CreateDefaultValueDelegate defaultValueCreator) [0x00072] in D:\a\1\s\Xamarin.Forms.Core\BindableProperty.cs:72 
  at Xamarin.Forms.BindableProperty.Create (System.String propertyName, System.Type returnType, System.Type declaringType, System.Object defaultValue, Xamarin.Forms.BindingMode defaultBindingMode, Xamarin.Forms.BindableProperty+ValidateValueDelegate validateValue, Xamarin.Forms.BindableProperty+BindingPropertyChangedDelegate propertyChanged, Xamarin.Forms.BindableProperty+BindingPropertyChangingDelegate propertyChanging, Xamarin.Forms.BindableProperty+CoerceValueDelegate coerceValue, Xamarin.Forms.BindableProperty+CreateDefaultValueDelegate defaultValueCreator) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableProperty.cs:132 
  at PanCardView.CardsView..cctor () [0x000e9] in <04d09958f98746d4b02c09a9054fbd9f>:0 
   --- End of inner exception stack trace ---
  at PanCardView.Preserver.Preserve () [0x00000] in <04d09958f98746d4b02c09a9054fbd9f>:0 
  at PanCardView.Droid.CardsViewRenderer.Preserve () [0x00000] in <4fd3ceafddf54a518129c196ab60c7fe>:0 
  at CoverFlowSample.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00051] in c:\users\ibrahim\source\repos\CoverFlowSample\CoverFlowSample\CoverFlowSample.Android\MainActivity.cs:29 }`

**Comment by AndreiMisiukevich** [comment]
@IbrahimElshafey did you change/add any bindable properties? it says, that there is mismatch of types there.

**Comment by AndreiMisiukevich** [comment]
I cannot replicate this issue

**Comment by IbrahimElshafey** [comment]
I created a sample but it doesn't happen I'll try again.

**Comment by AndreiMisiukevich** [comment]
@IbrahimElshafey ping me please with sample, if you create it :)

**Comment by bnSonic** [comment]
I have this problem with CoverFlowView too - it seems like the part on the screen isn't refreshed (the overlapping fragments of the previous/next view are left)

I just 
- created a new Xamarin Forms project,
- added the NuGet Package (Version 2.1.7),
- added the CoverFlowView to the MainPage together with a simple TemplateSelector. 
- I added a MyView.xaml/.cs (= ContentView) 
- and a ViewModel.
all very simple to test this control

I have copy/pasted the codes into the attached textfile - don't know how to easily attach the whole project without binaries etc - but the code really is a few lines, so it would be easy to read/copy paste into a new project.

[sample-code.txt](https://github.com/AndreiMisiukevich/CardView/files/3418652/sample-code.txt)

**Comment by AndreiMisiukevich** [comment]
@bnSonic create project, remove bin/obj, archive solution to zip and send me

**Comment by bnSonic** [comment]
Here we go :)

Attached is the project/solution
and 4 screenshots showing the phenomenon in the iOS Simulator
1 - the App start; there are 3 Views in this demo 
2 - first swipe to left - all looks good
3a - if you swipe right again to go back to the first view, you can see some artifact on the left side; looks like the overlapping part of that view isn't cleared
3b - if you swipe further the the left to go to the 3rd view, you see these artefacts on both sides - the rest of the first and the last view not beeing cleared/moved

Hope that helps
 
[CarouselTest.zip](https://github.com/AndreiMisiukevich/CardView/files/3420291/CarouselTest.zip)
![3b-swipe-left-see-overlapping-on-left-and-right-artefacts](https://user-images.githubusercontent.com/1857728/61683986-11be1100-ad18-11e9-90e1-1828ff3ed47c.png)
![3-swipe-right-again-see-artefact-left](https://user-images.githubusercontent.com/1857728/61683987-11be1100-ad18-11e9-9110-4b5a39faf7e7.png)
![2-swipe-left](https://user-images.githubusercontent.com/1857728/61683988-11be1100-ad18-11e9-928d-fc73d40bc52d.png)
![1-start](https://user-images.githubusercontent.com/1857728/61683989-11be1100-ad18-11e9-8d0e-3f66aa27dcae.png)

**Comment by AndreiMisiukevich** [comment]
great, i believe it will be easy to fix :)

**Comment by AndreiMisiukevich** [comment]
@bnSonic 
![image](https://user-images.githubusercontent.com/10124814/61916744-6351e000-af52-11e9-8a58-227f5ff7ca71.png)

**Comment by AndreiMisiukevich** [comment]
```csharp
    public class CarouselTS : DataTemplateSelector
    {
        private readonly DataTemplate _myViewTemplate = new DataTemplate(typeof(MyView));
        protected override DataTemplate OnSelectTemplate(object item, BindableObject container)
        {
            return _myViewTemplate;
        }
    }
```

**Comment by bnSonic** [comment]
You mean why do i create a new instance of the template?
That was a test because in the real app I plan to use different views depending on the data - so I was curious to see if that would have an impact on performance

**Comment by AndreiMisiukevich** [comment]
> You mean why do i create a new instance of the template?
> That was a test because in the real app I plan to use different views depending on the data - so I was curious to see if that would have an impact on performance

That is fine. But you made a mistake. You should create template only ONCE! Because template is not a view, it's like a factory

```csharp
public class CarouselTS : DataTemplateSelector
    {
        private readonly DataTemplate _view1Temp = new DataTemplate(typeof(View1));
        private readonly DataTemplate _view2Temp = new DataTemplate(typeof(View2));
        protected override DataTemplate OnSelectTemplate(object item, BindableObject container)
        {
            return item is ViewModel1 ?  _view1Temp : _view2Temp;
        }
    }
```

you should use it like this.

Does it make sense?

**Comment by bnSonic** [comment]
Hehe sure - but see:
I could’ve either typed a lot to add 10 templates and create them once - or, for the sake of a quick an dirty very first look at your controls, write a single line to create them while swiping :) where’s the difference in the context of this little demo? (As long as i dont swipe around for hours ;))

**Comment by AndreiMisiukevich** [comment]
> Hehe sure - but see:
> I could’ve either typed a lot to add 10 templates and create them once - or, for the sake of a quick an dirty very first look at your controls, write a single line to create them while swiping :) where’s the difference in the context of this little demo? (As long as i dont swipe around for hours ;))

Anyway you can use IsViewReusingEnabled = false, but DataTemplateSelector should return the same DataTemplate for particular item.

**Comment by bnSonic** [comment]
*LOL* - Well NOW i got you! Pardon me, i thought you found some bad style while debugging - But what you meant is: THIS bad style is causing the problem :D 

I changed it to 3 Templates that are created once - Problem gone m) 

… i just was lazy doing a little "is this a component i like to use"-test and what i got was a homemade problem … i feel soooo … well …

Thank you and have a nice weekend :) 👍

**Comment by AndreiMisiukevich** [comment]
Nice to hear) great
