### ISSUE TITLE
Mix of 2 CarouselView

### ISSUE THREAD

**Issue by xsethx** [AndreiMisiukevich/CardView#186]
Hello Andrei,
Can we have a mix of 2 controls you have create?
We want if is possible the CarouselFlowView for main display.
But we want if is possible the CarouselView the dots below the image display.
Do you think it's easy to set up?

Thank you for you help and you dev
Ludovic

**Comment by AndreiMisiukevich** [comment]
Hi, could you please show me mock up / image ?
What do you want to achieve?

**Comment by xsethx** [comment]
Hello, I made a model.
You think it's possible?
And as you can see I also made the two elements more visible on the sides.
Thank you for your help !
What attribute should I use to do this in the CoverFlowView?
![Mock_Image CarouselView](https://user-images.githubusercontent.com/49283207/55859829-27e20000-5b73-11e9-8044-c39812ab688f.png)

**Comment by AndreiMisiukevich** [comment]
IndicatorsControl :)

Just add it as child to your CoverFlowView or add anywhere and set your coverFlowView as bindingContext :)
