### ISSUE TITLE
System.InvalidOperationException: Cannot change ObservableCollection

### ISSUE THREAD

**Issue by shoeIT** [AndreiMisiukevich/CardView#189]
Hey Andrei,
I try to implement the orientation change in my app and there is an error coming up.
I'm not quite sure if its a CardView bug, but when you look at the call stack it seems to be an issue there or in XF. I use the latest version of both (2.0. 6 | 3.6.0.293080)

I have to different CardViews (Carousels) each in one page. When I change pages and then change my orientation to landscape an error occurs, I think it must be about the layout and the observable collections there, since I dont use any in this page where the error occurs.
(There are no problems if I don't change orientation)

```
System.InvalidOperationException: Cannot change ObservableCollection during a CollectionChanged event.

ObservableCollection`1[T].CheckReentrancy ()
ObservableCollection`1[T].MoveItem (System.Int32 oldIndex, System.Int32 newIndex)
ObservableCollection`1[T].Move (System.Int32 oldIndex, System.Int32 newIndex)
Layout.LowerChild (Xamarin.Forms.View view) D:\a\1\s\Xamarin.Forms.Core\Layout.cs:186
CardsView.SendChildrenToBackIfNeeded (Xamarin.Forms.View view, Xamarin.Forms.View topView)
CardsView.AddChild (Xamarin.Forms.View topView, Xamarin.Forms.View[] views)
CardsView.InitViews (PanCardView.Processors.ICardProcessor processor, PanCardView.Enums.AnimationDirection animationDirection, System.Collections.Generic.IEnumerable`1[T] bookedViews, System.Int32[] indeces)
CardsView.SetupPrevView (System.Int32 index)
CardsView.SetupBackViews (System.Nullable`1[T] index)
CardsView.SetCurrentView ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
```

**Comment by AndreiMisiukevich** [comment]
@shoeIT hi
small sample please

Children is observable collection. So, i think, it's XF bug indeed

**Comment by shoeIT** [comment]
thx I will se what I can do, its difficult to reproduce with a small sample

**Comment by AndreiMisiukevich** [comment]
@shoeIT hmmm probably we will have to call something in MainThread..

**Comment by PaulsonMac** [comment]
Ok, may I know which nuget package version this fix was applied..?

**Comment by shoeIT** [comment]
> Ok, may I know which nuget package version this fix was applied..?

the current one works fine, error is gone, thanks Andrei!

**Comment by PaulsonMac** [comment]
@shoeIT, thanks for the quick reply. I hope you have verified it correctly, because I couldnt do it...
