### ISSUE TITLE
ListView within CardView Card

### ISSUE THREAD

**Issue by thedjnova** [AndreiMisiukevich/CardView#19]
I have been working with CardView to produce a page system and found that having a ListView within a Card on Android has issues with the list items not being scrollable and also that Command binding on the ListView Items templates do not fire.

On iOS the problem does not exist, on further digging I found that the SelectedItemChanged also does not fire on Android.

Any ideas where I should look to patch this?

**Comment by thedjnova** [comment]
Sidenote: This is within a SceneView, but I find this is also appearing within the base CardView.

**Comment by AndreiMisiukevich** [comment]
@thedjnova Hi
SceneView hasn't been released yet..
I think, you meant CarouselView

So, for fixing this issue check readme (Workarounds section) https://github.com/AndreiMisiukevich/CardView/blob/master/README.md

**Comment by thedjnova** [comment]
Thanks for such a quick response, I have been using the following class.

https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/SceneView.cs

The ReadMe only covers the opposite situation of putting CardView inside a ScrollView/ListView, my issue is in attempting to do the opposite, a ListView inside CardView/SceneView.

Everything else works brilliantly apart from having to set the BindingContext on each card manually on a PositionChanged.

**Comment by AndreiMisiukevich** [comment]
Did you clone this repo? Because on Nuget (https://www.nuget.org/packages/CardsView) there are no such class (SceneView)

Could you pls provide your code?
I will check it later

**Comment by AndreiMisiukevich** [comment]
And try pls CarouselView instead of SceneView. Deal?)

**Comment by thedjnova** [comment]
Yes, I am running from your bleeding edge code, CardView wasn't enough for my use.

I will put together a demo of the issue now as can't share the entire codebase unfortunately.

**Comment by AndreiMisiukevich** [comment]
There is a problem.. Because SceneView isn't stable now. It hasn't been released. And I cannot guarantee that it will work perfect.. Now it isn't working at all.



But send you demo) I appreciate it

**Comment by thedjnova** [comment]
Here is a sample of the issue built using the NuGet version (Confirmation the issue exists deeper than SceneView, I love SceneView btw, very stable for my use case :)).

Running the iOS project will display 2 cards with ListViews, selecting a ListView Item will then throw an expected Exception.

Running the Android project will display the same 2 cards with the same ListViews, selecting a ListView Item does not throw the expected exception.

[AndreiSample.zip](https://github.com/AndreiMisiukevich/CardView/files/1924257/AndreiSample.zip)

**Comment by AndreiMisiukevich** [comment]
@thedjnova thanks
I will try to figure out what's the matter

**Comment by thedjnova** [comment]
Further investigation shows that the command will be fired on the first Card before any swipes have been made.

If you have swiped to another page, then the command is not triggered.

**Comment by AndreiMisiukevich** [comment]
I think, it can be Xamarin.Forms bug
Because, almost whole project's code is crossplatform...

**Comment by thedjnova** [comment]
Agreed, I have a feeling its related to placing ListViews within ScrollViews.

There is apparently now support within Xamarin.Android that resolves this in API 21+, as mentioned here.

https://stackoverflow.com/questions/6210895/listview-inside-scrollview-is-not-scrolling-on-android/6211286#6211286

If it is a case of it being related then with some luck we may be able to get this fixed.

I will be looking deeper into it tonight when I get home so I will keep you updated on if I find a solution.

**Comment by AndreiMisiukevich** [comment]
@thedjnova I noticed several strange moments in your sample
I will add demo project into my samples and try to debug it

**Comment by AndreiMisiukevich** [comment]
@thedjnova tell me pls your goal)
What do you want to achieve?)

Several different cards with ONE binding context from parent?

**Comment by AndreiMisiukevich** [comment]
@thedjnova I found the reason.
So, TextCell has bug..
Check the sample. I changed TextCell to ViewCell with label and it works.

**Comment by thedjnova** [comment]
Yes I think its safe to say the issue isn't within CardView.

As for the BindingContext, I was only using the single context for the time being as I was trying out CardsView before tearing the original view model apart within my project.

End game will be to have a different context for each card, the way its meant to be :)
