### ISSUE TITLE
Ability to swipe in both directions

### ISSUE THREAD

**Issue by nawidy** [AndreiMisiukevich/CardView#193]
Thanks as always for the consistent updates and support!
I’d like to be able to use this package to swipe left and right between items and then swipe up and down (deleting the item). Currently I’m doing this by overloading OnPanUpdated on a gesturerecognizer for frame, it be awesome to have native support for smoother animations/customizations for animation speed going up and down along with optionally deleting the item.

**Comment by AndreiMisiukevich** [comment]
@nawidy hi
Hm, it won't be super easy, but it's good idea to consider this possible enhancement :)

**Comment by nawidy** [comment]
Thanks @AndreiMisiukevich  as always for your prompt response!
The current method I have works with the exception of a quick swipe (I'm guessing because I'm using pan update). Also do you know if there's a difference between iOS and android for this swipe? my custom up swipe works nicely on iOS but on android the frame won't move much when trying to swipe up.
Thanks,
- Nawid

**Comment by AndreiMisiukevich** [comment]
@nawidy i think, that's due my renderer's code ... https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView.Droid/CardsViewRenderer.cs

So, that's why i said - it won't be super easy :)

I think, i will have to add one more property for managing possibility to swipe vertically..

**Comment by nawidy** [comment]
I see thanks for clarifying :)

**Comment by nawidy** [comment]
@AndreiMisiukevich, is this something that could be potentially worked on and be provided in the next 3 weeks or so?
Thank you for all of your support!

**Comment by AndreiMisiukevich** [comment]
@nawidy not sure..
BTW, you can try ItemSwiped event as well
