### ISSUE TITLE
How to set transparent background for CoverFlowView?

### ISSUE THREAD

**Issue by Skorska** [AndreiMisiukevich/CardView#196]

**Comment by AndreiMisiukevich** [comment]
Hi
What exactly do you mean here ?

IsClippedToBounds = false ?

More info please: actual/expected

**Comment by Skorska** [comment]
![Фотографии 2019-05-07 20 10 32](https://user-images.githubusercontent.com/2912287/57319044-5ddbbb00-7104-11e9-8995-f96b5a03fb1f.png)
Can you look at that picture? By default background of cover flow view is white. I can change color for any other colors but cannot do transparent.

**Comment by Skorska** [comment]
![Card - skorskaira@gmail com - Gmail - Google Chrome 2019-05-07 20 31 06](https://user-images.githubusercontent.com/2912287/57320339-61247600-7107-11e9-8039-854a3c09997a.png)

**Comment by AndreiMisiukevich** [comment]
weird..
Could you please provide small sample?
I presume it's bug in your code.

How did you put map under the coverflow ? Seems you put them inside stack layout, what is wrong.

You should use absolute layout

**Comment by AndreiMisiukevich** [comment]
Yeah, I am sure you uses wrong layout type.

Use absolute layout or grid instead

**Comment by Skorska** [comment]
Thanks for your help. I really appreciate this. Fixed.

**Comment by AndreiMisiukevich** [comment]
@Skorska cool :)
If you like this plugin, you may star 🌟 it )
