### ISSUE TITLE
It only works properly after I refresh the ItemsSource

### ISSUE THREAD

**Issue by jerryno6** [AndreiMisiukevich/CardView#197]
**I'm using VS 2019 for MAC, Xamarin.Forms 3.2.0.871581**

I used this library in my project, and I saw that, It only works properly if I refresh the ItemsSource.
For the first time of loading, it still had the peek for previous Item even when I was displaying the first Item.

I setup as below
 `               <cards:CoverFlowView 
                    IsViewCacheEnabled="false"
                    HeightRequest="180"
                    PositionShiftValue="70"
                    IsCyclical="false"
                    ItemsSource="{Binding Data.Value}">`

1. When it finished displaying on screen, I swipe left to see the 2nd item
=> it worked well
2. I swipe right to see 1st item
=> It displayed peek for previous item

=> expected: it should not display peek for previous item. because the 1st item does have previous item.

3. I click button refresh, to load data and binddata again. This time, it worked well.

**Comment by AndreiMisiukevich** [comment]
Hi,
Thanks for reporting

Why do you use IsViewCachingEnabled ?

Provide please sample. I will help to solve your case.

**Comment by jerryno6** [comment]
The reason why I set IsViewCachingEnabled="false" is that:
On my view, there is a Delete button, and if user click on it, the card would disappear. But afther that, when I refresh the ItemsSource, some items, it display white ( blank) and some Items it can display the view. 

It sounds like the issue only appear on my project. I will try to reproduce this issue on an empty xamarin project.

**Comment by AndreiMisiukevich** [comment]
@jerryno6 yeah)
It would be awesome, if you fork my repository, add code with issue, then send me branch name.
It will allow me to debug easily

**Comment by jerryno6** [comment]
[https://github.com/jerryno6/CardView/tree/197](https://github.com/jerryno6/CardView/tree/197)

Here is the branch that I have folked and commit some changes.
It does not work well if I use Xamarin.Forms 3.2.0.871581

*** The peek layout on the left, it does not move, when I drag.**

**Comment by AndreiMisiukevich** [comment]
@jerryno6 i think, you needn't have to disable view caching
Could you please provide sample what's wrong with view caching?
Show me the error

**Comment by AndreiMisiukevich** [comment]
Disabling view caching has no sense for CoverFlowView

**Comment by AndreiMisiukevich** [comment]
> The reason why I set Value for **IsViewCachingEnabled** is that:
> On my view, there is a Delete button, and if user click on it, the card would disappear. But afther that, when I refresh the ItemsSource, some items, it display white ( blank) and some Items it can display the view.
> 
> When I set sViewCachingEnabled="false", It worked well.
> 
> It sounds like the issue only appear on my project. I will try to reproduce this issue on an empty xamarin project.

seems your problem can be solved by bindings easily.

So, show me initial issue and we will solve it without cache disabling

**Comment by AndreiMisiukevich** [comment]
anyway: don't set IsViewCacheEnabled to **false** (it's important to keep **true** for coverFlowView)

**Comment by AndreiMisiukevich** [comment]
removing items works fine, just tried on sample
So, if you want to get help, provide sample. I think, there is some bug in your code.

**Comment by jerryno6** [comment]
Yes, I will test it again, and provide you the simplest code, if I can reproduce it. Thanks for your support.
