### ISSUE TITLE
1 Item Still Swipes

### ISSUE THREAD

**Issue by ryanherman** [AndreiMisiukevich/CardView#198]
Depending on certain properties, there may be only 1 item for the CarouselView to load.  When 1 item is loaded, you can still swipe the view slightly off the screen.  Is there anyway to disable swiping so they cannot swipe but still use the view?

**Comment by AndreiMisiukevich** [comment]
@ryanherman hi :) yes, of course
But you can achieve it by several ways.

1) If carousel.ItemsCount == 1, set IsUserInteractionEnabled = false, else IsUserInteractionEnabled = true

**Comment by AndreiMisiukevich** [comment]
@ryanherman but the most proper way would be:

2) Check this class https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Processors/BaseCarouselFrontViewProcessor.cs#L17

Use it like

```csharp
var carouselView = new CarsouselView(new BaseCarouselFrontViewProcessor { NoItemMaxPanDistance = 0 }, new BaseCarouselBackViewProcessor() );
```
