### ISSUE TITLE
Set up UWP project sample

### ISSUE THREAD

**Issue by AndreiMisiukevich** [AndreiMisiukevich/CardView#2]
I'm working on Mac.. So, I can't test this pack on UWP.
Maybe, somebody want to help?
I will be grateful)

**Comment by 207713** [comment]
PR is done :)

**Comment by AndreiMisiukevich** [comment]
@207713 thanks) I will validate it)

**Comment by 207713** [comment]
@AndreiMisiukevich i have just pushed the updated code :)

**Comment by AndreiMisiukevich** [comment]
Merged https://github.com/AndreiMisiukevich/CardView/pull/3

**Comment by AndreiMisiukevich** [comment]
@207713 Thanks a lot!)
