### ISSUE TITLE
[Feature request] Clickable indicator dots (for desktop UWP especially)

### ISSUE THREAD

**Issue by JTOne123** [AndreiMisiukevich/CardView#20]
It would be nice to have the opportunity to switch to an adjacent slide by clicking on the indicator dot.

I guess it important for the desktops because don't convenient to swipe by a mouse cursor.

**Comment by AndreiMisiukevich** [comment]
nice idea) It won't be difficult to implement this.

**Comment by JTOne123** [comment]
It's ok, normal click area for a cursor but on mobile, nobody will click on this indicators

**Comment by AndreiMisiukevich** [comment]
@JTOne123 so, i think, we can close this issue
it will be available in the next release)

**Comment by JTOne123** [comment]
thanks! good job!
