### ISSUE TITLE
Left and right arrow control have the same arrow and execute the same swipe direction

### ISSUE THREAD

**Issue by VladislavAntonyuk** [AndreiMisiukevich/CardView#200]
![image](https://user-images.githubusercontent.com/33021114/58411942-21094100-807e-11e9-953c-7e15fa75352e.png)

**Comment by AndreiMisiukevich** [comment]
@VladislavAntonyuk hi

is it UWP ?

**Comment by AndreiMisiukevich** [comment]
Is it possible to reproduce on iOS or Android ?

**Comment by VladislavAntonyuk** [comment]
Hi, the issue is reproduced on GTK, WPF, Android. Looks like in code LeftArrowControl has invalid Text

**Comment by AndreiMisiukevich** [comment]
are you sure about the same swipe direction ?

**Comment by AndreiMisiukevich** [comment]
Does anybody want to debug, solve and make PR?

**Comment by AndreiMisiukevich** [comment]
updated arrows
