### ISSUE TITLE
Indicator IsVisible Property Nonfunctional

### ISSUE THREAD

**Issue by InnerScript** [AndreiMisiukevich/CardView#201]
Setting the IsVisible property in the indicator XAML does not have effect, as the IsVisible property is set automatically regardless.

The issue occurs in IndicatorsControl.cs : 217 - ResetVisibility()

**Suggestion:**
Make a private property that respects the XAML state and view models property change notification that ResetVisibility() respects.

**Example of Intended Implementation:**
```xaml
                <cards:CarouselView ItemsSource="{Binding ConnectedDevices}" SelectedIndex="{Binding SelectedIndex}" SlideShowDuration="0" IsCyclical="False" VerticalOptions="Start">

                    <cards:CarouselView.ItemTemplate>
                        <DataTemplate>
                            <ContentView>
                                <StackLayout HorizontalOptions="Center" VerticalOptions="Start" Margin="0,0,0,40">
                                    
                                    <!-- Stuff -->
                                </StackLayout>
                            </ContentView>
                        </DataTemplate>

                    </cards:CarouselView.ItemTemplate>

                    <cardcontrols:IndicatorsControl ToFadeDuration="0" Margin="0" VerticalOptions="End" IsVisible="{Binding IndicatorVisible}" />
                    
                </cards:CarouselView>
```

**Comment by AndreiMisiukevich** [comment]
@InnerScript hm, do you need to make it invisible sometimes?

don't set ToFadeDuration="0", just remove this property and you will be able to manage IsVisible yourself

**Comment by InnerScript** [comment]
@AndreiMisiukevich 

Setting ToFadeDuration as you suggested does not make IsVisible functional. (v 2.1.2)

My use case for hiding the indicator is that in our app, often there will be only one item is the list. The dot below the select in this case isn't useful and not visually appealing.

        public bool IndicatorVisible
        {
            get {
                return _connectedDevices.Count > 1;
            }
        }

**Comment by AndreiMisiukevich** [comment]
@InnerScript so, in this case you can made binding ToFadeDuration to ItemsCount...
sounds difficult

Ok, i think, we can add new property..

**Comment by InnerScript** [comment]
@AndreiMisiukevich 

As I suggested in the opening post, I think tracking the intended state of IsVisible as a non-visible/non-bndingable property is the best result

In that way, you can then change the appearance as intended. For example, if there are properties set for fade, possibly when IsVisible changes state, the fade animation is played for all

To be clear, developers would expect IsVisible to function, rather than a new externally bound property name (if that's what you were thinking)

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich
> 
> As I suggested in the opening post, I think tracking the intended state of IsVisible flag is the best result
> 
> In that way, you can then change the appearance as intended. For example, if there are properties set for fade, possibly when IsVisible changes state, the fade animation is played for all
> 
> To be clear, developers would expect IsVisible to function, rather than a new externally bound property name (if that's what you were thinking)

but how can we achieve it? :) it is possible at all?

**Comment by AndreiMisiukevich** [comment]
Ok, i think, i will add new properties

***MinimumVisibleIndicators (-1)** and **MaximumVisibleIndicators (-1)**


And you will be able to manage visibility state

**Comment by InnerScript** [comment]
I think you're correct... Was looking into how to override the base IsVisible property, and it just wasn't as clean as I had initially thought it would be.

Using a new property MinimumVisibleIndicators would be a much cleaner code implementation internally.

**Comment by AndreiMisiukevich** [comment]
docs: https://github.com/AndreiMisiukevich/CardView/blob/master/docs/IndicatorsControl.md

**Comment by InnerScript** [comment]
👍 

I agree it's a good idea to keep the minimum default at 1, so it behaves identically for previous API users.

Is there anything I can do to help implement/test?

**Comment by AndreiMisiukevich** [comment]
@InnerScript yes, please
could you please install latest nuget version and test this new feature :)

**Comment by InnerScript** [comment]
@AndreiMisiukevich 

I just got a chance to test the MinimumVisibleIndicatorsCount just now. It is verified.

- When not set, works as previous (regression)
- When set to 2, works as I hoped when opening this issue
- When a second is added to the list at runtime, the indicator appears
- When a second item is removed from the list at runtime, the indicator disappears

Thank you very much for implementing this change so quickly! 👍 👍

**Comment by AndreiMisiukevich** [comment]
@InnerScript thanks :)
