### ISSUE TITLE
Binding color to any child element has no effect

### ISSUE THREAD

**Issue by Pirate911** [AndreiMisiukevich/CardView#202]
Hi ,
Something weird is happening . If I try to bind BackGroundColor to any element inside CarouselView it doesn't have effect . If I move the tag to outside Carousel control it change background color .

This doesn't work
```xaml
<cards:CarouselView 
        ItemsSource="{Binding QuestionData}"
        SlideShowDuration="3500"
        SelectedIndex="{Binding CurrentIndex}">
        <cards:CarouselView.ItemTemplate>
                    <DataTemplate>
<Frame BackgroundColor="{Binding Choice1Color}"
```

but if I move the **BackgroundColor="{Binding Choice1Color}"** to Frame before opening of 
<cv:CarouselViewControl  it bind correctly . 

What's the problem ?

**Comment by AndreiMisiukevich** [comment]
Hi, you made a mistake. That's the problem :)

In first case xamarin.forms tries to find Choice1Color in your **QuestionData** MODEL, because that model becomes the BindingContext for that card.

So, you need to bind to your pages.binding context

```BackgroundColor="{Binding Choice1Color, Source={x:Reference page.BindingContext}}"```

where page - x:Name="page" of your page

**Comment by Pirate911** [comment]
Thanks for the reply . 
I used below code but it's the same result : 

` <Frame  BackgroundColor="{Binding Choice1Color, Source={x:Reference Testpage1} , Path=BindingContext}" `

this one errors out : Position 92:36. Can not find the object referenced by `Testpage.BindingContext`

` <Frame BackgroundColor="{Binding Choice1Color, Source={x:Reference Testpage.BindingContext}}"`

**Comment by Pirate911** [comment]
I got it working this way : 
`BackgroundColor="{Binding BindingContext.Choice1Color , Source={x:Reference Testpage1}}"`

Thanks a lot @AndreiMisiukevich for pointing out the issue .

**Comment by AndreiMisiukevich** [comment]
@Pirate911 you are welcome
