### ISSUE TITLE
Binding Errror with last Xamarin Forms

### ISSUE THREAD

**Issue by Cali03** [AndreiMisiukevich/CardView#203]
Hi,

I just update the new release of Xamarin.Forms v4.0.0.471375 and i got an error using 
CarouselView.ItemTemplate

No property, bindable property, or event found for 'ItemTemplate', or mismatching type between value and property.

Seems to be they change something because i have similar error with another plugins respect binding property

Thanks

**Comment by AndreiMisiukevich** [comment]
@Cali03 hi, do you call ```CardsViewRenderer.Preserve() ``` ?

**Comment by Cali03** [comment]
Hi @AndreiMisiukevich, yes i did. All was working like a charm untill today. They publish the new Xamarin.Forms 9 hours ago. Did you try it?

**Comment by AndreiMisiukevich** [comment]
@Cali03 not yet.
Probably we should post issue to them.
It's super strange

**Comment by AndreiMisiukevich** [comment]
@Cali03 try via code maybe?

**Comment by Cali03** [comment]
@AndreiMisiukevich yes it very strange and like i say i got same error with another plugins (Iconize and SegmentedControl) but i downgrade Xamarin.Forms and all works.
Just hope it's a real issue and don't create that for nothing.

try via code maybe? don't unterstand that ...

**Comment by AndreiMisiukevich** [comment]
@Cali03 try to set binding through the code :)

carousel.SetBinding(...)

:)

**Comment by Cali03** [comment]
@AndreiMisiukevich ok i will try it. 
I can tell you that I was able to remove the error for the SegmentedControl Plugin using x:StaticRessource for color properties, instead of generic colors like White, Gray or Blue.

**Comment by mzaeemkhan** [comment]
Same issue for me as well after update...
![Screenshot_3](https://user-images.githubusercontent.com/43844004/58704500-ae71cb80-83c5-11e9-8ad6-28aec01b862d.png)

**Comment by davidortinau** [comment]
Think this is related to what is also causing this https://github.com/xamarin/Xamarin.Forms/issues/6375 

We are working on correcting it. Apologies.

**Comment by AndreiMisiukevich** [comment]
@davidortinau 
thanks for participation David

**Comment by AndreiMisiukevich** [comment]
closed as XF bug
