### ISSUE TITLE
Wrong layoyt if you set items source before appearing 

### ISSUE THREAD

**Issue by maukur** [AndreiMisiukevich/CardView#204]
I have a bug with bad layout items in CoverFlowView.

I use custom [StateContainer](https://github.com/xDelivered-Patrick/Xamarin.Forms.Essentials/blob/master/Essentials/Controls/State/StateContainer.cs) with CoverFlowView into ScrollView.

**But when i try set items source i get the result:**

![image](https://user-images.githubusercontent.com/8806716/58704660-7498c900-83b5-11e9-84dc-e7888db63532.png)

**In real solution it look like as:** 

![image](https://user-images.githubusercontent.com/8806716/58705425-da865000-83b7-11e9-9fac-b3df5498ce19.png)

**After drag items i get normal result:**

![image](https://user-images.githubusercontent.com/8806716/58704682-837f7b80-83b5-11e9-86e8-cb0888bb0a56.png)

I create repository with the bug: [CarouselBug](https://github.com/maukur/CarouselBug)

**Comment by AndreiMisiukevich** [comment]
it would be great, if you could fork my repo and apply your test sample in your fork

**Comment by maukur** [comment]
> it would be great, if you could fork my repo and apply your test sample in your fork

Okey i update my repository and add source for CardView. 
[CarouselBug](https://github.com/maukur/CarouselBug)
