### ISSUE TITLE
IAnimationsChecker is throwing exceptions when testing with MockForms

### ISSUE THREAD

**Issue by danstraughn** [AndreiMisiukevich/CardView#207]
During writing unit tests using Moq and Nunit i noticed that the pages that i had the CarouselView implemented were throwing an exception that was daunting at first.  But i have narrowed it down to what is causing the issue.  

https://github.com/AndreiMisiukevich/CardView/blob/ed15026214d1e42a43742a09065609a1009bbd2f/PanCardView/Utility/AnimationWrapper.cs#L42

The DependencyService can never resolve the IAnimationsChecker but still returns true which may need to be false so it can skip out to next lines of code and proceed as it should.

The work around for now is to create:
private class MockAnimationCheck : IAnimationsChecker
        {
            public bool AreAnimationsEnabled { get; } = false;
        }

And in my tests register:
DependencyService.Register<IAnimationsChecker, MockAnimationCheck>();

I believe that the code that is being checked in the if statement needs to be refactored a bit to handle this.  Other than that this is one great piece of work.

**Comment by AndreiMisiukevich** [comment]
what is the exception ?? if animationChecker = null it means that animations aren't managed and enabled by default.

So, i don't think it should return false (it will disable iOS animations!)

**Comment by danstraughn** [comment]
> what is the exception ?? if animationChecker = null it means that animations aren't managed and enabled by default.
> 
> So, i don't think it should return false (it will disable iOS animations!)

Here is the exception, i'm not entirely sure what the solution would be.  Since these tests are not running on an actual platform but in a Mocked environment using XamMocks it throws the following exception:  

Output stream: 
Unhandled Exception: System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds.
Parameter name: destinationArray
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Xamarin.Forms.Internals.Ticker.SendSignals(Int64 step)
   at Xamarin.Forms.Mocks.TestTicker.EnableTimer()
   at Xamarin.Forms.Internals.Ticker.Insert(Func`2 timeout)
   at Xamarin.Forms.Tweener.Start()
   at Xamarin.Forms.AnimationExtensions.<>c__DisplayClass7_0`1.<Animate>b__0()
   at Xamarin.Forms.AnimationExtensions.Animate(IAnimatable self, String name, Action`1 callback, UInt32 rate, UInt32 length, Easing easing, Action`2 finished, Func`1 repeat)
   at PanCardView.Utility.AnimationWrapper.Commit(View view, String name, UInt32 rate, UInt32 length, Easing easing)
   at PanCardView.Controls.ArrowControl.ResetVisibility(Nullable`1 appearingTime, Easing appearingEasing, Nullable`1 dissappearingTime, Easing disappearingEasing)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


Hope it helps.

**Comment by AndreiMisiukevich** [comment]
@danstraughn it's Xamarin.Forms issue
as you can see -- ```at Xamarin.Forms.AnimationExtensions.Animate```

**Comment by AndreiMisiukevich** [comment]
@danstraughn ah, no. it's crash inside you test framework

look at stacktrace :)

**Comment by AndreiMisiukevich** [comment]
https://github.com/xamarin/Xamarin.Forms/blob/e50775037ad45e42a9407088db7a8a949482efef/Xamarin.Forms.Core/Internals/Ticker.cs#L109-L127

**Comment by AndreiMisiukevich** [comment]
could you please provide me small sample project how can i reproduce this issue?

**Comment by AndreiMisiukevich** [comment]
https://stackoverflow.com/questions/10362023/destination-array-not-long-enough

thread-safety issue https://stackoverflow.com/questions/10362023/destination-array-not-long-enough

**Comment by danstraughn** [comment]
> https://stackoverflow.com/questions/10362023/destination-array-not-long-enough
> 
> thread-safety issue https://stackoverflow.com/questions/10362023/destination-array-not-long-enough

If you write any unit tests targeting Xamarin forms pages with this component in Xaml including your sample project you have using XamMocks it will happen.

**Comment by AndreiMisiukevich** [comment]
@danstraughn the best idea -- resolve this bug on XF project)
so, if you provide me sample, i'll try to do it
