### ISSUE TITLE
VerticalSwipe is reset when is into a Listview

### ISSUE THREAD

**Issue by paulPlaza** [AndreiMisiukevich/CardView#208]
Hello Andrei,

Question, the carousel changes position when moving vertically within a stacklayoud-BindableLayout or listview in Android.

Now try configuring ParentScrollView and the VerticalSwipeThresholdDistance (2000) properties.

How can I do so that I do not have this behavior?

Source:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26031851/58997610-fe380480-87c2-11e9-80a4-8c9154a80432.gif)
[AppTest.zip](https://github.com/AndreiMisiukevich/CardView/files/3259424/AppTest.zip)

Source Github
https://github.com/paulPlaza/Apptest

thank you very much for your help

**Comment by AndreiMisiukevich** [comment]
Hi, have you read documentation yet?

https://github.com/AndreiMisiukevich/CardView/blob/master/docs/CardsView.md

MoveThresholdDistance

**Comment by paulPlaza** [comment]
hello Andrei.
thank you for your answer, if you review all the documentation and likewise probe with these exaggerated values so that I stop changing my view, but I did not succeed.

![image](https://user-images.githubusercontent.com/26031851/59053126-49e7be00-8856-11e9-936e-9adf40e76459.png)
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/26031851/59053751-c038f000-8857-11e9-9e68-b72e8d32f0ae.gif)


What I do is pass three views on the carousel, the number on the left is the SelectedIndex of the carouserview, the problem occurs when scrolling up and down also changes the SelectedIndex of the carouserview.

I tried to see if I entered the SetIsTouchHandled (CardsViewRenderer.cs) method but when I scroll up or down it does not enter.

I do this on a Samsung S10 device - Xiaomi A1 with Android 9.

If you can give me another help I would appreciate it

**Comment by AndreiMisiukevich** [comment]
Only disabling panGesture... IsPanInteractionEnabled = false

**Comment by paulPlaza** [comment]
Thank you very much, that property also I already put it in false, and I still do not have the expected result.
