### ISSUE TITLE
show up to two items

### ISSUE THREAD

**Issue by waletoye** [AndreiMisiukevich/CardView#209]
A carouselview or coverflow view should be able to show up to two items at a time.

Is there a way to achieve this sample below?

![1559741445296699592626202681020](https://user-images.githubusercontent.com/32836274/59143920-4411ea00-89c8-11e9-872e-309068758570.jpg)

**Comment by AndreiMisiukevich** [comment]
It's regular coverflow, no ?

**Comment by waletoye** [comment]
I'm suggesting an enhancement. Your views cover just about the entire parent view,

**Comment by AndreiMisiukevich** [comment]
@waletoye got it)

**Comment by AndreiMisiukevich** [comment]
@waletoye actually you can achieve it now, if one card contains 2 frames. Does it make sense?

**Comment by waletoye** [comment]
@AndreiMisiukevich yeah i think it does. 
I figured i could use a horizontal stacklayout in an horizontal scrollview to get the same effects.

Thanks
