### ISSUE TITLE
Feature Request - Ability to set Front and Back Processors via property/xaml

### ISSUE THREAD

**Issue by thedjnova** [AndreiMisiukevich/CardView#21]
Would remove the need to setup control in code-behind.

Currently the only way to not need to place code for injecting processors is to sub-class CardsView/CarouselView and pass them into base().

Allowing the setup of processors from Xaml via static resources/bindings would make control much cleaner and MVVM'y.

Looks possible, but I will try it out to see.

**Comment by AndreiMisiukevich** [comment]
hmm)
1) How do you want to create processors via xaml?) It's smth impossible, because they require animations.
2) You can pass any parameters to constructor via xaml (https://forums.xamarin.com/discussion/47886/xaml-setting-a-constructor-parameter)
3) It's not obligatory to pass processors (you can use default ones). But if you want to customize them, you can extend cardsView/carouselView controls)

Also, processors MUST be set, before initialization. So, it's single way to prevent NULL ref on start.

I hope, it's clear)

**Comment by thedjnova** [comment]
This kind of system would remove the need for any extending or code behind?

`
<ContentPage>
<ContentPage.Resources>
        <ResourceDictionary>
            <selectors:BriefingCardSelector x:Key="CardSelector" />
            <processors:CustomFrontProcessor x:Key="FrontProcessor" />
            <processors:CustomBackProcessor x:Key="BackProcessor" />
        </ResourceDictionary>
    </ContentPage.Resources>
    
	<cardView:SceneView x:Name="_carousel"
                        BackViewsDepth="1"
                        Items="{Binding Cards}"
                        ItemTemplate="{x:StaticResource CardSelector}"
                        FrontProcessor="{x:StaticResource FrontProcessor}"
                        BackProcessor="{x:StaticResource BackProcessor}">
        <cardView:SceneView.Children>
            <cardViewControls:IndicatorsControl />
        </cardView:SceneView.Children>
    </cardView:SceneView>
</ContentPage>
`

**Comment by AndreiMisiukevich** [comment]
Okay, but you can pass them as parameters https://forums.xamarin.com/discussion/47886/xaml-setting-a-constructor-parameter

**Comment by thedjnova** [comment]
I agree that passing them as an argument works.

However from a performance stand point, being able to have processor instances in the Resource library, which are then reused throughout an application would be much better than having an instance created for every use of CardsView/CarouselView.

**Comment by AndreiMisiukevich** [comment]
I don't see benefits)
1) You can pass them as parameters
2) You can extend base control and set processors by default instead of mine ones
