### ISSUE TITLE
Views sometimes don't render when adding or removing from ObservableCollection

### ISSUE THREAD

**Issue by SkeletonJohn** [AndreiMisiukevich/CardView#210]
I have a CarouselView bound to a collection of ContentViews.

```xaml
<cards:CarouselView ItemsSource="{Binding Lists}" SelectedItem="{Binding CurrentList}"  HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
                    <cards:CarouselView.ItemTemplate>
                        <DataTemplate>
                            <ContentView Content="{Binding}" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
                            </ContentView>
                        </DataTemplate>
                    </cards:CarouselView.ItemTemplate>
                </cards:CarouselView>
```

```csharp
public ObservableCollection<ContentView> Lists { get; set; }
```

All works well on initial load, but when I add items:

```csharp
var page = new ListPage { Name = e.Name, ShowChecked = false, Sort = 1, CreatedDate = DateTime.Now, LastUpdateDate = DateTime.Now };
Lists.Add(new ListItemView(page));
CurrentList = Lists[CurrentIndex];
```
(ListItemView is a simple ContentView.)

Sometimes the view doesn't render, and I end up with a blank page.  If I stop and restart the app, the new view renders as expected.

This also seems to happen when I delete an item from the collection.  Has anyone else run into this issue? Am I doing something wrong?

I would love to use this control, but I need it to render the view consistently.

**Comment by AndreiMisiukevich** [comment]
Hi, provide sample please
I presume, there is some bug in your solution )

**Comment by SkeletonJohn** [comment]
Thanks for responding.  I've found that if I turn off Caching (IsViewCacheEnabled="False") I don't have the issue, but then it's extremely slow.  I'll try to put together a sample, but on a tight deadline right now.  We've decided to go with a different approach for now.   
  
  
  

----------------------------------------

**Comment by SkeletonJohn** [comment]
We were unable to re-create this in a small sample project.  We re-implemented it in out project and it seems to be working as expected.  I'm not sure exactly what happened.  Thank you.
