### ISSUE TITLE
Left and Right arrows are the same on Android not happening on iOS

### ISSUE THREAD

**Issue by danstraughn** [AndreiMisiukevich/CardView#211]
![Screen Shot 2019-06-10 at 11 05 14 AM](https://user-images.githubusercontent.com/2358467/59216140-dbfe0800-8b6f-11e9-8107-608596b7faa9.png)

This is happening on the latest version?  No customization just a carousel on android, happens in emulator and on devices.

EDIT:  Looks like the source resources in your repo for the images for Left and Right are the same all ,pointing right.  I don't know if that helps any.

**Comment by AndreiMisiukevich** [comment]
@danstraughn hi.

What a hell is going on ...

![image](https://user-images.githubusercontent.com/10124814/59254124-41b5c700-8c38-11e9-8e2d-f9a5f083d69d.png)

![image](https://user-images.githubusercontent.com/10124814/59254209-7033a200-8c38-11e9-990c-33cb436290ec.png)


How is it possible?
--

Okay, does left arrow navigate to proper direction? Can you try to set Rotation = 180 for left arrow ?

**Comment by danstraughn** [comment]
> @danstraughn hi.
> 
> What a hell is going on ...
> 
> ![image](https://user-images.githubusercontent.com/10124814/59254124-41b5c700-8c38-11e9-8e2d-f9a5f083d69d.png)
> 
> ![image](https://user-images.githubusercontent.com/10124814/59254209-7033a200-8c38-11e9-990c-33cb436290ec.png)
> 
> ![image](https://user-images.githubusercontent.com/10124814/59254389-c0126900-8c38-11e9-9949-761100c03657.png)
> 
> ## How is it possible?
> Okay, does left arrow navigate to proper direction? Can you try to set Rotation = 180 for left arrow ?
> 
> I suspect, it's some kind of xamarin.forms image / imagesource issue
> 
> Is it possible to reproduce on my sample?

Yes it is reproducible using your latest sample in the repo.  The arrows work as they should it's just the image that is off.  I can try to use the Rotation as work around, but you should try the sample Carousel Xaml and see that the arrows are in fact the same.  Strange that iOS works and Android has this issue.

**Comment by AndreiMisiukevich** [comment]
stupid bug... i will look at it. tooooooo strange!

**Comment by AndreiMisiukevich** [comment]
and why isn not workaround working ?.. very strange

**Comment by danstraughn** [comment]
> and why isn not workaround working ?.. very strange

The workaround is working! I just added the rotation to android only.  It works great for Android.  iOS is still solid.

**Comment by AndreiMisiukevich** [comment]
@danstraughn ah, sorry. my bad :)

okay, need to find the reason...

**Comment by shivangimittal41** [comment]
Change in the Resource Image is needed indeed.
That's all

**Comment by AndreiMisiukevich** [comment]
@shivangimittal41 really?) Why does it work fine on iOS ?) They uses the same images from crossplatform assembly.

**Comment by AndreiMisiukevich** [comment]
stupid mac images rotation lol. Really, i don't know HOW does it work on iOS right now.

**Comment by AndreiMisiukevich** [comment]
https://www.nuget.org/packages/CardsView/2.1.4

**Comment by AndreiMisiukevich** [comment]
Does it work fine now?

**Comment by pmahend1** [comment]
Yes.

> 
> 
> Does it work fine now?

**Comment by AndreiMisiukevich** [comment]
Great
