### ISSUE TITLE
[iOS only] CollectionView inside CarouselView throws "System.NullReferenceException".

### ISSUE THREAD

**Issue by mr-johnlocke8** [AndreiMisiukevich/CardView#212]
I get "Object reference not set to an instance of an object" when navigating a CarouselView with CollectionView inside.

To reproduce:
A ViewModel with Items property, having **2** items (with 3 for example I get no crash, sometimes with 7.. it is "random").

```
<cards:CarouselView
    SelectedItem="{Binding CurrentItem, Mode=TwoWay}"
    ItemTemplate="{StaticResource ItemTemplate}"
    ItemsSource="{Binding Items}" />
```

and ItemTemplate
```
<DataTemplate x:Key="ItemTemplate>
    <CollectionView
        SelectedItem="{Binding CurrentSubItem, Mode=TwoWay}"
        ItemTemplate="{StaticResource SubItemTemplate}"
        ItemsSource="{Binding SubItems}" />
</DataTemplate>
```

Browsed the code looking for it, no luck so far.

Also, using CardsView / CoverFlowView fix that problem.

**Comment by mr-johnlocke8** [comment]
Another thing I just figured out: if "SubItems" is not empty then no crash occurs. Only when "SubItems" is an empty collection (ObservableCollection in my case)

**Comment by AndreiMisiukevich** [comment]
Hi @mr-johnlocke8 
could you please provide small sample for reproducing this issue and / or exception stacktrace at least

**Comment by AndreiMisiukevich** [comment]
i presume it's Xamarin.Forms bug. Seems iOS collection view implementation throws an exception in case of its ItemsSource isn't empty and you try to set empty / null value.

so, provide sample or stacktrace please

**Comment by AndreiMisiukevich** [comment]
Can you provide sample?

**Comment by AndreiMisiukevich** [comment]
report this bug to XF project

**Comment by americofreitasjr** [comment]
I'm having a similar problem, however when using a collectionview inside a carouselview.

**Comment by AndreiMisiukevich** [comment]
@americofreitasjr as i said, i think it's XF bug. I need sample for reporting it to them.
