### ISSUE TITLE
[UWP] System.AccessViolationException: Attempted to read or write protected memory

### ISSUE THREAD

**Issue by vijaypalve** [AndreiMisiukevich/CardView#213]
I have implemented application using Xamarin.Forms 4.0.0.482894 and CardView 2.1.3
Uwp app: “System.AccessViolationException: Attempted to read or write protected memory”
Above exception throws only on UWP, iOS and Android works fine

**Comment by AndreiMisiukevich** [comment]
Hi, why did you decide, that this issue is related to CardsView ?

**Comment by vijaypalve** [comment]
@AndreiMisiukevich  
I have used same data structure and image url in scroll view, it's working fine.
And also this CardView works fine for iOS and Android.

`<StackLayout Grid.Row="1" Orientation="Vertical" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" Padding="10">
                    <cards:CarouselView ItemsSource="{Binding Images}" SelectedIndex="{Binding SelectedIndex}">
                        <cards:CarouselView.ItemTemplate>
                            <DataTemplate>
                                <ContentView>
                                    <Grid>
                                        <Grid.RowDefinitions>
                                            <RowDefinition Height="0.8*"/>
                                            <RowDefinition Height="0.2*"/>
                                        </Grid.RowDefinitions>
                                        <ffimageloading:CachedImage Grid.Row="0" Source="{Binding ImgURL}" Margin="5" DownsampleToViewSize="true" Aspect="AspectFit"
                                                                    VerticalOptions="FillAndExpand" ErrorPlaceholder="noimage.jpg" HorizontalOptions="FillAndExpand">
                                            <ffimageloading:CachedImage.GestureRecognizers>
                                                <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped" CommandParameter="{Binding ImgURL}" />
                                            </ffimageloading:CachedImage.GestureRecognizers>
                                        </ffimageloading:CachedImage>
                                        
                                        <StackLayout Grid.Row="1" BackgroundColor="Transparent" Padding="12">
                                            <Label x:Name="CommentTitle" HorizontalOptions="Start" VerticalOptions="Start" Style="{StaticResource ViewBoldLabel}" Text="Comment" TextColor="Black" />
                                                                                              </StackLayout>
                                            </StackLayout>
                                        </StackLayout>
                                    </Grid>
                                </ContentView>
                            </DataTemplate>
                        </cards:CarouselView.ItemTemplate>

                        <controls:IndicatorsControl BackgroundColor="Transparent" CascadeInputTransparent="True" 
                                                    SelectedIndicatorStyle="{StaticResource ActiveIndicator}"
                                                    UnselectedIndicatorStyle="{StaticResource InactiveIndicator}"/>
                        
                    </cards:CarouselView>
                </StackLayout>`

**Comment by vijaypalve** [comment]
Hello @AndreiMisiukevich 
After I have removed following lines from code, it works.

```
<!--<controls:IndicatorsControl BackgroundColor="Transparent" CascadeInputTransparent="True" 
                                                    SelectedIndicatorStyle="{StaticResource ActiveIndicator}"
                                                    UnselectedIndicatorStyle="{StaticResource InactiveIndicator}"/>-->
```

**Comment by vijaypalve** [comment]
But I need indicators...

**Comment by AndreiMisiukevich** [comment]
@vijaypalve this is some kind of XF issue, definitely.
but you can try workaround this issue

maybe copy-paste code from https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Controls/IndicatorsControl.cs

And try to play with it

**Comment by AndreiMisiukevich** [comment]
@vijaypalve https://github.com/xamarin/Xamarin.Forms/issues/1823 ?
is it our case?

**Comment by vijaypalve** [comment]
@AndreiMisiukevich 
Please find the attached project. 
And reproduced removed/ adding following lines  from code, it works.
```
<!--<controls:IndicatorsControl BackgroundColor="Transparent" CascadeInputTransparent="True" 
                                                    SelectedIndicatorStyle="{StaticResource ActiveIndicator}"
                                                    UnselectedIndicatorStyle="{StaticResource InactiveIndicator}"/>-->
```
[App1.zip](https://github.com/AndreiMisiukevich/CardView/files/3286084/App1.zip)

**Comment by AndreiMisiukevich** [comment]
@vijaypalve hi :)
i'm going to create pre-release version without batching for UWP

https://github.com/xamarin/Xamarin.Forms/issues/1823#issuecomment-501906681

Will you be able to test it ? (unfortunately i work on mac)

**Comment by vijaypalve** [comment]
@AndreiMisiukevich Please let me know version number.

**Comment by AndreiMisiukevich** [comment]
@vijaypalve i will create it a little bit later and let you know :)
Thanks

**Comment by vijaypalve** [comment]
@AndreiMisiukevich OK :)
thanks

**Comment by AndreiMisiukevich** [comment]
@vijaypalve please check 2.1.5-pre version

**Comment by vijaypalve** [comment]
@AndreiMisiukevich 
Thank you ,
 I will check and let you know.

**Comment by vijaypalve** [comment]
Hello @AndreiMisiukevich 
I have checked after updating plugin, but issue remains same.
Please find the attached screen shots and sample app.
<img width="667" alt="Capture" src="https://user-images.githubusercontent.com/14092016/59576816-a52f7100-90de-11e9-8f2c-0339786b10b3.PNG">

[App17062019.zip](https://github.com/AndreiMisiukevich/CardView/files/3295173/App17062019.zip)

**Comment by vijaypalve** [comment]
Hello @AndreiMisiukevich, any update?

**Comment by AndreiMisiukevich** [comment]
> Hello @AndreiMisiukevich, any update?

no) but you can ping XF team on their github.

**Comment by AndreiMisiukevich** [comment]
@vijaypalve here is workaround https://github.com/xamarin/Xamarin.Forms/issues/1823#issuecomment-503072496

**Comment by AndreiMisiukevich** [comment]
So, use workaround :)
