### ISSUE TITLE
No way to stop infinite loop in Carousel View

### ISSUE THREAD

**Issue by Cklauber** [AndreiMisiukevich/CardView#215]
I am using the CarouselView and I am trying to find so when I am at the last image, it doesn't go back to the first image.

Any way we can do that?

Thanks.

**Comment by Cklauber** [comment]
Now I just found the IsCyclical, but when I set it to false, the indicators control disappear.

**Comment by Cklauber** [comment]
Nevermind, this only happens with Nox.
Please, close this issue.

Thank you.

**Comment by AndreiMisiukevich** [comment]
great)
