### ISSUE TITLE
Swipe Direction on UserInteracted

### ISSUE THREAD

**Issue by aldousrealo** [AndreiMisiukevich/CardView#216]
Hi! I would just like to thank you for your project because now I can use a stable and optimized CarouselView with lots of options, features, and its very convenient to use. 

Anyway, is there any chance you could add a swipe direction in your UserInteractedEventArgs? It would be great as I was trying to do some work around using CarouselView with ListView in it. The Card/ContentView inside the CarouselView wiggles when fast scrolling within the Card/ContentView and if I set the 'IsPanInteractionEnabled' to 'false', the CarouselView disables the swipe function to switch to another Card/ContentView. Also, if there are ways to know the Swipe Direction whenever I interact the CarouselView, it would be great if you could tell me how to use it. :)

Thanks in advance!

**Comment by AndreiMisiukevich** [comment]
Hi) https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/EventArgs/UserInteractedEventArgs.cs#L16

This property is what you need.

```if(Diff < 0)``` - means that user is swiping to **left** side
```if(Diff > 0)``` - means that user is swiping to **right** side

**Comment by AndreiMisiukevich** [comment]
Also you can try to set MoveThresholdDistance = 20. Perhaps it will solve your problem
