### ISSUE TITLE
Please check that your Nuget Package versions are compatible. Issue

### ISSUE THREAD

**Issue by Charuwaka** [AndreiMisiukevich/CardView#218]
Xamarin Forms 4.0
Card View Latest Version I'm using 2.1.4 (after i uninstalled no warnings build went fine)
This Nuget is Causing  lot of warnings as well as  **INCREASING BUILD TIME  MORE**

3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Animation.tooltip_enter. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Animation.tooltip_exit. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Attribute.textColorError. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Boolean.abc_config_closeDialogWhenTouchOutside. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Boolean.abc_config_showMenuShortcutsWhenKeyboardPresent. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Color.error_color_material. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Dimension.abc_action_bar_progress_bar_size. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Layout.tooltip. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Style.Base_V11_Theme_AppCompat_Dialog. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Style.Base_V11_Theme_AppCompat_Light_Dialog. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Style.Base_V11_ThemeOverlay_AppCompat_Dialog. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Style.Base_V12_Widget_AppCompat_AutoCompleteTextView. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Style.Base_V12_Widget_AppCompat_EditText. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Style.Base_V14_Widget_Design_AppBarLayout. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Style.Base_V21_Widget_Design_AppBarLayout. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Style.Base_V26_Widget_Design_AppBarLayout. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Style.Base_Widget_Design_AppBarLayout. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Style.Platform_V11_AppCompat. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Style.Platform_V11_AppCompat_Light. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Style.Platform_V14_AppCompat. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Style.Platform_V14_AppCompat_Light. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Style.Widget_Design_CoordinatorLayout. Please check that your Nuget Package versions are compatible.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping CAAA.Droid.Resource.Styleable.DesignTheme_textColorError. Please check that your Nuget Package versions are compatible.

**Comment by AndreiMisiukevich** [comment]
<TargetFrameworkVersion>v9.0</TargetFrameworkVersion>


What is yours?

**Comment by AndreiMisiukevich** [comment]
try latest version (2.1.5)
