### ISSUE TITLE
[Enhancement] Item is used detection

### ISSUE THREAD

**Issue by maruhe** [AndreiMisiukevich/CardView#220]
at first, you did a great work!!

I use CarouselView with a ScrollView inside the item's view and can't set the scroll position when I create the view (ScrollToAsync seem's not to work before the view gets displayed)
so currenlty I do ScrollToAsync on MyCarousel_ItemAppearing and this is quite unbeautiful
I know this is a general thing in xamarin forms but may you already have a workaround?

regards

**Comment by AndreiMisiukevich** [comment]
Hi,
How about ScrollToAsync(animated = false) ?

**Comment by AndreiMisiukevich** [comment]
how about adding new event ?

**Comment by AndreiMisiukevich** [comment]
@maruhe or just try

```csharp
protected virtual void SetupBackViews(int? index = null)
{
    base.SetupBackViews(index);
    //play with NextViews and PrevViews
}
```

**Comment by maruhe** [comment]
ScrollToAsync(animated = false) for sure
currently I do something like
myCarousel.ItemsSource = new ObservableCollection<myView>() { new myView(CurrentDay) };
and add more view's in MyCarousel_ItemAppearing so I get an endless carousel
may because of this index is always null in my case?
I'll have a look changing this to using an ItemTemplate and a Data-Objects in ItemsSource

**Comment by maruhe** [comment]
look's good, I just have to change some stuff to get it endless again..
this.Children[index.Value] as myView
is the best way to access the correct view?

**Comment by AndreiMisiukevich** [comment]
@maruhe unfortunately no (order of children can be different)

I suggest you to call scroll updates from your model

**Comment by maruhe** [comment]
hmm.. I'm unsure what exactly you mean by 
> I suggest you to call scroll updates from your model
so I added a little test-project to show my try
https://github.com/maruhe/AnotherCardTest
there is no accessable Collection of item-view's in CardView?

**Comment by maruhe** [comment]
after some more testing I came to the problem-point where I cahnged my ItemsSource to al Collection<View> some days ago:
OnBindingContextChanged in the ItemView sometimes is no getting called
I updated my test-project

**Comment by AndreiMisiukevich** [comment]
@maruhe does it work for you now?

**Comment by maruhe** [comment]
nope
it works correclty for about 8 of 12 item-views ;-D
may you have a look at https://github.com/maruhe/AnotherCardTest and just swipe through, there you see
OnBindingContextChanged sometimes does not get called for the ItemView (not or to late)

**Comment by maruhe** [comment]
...and index is oftain null in SetupBackViews

**Comment by AndreiMisiukevich** [comment]
i guess you need access to those views which are processing in certain moment, don't you?

**Comment by maruhe** [comment]
exactly, this would be best

**Comment by AndreiMisiukevich** [comment]
```csharp
cardsView.ViewsInUseCollectionChanged += (s, e) =>
{
    var views = cardsView.ViewsInUseCollection; //current used views
};
```

**Comment by AndreiMisiukevich** [comment]
2.1.6

**Comment by maruhe** [comment]
okay, so now I have to please you to show me my fault :-(

I updated the sample https://github.com/maruhe/AnotherCardTest 
in OnBindingContextChanged I generate the View-Content 
in MyCarouselView_ItemBeforeAppearing and MyCarouselView_ViewsInUseCollectionChanged I perform the ScrollToAsync

if you chek the sample and slide thoug you'll see a different behavior

it may can be a bug in xamarin forms so I have to write renderers for custom scolling, but becaus it's workling sometimes I think it could be possible to work always ;-)

**Comment by AndreiMisiukevich** [comment]
as i said

update to latest version and use
```csharp
cardsView.ViewsInUseCollectionChanged += (s, e) =>
{
    var views = cardsView.ViewsInUseCollection; //current used views
//Scroll new views
};
```
