### ISSUE TITLE
[Documentation] Spelling mistake

### ISSUE THREAD

**Issue by PaulsonMac** [AndreiMisiukevich/CardView#221]
> -> If you get crashes during ItemsSource update, try to add/set items in Main Thread (Device.BeginInvokeInMainThread)

Isn't this BeginInvokeOnMainThread..??

Please modify the quoted text from the docs - https://github.com/AndreiMisiukevich/CardView#workarounds

Thanks for the carousel control !  👍

**Comment by AndreiMisiukevich** [comment]
@PaulsonMac i appreciate any assistance :) if you'd like, you may validate all documentation and make PR with fixing it :)

**Comment by PaulsonMac** [comment]
👍

**Comment by AndreiMisiukevich** [comment]
@PaulsonMac would you like to make PR ?)
