### ISSUE TITLE
Cant Access CardView Class in Shared Project

### ISSUE THREAD

**Issue by USAMA-app** [AndreiMisiukevich/CardView#222]
Hello,
I added this control from nuget packages but in my shared project i cant find any namespace with a name of PanCardView. in android and ios project i easily find PanCardView namespance.

please check it out or suggest me the solution.
thanks

**Comment by AndreiMisiukevich** [comment]
provide me a sample please

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/60400591-93d67200-9b7e-11e9-9955-7c43a8343fb5.png)

**Comment by AndreiMisiukevich** [comment]
Cannot reproduce on new project. Try to remove bin / obj. Restore packages. Restart VS etc.

[CardsShared.zip](https://github.com/AndreiMisiukevich/CardView/files/3343199/CardsShared.zip)
