### ISSUE TITLE
Some props inaccessible in code (PCL)

### ISSUE THREAD

**Issue by alexpetin** [AndreiMisiukevich/CardView#223]
Hello!

I'm using CarouselView in PCL project - Profile111
It works in XAML with appropriate bindings, but some properties could not be used in code - build error on using ItemsSource, for example:

`Error CS0012 The type 'IEnumerable' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.`

Adding reference to NetStandard 2.0 does not help.

**Comment by AndreiMisiukevich** [comment]
@alexpetin try this https://github.com/dncuug/X.PagedList/issues/59#issuecomment-255189553

**Comment by alexpetin** [comment]
`Installing Microsoft.NETCore.Portable.Compatibility 1.0.1.
  OK https://www.nuget.org/api/v2/package/Microsoft.NETCore.Jit/1.0.2 2381ms
Installing Microsoft.NETCore.Jit 1.0.2.
Install failed. Rolling back...
Package 'Microsoft.NETCore.Jit.1.0.2' does not exist in project 'MDU'
Package 'Microsoft.NETCore.Jit.1.0.2' does not exist in folder 'C:\Work\mdu\MobileApp\D\packages'
Executing nuget actions took 3.91 sec
Could not install package 'Microsoft.NETCore.Jit 1.0.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

So, the `Microsoft.NETCore.Portable.Compatibility package` is incompatible with PCL Profile111...

**Comment by AndreiMisiukevich** [comment]
@alexpetin could you pls try to install older prerelease versions?

**Comment by AndreiMisiukevich** [comment]
btw seems Installing Microsoft.NETCore.Jit 1.0.2. cannot be installed

**Comment by AndreiMisiukevich** [comment]
https://github.com/dotnet/standard/issues/542#issuecomment-465375220 ?

**Comment by alexpetin** [comment]
> [dotnet/standard#542 (comment)](https://github.com/dotnet/standard/issues/542#issuecomment-465375220) ?

PCL Profile111 project is not a NetStandard project, nothing to rename :)

**Comment by alexpetin** [comment]
> @alexpetin could you pls try to install older prerelease versions?

`Could not install package 'Microsoft.NETCore.Portable.Compatibility 1.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by alexpetin** [comment]
`Could not install package 'Microsoft.NETCore.Runtime.Native 1.0.2-rc2-24027'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by AndreiMisiukevich** [comment]
@alexpetin try it https://forums.xamarin.com/discussion/80045/error-using-nuget

Add project.json to your PCL

**Comment by alexpetin** [comment]
PCL Profile111 is not compatible with netstandard 2.0
Никакой жсон не поможет :)

**Comment by alexpetin** [comment]
1.x only

**Comment by AndreiMisiukevich** [comment]
"CardsView": "1.6.2"

can you install this version? because this version works fine on one of my projects (i added project.json file for sure)

**Comment by alexpetin** [comment]
Yes, no errors with 1.6.2. Without any json.

**Comment by AndreiMisiukevich** [comment]
@alexpetin piece of s***t :)

Hm, i will try to find workaround, but cannot promise. PCL is deprecated )

**Comment by alexpetin** [comment]
ok, thanks!

**Comment by AndreiMisiukevich** [comment]
So, 1.6.2 is for PCL
If you want to use latest updates, you should migrate to netstandard
