### ISSUE TITLE
Binding view model for each carousel item 

### ISSUE THREAD

**Issue by huyjack178** [AndreiMisiukevich/CardView#224]
I have multiple view models for multiple item in carousel view. When ItemAppearing, I set the CurrentView's BindingContext to the specific ViewModel. But after I swipe to another view, then swipe back, the ViewModel is not be kept in the old view was binded. Is there any solution for it? 
Take a look at the screenshot. The view before appear is always have no data
![image](https://user-images.githubusercontent.com/11793001/60694356-12793980-9f08-11e9-831a-a7814548cc21.png)

**Comment by AndreiMisiukevich** [comment]
Hi,
Why don’t you use DataTemplateSelector ?

**Comment by huyjack178** [comment]
@AndreiMisiukevich I have already used DataTemplateSelector. But the item is not being cache for previous state 
`  protected override DataTemplate OnSelectTemplate(object item, BindableObject container)
        {
            var tabItem = item as TabModel;

            return tabItem.Template;
        }`

**Comment by AndreiMisiukevich** [comment]
Could you please create small and simple sample with your case ?) I am sure it’s something we will resolve without plugin code changes :)

**Comment by huyjack178** [comment]
Here is my code 
`<ContentView xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:LiveScore.Core.Controls.TabStrip"
             x:Name="this"
             xmlns:cards="clr-namespace:PanCardView;assembly=PanCardView"
             x:Class="LiveScore.Core.Controls.TabStrip.TabStrip"
             VerticalOptions="FillAndExpand"
             HorizontalOptions="FillAndExpand">
    <ContentView.Content>
        <StackLayout>
            <StackLayout.Resources>
                <local:TabItemTemplateSelector x:Key="tabItemTemplateSelector" />
            </StackLayout.Resources>
            <local:TabStripHeader x:Name="TabHeader" BackgroundColor="#0F111C" ItemsSource="{Binding ItemsSource}">
            </local:TabStripHeader>
            <ScrollView  VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
                <cards:CarouselView
                    x:Name="TabContent"
                    IsCyclical="false"
                    IsViewCacheEnabled="True"
                    SelectedIndex="{Binding SelectedTabIndex}"
                    ItemsSource="{Binding ItemsSource}"
                    ItemTemplate="{StaticResource tabItemTemplateSelector}">
                </cards:CarouselView>
            </ScrollView>
        </StackLayout>
    </ContentView.Content>
</ContentView>`

**Comment by AndreiMisiukevich** [comment]
It’s not code) it’s just xaml. I need to see full picture, you know :)

**Comment by huyjack178** [comment]
Page after 1st load
![image](https://user-images.githubusercontent.com/11793001/60703438-f7202580-9f2b-11e9-8905-15cb31bff56e.png)

Then move to other page and swipe back 

![image](https://user-images.githubusercontent.com/11793001/60703438-f7202580-9f2b-11e9-8905-15cb31bff56e.png)

**Comment by AndreiMisiukevich** [comment]
I don’t understand why do you set binding context on itemappearing 

Can you create sample project ?

**Comment by AndreiMisiukevich** [comment]
I even don’t understand why model has Template property...

**Comment by AndreiMisiukevich** [comment]
Well, provide small sample (UI does not matter)
And I will help you.

**Comment by AndreiMisiukevich** [comment]
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/data-templates/selector

That is how to use DataTemplateSelector

**Comment by AndreiMisiukevich** [comment]
your item should not contain reference to DataTemplate.
DataTemplateSelector should decide which template should be chosen for particular item.
