### ISSUE TITLE
[iOS only] ListView inside CarouselView throws an exception

### ISSUE THREAD

**Issue by vecalion** [AndreiMisiukevich/CardView#225]
Hey Andrei,

Here is an odd behavior that I'm experiencing in a project. I have CarouselView, each card contains a ListView that is bound to an ObservableCollection. If I call collection.Clear(), the app gets in an unstable state - if I continue to add/remove items to the collection, I get an exception:

> Reason: attempt to delete row 0 from section 0 which only contains 0 rows before the update

Here is a repro project: https://github.com/vecalion/CardsViewBugRepro
Here is a video on how to get the exception: https://youtu.be/UxeD5QkvkXU

Here is a line that causes the error: https://github.com/vecalion/CardsViewBugRepro/blob/master/cardsbug/ViewModels/MainViewModel.cs#L19

Can you please take a look?

**Comment by AndreiMisiukevich** [comment]
Hi
How about

```
Device.BeginInvokeOnMainThread(() => Cards[Position].Messages.Clear());
```

**Comment by vecalion** [comment]
Yeah, I had to mention that I saw about `Device.BeginInvokeOnMainThread` in the FAQ. It doesn't help.

**Comment by AndreiMisiukevich** [comment]
@vecalion could you please try to change ListView to CollectionView ?)

**Comment by vecalion** [comment]
@AndreiMisiukevich, CollectionView is in a preview right now and doesn't support context actions. Anyway, that looks like a workaround. There is an issue that leads to this crash. I wonder if you have any ideas where to start looking?

**Comment by AndreiMisiukevich** [comment]
I am almost sure, that it is XamarinForms issue. 
Adding / removing elements causes native crash (since something happens in background thread)

**Comment by vecalion** [comment]
I don't think this is a Xamarin.Forms bug. Similar errors happen when there are multiple subscriptions to the same event that forces UITableView to update elements or unnecessary views stay in memory. The fact that this happens only with CarouselView in a particular scenario is quite suspicious.

**Comment by vecalion** [comment]
@AndreiMisiukevich, I did a short investigation and I'm quite confident that this is NOT a XF bug. When `IsViewCacheEnabled` is set to false, the `PrepareView` method is called 3 times for the card with index 1 in the scenario on the video (1 time when the app starts and 2 times when the app is navigated to the second card). Each time `CreateRetrieveView` returns a new view since the caching is switched off. Each time the binding context is assigned here: https://github.com/AndreiMisiukevich/CardView/blob/92c234b7578710e63715966344371a376f336732/PanCardView/CardsView.cs#L1292

So at the moment when the user deletes a row - there are 3 views in memory bound to the same card. `CleanView` is never called.

**Comment by AndreiMisiukevich** [comment]
But IsViewCache enabled isn’t safe property. You should not use it in regular case

**Comment by vecalion** [comment]
@AndreiMisiukevich, not sure that I understood correctly. You're saying that the `IsViewCacheEnabled` should always be set to `false`, unless there is a reason not to do that?

**Comment by vecalion** [comment]
@AndreiMisiukevich, please take a look at this commit: 
https://github.com/vecalion/CardView/commit/fb535b44587cedac092cb4b92821bfc6a8d94d78

I've added a few methods to remove the binding from views that are going to be replaced. It could be a solution except for the method: `TryAutoNavigate`. 

Take a look at this code:
https://github.com/AndreiMisiukevich/CardView/blob/92c234b7578710e63715966344371a376f336732/PanCardView/CardsView.cs#L669-L674

Let's say I'm navigating from `0` to `1`. In the line 670, back views for `-1` and `1` are created. Then a bit later in the line 672 another view for `1` is created. I'm not sure why it is like that and how to avoid it. 

What do you think?

**Comment by AndreiMisiukevich** [comment]
@vecalion how does it help? You just clean bindingContext (what is can be wrong BTW, but doesn't matter for now)

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich, not sure that I understood correctly. You're saying that the `IsViewCacheEnabled` should always be set to `false`, unless there is a reason not to do that?

i mean you shouldn't change it (IsViewCacheEnabled = true is default value), but you changed it your sample

![image](https://user-images.githubusercontent.com/10124814/60775960-0b813f80-a131-11e9-9125-24f8bdcb96a3.png)

**Comment by AndreiMisiukevich** [comment]
i am still think it's xamarin forms bug

your card contains ListView
you change collections which is bound to your listView
you get crash

why do you think it's related to carousel?

**Comment by AndreiMisiukevich** [comment]
anyway i removed IsVieCachedEnabled="false" from your sample and cannot reproduce crash anymore

**Comment by AndreiMisiukevich** [comment]
ah, i got what is the reason of crash

one viewModel is bound to multiple views. for some reasons it causes the crash.

But removing this line **IsVieCachedEnabled="false"** should resolve this issue

**Comment by AndreiMisiukevich** [comment]
Does it help you?

**Comment by vecalion** [comment]
@AndreiMisiukevich, I can work around that, but IMO `IsViewCachedEnabled` doesn't work properly and either should be fixed or removed (or at least this behaviour should be documented with triple exclamation marks). Our team expected (and I guess anyone would expect that too) that at any point of time there is only one view for each card. If a card is not needed - it's destroyed. Otherwise, it's not efficient from the memory and performance point of view and in rear cases leads to crashes like this one.

**Comment by AndreiMisiukevich** [comment]
@vecalion frankly speaking i agree with you
i think, it makes sense to remove it or amend logic re your comment.. hmmm

**Comment by vecalion** [comment]
@AndreiMisiukevich let me know if I can help if you decide to change the logic.

**Comment by AndreiMisiukevich** [comment]
@vecalion what is more preferable?

So, you think that IsViewCacheEnabled = false should provide one and only one view for each card?

**Comment by AndreiMisiukevich** [comment]
@vecalion create pls separate ticket with you ideas, let's discuss and implement
It's not difficult.

**Comment by vecalion** [comment]
Here ve go: https://github.com/AndreiMisiukevich/CardView/issues/226
