### ISSUE TITLE
Design Proposal: IsViewCacheEnabled Improvements

### ISSUE THREAD

**Issue by vecalion** [AndreiMisiukevich/CardView#226]
Recently we've encountered a weird bug https://github.com/AndreiMisiukevich/CardView/issues/225. It turned out that the `IsViewCacheEnabled` flag is working not like we were expecting and there are potential issues with the current implementation.

### Current implementation

When the `IsViewCacheEnabled` is set to `false`, the lib creates multiple view instances of the same card. All these instances are bound to the same model and listen for updates. This is not efficient from the memory and performance points of view and in rear cases, like in https://github.com/AndreiMisiukevich/CardView/issues/225, leads to crashes. 

### Proposal

At any point of time there should be only one view instance for a certain card. E.g. if the user views the card with the index 2, there are 3 views created: for indices 1, _2_, 3 (in case if we need one prev/next cards). So:

PrevView: 1
Current: 2
NextView: 3

When the user navigates to the card with the index 3, the lib destroys the view for the index 1, reuses the view 2 for the PrevView, reuses the view 3 as the Current and creates a new view for the index 4.

[Unbound and destroyed] 1
PrevView: 2 (reused)
Current: 3 (reused)
NextView: 4 (newly created) 

If the user navigates back to the second card - the view 4 is destroyed and the view 1 is created. And so on.

**Comment by AndreiMisiukevich** [comment]
```csharp
public bool IsViewReusingEnabled { get; set; }
```

i think we should add new property and mark old as obsolete

**Comment by AndreiMisiukevich** [comment]
hmm, maybe we should came up with more suitable name..

how about **IsViewSharingEnabled** ? 

Need opinion

**Comment by vecalion** [comment]
Let me think aloud here:  
You want to add a new property to make sure that the changes will not break any existing clients?
The _NewProperty_ will work in conjuction with the `IsViewCacheEnabled `, i.e.:

- when `IsViewCacheEnabled` is set to `true`, _NewProperty_ has no effect;
- when `IsViewCacheEnabled` is set to `false` and _NewProperty_ is set to `false` - the lib works as it works now;
- when `IsViewCacheEnabled` is set to `false` and _NewProperty_ is set to `true` - the lib prevents multiple instances of the same cards.

Is that correct?

**Comment by AndreiMisiukevich** [comment]
@vecalion no, i am going to mark old property as obsolete. Just want to choose the most suitable name

**Comment by vecalion** [comment]
@AndreiMisiukevich well yeah, but there is still a transition period while you have both properties. So my question is: are you considering the new property as a replacement for the old one? And if yes - why do you want to change the name?

**Comment by AndreiMisiukevich** [comment]
@vecalion yes, as replacement.

because "is view cache enabled" sounds not so clear, doesn't it?

**Comment by vecalion** [comment]
It was clear to me until I got this bug :)

How about `CachingStrategy` with `RetainElement` / `RecycleElement` as it is in `ListView`?
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/performance

**Comment by AndreiMisiukevich** [comment]
@vecalion sound good) but what will RecycleElementAndDataTemplate do ?)
The same as RecycleElement ?

**Comment by vecalion** [comment]
Nah, IMO it's better to omit that value. So the lib can have it's own enum that mimics the first two options from CachingStrategy.

**Comment by AndreiMisiukevich** [comment]
@vecalion cool)

**Comment by AndreiMisiukevich** [comment]
@vecalion i was thinking about adding new enum. I think we won't do it. But also we won't use XF one.
Let me explain why

1) New one will require more complex setup via xaml (would be unclear for some newbie guys)
2) XF one has one useless value (+ it has name ListViewCaching strategy)

So, i am keen to add **IsViewReusingEnabled** property. Hope you would agree
