### ISSUE TITLE
Implementation Ideas

### ISSUE THREAD

**Issue by Abesoddy** [AndreiMisiukevich/CardView#227]
Hello everyone,

I would like to implement this plugin to have a functioning like this gif : http://www.giphy.com/gifs/Zai4isNPoelJHWeUIg

I don't know if this is the right place to ask for this but I think you know what it is possible to do with the plugin so I would like to know if it seems possible to you?

Thank you in advance for your feedback.

**Comment by AndreiMisiukevich** [comment]
look at CoverFlowView

**Comment by Abesoddy** [comment]
Actually I implemented CoverFlowView but the events of the plugin do not allow to do like the gif?

**Comment by AndreiMisiukevich** [comment]
ItemBeforeAppearing - changed size and opacity e.g

**Comment by AndreiMisiukevich** [comment]
or you may inherit these classes 

https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Processors/BaseCoverFlowFrontViewProcessor.cs

https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Processors/BaseCoverFlowBackViewProcessor.cs


and managed animations as you wish

**Comment by Abesoddy** [comment]
And the event UserInteracted could not be more fluid?

**Comment by AndreiMisiukevich** [comment]
@Abesoddy you can use it too. As you wish)

**Comment by Abesoddy** [comment]
There is no direction property in the OnUserInteracted event though?

**Comment by AndreiMisiukevich** [comment]
@Abesoddy use Diff property (negative and positive - Left and right)

**Comment by AndreiMisiukevich** [comment]
hope it makes sense :) but perhaps i should add such property as well

**Comment by AndreiMisiukevich** [comment]
@Abesoddy well, **Diff** property should be enough

**Comment by Abesoddy** [comment]
Yes it's good thank you very much :)
