### ISSUE TITLE
Views sometimes don't render when removing item from ObservableCollection

### ISSUE THREAD

**Issue by daxavarsanitatvasoft** [AndreiMisiukevich/CardView#228]
When I am removing item from my Itemsource of ObservableCollection, carousel disappears sometimes. I have used indicator control. Only indicator control is visible.

**Comment by daxavarsanitatvasoft** [comment]
`<cards:CarouselView VerticalOptions="FillAndExpand"  IsCyclical="False" 
                  AbsoluteLayout.LayoutBounds="0,1,1,0.28" AbsoluteLayout.LayoutFlags="XProportional,YProportional,WidthProportional,HeightProportional"
                                       SelectedIndex="{Binding CurrentIndex}" ItemsSource="{Binding ItemCollection}" Margin="0,0,0,10">
                    <cards:CarouselView.ItemTemplate>
                        <DataTemplate>
                            <ContentView>`

....Content goes here

`</ContentView>
                        </DataTemplate>
                    </cards:CarouselView.ItemTemplate>
                    <cardcontrols:IndicatorsControl Margin="0,0,0,20"/>
                </cards:CarouselView>`

Here's the code for my carousel.

**Comment by AndreiMisiukevich** [comment]
try to remove elements with Device.BeginInvokeOnMainThread

**Comment by AndreiMisiukevich** [comment]
iOS / android?

**Comment by daxavarsanitatvasoft** [comment]
> try to remove elements with Device.BeginInvokeOnMainThread



> iOS / android?

both

**Comment by daxavarsanitatvasoft** [comment]
> iOS / android?

both

**Comment by AndreiMisiukevich** [comment]
@daxavarsanitatvasoft okay, try with main thread or provide me a sample project
because i cannot reproduce it. Thanks

**Comment by AndreiMisiukevich** [comment]
cannot reproduce

i am sure there is a bug in your code, which i cannot know

provide sample project and i will help you to solve it
