### ISSUE TITLE
CarouselView Not Found

### ISSUE THREAD

**Issue by 4gDad** [AndreiMisiukevich/CardView#23]
I am trying to implement the CarouselView in my app following the instructions outlined but I am getting this runtime error?  I am using the sample application as a reference.

{Xamarin.Forms.Xaml.XamlParseException: Position 29:22. Type cards:CarouselView not found in xmlns clr-namespace:PanCardView;assembly=PanCardView   at Xamarin.Forms.Xaml.CreateValuesVisitor.Visit (Xamarin.Forms.Xaml.ElementNode node, Xamarin.Forms.Xaml.INode pa…}

**Comment by AndreiMisiukevich** [comment]
Hi, do you use nuget package?
Yes, that's because you didn't add reference to this control.

"cards"

**Comment by 4gDad** [comment]
Thanks for responding.
Yes, I did use the nuget package.
My Nuget dependencies shows CardsView 1.4.1 and I added this namespace as part of my view .xaml 
xmlns:cards="clr-namespace:PanCardView;assembly=PanCardView"

**Comment by AndreiMisiukevich** [comment]
Hmm.. try to remove all bin and obj and packages

Restart VS , restore packages..
And maybe try to create control via code.

I think it can be something with VS..

**Comment by 4gDad** [comment]
Do I need to add the PanView project as part  of my solution?

**Comment by AndreiMisiukevich** [comment]
If you added nuget TO PCL/IOS/ANDROID/UWP, you needn't add project as part of solution.

**Comment by AndreiMisiukevich** [comment]
Have you resolved it yet?
