### ISSUE TITLE
Next/Prev Elements Enable

### ISSUE THREAD

**Issue by FFJoseDelgado** [AndreiMisiukevich/CardView#230]
As discussed before a good idea would be to have two new properties.

public bool IsPanToNextElementsEnabled { get; set; }
public bool IsPanToPrevElementsEnabled {get; set; }

To be able to block the swipe to next or previous item depending on the needs.

Right now there is no property to make this.

**Comment by AndreiMisiukevich** [comment]
@FFJoseDelgado would be available in the next release
