### ISSUE TITLE
Image Zoom

### ISSUE THREAD

**Issue by Monikaprime** [AndreiMisiukevich/CardView#231]
When we do image Zoom Pinch Gesture & Pan Gesture is  not working. Please can you add that functionality also

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/issues/72

**Comment by Monikaprime** [comment]
I tried with IsPanInteractionEnabled="False" but still not getting zoom effect
want i can submit my code and also i want Cards viw in Carousel View in this on making swipe in cards view, it is making Carousel view swipe please help for same

**Comment by AndreiMisiukevich** [comment]
> I tried with IsPanInteractionEnabled="False" but still not getting zoom effect
> want i can submit my code and also i want Cards viw in Carousel View in this on making swipe in cards view, it is making Carousel view swipe please help for same

have you added PanGestureRecognizer and PinchGestureRecognizer?

**Comment by Monikaprime** [comment]
I am not getting where to add this Recognizer

**Comment by Monikaprime** [comment]
Can u please post or send any sample
