### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'PanCardView.Droid.ParentScrollViewRenderer'.

### ISSUE THREAD

**Issue by hamid-shaikh** [AndreiMisiukevich/CardView#234]
Version = 2.1.6

Effected Platform = **Android**

UI Hierarchy
**cards:ParentScrollView** > **cards:CarouselView** > **ListView**

Error occurring while navigating back to previous page

```
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeVirtualBooleanMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
View.get_IsLayoutRequested ()
ScrollViewRenderer.OnScrollToRequested (System.Object sender, Xamarin.Forms.ScrollToRequestedEventArgs e) D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs:373
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.26(intptr,intptr)
```

Please let me know if more information required

**Comment by AndreiMisiukevich** [comment]
Hi, don't think it's CardsView bug

https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView.Droid/ParentScrollViewRenderer.cs

it's super trivial renderer

**Comment by AndreiMisiukevich** [comment]
what will happen if you change ParentScrollView to ScrollView ?

**Comment by AndreiMisiukevich** [comment]
Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs:373

**Comment by hamid-shaikh** [comment]
Changing to ScrollView also produces same error. Hence it seems to be Xamarin bug.
I will report this issue on Xamarin.Forms forum.

Thanks for your quick support.

**Comment by AndreiMisiukevich** [comment]
@hamid-shaikh if you provide me small sample i will fix this issue on Xamarin.Forms side :)

**Comment by hamid-shaikh** [comment]
> @hamid-shaikh if you provide me small sample i will fix this issue on Xamarin.Forms side :)

Sure will try to create a small sample on coming weekend and will update as soon as uploaded
