### ISSUE TITLE
Fast paging with arrow controls causes images from other cards to stack on carousel

### ISSUE THREAD

**Issue by garnelsoftware** [AndreiMisiukevich/CardView#235]
Thanks for a great plugin, I'm finding it very useful but I've hit a problem with both my own paging control and the plugin Left/Right arrow control.
I'm using ffImage on the carousel which works well when swiping but if I move left or right with the arrow controls quickly then the images begin to stack up. Backviewsdepth and viewcacheenabled are set to default but I tried 0 and false respectively to no avail. 

Please help!

**Comment by AndreiMisiukevich** [comment]
@garnelsoftware hi
could you please record small video? How does it look?

**Comment by garnelsoftware** [comment]
Hi Andrei,

Thanks for your reply, I really appreciate it.

I have tried to record a short video showing what happens when I start
"double clicking" e.g. tapping rapidly on the arrow control buttons.

Swipes and slow button taps are fine.

https://drive.google.com/a/garnelsoftware.co.uk/file/d/15pYbROAy5wtkzwz4miryFZ-Lr1AO2SiP/view?usp=drivesdk

Best regards,

Tom

**Comment by AndreiMisiukevich** [comment]
@garnelsoftware so, did we solve this issue?

**Comment by garnelsoftware** [comment]
Hi Andrei, yes this was caused by setting the property IsAutoNavigatingAnimationEnabled on the carousel control to false.
It's working now, thank you for your help!
