### ISSUE TITLE
Disable vertical swipe [IsVerticalSwipeEnabled]

### ISSUE THREAD

**Issue by AlexeyBuryanov** [AndreiMisiukevich/CardView#236]
How to disable vertical swipe? It is possible?

**Comment by AndreiMisiukevich** [comment]
Hi, yes. Look at documentation please.

**Comment by AlexeyBuryanov** [comment]
Of course I saw documentation before asking. It would be nice to have something like "IsVerticalSwipeEnabled"

**Comment by AndreiMisiukevich** [comment]
@AlexeyBuryanov VerticalSwipeThresholdDistance = "2000"
Does it help?

**Comment by AlexeyBuryanov** [comment]
This does not work. Maybe because the carousel in scroll (a lot of them) and I use ParentScrollView

**Comment by AndreiMisiukevich** [comment]
Do you test on android?

**Comment by AlexeyBuryanov** [comment]
Yes, and iOS too

**Comment by AndreiMisiukevich** [comment]
Could you please explain what do you wish to achieve? why do you need to disable vertical swipe?

It's weird that VerticalSwipeThresholdDistance = "2000" doesn't work for android.. for iOS maybe, but for android should work

**Comment by AndreiMisiukevich** [comment]
can you confirm that VerticalSwipeThresholdDistance = "2000" for android as well ? 
would be great to have a small sample

**Comment by maruhe** [comment]
f.e. if you have vertical ScrollView's inside you CardView's full disabling of vertical swiping could be nice (I think)

**Comment by AndreiMisiukevich** [comment]
@maruhe would you mind to prepare sample?)

**Comment by maruhe** [comment]
4sure, here you are: http://jonny.mobi/dev/CardsSampleScroll.zip

it works fin on Android, doesn't on UPW and i couldn't try on iOS

**Comment by AndreiMisiukevich** [comment]
@maruhe so this bug is only on UWP ?

**Comment by AndreiMisiukevich** [comment]
@maruhe it's impossible

IsPanInteractionEnabled = false

Only this solution for you

**Comment by AndreiMisiukevich** [comment]
iOS and Android solution only

IsVerticalSwipeEnabled

for UWP use IsPanInteractionEnabled = false
