### ISSUE TITLE
CarouselView flickering after rotate animation

### ISSUE THREAD

**Issue by wm1sr** [AndreiMisiukevich/CardView#238]
We have an application that runs on Android and iOS devices. 

This week, we started using CarouselView to keep track of logged in users, but we're experiencing some weird behaviors after we apply a rotate animation in the parent layout that holds the CarouselView: some of the other elements starts to flicker on screen, and sometimes doesn't even appear.

This only happens in the iOS app.

If we disable the rotate animation, and instead use a fade animation, this does not occur.

Could we have some help?

**Comment by AndreiMisiukevich** [comment]
Hmmm, interesting.
But I am sure it will be related to XF :( because code of this plugin is almost cross platform. And if android works fine, it means that it’s XF iOS specific issue.

Would you mind to create small sample?

**Comment by AndreiMisiukevich** [comment]
can you add small sample? and i will fix it asap (in case of it's CardsView issue)
