### ISSUE TITLE
carouselView iOS IOrdinateHandler

### ISSUE THREAD

**Issue by cbwalther1** [AndreiMisiukevich/CardView#24]
The custom scroll function for the ParentScrollView (HandleOrdinateValue) is performing incorrectly. It will go past the height of my outer scrollview.

**Comment by cbwalther1** [comment]
I got it to work by changing
`var newValue = ScrollY + _prevY - y`
to
`var newValue = - y`

**Comment by AndreiMisiukevich** [comment]
Thanks for feedback)
