### ISSUE TITLE
Question: How to size PancardView vertically so that the image maintains aspect and fills the whole width?

### ISSUE THREAD

**Issue by j4ni** [AndreiMisiukevich/CardView#241]
* I display landscape oriented images from URL inside PancardView on a vertical phone. 
* The images are generally of less width than the screen width. 
* I would like to maintain the aspect ratio of the images but resize them to allocate the entire width of the screen (phone is vertical)

I could not find a method which would behave nicely with slightly different phone screen aspect ratios/sizes. I have tried all combinations of HeightRequest and horizontal/verticalOptions = CenterAndExpand. Nothing worked.

How to solve this? Should I query the phone for screen dimensions, get image dimensions/aspect ratio from FFImageLoading and set the calculated width height on the Frame object inside CardsView? Pretty complicated (since x:Name is not working and I am not sure I would like to pollute my VM )

Thanks in advance!

```
                    <pancardview:CardsView
                        x:Name="cardView"
                        ItemsSource="{Binding DisplayImages}"
                        SelectedIndex="{Binding GalleryIndex, Mode=OneWayToSource}"
                        SelectedItem="{Binding SelectedGalleryImage, Mode=OneWayToSource}"
                        IsCyclical="True"
                    >

                        <pancardview:CardsView.ItemTemplate>
                            <DataTemplate>
                                <ContentView>
                                    <Frame 
                                        x:Name="frame"
                                        HeightRequest="226"
                                        Padding="0" 
                                        HasShadow="false"
                                        IsClippedToBounds="true"
                                        CornerRadius="10"
                                        BackgroundColor="WhiteSmoke"
                                    >
                                        <ffimageloading:CachedImage 
                                            x:Name="image"
                                            Aspect="AspectFit"                                            
                                            ErrorPlaceholder="movie_backdrop_placeholder_lg"
                                            RetryCount="1">

                                            <ffimageloading:CachedImage.GestureRecognizers>
                                                <TapGestureRecognizer Command="{Binding  Path=BindingContext.TapImageCommand, Source={x:Reference movieDetailPage}}" />
                                            </ffimageloading:CachedImage.GestureRecognizers>

                                            <ffimageloading:CachedImage.Source>
                                                <UriImageSource
                                                    Uri="{Binding Path=FilePath}"
                                                />
                                            </ffimageloading:CachedImage.Source>                                            
                                        </ffimageloading:CachedImage>                                        
                                    </Frame>                                    
                                </ContentView>
                            </DataTemplate>
                        </pancardview:CardsView.ItemTemplate>

                    </pancardview:CardsView>     
```

**Comment by AndreiMisiukevich** [comment]
Set AspectFill aspect to image

**Comment by j4ni** [comment]
Hi There,

I have tried what you have suggested:
- Removed `HeightRequest="226"` from `Frame`
- Set `Aspect="AspectFill"` on `CachedImage`

The image loaded by FFImage has a W/H aspect of 1.7777

Result is here: [https://pasteboard.co/It4JJVN.jpg](https://pasteboard.co/It4JJVN.jpg)
[https://pastebin.com/4iwXJ8db](https://pastebin.com/4iwXJ8db)

You can see, that the image is not distorted, but top and bottom are clipped. 

Now if I set AspectFit:
[https://pasteboard.co/It4Q89z.jpg](https://pasteboard.co/It4Q89z.jpg)
[https://pastebin.com/fxbcDP22](https://pastebin.com/fxbcDP22)


What I would like to achieve (ideally) :
-Images should not be distorted (uniform X and Y scaling)  at all cost
-99% of the images should fit the width of the screen (important). 
95% of the images /movie backdrops/ are 1.77 (16:9) aspect ratio, 4% has  1.33 (4:3)  aspect /trailer thumbnails/ and some 1% outlier images have portrait orientation /posters if no movie backdrop exists/.
-Images with 16:9 should never crop and should take as much vertical space as needed -but nothing more (very important)
-Images with 4:3 should crop to 16:9 ideally, but thats not really important. 
-Images with portrait orientation should scale to a predefined height and maintain aspect ratio. In this case black bars left and right are acceptable.

So thats the thing, I have tried every setting I could imagine With and without frame, with and without grid etc but to no avail.

**Comment by j4ni** [comment]
I have to mention, that I have the aspect/width/height of the image to load in my ImageModel class as a public property for every image except the first one. for the first one I can reasonably assume that thats 1.77 (99% of the time), but never 4:3.

**Comment by AndreiMisiukevich** [comment]
@jungjanos i think you should:
1) set IsViewReusing to **False**
2) play with Aspect, Width, Height of Frame for particular model (Bindings with converters)
