### ISSUE TITLE
Crash in iOS when assigning ContentViews to ItemsSource in Xaml

### ISSUE THREAD

**Issue by JosHuybrighs** [AndreiMisiukevich/CardView#242]
Hi,
I encountered a strange fault with CarouselView running on iOS, which crashes the app when it runs on a physical device but not when it runs on the iOS simulator. Android is OK in both cases.
The error occurs when I populate ItemsSource of CarouselView within XAML with a number of  ContentView controls. When I assign the list using code-behind then the error does not occur.

This is what I do in XAML:

```xaml
<cards:CarouselView x:Name="CarouselVw">
      <cards:CarouselView.ItemsSource>
        <x:Array Type="{x:Type ContentView}">
          <views:Intro1View Margin="0,0,0,48"/>
          <views:Intro2View Margin="0,0,0,48"/>
          <views:Intro3View Margin="0,0,0,48"/>
        </x:Array>
      </cards:CarouselView.ItemsSource>
      <cardsctrls:IndicatorsControl SelectedIndicatorStyle="{StaticResource ActiveIndicator}"
                                    UnselectedIndicatorStyle="{StaticResource InactiveIndicator}" />
</cards:CarouselView>

```
The 3 ContentViews are simple XAML-defined views with each having an image and a couple of labels.

When I do the assignment in code-behind, everything works fine, like in:

```csharp
public AppTourPage(AppTourViewModel viewModel)
{
   this.BindingContext = viewModel;
   InitializeComponent();
   if (viewModel.IsInitialAppTour)
   {
     NavigationPage.SetHasNavigationBar(this, false);
   }
   CarouselVw.ItemsSource = new ContentView []
   {
     new Intro1View(),
     new Intro2View(),
     new Intro3View()
   };
 }
```

Have to say also that the iOS device I have been testing on runs ios 11.4.1.

**Comment by AndreiMisiukevich** [comment]
Weird. What is the stacktrace of exception ?
I don’t think it’s CardsView issue

**Comment by JosHuybrighs** [comment]
Thanks for the prompt reply. I am afraid I can't provide more information (like console output or stacktrace) since I am developing using Mac-In-Cloud. I don't have a physical Mac and so are left with just trying to make ipa files and try to pinpoint the problem using trial and error methods.

I can of course try to come up with a simple "Hello Xamarin" app, add your plugin and my ContentViews and see if the problem still occurs on my device. Give me some time for this.

**Comment by AndreiMisiukevich** [comment]
@JosHuybrighs thank a lot. Look forward

**Comment by AndreiMisiukevich** [comment]
maybe try "{x:Type View}"
```xaml
<cards:CarouselView x:Name="CarouselVw">
      <cards:CarouselView.ItemsSource>
        <x:Array Type="{x:Type View}">
...
        </x:Array>
      </cards:CarouselView.ItemsSource>
</cards:CarouselView>
```

**Comment by AndreiMisiukevich** [comment]
btw what is views:Intro1View. Maybe it uses "Parent" property in constructor ? (which is null in case of first approach)

**Comment by AndreiMisiukevich** [comment]
hope it helped
