### ISSUE TITLE
Don't know how to have both scroll and swipe

### ISSUE THREAD

**Issue by FruitAndAShape** [AndreiMisiukevich/CardView#243]
I have a WebView in an absolute layout as a carousel screen.

On Android, I was using this to enable scrolling in the WebView...

```
Control.Touch += Control_Touch;

void Control_Touch(object sender, Android.Views.View.TouchEventArgs e)
        {
            switch (e.Event.Action)
            {
                case MotionEventActions.Down:

                    Control.Parent.RequestDisallowInterceptTouchEvent(true);

                    break;

                case MotionEventActions.Up:

                    Control.Parent.RequestDisallowInterceptTouchEvent(false);

                    break;
            }

            Control.OnTouchEvent(e.Event);
        }
```

But that stops swiping from working. If I don't add this code then I can have swipe but no vertical scrolling.

On iOS, I get vertical scrolling but no swipe.

How do I have scrolling and swipe on both platforms?

**Comment by AndreiMisiukevich** [comment]
IsPanInteractionEnabled = false only

**Comment by FruitAndAShape** [comment]
I have tried adding `IsPanInteractionEnabled = false` to my carousel and it has no effect.

**Comment by AndreiMisiukevich** [comment]
@FruitAndAShape it means that XF has such restriction. Because this property disables PanGestureRecognizer and navigation work via swipe gestures only.

**Comment by FruitAndAShape** [comment]
I don't understand. Is it possible to have both swipe and scroll?

**Comment by AndreiMisiukevich** [comment]
@FruitAndAShape seems not for WebView. Or i don't know how to achieve it.
If you know, feel free to make PR )

**Comment by FruitAndAShape** [comment]
ok. Maybe I will try and trigger it in code from an interaction with the WebView.

Also, when jumping from one card to another, the flow direction isn't consistent. Is it possible to override the flow direction?

**Comment by AndreiMisiukevich** [comment]
if i understood correctly: this method is private now 

https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs#L941-L965

But we can make it **protected virtual**

**Comment by FruitAndAShape** [comment]
`IsCyclical="false"` has fixed it. Thanks.
