### ISSUE TITLE
Carousel is swiping by itself inside ParentScrollView when scrolling page up and down.

### ISSUE THREAD

**Issue by TobyKolk** [AndreiMisiukevich/CardView#245]
I've put the carousel view inside the parentscrollview, I also tried setting the verticalswipethreshold however, as soon as I scroll the page up or down from the carousel it is paging (left right) by itself, this is unwanted behaviour, how can I stop this?  Android.

**Comment by AndreiMisiukevich** [comment]
Hi, have you read documentation yet?

**Comment by AndreiMisiukevich** [comment]
MoveThresholdDistance = 10 (or 20)

**Comment by TobyKolk** [comment]
Hmm. nope this didn't help I'm afraid.  If I try to drag to scroll the page up or down by the carousel control, it is still rotating to the next option, even with the WidthThresholdDistance set to 10 or 20.

**Comment by AndreiMisiukevich** [comment]
@TobyKolk show me the sample please

**Comment by AndreiMisiukevich** [comment]
@TobyKolk stop! why did you use WidthThresholdDistance instead of **MoveThresholdDistance** ??

**Comment by TobyKolk** [comment]
Ah ok, I will try that

**Comment by TobyKolk** [comment]
Sorry my bad, I did use MoveThresholdDistance, not Width....

**Comment by TobyKolk** [comment]
Ok I recorded a short webm clip to illustrate the issue, but looks like its not supported here... =/

**Comment by TobyKolk** [comment]
![CarouselIssue](https://user-images.githubusercontent.com/52919405/62873840-00b16000-bd18-11e9-90ff-13cae5d66eb2.gif)

**Comment by TobyKolk** [comment]
Hmm, I think I'm getting closer to better behavior using  VerticalSwipeThresholdDistance="200" SwipeThresholdDistance="30".  Does this look reasonable?

**Comment by AndreiMisiukevich** [comment]
@TobyKolk yeah, it is
does it solve your issue?

**Comment by AndreiMisiukevich** [comment]
@TobyKolk btw, do you see it 
![image](https://user-images.githubusercontent.com/10124814/62927241-ce0e7280-bdbe-11e9-9921-b51b2066db71.png) ?

seems to be a bug ) but not related to this plugin))

**Comment by TobyKolk** [comment]
Hi, yes I saw that, its the ScreenToGif app I used to capture the animation for you.  Doesn't happen on the emulator or device :D.  And yes, it seems to behave better now although it does still glitch slightly but it is acceptable for now.

**Comment by AndreiMisiukevich** [comment]
SwipeThresholdDistance = 20 and VerticalSwipeThresholdDistance = 2000 maybe better ?

**Comment by AndreiMisiukevich** [comment]
and MoveThresholdDistance = 20 !

**Comment by AndreiMisiukevich** [comment]
MoveThresholdDistance is very important

**Comment by TobyKolk** [comment]
![CarouselIssue2](https://user-images.githubusercontent.com/52919405/62928547-a44e4f00-bdb0-11e9-8a39-2cfb5867fd46.gif)

Notice the slight movement to the right when I pull down?

**Comment by TobyKolk** [comment]
Hmm, I prefer without movethresholddistance set tbh - gives the slide a better feel.
