### ISSUE TITLE
Trouble compiling source - android

### ISSUE THREAD

**Issue by bnSonic** [AndreiMisiukevich/CardView#248]
Hi :)
I've downloaded the code
Created a clean solution (Visual Studio for Mac)
Added the downloaded projects (PanCardView, PanCardView.Droid, PanCardView.iOS)
Restored NuGet Packages

Problem:
the .Droid Version shows nearly every Xamarin-Reference with a Red circle X
After Adding NuGet Packages for Xamarin.Forms, Android.Arch etc. i left with 3 Compiler Errors:

/Users/me/Projects/CardView/packages/Crosslight.Xamarin.Build.Download.25.3.1/build/Crosslight.Xamarin.Build.Download.targets(3,3): Error XBD009: Partial Download Failed for one or more parts (XBD009) (PanCardView.Droid)

/Users/me/Projects/CardView/packages/Crosslight.Xamarin.Build.Download.25.3.1/build/Crosslight.Xamarin.Build.Download.targets(3,3): Error: Invalid 'HttpContent' instance provided. It does not have a content type header starting with 'multipart/'.
Parameter name: content (PanCardView.Droid)

/Users/me/Projects/CardView/packages/Crosslight.Xamarin.Build.Download.25.3.1/build/Crosslight.Xamarin.Build.Download.targets(3,3): Error XBD404: Please open the Android SDK Manager and install the latest version of 'Android Support Repository' from the 'Extras' section, and then reload your solution. (XBD404) (PanCardView.Droid)

I have added some Android SDK for Oreo 8.0 and 8.1 … i'm out of ideas... Still nearly all References are Red-Flagged

Forms and iOS version compile just fine

**Comment by AndreiMisiukevich** [comment]
are you trying to compile this library?

> I have added some Android SDK for Oreo 8.0 and 8.1

try to add 9.0 as well

**Comment by bnSonic** [comment]
9.0 was there from the beginning

yes i was trying to compiling the library from scratch :) Just to have the code ready for debugging or tweaking

**Comment by AndreiMisiukevich** [comment]
hmm try to remove bin/obj maybe

and..

![image](https://user-images.githubusercontent.com/10124814/63191308-dc83b500-c070-11e9-82fc-9eab31ec2b37.png)

![image](https://user-images.githubusercontent.com/10124814/63191324-e60d1d00-c070-11e9-8670-eaa240801fae.png)


![image](https://user-images.githubusercontent.com/10124814/63191339-ee655800-c070-11e9-9ef0-8732f187e491.png)

**Comment by bnSonic** [comment]
- deleted all bin / obj directories
- added the SDK / Tools you showed in the screenshots
- after first recompile i was able to Relocate all References (they had a yellow warning symbol)

Then it compiles :) Thank you.

With the Sample-Solution i have other problems but i'm not sure if i really like to search/solve them ;) 

Dont' know, maybe it would help if you put a solution file into this repository? (i don't know how many other download and compile it themselfs :) )

**Comment by AndreiMisiukevich** [comment]
@bnSonic https://github.com/AndreiMisiukevich/CardView/tree/master/PanCardViewSample

here is solutions file)
