### ISSUE TITLE
ItemAppearing/ItemAppeared Event/Commad not calls for the first Time

### ISSUE THREAD

**Issue by sarthak199526** [AndreiMisiukevich/CardView#249]
ItemAppearing/ItemAppeared Event/Commad not calls for the first Time.Once swiped Everything work Ok Then

**Comment by AndreiMisiukevich** [comment]
thx, i will take a look

**Comment by AndreiMisiukevich** [comment]
Just validated. Works fine

![image](https://user-images.githubusercontent.com/10124814/63302722-920b6e00-c2e6-11e9-994d-15923562cc37.png)

![image](https://user-images.githubusercontent.com/10124814/63302751-9e8fc680-c2e6-11e9-9aec-4c4e1f572064.png)
