### ISSUE TITLE
Question: Using in Master-Detail App?

### ISSUE THREAD

**Issue by bnSonic** [AndreiMisiukevich/CardView#250]
Hi,

i you have a Master-Detail App, the "swipe from left to right"-gesture is there to show the Master-Page (Menu)

Any chance to place a CoverFlowView on a Detail Page an:
- Having the swipe-gesture moving the slides on the CoverflowView
- except if the user starts swiping from very far to the left, then the MainPage (Menu) should be shown 

Is this possible?

**Comment by bnSonic** [comment]
a bit of an ugly workaround:
- Place the CoverFlowView inside a Grid (just one cell with width = "*")
- after that place a Box in the same cell; the Box is now place on top of the coverflow. Make it VerticalOption = FillAndExpand; HorizontalOptions = "Start"; WidthRequest = "20"
Now you can add GestureRecognizer for the Box to get a Right-Swipe - In that Event you can make the MasterDetailPage to do .IsPresented = true to show the Menu

It works… but yeah… bit of a hack ;)
… the CoverFlow and the controls inside it won't get any tap-events if user taps far left
… Menu is opened automatically; user cannot swipe it open at his own pace (minor problem)

I don't know - maybe the CoverFlowView could have some option to ignore Swipe-Gestures that started far left or right at the edges so the GUI could do it's own stuff there?

**Comment by AndreiMisiukevich** [comment]
you can put coverflow into absolute layout and put content view above coverflow. So, coverflow view won't get touches from content view area.
Does it make sense?

**Comment by bnSonic** [comment]
:) yes, similar approach - but then the Coverflow wouldn't get any event… I think i will play with small overlay-boxes then because i like to swipe thru the coverflow AND let the user swipe in the MainPage … will see :)

**Comment by AndreiMisiukevich** [comment]
@bnSonic yeah) i meant small overlay boxes ) not all space. Just a little spaces from left/right sides
