### ISSUE TITLE
TapGestureRecognizer error message in application output 

### ISSUE THREAD

**Issue by b12kab** [AndreiMisiukevich/CardView#252]
I'm currently getting this message in the application output log:
_Element: Xamarin.Forms.TapGestureRecognizer is already a child of PanCardView.Controls.IndicatorItemView. Remove Xamarin.Forms.TapGestureRecognizer from PanCardView.Controls.IndicatorItemView before adding to PanCardView.Controls.IndicatorItemView._

Note that the functionality of the TapGestureRecognizer is still working, but I like to not have any errors.

I tried going back to a prior NuGet version that didn't get this error: 2.1.3. I tried using it but it's giving the same error as in 2.2.0. 

I've just moved to Xamarin forms 4.x; it appears that something internal has changed with it and before XF 4.x where CardView 2.2.0 works fine; after 4.x, it gives the above error. 

To help out, I've created 2 repos that show this problem:

Before XF4 - https://github.com/b12kab/CardViewExampleXFBelow4
After XF4 - https://github.com/b12kab/CardViewExampleXFAbove4

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/blob/89f2e0bf469e6e633cca981a4c1b6abdd1bab34e/PanCardView/Controls/IndicatorsControl.cs#L359-L364

Seems they forbid to share gesture recognizers among several views.
Okay, it wont be easy to fix

**Comment by b12kab** [comment]
Thanks for the information.

**Comment by AndreiMisiukevich** [comment]
@b12kab if you wish, you can make PR :)

**Comment by AndreiMisiukevich** [comment]
v.2.2.1
