### ISSUE TITLE
SlideShow Only forward cycling

### ISSUE THREAD

**Issue by MindRus** [AndreiMisiukevich/CardView#253]
Hello, i use carouselview. My properties for this control:
IsCyclical="True" IsAutoInteractionRunning="True" IsOnlyForwardDirection="True" SlideShowDuration="2000"

When user scrolling iscyclical works fine, but if auto scrolling, then scrolling works like:
first element -> last element , first element <- last element 

hence no cycle and IsOnlyForwardDirection="True"  doesnt helps this situation.

**Comment by AndreiMisiukevich** [comment]
Hi, what are you trying to achieve?

**Comment by AndreiMisiukevich** [comment]
IsAutoInteractionRunning="True" remove it. This property works in OneWayToSource binding mode. It's wrong to set it

**Comment by AndreiMisiukevich** [comment]
don't change any property. IsCyclical="True" by default

**Comment by AndreiMisiukevich** [comment]
IsOnlyForwardDirection="True"  means that all side cards are retrieved from further items

items indexs [0, 1, 2, 3, 4 ... 5]

e.g current index is 3. then left and right elements will be items with index 4 both

**Comment by AndreiMisiukevich** [comment]
So, just don't change any property.

Still have any issues? ping me)

**Comment by MindRus** [comment]
I did it, like you say. I want cyclic auto scrolling banners. User looping works, auto doesnt.

https://youtu.be/vFJviqyNjjA

**Comment by AndreiMisiukevich** [comment]
@MindRus got it. Okay. It will work fine with 3 images

**Comment by AndreiMisiukevich** [comment]
for two items i need to make "protected virtual" this method https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs#L934

and you will be able to override it and return "next" always

**Comment by MindRus** [comment]
Yes, yes, with 3 or more banners it works well. Thank you.

**Comment by AndreiMisiukevich** [comment]
you may validate it on my samples) would be included to next release

**Comment by MindRus** [comment]
Ok, thank you

**Comment by AndreiMisiukevich** [comment]
v.2.2.1
