### ISSUE TITLE
Left and RightArrowControl when Set to IsVisible=False they still show.

### ISSUE THREAD

**Issue by developer9969** [AndreiMisiukevich/CardView#255]
Amazing Controls!!!

I have found an issue with LeftArrowControl and RightArrowControl. If you set it to IsVisible="False"  ,it does not seem to apply.
What I did is in  your CarouselSampleXamlView I did as follows but the arrows still show.

     <controls:LeftArrowControl  IsVisible="False"/>
        <controls:RightArrowControl  IsVisible="False"/>

Thanks for wonderful controls

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Controls/ArrowControl.cs#L166-L209

Hi) yes, it's because IsVisible is used by ArrowControl

Do you really need to make arrows invisible? Just don't add them

**Comment by developer9969** [comment]
Thanks for your reply.
I am building a generic screen in a Prism module and this module can be used by different apps and  some app can have the arrows others dont.
That is why. I

**Comment by AndreiMisiukevich** [comment]
@developer9969 well, try to set

UseParentAsBindingContext = false, IsVisible = false

**Comment by developer9969** [comment]
@AndreiMisiukevich  Many thanks for these wonderful controls! And yes that works

**Comment by AndreiMisiukevich** [comment]
@developer9969 you may "star" this repo if you wish haha)
