### ISSUE TITLE
Zooming Funtionality

### ISSUE THREAD

**Issue by sarthak199526** [AndreiMisiukevich/CardView#256]
Hi @AndreiMisiukevich  Can we have a zoom functionality at-least on carousel view.Like all other native carousel view facebook does that . Like using pinch gesture and double tapped

I tried adding on image view but it scalling is not the write idea it conflicts when pinching a place where image view was not present earlier before zooming but it does after zooming In this case pinchgesture does not work since we did scalling not increasing height and width

I really love your work man :)

**Comment by AndreiMisiukevich** [comment]
@sarthak199526 Hi, cannot answer on the spot. Need to try)
But you always can play with it yourself

**Comment by sarthak199526** [comment]
An example would be fabulous for only Image carousel view If you got time someday :)

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/issues/280

@sarthak199526 how about this approach?) WebView

**Comment by sarthak199526** [comment]
I guess that would work :)

**Comment by AndreiMisiukevich** [comment]
@sarthak199526 but stay online in case of any other questions :))
