### ISSUE TITLE
Upgrading from 2.1.7 to 2.2.0 - Broken Functionality

### ISSUE THREAD

**Issue by derdogant** [AndreiMisiukevich/CardView#258]
The function below was adding new cards without any problem in 2.1.7 version. However, it started to fail after the new version 2.2.0. Doesn't raise any exception but sometimes doesn't display the new cards. However, new cards appear after the selected card index is changed.

<pre><code>
private void ButtonAddNew_Clicked(object sender, EventArgs e)
{
    var o = (CarouselSampleScrollViewModel)BindingContext;

    if (o == null)
        BindingContext = new CarouselSampleScrollViewModel(new dynamoQuestion());

    o = (CarouselSampleScrollViewModel)BindingContext;

    var item = new QuestionChoice();

    if (o.Items.Count < 0) {
        item.Number = 1;
        o.Items.Add(item);
    }
    else {
        item.Number = _carouselView.ItemsCount + 1;
        o.Items.Insert(o.Items.Count, item);
    }

    _carouselView.SelectedIndex = _carouselView.ItemsCount - 1;
}
</code></pre>

**Comment by AndreiMisiukevich** [comment]
Hi
Could you please create a small sample project?

**Comment by AndreiMisiukevich** [comment]
the best approach would be to fork my repository and add sample there

**Comment by AndreiMisiukevich** [comment]
cannot reproduce on iOS simulator with CardsView

It must be you updates something else. Or just missed providing something

I wait for sample from you :)

**Comment by AndreiMisiukevich** [comment]
QuestionChoice is it class or struct ?

Well, just crate sample and I will help you)

**Comment by AndreiMisiukevich** [comment]
cannot reproduce
