### ISSUE TITLE
MasterDetail page selected index issue

### ISSUE THREAD

**Issue by MrMayTwenty** [AndreiMisiukevich/CardView#259]
Hi @AndreiMisiukevich  
Currently i'm encountering an issue with the CarouselView's selected index
It seems that when i navigate to page in a MasterDetail the selectedindex seems to change (Decreases by 1). 

Found a similar issue on #173
but i'm already at the latest release 2.2.0

**Comment by AndreiMisiukevich** [comment]
@MrMayTwenty hmmm, strange
Could you please fork my repository and add sample?) I will debug and resolve asap :)

**Comment by AndreiMisiukevich** [comment]
need sample
