### ISSUE TITLE
ItemSwipeUp Issue

### ISSUE THREAD

**Issue by saurabh1993-05** [AndreiMisiukevich/CardView#262]
Hey Andrey,
My Issue is that I want when I swipe up cube view will go back. I am using Item swiped Event for it but I did not 
get Up or Down swipe.
Right and Left is working great.
Please help.

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/64136090-b2afe980-cdf7-11e9-85fa-e787e995e188.png)

are you sure you swipe with enough velocity?

**Comment by AndreiMisiukevich** [comment]
in another case, try to add SwipeGestureRecognizer yourself

**Comment by saurabh1993-05** [comment]
When I am using ItemSwiped then I will get like this
  async  void Handle_ItemSwiped(PanCardView.CardsView view, PanCardView.EventArgs.ItemSwipedEventArgs args)
        {
            if (args.Direction.ToString()=="Right")
            {
}
}

you are getting ItemSwipeDirection and index.
I am using latest version 2.2.0 .

**Comment by saurabh1993-05** [comment]
it's working fine in iOS .
I am getting Up direction in iOS but not in Android.

**Comment by AndreiMisiukevich** [comment]
v.2.2.1
