### ISSUE TITLE
CarouselView IndicatorsControl Position Change

### ISSUE THREAD

**Issue by riteshdarji** [AndreiMisiukevich/CardView#263]
Hi Andrey,

Can we change CarouselView IndicatorsControl Position? 
Currently it is displayed at bottom side.
I want to display it at top of the screen.

**Comment by AndreiMisiukevich** [comment]
Hi, yes of course
Just play AbsoluteLayout.LayoutFlags and AbsoluteLayout.LayoutBounds

So, just set AbsoluteLayout.LayoutBounds = ".5,0,-1,-1"

**Comment by AndreiMisiukevich** [comment]
Did it help?

**Comment by riteshdarji** [comment]
Thanks @AndreiMisiukevich 
I am using CarouselView IndicatorsControl in Grid, So AbsoluteLayout.LayoutBounds = ".5,0,-1,-1" is not working for me.
But I got a solution I have set bottom margin of this control from code behind with screen height - 70.
this.indicators.Margin = new Thickness(0, 0, 0, App.Current.MainPage.Height - 70);
This is working for me.

Thanks a lot.
