### ISSUE TITLE
Stop ItemSwiped from finishing

### ISSUE THREAD

**Issue by jorgvanriet** [AndreiMisiukevich/CardView#267]
Hi @AndreiMisiukevich,

I am using the CarouselView and i want to use the OnItemSwiped or the ItemSwipedCommand to navigate between my items.
I am looking for a way to stop the swipe action (e.g. e.Handled = true) to prevent the swipe from finishing and remain in the original(pre-swipe) state.

Is this possible?

Regards 

Jorg

**Comment by AndreiMisiukevich** [comment]
Hi, for now -- no, unfortunately

**Comment by AndreiMisiukevich** [comment]
can you show, what do you want to achieve?

**Comment by jorgvanriet** [comment]
I am using the CasouselView as a Wizard.
By using a DataTemplateSelector i can use multiple views in the CarouselView.
I have a header for the view title and a footer for the "Next" and "Previous" buttons.

The buttons i use for navigating forward and backward through the wizard. On navigating i validate the content of the view and i can stop the carousel from going to the next view.

But when i swipe i cannot prevent the carousel from going to the next item(by using either the ItemSwipedCommand or the ItemSwiped event).

I was hoping you could tell me how to do that :).

**Comment by AndreiMisiukevich** [comment]
Hm, just set IsUserInteractionEnabled = false

**Comment by jorgvanriet** [comment]
Ok i'll  just disable the interaction for now

Thanx for the help !

**Comment by AndreiMisiukevich** [comment]
also you can try to play wit IsNextItemPanInteractionEnabled IsPrevItemPanInteractionEnabled

Set them after you checks
