### ISSUE TITLE
Backward swipe issue on coverflow

### ISSUE THREAD

**Issue by syakuronano** [AndreiMisiukevich/CardView#268]
Hi, I get issue on coverflow when on backward swipe. Card looks double
![CarouselIssue](https://user-images.githubusercontent.com/20804761/64308970-b09f8380-cfcd-11e9-9a47-5950ceba69df.Gif)

Can you have any suggestion for my issue?
here my code:
https://github.com/syakuronano/bugrepropanvw

Thank you

**Comment by AndreiMisiukevich** [comment]
first of all i removed useless properites

```xaml
                    <card:CoverFlowView PositionShiftValue="60"
                                             ItemsSource="{Binding CardItems}"
                                             ItemTemplate="{StaticResource cardTemplateSelector}"
                                             VerticalOptions="FillAndExpand">

                    </card:CoverFlowView>
```

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/64319551-539fcf80-cfc5-11e9-9b6a-26e380022fd0.png)

Frame should have MARGIN = "40, 0" e.g.

play with margin

**Comment by syakuronano** [comment]
Thank you for your response but I got 2 questions
1. What do you mean remove useless properties? The properties are used for binding the objects.
2. I mean, my issue is when I swipe backyard on purple card, I get purple card again on left side. it is not like on forward swipe, which I get next color card part on right side and I need it to show in my app. set the margin means I do not get the next color cards

**Comment by AndreiMisiukevich** [comment]
>> What do you mean remove useless properties? Those properties are used for binding the objects.

Yes, but they work in OneWayToSource binding mode (check the documentation for more info about them)
