### ISSUE TITLE
How to make swipe more smoothly?

### ISSUE THREAD

**Issue by huyjack178** [AndreiMisiukevich/CardView#270]
Hi, I have  tried the old carousel view https://github.com/alexrainman/CarouselView, and I saw it more smoothly than yours. Do you have any configuration for it?

**Comment by AndreiMisiukevich** [comment]
what do you mean? Animation?

**Comment by AndreiMisiukevich** [comment]
every processor has AnimationLength and AnimEasing properties, you may set desired value

**Comment by huyjack178** [comment]
Yes, the animation

**Comment by huyjack178** [comment]
> every processor has AnimationLength and AnimEasing properties, you may set desired value

let me try this

**Comment by huyjack178** [comment]
You can see in this screenshot, when I swipe right from the very first item, the space is still like the image, it make me feel not smoothly 
![image](https://user-images.githubusercontent.com/11793001/64517149-f5068880-d319-11e9-9923-12de72fc6f03.png)

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/64517783-ab0daa80-d2f9-11e9-81fe-966848f2f4d4.png)

properties are there

**Comment by AndreiMisiukevich** [comment]
AnimationLength and AnimEasing

**Comment by AndreiMisiukevich** [comment]
would be better to see a video
the image doesn't provide more info

**Comment by huyjack178** [comment]
![image](https://user-images.githubusercontent.com/11793001/64519052-96dba480-d31d-11e9-9786-6cf17fdee215.png)

**Comment by huyjack178** [comment]
![RPReplay_Final1568020626](https://user-images.githubusercontent.com/11793001/64519078-a5c25700-d31d-11e9-93f1-f8e6460321be.gif)

**Comment by huyjack178** [comment]
This is my expectation
![RPReplay_Final1568020922](https://user-images.githubusercontent.com/11793001/64519386-36009c00-d31e-11e9-8735-338ee985f28f.gif)

**Comment by AndreiMisiukevich** [comment]
Well, try to set https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Processors/BaseCarouselFrontViewProcessor.cs#L18 to 100 for example
