### ISSUE TITLE
Children does not return all elements

### ISSUE THREAD

**Issue by K232** [AndreiMisiukevich/CardView#271]
Hi Andrei,
I've noticed a strange behaviour in the carousel view: The Children-Property does not return all children. I thought it's related to some controls, but it seems that the maximum of returned children is 3 ?

I'm using the code which I've posted here https://github.com/AndreiMisiukevich/CardView/issues/260#issuecomment-527827927 so childrens are added via XAML. Setting a Breakpoint in _foreach (View v in CarouselTest.Children)_ in _OnAppearing_ shows always just a maximum of 3 children, regardless of what you add. The Carousel itself shows all elements, that's fine. But it seems that the Children-Property never returns more than 3 elements...?

**Comment by AndreiMisiukevich** [comment]
@K232 yes, that's true. Views are reused among all items. (like recycleElementStrategy). It was done for better performance and memory management
