### ISSUE TITLE
Setting BackViewsDepth make Carousel View hang for the first load

### ISSUE THREAD

**Issue by huyjack178** [AndreiMisiukevich/CardView#272]
Sorry for asking many times but I tried to use BackViewsDepth = 2 for best rendering, but on the first load, the carousel view is not work as normal. I don't know why, the first load not navigate to correct page. Please refer to the video

![new](https://user-images.githubusercontent.com/11793001/64584527-3d2bb680-d3bf-11e9-8237-d6c0e1871fbc.gif)

Without using BackViewsDepth, It's very normal. Very strange. Please help
![old](https://user-images.githubusercontent.com/11793001/64584591-8f6cd780-d3bf-11e9-8bf8-f5521ef48ac9.gif)

**Comment by AndreiMisiukevich** [comment]
BackViewsDepth = 2, it means that you are trying to load **5** (!!!) views on start. It's so heavy.
(2 from the left side, 2 from the right side and one current)

**Comment by huyjack178** [comment]
> BackViewsDepth = 2, it means that you are trying to load **5** (!!!) views on start. It's so heavy.
> (2 from the left side, 2 from the right side and one current)

I got it but data is loading on demand, so only empty view

**Comment by AndreiMisiukevich** [comment]
what is the issue? Blinking?

**Comment by AndreiMisiukevich** [comment]
@huyjack178 could you please fork my repository and reproduce it on any sample? I will debug this case if it is something on CardsView side :)

**Comment by huyjack178** [comment]
Sorry for replying late, I have work-arround solution by setting IsViewReusingEnabled="False" than setting BackDepthView, it make my swipe more smoothly, maybe each view doesn't reuse others make it

**Comment by huyjack178** [comment]
@AndreiMisiukevich 
I have one more question, ask here for not creating issue
Sometimes, I see that issue, the view is crop like the image. Do you know why?
![image](https://user-images.githubusercontent.com/11793001/64668281-3c5e5780-d487-11e9-8498-4a2c4bc33cfb.png)

**Comment by AndreiMisiukevich** [comment]
@huyjack178 i don't think it's related to CardsView. Seems something with layouting. Try to use FillAndExpand

**Comment by AndreiMisiukevich** [comment]
@huyjack178 can you test in on my samples?

Just change any ItemTemplate to ContentView { BackgroundColor = Color.Red }

I am sure that there is no issue in CardsView. It's smth related to your code / xaml or XF

CardsView is AbsoluteLayout. It put cards into itself with AbsoluteLayoutFlags = "All" and AbsoluteLayouytBound = "0, 0, 1, 1"

**Comment by huyjack178** [comment]
It's only happening in iphone Xr, Xs is normal. So weird. Please ignore that issue. I will test it in real device and check later. Thank you so much

**Comment by huyjack178** [comment]
@AndreiMisiukevich Can not reproduce with your sample because of your simple layout. My project need a lot of info in ListView. When checking, I see it's easy happen when use mobile network (3G/4G, not wifi). My list view has more than 1000 rows and I saw it because of heavy listview make rendering wrong.

**Comment by huyjack178** [comment]
@AndreiMisiukevich Thanks god, I change stacklayout by flexlayout and that issue has gone. I think cardview have problem with item datatemplate using stacklayout

**Comment by AndreiMisiukevich** [comment]
@huyjack178 it's no CardsView problem then :)
There is a problem with StackLayout :D
CardsView just moves layouts
