### ISSUE TITLE
OutOfMemory Exception

### ISSUE THREAD

**Issue by garnelsoftware** [AndreiMisiukevich/CardView#273]
Hi Andrei,

Thank you for your fantastic plugin but I wonder if you could help me?
I have two devices that I am playing with, one API 19 and the other API 27.

I am using your CarouselView with FFImageLoading and have just recently switched my PNGs to SVGs because of scalability.

My problem is that each card consumes 8MB of memory when creating the bitmap for the SVG. On the older device this seems to hit both the heap and total memory whereas the heap on the newer device remains untouched. (On more complicated cards which switches between 2 SVGs it uses around 16MB)

After about 30 swipes on the old one I get the exception. The newer device hasn't had one yet but I am wary about the fact that the memory consumption does not drop.

I have the CacheType set to None on SvgCachedImage but the memory consumption still goes up. I use InvalidateCacheAsync in TrimMemory as suggested by FFImageLoading which periodically returns some of the memory.

Please can you advise?

Many thanks,

Tom

**Comment by AndreiMisiukevich** [comment]
Hi @garnelsoftware seems it's FFImage issue something is not disposed

**Comment by garnelsoftware** [comment]
Thanks Andrei.

I have put an invalidatecache & GC collect in the card disappearing & back/home navigate and it stops the OOM.
A lot of internet searches on ffimageloading seems to imply that the carousels in use aren't attempting to dispose/destroy the images.
Do you have any advice on necessary cleanup when using the carousel? (i.e. which method to override etc) I feel that my approach is currently ineffecient and wasteful.

**Comment by AndreiMisiukevich** [comment]
No, better approach would be:

```csharp
class BackProcessor: BaseBackCarouselViewProcessor {
    override HandleCleanView(...) { // overrirde this method and 
        base.HandleCleanView(); // call base method
// here your code
 }
}
```

And try 
```
var carousel = new PanCardView.CarouselView(new BaseFrontCarouselViewProcessor(), new BackProcessor()) { IsViewReusing = false }
```

**Comment by garnelsoftware** [comment]
Great! Thanks Andrei, I'll try that later! I really appreciate your help, thank you again.
