### ISSUE TITLE
UserInteracted event doesn't fire on iOS

### ISSUE THREAD

**Issue by LynoDesu** [AndreiMisiukevich/CardView#274]
When I subscribe to this event, it only fires on Android. It is never fired on iOS.

**Comment by AndreiMisiukevich** [comment]
Are you sure? There are no other properties set for iOS?

**Comment by AndreiMisiukevich** [comment]
Show me the sample, please

**Comment by LynoDesu** [comment]
Hi,

I'll out together a simple sample when I have a bit more time, but this is what I'm doing:

Works fine on Android, but never fires on an iOS device or simulator

```
public partial class ProductImageCarouselView : ContentView
    {
        public ProductImageCarouselView()
        {
            InitializeComponent();

            Carousel.UserInteracted += Carousel_UserInteracted;
        }

        private void Carousel_UserInteracted(PanCardView.CardsView view, PanCardView.EventArgs.UserInteractedEventArgs args)
        {
            if (args.Status == PanCardView.Enums.UserInteractionStatus.Ended && args.Diff > -10 && args.Diff < 10)
            {
                if (BindingContext is ViewProductPageViewModel viewModel)
                {
                    if (Carousel.SelectedItem is ProductImage image)
                    {
                        viewModel.ImageTappedCommand.Execute(image);
                    }
                }
            }
        }
    }
```

**Comment by AndreiMisiukevich** [comment]
let me check it

**Comment by AndreiMisiukevich** [comment]
Can you post xaml as well?

**Comment by AndreiMisiukevich** [comment]
Just verified, works as expected.
Post sample please, i presume there is any bug in your xaml

**Comment by AndreiMisiukevich** [comment]
http://www.giphy.com/gifs/fVJaPapy5Ppp80Q56y

**Comment by shubhambhosale** [comment]
@AndreiMisiukevich 
I think to replicate the issue we need to add the WebView inside the CarouselView. 
Then it should stop the firing the UserInteracted event on the iOS.

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich
> I think to replicate the issue we need to add the WebView inside the CarouselView.
> Then it should stop the firing the UserInteracted event on the iOS.

Yes, there is a conflict of gestures. You should choose where PanGesture is working and where it isn't

**Comment by shubhambhosale** [comment]
I have set IsPanInteractionEnabled="False" on the CarouselView. But still it didn't detect the UserInteracted event on the iOS.

**Comment by AndreiMisiukevich** [comment]
You should set IsEnabled = false to your WebView

**Comment by AndreiMisiukevich** [comment]
Or InputTransparent = true
