### ISSUE TITLE
[Bug] SelectedIndex - CoverFlowView

### ISSUE THREAD

**Issue by PauchardThomas** [AndreiMisiukevich/CardView#279]
Hi,

I want to save the current index from the CoverFlowView and retrieve it when switching ItemSource.

I discovered a bug for the CoverFlowView : 

Summary : When switching ItemSource the SelectedIndex is always set to -1 from the previous SelectedIndex.

Please see my repo : https://github.com/PauchardThomas/CardViewTest

**Comment by PauchardThomas** [comment]
@AndreiMisiukevich Any idea ?

**Comment by AndreiMisiukevich** [comment]
@PauchardThomas sorry mate, it was a SUPER busy month for me :(
But I am freer now. And I promise to check on this week (maybe today.. maybe a little bit later)

**Comment by PauchardThomas** [comment]
@AndreiMisiukevich No problem ;-)

**Comment by AndreiMisiukevich** [comment]
Hi, first of all i think you should add margin 
![image](https://user-images.githubusercontent.com/10124814/65551893-97825680-df2b-11e9-94d1-8ff652e67613.png)


30, 0
or
25, 0 at least

**Comment by PauchardThomas** [comment]
Thank you very mch. Waiting for the release ;)

**Comment by AndreiMisiukevich** [comment]
@PauchardThomas I am going to make it on this week)

**Comment by AndreiMisiukevich** [comment]
v2.2.2
