### ISSUE TITLE
Swiping if Pangesture is not enabled

### ISSUE THREAD

**Issue by shoeIT** [AndreiMisiukevich/CardView#280]
Hey Andrei,
until version 2.16 it was possible to swipe the carousel view even if pangesture was set to false.
I need to set it to false on some views since I show a web view where the user can zoom in, it was still possible to swipe if the user starts at the very left or right end of the screen.
This is not possible anymore atm.
Is this expected behaviour ? Can I achieve the fuctionality otherwise ? 
Do you have any hints ?

**Comment by AndreiMisiukevich** [comment]
Can you provide a small sample?

**Comment by AndreiMisiukevich** [comment]
So, 2.1.5 works fine, but 2.1.6 - not?

**Comment by shoeIT** [comment]
I try to provide it the next days!
2.16 is working, afterwards not

**Comment by AndreiMisiukevich** [comment]
@shoeIT ah, got it)

**Comment by AndreiMisiukevich** [comment]
Did it work on iOS and Android ?? or Android only?

**Comment by AndreiMisiukevich** [comment]
seems this guy updated behavior https://github.com/AndreiMisiukevich/CardView/commit/5b1ed5ff076e766099e653bcd3fed84aed05c27e

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/commit/5b1ed5ff076e766099e653bcd3fed84aed05c27e#diff-8cc6ebe1b5bce65a7563dd4ee7cea8f5R499

**Comment by AndreiMisiukevich** [comment]
Hmmm, I presume you tested on Android only, yeah?

**Comment by shoeIT** [comment]
yes until now I tested only on Android.  iOS update ATM therefore I can try it later or tomorrow!

**Comment by shoeIT** [comment]
in iOS everything works out of the box exactly like I want and as it worked until 216 in Android with pangesture = false

I mean, what is the expected behaviour if you show a svg in a webview. The should be able to zoom into the web view and the user should be able to swipe  right?
In Android atm you could either swipe or zoom but not both of it...I don't think that what we want?

**Comment by AndreiMisiukevich** [comment]
@shoeIT makes sense

**Comment by AndreiMisiukevich** [comment]
pangesture = false // could you pls explain it? Is it IsPanInteractionEnabled ?

**Comment by AndreiMisiukevich** [comment]
Well, it would be fantastic, if you forked my project and applied a sample there :)
It will allow me to fix this issue ASAP. I believe I know what is the reason.

**Comment by AndreiMisiukevich** [comment]
So, you used it like: 

carousel.IsPanInteractionEnabled = Device.RuntimePlatform != Device.Android;

Yeah?

**Comment by shoeIT** [comment]
thank's for your support, I try to provide a sample asap!

I use data binding and on a certain position if 
```
 if (Device.RuntimePlatform == Device.Android)
                                        {                                          
                                            PanGestureEnabled = false;
                                        }

```
then I'm able to zoom in the webview containing a svg.


```
    <cards:CarouselView
                     BackgroundColor="White"
                     HorizontalOptions="FillAndExpand"                                           
                     VerticalOptions="FillAndExpand"
                     VerticalSwipeThresholdDistance="3000"
                    ItemsSource="{Binding CarouselViewInputItems}"          
                    IsPanInteractionEnabled ="{Binding PanGestureEnabled}"
                   x:Name="WoICarouselCards"                 
                   AreAnimationsEnabled="True"
                       IsUserInteractionInCourse="False"
                            UserInteracted="UserInteracted"
            IsCyclical ="False"
        SelectedIndex="{Binding Position, Mode=TwoWay}" >
```

**Comment by AndreiMisiukevich** [comment]
@shoeIT I added one new property. So I will create new release today

**Comment by AndreiMisiukevich** [comment]
ShouldThrottlePanInteraction = true

**Comment by AndreiMisiukevich** [comment]
v2.2.2

**Comment by shoeIT** [comment]
THX works fine so far. 
PanGestureEnable = true
ShouldTrhottlePanInteractions = true   IF you need to zoom in and out or scroll on a View (e.g. WebView)

**Comment by AndreiMisiukevich** [comment]
@shoeIT thanks for the feedback :D
