### ISSUE TITLE
IsVerticalSwipeEnabled Property Not Working

### ISSUE THREAD

**Issue by becarioWelldex** [AndreiMisiukevich/CardView#281]
Hi andrei, i have a problem with this property. when i tried to use it i set it to false and the carousel ignore the property and can still swipe vertical to change card.
`IsVerticalSwipeEnabled=false`

Version: 2.2.1.

Thank You.
BTW Nice nugget, love it.

**Comment by becarioWelldex** [comment]
Solved

**Comment by AndreiMisiukevich** [comment]
@becarioWelldex Hi) How did you solve it?

**Comment by becarioWelldex** [comment]
@AndreiMisiukevich only working right now in iOS not in Android

**Comment by becarioWelldex** [comment]
> @becarioWelldex Hi) How did you solve it?

i just type the verticalswipeenabled property to false

**Comment by AndreiMisiukevich** [comment]
also try to set MoveThresholdDistance = 20

**Comment by becarioWelldex** [comment]
> also try to set MoveThresholdDistance = 20

When i scroll from carousel on iOS it lags a little

**Comment by AndreiMisiukevich** [comment]
> > also try to set MoveThresholdDistance = 20
> 
> When i scroll from carousel on iOS it lags a little, like the scroll is not smooth

can you show, what do you mean? You said that iOS works fine
