### ISSUE TITLE
Double cards on the left part of the screen.

### ISSUE THREAD

**Issue by samukasantos** [AndreiMisiukevich/CardView#282]
Hey Andrei,

I am using coverflow to fulfill one of the expected requirements but found one when using a TemplateSelector due to some differences between the cards. The IsCyclical property needs to be set as this is expected behavior. Here are two code snippets where the first is the DataTemplates definition and then how the component was defined in XAML.

![image](https://user-images.githubusercontent.com/5481198/65510279-ea521300-df17-11e9-8562-4a29d8d5dc3d.png)

![image](https://user-images.githubusercontent.com/5481198/65510339-0ce42c00-df18-11e9-9078-aff1d5d22229.png)

Thus when sliding from left to right we can observe an overlap of the left card.

![WhatsApp Image 2019-09-24 at 22 14 27](https://user-images.githubusercontent.com/5481198/65510848-36ea1e00-df19-11e9-8921-7fb707bb4f1e.jpeg)

![WhatsApp Image 2019-09-24 at 22 14 27 (1)](https://user-images.githubusercontent.com/5481198/65510876-40738600-df19-11e9-98e8-0c13af338f11.jpeg)

![WhatsApp Image 2019-09-24 at 22 14 27 (2)](https://user-images.githubusercontent.com/5481198/65510901-4b2e1b00-df19-11e9-82a9-48d96274a102.jpeg)

**Comment by AndreiMisiukevich** [comment]
@samukasantos Hi) May I ask you about small assistance?)
Could you please fork this repository and add sample which demonstrates this bug?

**Comment by samukasantos** [comment]
Hi Andrei,

Here is the compressed project I hope it can help. Thanks !

[cardviewbugs-1.zip](https://github.com/AndreiMisiukevich/CardView/files/3655870/cardviewbugs-1.zip)

**Comment by AndreiMisiukevich** [comment]
@samukasantos yes, I see that there is an issue on your sample. But it's overloaded with other stuff.
Can you create a very simple sample project with this issue? cuz I cannot reproduce it on my samples

**Comment by AndreiMisiukevich** [comment]
A simple project with one page, use BoxView for templates (just use different colors for example)

**Comment by AndreiMisiukevich** [comment]
or I can reproduce... hmmm

**Comment by AndreiMisiukevich** [comment]
IsCyclical=false fixes issue

**Comment by samukasantos** [comment]
Hey Andrei, 

Thanks for your feedback. I need to have IsCyclical=true I tested with false value and could realize it works but this behavior is totally important for the product. I could realize about the number of the elements too, I don't know if it makes sense but in a debugging session the OnSelectTemplate  from DataTemplateSelector is being called 5 times for 4 elements.

Cheers !

**Comment by AndreiMisiukevich** [comment]
@samukasantos I know the reason of the bug :)
And 5 times for 4 elements is fine.. because:

[left2] - [left1] - [CURRENT] - [right1 - [right2]

Since you have 4 elements in ItemsSource, right2 should be the same with left2 (That is why cardsView creates one more element) I need to think, how to manage them.

So, no need any samples.

**Comment by AndreiMisiukevich** [comment]
v2.2.2

**Comment by samukasantos** [comment]
Hey Andrei, 

I tested in some devices and the issue gone! Thank you very much and I appreciate your help !

Cheers,

**Comment by AndreiMisiukevich** [comment]
@samukasantos glad to hear it)
if you like this plugin, you may start this project
