### ISSUE TITLE
Individual Views for each Carousel Item

### ISSUE THREAD

**Issue by mzhukovs** [AndreiMisiukevich/CardView#283]
The carousel I wish to create has some very different display needs per each item, making it a little tough to come up with an item template. Is it possible to just pass in a pre-defined collection of views as the ItemsSource and essnetially just have the CarouselView display them as they are? I guess one way to describe it would be as similar to an XF CarouselPage but within a CarouselView?

**Comment by AndreiMisiukevich** [comment]
Hi, yes, sure. Just put collections of views to ItemsSource

![image](https://user-images.githubusercontent.com/10124814/65830540-250dcf80-e2b9-11e9-9c31-6dee80e27699.png)

**Comment by mzhukovs** [comment]
ah so awesome, thank you!! @AndreiMisiukevich
