### ISSUE TITLE
NullReferenceException when using Processors

### ISSUE THREAD

**Issue by matt-goldman** [AndreiMisiukevich/CardView#284]
I am using a carousel view, I've added the processors, as per documentation and samples. However when the view loads my app crashes with a NullReferenceException.

Here is the XAML:

```
<cards:CarouselView ItemsSource="{Binding Profiles}"
                                    SelectedIndex="{Binding PositionSelected}"
                                    VerticalOptions="FillAndExpand"
                                    HorizontalOptions="FillAndExpand"
                                    AbsoluteLayout.LayoutBounds="1,1,1,1"
                                    AbsoluteLayout.LayoutFlags="All">

                    <cards:CarouselView.Behaviors>
                        <behaviors:EventToCommandBehavior EventName="ItemDisappearing"
                                                          Command="{Binding OnCardSwiped}"/>
                    </cards:CarouselView.Behaviors>

                    <x:Arguments>
                        <proc:BaseCoverFlowFrontViewProcessor RotationFactor="0" ScaleFactor="0.7" OpacityFactor="0.25" />
                        <proc:BaseCoverFlowBackViewProcessor RotationFactor="0" ScaleFactor="0.7" OpacityFactor="0.25" />
                    </x:Arguments>

                    <cards:CarouselView.ItemTemplate>
                        <DataTemplate>
                            <controls:DevCard/>
                        </DataTemplate>
                    </cards:CarouselView.ItemTemplate>
                </cards:CarouselView>
```

Here is the exception detail:

> System.NullReferenceException: Object reference not set to an instance of an object
>   at PanCardView.Processors.BaseCoverFlowBackViewProcessor.GetStep (PanCardView.CardsView cardsView) [0x0000d] in <0d63e6746cbf4a3f9cc5afdd19f2f4f0>:0
>   at PanCardView.Processors.BaseCoverFlowBackViewProcessor.HandleInitView (System.Collections.Generic.IEnumerable`1[T] views, PanCardView.CardsView cardsView, PanCardView.Enums.AnimationDirection animationDirection) [0x00030] in <0d63e6746cbf4a3f9cc5afdd19f2f4f0>:0
>   at PanCardView.CardsView.InitViews (PanCardView.Processors.ICardProcessor processor, PanCardView.Enums.AnimationDirection animationDirection, System.Collections.Generic.IEnumerable`1[T] bookedViews, System.Int32[] indeces) [0x00077] in <0d63e6746cbf4a3f9cc5afdd19f2f4f0>:0
>   at PanCardView.CardsView.SetupNextView (System.Int32 index, System.Collections.Generic.IEnumerable`1[T] bookedViews) [0x00039] in <0d63e6746cbf4a3f9cc5afdd19f2f4f0>:0
>   at PanCardView.CardsView.SetupBackViews (System.Nullable`1[T] index) [0x00029] in <0d63e6746cbf4a3f9cc5afdd19f2f4f0>:0
>   at PanCardView.CardsView.SetCurrentView () [0x0016f] in <0d63e6746cbf4a3f9cc5afdd19f2f4f0>:0
>   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021
>   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSAction.cs:178
> 

I hope this helps, please let me know if you need any more information.

**Comment by AndreiMisiukevich** [comment]
proc:Base**CoverFlow**FrontViewProcessor
proc:Base**CoverFlow**BackViewProcessor


Hi, yeah. You are using the wrong processors.
should be:

proc:Base**CarouselView**FrontViewProcessor
proc:Base**CarouselView**BackViewProcessor

if you want to use it within CarouselView

**Comment by AndreiMisiukevich** [comment]
but I will add a check here:

https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Processors/BaseCoverFlowBackViewProcessor.cs#L123


So, just switch to proper processors :)

**Comment by matt-goldman** [comment]
> proc:Base**CoverFlow**FrontViewProcessor
> proc:Base**CoverFlow**BackViewProcessor
> 
> Hi, yeah. You are using the wrong processors.
> should be:
> 
> proc:Base**CarouselView**FrontViewProcessor
> proc:Base**CarouselView**BackViewProcessor
> 
> if you want to use it within CarouselView

Ah I see - thanks!
