### ISSUE TITLE
IsPanInteractionEnabled not working.

### ISSUE THREAD

**Issue by becarioWelldex** [AndreiMisiukevich/CardView#285]
Hi, i have the property IsPanInteractionEnabled="False" and is not swiping to the left or right, what is happening?.

In both platforms iOS and Android.

I am doing it wrong?

this is the code.

<cards:CarouselView 
                    x:Name="CarouselSlide"    
                    ItemsSource="{Binding Cartas}" 
                    HeightRequest="400"
                    IsCyclical="False"
                    IsVerticalSwipeEnabled="False"
                    IsPanInteractionEnabled="False">

                    
                <x:Arguments>
                    <proc:BaseCarouselFrontViewProcessor ScaleFactor="0.5" OpacityFactor="0"/>
                    <proc:BaseCarouselBackViewProcessor ScaleFactor="0.5" OpacityFactor="0"/>
                </x:Arguments>

                <cards:CarouselView.ItemTemplate>
                    <DataTemplate>
                        <ContentView>
                            <Frame BackgroundColor="#002D72" CornerRadius="10" BorderColor="White" HasShadow="True">
                                <Grid>
                                    <Grid.RowDefinitions>
                                        <RowDefinition Height="25"></RowDefinition>
                                        <RowDefinition Height="*"></RowDefinition>
                                    </Grid.RowDefinitions>
                                    <StackLayout Grid.Row="0">
                                        <Label Text="{Binding Titulo}" HorizontalOptions="CenterAndExpand" TextColor="White" FontSize="Medium"/>
                                    </StackLayout>
                                    <StackLayout Grid.Row="1">
                                        <references:ChartView x:Name="GraficaVisual" HeightRequest="300" Chart="{Binding Grafica}"/>
                                    </StackLayout>
                                </Grid>
                            </Frame>
                        </ContentView>
                    </DataTemplate>
                </cards:CarouselView.ItemTemplate>
            </cards:CarouselView>

**Comment by AndreiMisiukevich** [comment]
Hi :) sorry for the delay

**Comment by AndreiMisiukevich** [comment]
IsPanInteractionEnabled forbids to use "panGesture" ... hmm, like smooth scrolling, but preserves the ability to use "swipeGesture". Does it make sense? :)

So, if you wish to forbid any user interaction with your carousel, you should use another property **IsUserInteractionEnabled**

**Comment by becarioWelldex** [comment]
> IsPanInteractionEnabled forbids to use "panGesture" ... hmm, like smooth scrolling, but preserves the ability to use "swipeGesture". Does it make sense? :)
> 
> So, if you wish to forbid any user interaction with your carousel, you should use another property **IsUserInteractionEnabled**

yeah it makes sense but that property don't let me to swipe in both platforms.
btw carouselview now works perfectly with parent:scrollview on android, now the carouselview doesn't move when i swipe up or down, it moves perfectly (smooth) in android but on iOS doesnt'.

Here are the values.
` 
<StackLayout Padding="15">
                <cards:CarouselView 
                    x:Name="CarouselSlide"    
                    ItemsSource="{Binding Cartas}" 
                    HeightRequest="400"
                    IsCyclical="False"
                    IsVerticalSwipeEnabled="False"
                    SwipeThresholdDistance="300"
                    VerticalSwipeThresholdDistance="9000">
                    
                <x:Arguments>
                    <proc:BaseCarouselFrontViewProcessor ScaleFactor="0.5" OpacityFactor="0"/>
                    <proc:BaseCarouselBackViewProcessor ScaleFactor="0.5" OpacityFactor="0"/>
                </x:Arguments>
`

**Comment by AndreiMisiukevich** [comment]
Yes, as for iOS it's known issue, that ParentScrollView works badly

**Comment by AndreiMisiukevich** [comment]
What are you trying to achieve?

**Comment by becarioWelldex** [comment]
> What are you trying to achieve?

Trying to make it smooth like a normal scrollview

**Comment by AndreiMisiukevich** [comment]
> > What are you trying to achieve?
> 
> Trying to make it smooth like a normal scrollview

IsPanInteractionEnabled = false and use regualar scrollView (you won't be able to pan cards, but still can swipe them)

**Comment by becarioWelldex** [comment]
> > > What are you trying to achieve?
> > 
> > 
> > Trying to make it smooth like a normal scrollview
> 
> IsPanInteractionEnabled = false and use regular scrollView (you won't be able to pan cards, but still can swipe them)

i did what you said (normal scrollview and IsPanInteractionEnabled = false ) but i can't swipe cards on both platforms

       <ScrollView>     
            <StackLayout Padding="15">
                <cards:CarouselView 
                    x:Name="CarouselSlide"    
                    ItemsSource="{Binding Cartas}" 
                    HeightRequest="400"
                    IsCyclical="False"
                    IsVerticalSwipeEnabled="False"
                    IsPanInteractionEnabled="False">

**Comment by AndreiMisiukevich** [comment]
@becarioWelldex you cannot pan (panGesture) or swipe (swipeGesture)?

**Comment by becarioWelldex** [comment]
@AndreiMisiukevich i can't swipe to change cards

**Comment by AndreiMisiukevich** [comment]
@becarioWelldex I see a bug. But anyway I can swipe 1 time

**Comment by AndreiMisiukevich** [comment]
check on my sample pls
