### ISSUE TITLE
[Feature Request] CoverFlow animate over multiple cards by changing SelectedIndex

### ISSUE THREAD

**Issue by fjorge-joshkautz** [AndreiMisiukevich/CardView#286]
_Hopefully this isn't already implemented and I simply overlooked the feature (although, I would also be pleased if this was the case)._

In regards to #158 , I think it would be cool if there was the ability for CoverFlow to animate across _multiple_ cards by changing SelectedIndex or SelectedItem. From what I can tell, this is automatic animation works great for cards that are adjacent to one another, but transitioning from the first card to the third card does not display an animation - I understand that in most cases you might not want this, but I think the ability to choose if you want to have this animation display would be nice to have.

[Here is an example](https://i.imgur.com/oiy1MdH.mp4) of current behavior to help visual what I'm trying to explain. Thank you for the consideration!

**Comment by AndreiMisiukevich** [comment]
@fjorge-joshkautz hi) Yeah, I understand you. It would be really very cool feature. But I couldn't implement it. It isn't a trivial task :(

**Comment by AndreiMisiukevich** [comment]
@fjorge-joshkautz how about Fade in / Fade out animation for such cases?

**Comment by fjorge-joshkautz** [comment]
The ability for an animation of any kind in this use case seems like a useful user experience to me. I would be out of line demanding that that a feature be created - I just was thinking that it could be a cool and likely useful feature if it were to be developed. I have been playing around with the initial suggestion, and as you said, it certainly isn't trivial :) I think that fading animations is a much more realistic and achievable goal, if one were inclined to pursue the development of this.

**Comment by AndreiMisiukevich** [comment]
http://www.giphy.com/gifs/StoKNYGnrd4fanT2lK

**Comment by AndreiMisiukevich** [comment]
@fjorge-joshkautz I will release on this week I think)

**Comment by fjorge-joshkautz** [comment]
Awesome - I look forward to it! Thank you!

**Comment by AndreiMisiukevich** [comment]
@fjorge-joshkautz I will release it on this week)

**Comment by AndreiMisiukevich** [comment]
2.3.2
