### ISSUE TITLE
TabView value cannot be null.

### ISSUE THREAD

**Issue by alkharashiam** [AndreiMisiukevich/CardView#287]
Hi , 
I am experimenting with tab view , When I create  embedded tab view It works fine only if every tab content is emtpy . when I try to add a list view or collection view i get value cannot be null error .

**Comment by AndreiMisiukevich** [comment]
please show me your case

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardViewSample/PanCardViewSample/Views/CubeSampleXamlView.xaml

here is my sample

**Comment by alkharashiam** [comment]
this is new , I was using this one :https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardViewSample/PanCardViewSample/Views/CarouselSampleEmbeddedView.xaml

**Comment by alkharashiam** [comment]
<tv:TabViewControl HeaderSelectionUnderlineColor="#800080" HeaderTabTextColor="#800080" HeaderBackgroundColor="#B666D2" HeaderTabTextFontSize="15" TabSpacing="40">
                            <tv:TabViewControl.TabItems>
                                <Binding>
                                    <Binding.Source>
                                        <x:Array Type="{x:Type tv:TabItem}">
                                            <tv:TabItem HeaderIconSource="gift_48.png" HeaderIconWidthRequet="32" HeaderText="Page 1">
                                                <tv:TabItem.Content>
                                                    <StackLayout BackgroundColor="#e9bae5">
                                                        <Label Text="tt"></Label>
                                                        <ListView x:Name="ProgramList">
                                                            <ListView.ItemTemplate>
                                                                <DataTemplate>
                                                                    <ViewCell>
                                                                        <StackLayout>
                                                                            <Label x:Name="NameLabel" Text="{Binding ProgramName}"  FontSize="Large"/>
                                                                            <Label Text="{Binding ProgramDescription}"  FontSize="Small"/>
                                                                        </StackLayout>
                                                                    </ViewCell>
                                                                </DataTemplate>
                                                            </ListView.ItemTemplate>
                                                        </ListView>
                                                    </StackLayout>
                                                </tv:TabItem.Content>
                                            </tv:TabItem>

i edited Xam.Plugin.TabView to take a logo

**Comment by alkharashiam** [comment]
```
 <cards:CubeView.ItemTemplate>
                <DataTemplate>
                    <ContentView>
                        <Frame 
                            VerticalOptions="Center"
                            HorizontalOptions="Center"
                            HeightRequest="300"
                            WidthRequest="300"
                            Padding="0" 
                            HasShadow="false"
                            BackgroundColor="{Binding Color}"
                            IsClippedToBounds="true"
                            CornerRadius="10">
                            
                            <ffimage:CachedImage
                                Source="{Binding Source}" Aspect="AspectFill"/> 
                            
                        </Frame>
                    </ContentView>
                </DataTemplate>
            </cards:CubeView.ItemTemplate>
        </cards:CubeView>
```

how do i define different datatemplate for different cube?

**Comment by fjorge-joshkautz** [comment]
In the past I've used a DataTemplateSelector in C#, here is the documentation to get you steered in the right direction (https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.datatemplateselector?view=netframework-4.8). I'll likely actually be playing around with setting multiple DataTemplates in XAML today, so if I find anything that I think would be helpful for you, I'll keep you posted.

**Comment by AndreiMisiukevich** [comment]
@fjorge-joshkautz I know what is DataTemplateSelector lol :D
And you definitely can use it with this control. Just put it to CubeView.ItemTemplate

**Comment by alkharashiam** [comment]
I dont want to use a datatemplateselector . I meant to use something like this 
<cubeview tab1>
<content 1>
<cubeview tab2>
<content 2>
in xaml

**Comment by AndreiMisiukevich** [comment]
put your views array inside "ItemsSource"

**Comment by AndreiMisiukevich** [comment]
> https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardViewSample/PanCardViewSample/Views/CarouselSampleEmbeddedView.xaml

just a moment, it's not a part of the library! this control is for test only
