### ISSUE TITLE
Cannot set default selected index in TabControl

### ISSUE THREAD

**Issue by huyjack178** [AndreiMisiukevich/CardView#289]
I have 7 items in my carousel view. I want to set the item 4 is the default when appearing in TabControl

**Comment by AndreiMisiukevich** [comment]
Fixed

**Comment by AndreiMisiukevich** [comment]
2.3.2

**Comment by huyjack178** [comment]
@AndreiMisiukevich will new version work when I set selected index in Carousel View?

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich I have tried new version, selected index is already set but the striped bar is disappeared. I see your sample work normal with xamarin form 3.x, after upgrade to 4.x, the striped bar disappears too. I see the problem is about the CardsView.ProcessorDiff can not binding to TabControl in the 1st load. Please check

yes

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich I have tried new version, selected index is already set but the striped bar is disappeared. I see your sample work normal with xamarin form 3.x, after upgrade to 4.x, the striped bar disappears too. I see the problem is about the CardsView.ProcessorDiff can not binding to TabControl in the 1st load. Please check

so can I reproduce it on my sample? I just need to update XF to the latest version, right?

**Comment by huyjack178** [comment]
> > @AndreiMisiukevich I have tried new version, selected index is already set but the striped bar is disappeared. I see your sample work normal with xamarin form 3.x, after upgrade to 4.x, the striped bar disappears too. I see the problem is about the CardsView.ProcessorDiff can not binding to TabControl in the 1st load. Please check
> 
> so can I reproduce it on my sample? I just need to update XF to the latest version, right?

Yes :D

**Comment by huyjack178** [comment]
@AndreiMisiukevich any news? :D

**Comment by AndreiMisiukevich** [comment]
2.3.3

**Comment by huyjack178** [comment]
@AndreiMisiukevich works like a charm, thanks a lot :)
