### ISSUE TITLE
Cannot set initial position via SelectedItem binding

### ISSUE THREAD

**Issue by jorgvanriet** [AndreiMisiukevich/CardView#290]
Hi Andrei,

I am using the 'CoverFlowView' and when i bind the ItemSource and set the SelectedItem to the last item in the list, it keeps resetting the SelectedItem to the first item in the list.

Any tips?

Regards,

Jorg

**Comment by AndreiMisiukevich** [comment]
Hi @jorgvanriet could you please share your xaml?

**Comment by jorgvanriet** [comment]
`<panCardView:CoverFlowView x:Name="CoverFlowView1" ItemsSource="{Binding Path=BindingContext.ProgressList, Source={x:Reference Name=DevelopmentViewName}}" 
                               VerticalOptions="FillAndExpand" IsCyclical="False" SelectedItem="{Binding Path=BindingContext.SelectedItem, Source={x:Reference Name=DevelopmentViewName}, Mode=OneWay}">
        <panCardView:CoverFlowView.ItemTemplate>
            <DataTemplate>
                <StackLayout VerticalOptions="FillAndExpand" Padding="20">
                    <Label Text="{Binding Title}" Style="{StaticResource LabelPinkLarge}" />
                    <Label Text="{Binding Week, StringFormat='Week {0}'}" Style="{StaticResource LabelPink}" />
                    <Label Text="{Binding Message}" Style="{StaticResource LabelBlack}" />
                </StackLayout>

            </DataTemplate>
        </panCardView:CoverFlowView.ItemTemplate>
    </panCardView:CoverFlowView>`

**Comment by jorgvanriet** [comment]
Sorry quotes are messing it up

**Comment by AndreiMisiukevich** [comment]
Mode=OneWay

I presume should be a default (two-way, cuz you want to keep it updated in case of any swipes)

**Comment by AndreiMisiukevich** [comment]
```SelectedItem="{Binding Path=BindingContext.SelectedItem, Source={x:Reference Name=DevelopmentViewName}}"```

**Comment by jorgvanriet** [comment]
It's not the OneWay that was just something i tried sorry

**Comment by AndreiMisiukevich** [comment]
@jorgvanriet so, what is the issue?
You cannot select initial item with SelectedItem property, right? But then it works, yep?

**Comment by jorgvanriet** [comment]
Yes, unable to set the initial item.

**Comment by AndreiMisiukevich** [comment]
@jorgvanriet thx, I'll take a look on my sample )

**Comment by AndreiMisiukevich** [comment]
```xaml
    <cards:CarouselView 
        ItemsSource="{Binding Items}"
        SelectedItem="{Binding CurrentItem}">

        <cards:CarouselView.ItemTemplate>
            <DataTemplate>
                <ContentView>
                </ContentView>
            </DataTemplate>
        </cards:CarouselView.ItemTemplate>
    </cards:CarouselView>
```

Works fine for me

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/66522267-b5d47e80-eaf5-11e9-96cd-6324aee3688f.png)

**Comment by AndreiMisiukevich** [comment]
try to build a small sample

**Comment by AndreiMisiukevich** [comment]
btw there is SelectedIndex property if you want to use index instead of an item

**Comment by jorgvanriet** [comment]
Andrei,

I am using the CoverFlowView and your example is the CarouselView.
When i use the SelectedIndex instead of the SelectedItem it works fine.

When i use the SelectedItem is does not work.

**Comment by AndreiMisiukevich** [comment]
@jorgvanriet can I reproduce this issue on my CoverFlowView sample?

**Comment by jorgvanriet** [comment]
You mean you can reproduce or you cannot?

**Comment by AndreiMisiukevich** [comment]
@jorgvanriet sorry. It was a question :) Is it possible to reproduce this issue on my sample?

**Comment by jorgvanriet** [comment]
As a work around i am now binding to the SelectedIndex where i am setting the SelectedItem (i need it for the information it holds)

I will try to reproduce it.

**Comment by jorgvanriet** [comment]
It works with the simple version
I have no idea what the difference is between SelectedIndex and SelectedItem
And no clue why 'SelectedIndex' works and 'SelectedItem' doesn't

Tnx for the help

**Comment by AndreiMisiukevich** [comment]
@jorgvanriet can you build a sample that represents this issue?

**Comment by AndreiMisiukevich** [comment]
Seems I've fixed it

**Comment by AndreiMisiukevich** [comment]
@jorgvanriet I will create a release on this/next week :) if it's not super urgent for you

**Comment by jorgvanriet** [comment]
Tnx alot Andrei !
I will be looking forward to the update :)

**Comment by jorgvanriet** [comment]
Just to let you know it works like a charm! 
Tnx for the quick response!

**Comment by AndreiMisiukevich** [comment]
@jorgvanriet thanks for the feedback :)
