### ISSUE TITLE
CardView swipe up and down

### ISSUE THREAD

**Issue by georgemichailou** [AndreiMisiukevich/CardView#294]
Can i create something like this with CardView ?

![image-asset](https://user-images.githubusercontent.com/14372162/66756430-aad96f80-eea2-11e9-9890-ee7e4fce23b7.gif)

Thanks for the amazing work !!!

**Comment by AndreiMisiukevich** [comment]
Hi, yes, it's possible. But it will require customization because currently there is no exact animation.
Or you can use CardsView and play with rotation.

Also if you want I can consider this enhancement/sample

**Comment by georgemichailou** [comment]
I will try the CardView but if I use rotation and my binding views is rotated also.....

I presiate your help and ideas very much!! 

This is my project, on which I am working on
https://github.com/georgemichailou/ShaXam

**Comment by AndreiMisiukevich** [comment]
@georgemichailou yes, that is why you should set rotation twice

cardsView.Rotation = 90;

<DataTemplate>
  <ContentView Rotation="-90"
</DataTemplate>

**Comment by AndreiMisiukevich** [comment]
But I can consider such an enhancement.

maybe adding a new property "Orientation = [Horizontal | Vertical | Both (in future)]

**Comment by georgemichailou** [comment]
@AndreiMisiukevich Orientation property sounds like a very good feature !! I don't know if the Both option for orientation property is helpful.

**Comment by liangshaojiang** [comment]
> But I can consider such an enhancement.
> 
> maybe adding a new property "Orientation = [Horizontal | Vertical | Both (in future)]

您好 这个功能什么时候添加？

**Comment by AndreiMisiukevich** [comment]
> > But I can consider such an enhancement.
> > maybe adding a new property "Orientation = [Horizontal | Vertical | Both (in future)]
> 
> 您好 这个功能什么时候添加？

In English or Russian or Belarussian, please

**Comment by AndreiMisiukevich** [comment]
> > But I can consider such an enhancement.
> > maybe adding a new property "Orientation = [Horizontal | Vertical | Both (in future)]
> 
> 您好 这个功能什么时候添加？

Cannot tell you an exact date, sorry. But I hope in this month

**Comment by AndreiMisiukevich** [comment]
added IsHorizontalOrientation property

**Comment by georgemichailou** [comment]
Thanks @AndreiMisiukevich for your time and help !!!
