### ISSUE TITLE
[Question] could we use TabControl without cardview?

### ISSUE THREAD

**Issue by aaa1902** [AndreiMisiukevich/CardView#297]
Title says it all

**Comment by AndreiMisiukevich** [comment]
yes, you can.
But you will have to set up several bindings

https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Controls/TabsControl.cs#L82-L86

**Comment by AndreiMisiukevich** [comment]
How do you like to use it without carousel view ?

**Comment by aaa1902** [comment]
> yes, you can.
> But you will have to set up several bindings
> 
> https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Controls/TabsControl.cs#L82-L86

Thanks! also another question what should i set on the Diff and max Diff?
and I also encountered this
Binding 'SelectedIndex' Property not found on 'MyViewModel', target property: 'PanCardView.Controls.TabsControls.SelectedIndex'

> How do you like to use it without carousel view ?

I was originally going to use it with carouselview using a datatemplate for each pane  unfortunately i have problems with it expanding.
As a workaround i just try to switch views.

**Comment by AndreiMisiukevich** [comment]
@aaa1902 I don't think you need TabsControl indeed. Because the main goal of this control is providing "live" stripe. It moves with the CarouselView.

You can just create grid and add tap gestures there
