### ISSUE TITLE
SelectedIndex did not changed after item removed

### ISSUE THREAD

**Issue by Carl-Wen** [AndreiMisiukevich/CardView#298]
``` xml
<cards:CoverFlowView
    VerticalOptions="CenterAndExpand"
    HorizontalOptions="CenterAndExpand"
    IsPanSwipeEnabled="True"
    ItemsSource="{Binding Images}"
    SelectedIndex="{Binding CurrentIndex, Mode=TwoWay}"
    ItemSwiped="Handle_Swiped">
    <cards:CoverFlowView.ItemTemplate>
                    <DataTemplate>
                        <Image Aspect="AspectFit"
                               Source="{Binding .}" />
                    </DataTemplate>
      </cards:CoverFlowView.ItemTemplate>
</cards:CoverFlowView>
```
First, I use it to display images, and I find that after I remove one image from ItemsSource, selectedIndex did not changed.
Second, **SelectedIndex="{Binding CurrentIndex, Mode=TwoWay}"** **Mode=TwoWay** seems not worked.

version: 2.3.4.

**Comment by AndreiMisiukevich** [comment]
I guess it's related https://github.com/AndreiMisiukevich/CardView/issues/290 and already fixed :) just need to bump new version

**Comment by AndreiMisiukevich** [comment]
>> First, I use it to display images, and I find that after I remove one image from ItemsSource, selectedIndex did not change.

Can you please explain?

example:
[0] - [1] - [2] - [3]
CurrentIndex = 1;
We try to remove image by index [2]
CurrentIndex is still 1 and it's right

what is your case?

**Comment by AndreiMisiukevich** [comment]
>> Second, SelectedIndex="{Binding CurrentIndex, Mode=TwoWay}" Mode=TwoWay seems not worked.

it's TwoWay by default and should work. What is your case? Are you trying to remove it in ViewModel and nothing happened? Are you sure you raise PropertyChanged event

Could you pls prepare a sample, if you want to get it fixed in the next release (today / on weekend)

**Comment by Carl-Wen** [comment]
> > > First, I use it to display images, and I find that after I remove one image from ItemsSource, selectedIndex did not change.
> 
> Can you please explain?
> 
> example:
> [0] - [1] - [2] - [3]
> CurrentIndex = 1;
> We try to remove image by index [2]
> CurrentIndex is still 1 and it's right
> 
> what is your case?

Your example is A, it is right, and then B, C:
B:
> example:
> [0] - [1] - [2] - [3]
> CurrentIndex = 3;
> We try to remove image by index [3]
> CurrentIndex should be 2;

C:
> example:
> [0] - [1] - [2] - [3]
> CurrentIndex = 2;
> We try to remove image by index [2]
> CurrentIndex should be 2(the image may should be [3]);

Now my case is B, I don't know which image showed after remove image by CurrentIndex, [0] and [2] is possible, but no mater which one is showed, CurrentIndex should not be 3.

**Comment by Carl-Wen** [comment]
> > > Second, SelectedIndex="{Binding CurrentIndex, Mode=TwoWay}" Mode=TwoWay seems not worked.
> 
> it's TwoWay by default and should work. What is your case? Are you trying to remove it in ViewModel and nothing happened? Are you sure you raise PropertyChanged event
> 
> Could you pls prepare a sample, if you want to get it fixed in the next release (today / on weekend)

This is related to first issue, I will reply you after a test tomorrow.

**Comment by AndreiMisiukevich** [comment]
try 2.3.5

**Comment by Carl-Wen** [comment]
> try 2.3.5

@AndreiMisiukevich Thank you for the fix, it works fine now.
