### ISSUE TITLE
Improvement on Nesting CardView in ScrollView

### ISSUE THREAD

**Issue by kcrandall** [AndreiMisiukevich/CardView#299]
Improvement on nesting CardView in ScrollView. Your workaround is completely functional, save the fact that it doesn't enable high velocity scrolls (when a user scrolls fast and lifts it only scrolls a little bit). I have a suggestion to avoid the interface and possibly fix the scrolls not feeling smooth with the current workaround. 

Put a boolean bindable prop in the card control named something like AutoFindAndScrollParentScroll. What could be better about finding the parent is that you could add a custom Effect to whatever ScrollView is the parent and it could properly pass the pan effect to the ScrollView using the native Effect.

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/effects/introduction

then if its true do something like this on vertical panning:

```
                        ScrollView scrollView = null;
                        var parent = this.Parent;
                        while (parent != null)
                        {
                            if (parent.GetType() == typeof(ScrollView) || parent.GetType().IsSubclassOf(typeof(ScrollView)))
                            {
                                scrollView = parent as ScrollView;
                                break;
                            }
                            parent = parent.Parent;
                        }
                        scrollView.ScrollToAsync(0, yValue);
                        // OR even better add the effect to the scrollview to pass pan args natively
```

**Comment by AndreiMisiukevich** [comment]
>> scrollView.ScrollToAsync(0, yValue);
Have you tried this work around?

**Comment by kcrandall** [comment]
I haven't implemented it into your library and tried it no. But it's the same thing you do, and I do it as well on another control I use. I'm just suggesting you implement the scrolling inside the cardview instead of attaching the interface externally. Inside your handleordinate function in the cardview just use this code to find the parent scrollview instead of requiring the scrollview to implement the interface. 

The second improvement would be to do this to attach an effect instead of the scrolltoasync that passes pan natively. This I have no clue how exactly to do it natively, but I'm sure it's possible. This which would automatically attach the render function on Android instead of using a renderer. You could also improve it as I said by passing the pan args directly to the scrollview instead of just the Y values. Then it could respond properly to user input instead of stopping abruptly when the user moves finger off screen.

**Comment by kcrandall** [comment]
I'm saying this because I implemented the interface on my content page because I use Sflistview. So I found the child scroll view in the sflistview and then manually handled the method you fire. It works well enough but it could be done entirely inside the library instead of externally with a lot less effort. (And the second thing I suggested could work much better with Adding native effects)

**Comment by AndreiMisiukevich** [comment]
@kcrandall but it won't work. I mean "ScrollTo"
You can try it yourself (just download source code and update).

But if it works, feel free to make PR)

**Comment by kcrandall** [comment]
I tried it and it works the same way as adding the interface. It's just all done inside the CardView. I made a PR. More work is needed to make the scrolling more fluid. This has to be done natively. If I have time ill look into it and adding an effect to the ParentScrollView I added in the PR.

**Comment by kcrandall** [comment]
I just saw the new commit seems to be even better then my PR since it does it in the renderer. It looks like the ShouldRecognizeSimultaneously you implemented is way better then either your previous solution or my improvement. If that works all that's needed I guess is to improve the Android part so it doesn't need that scrollview renderer.

**Comment by kcrandall** [comment]
This post seems promising if you pass the ParentScrollView down to the android renderer and just pass the touches there.

https://stackoverflow.com/questions/6374592/passing-touch-events-to-the-parent-view
```
private LinearLayout mParentView;
private TextView mTextView;
private View.OnTouchListener mParentListener = new OnTouchListener() {

    @Override
    public boolean onTouch(View v, MotionEvent event) {
        ......
        return false;
    }
};
mParentView.setOnTouchListener(mParentListener);

mTextView.setOnTouchListener(new View.OnTouchListener() {
    @Override
    public boolean onTouch(View v, MotionEvent event) {
        mParentListener.onTouch(mParentView, event);
        return false;
    }
};
```

**Comment by kcrandall** [comment]
https://forums.xamarin.com/discussion/60621/pangesturerecognizer-stealing-input-in-listview
also I just like to comment here for anyone that uses Xamarin.Forms.ListView. If you use SfListView from syncfusion it has a ScrollView child. So CardView could find the ScrollView in the descendants, whereas I'm not sure if Xamarin.Forms.ListView can (I don't think it can).

**Comment by AndreiMisiukevich** [comment]
yeah @rotorgames helped me
https://gist.github.com/rotorgames/89b124dd85a5bd22c4ca7883183e17e1

just need to embed android's flow to our renderer :)

**Comment by kcrandall** [comment]
Awesome thanks :)

**Comment by AndreiMisiukevich** [comment]
2.3.6

**Comment by kcrandall** [comment]
I have a question about this, I wasn't able to get it working in 2.3.6 on iOS was wondering if I have this configured wrong. 
```
<cards:CubeView
                        x:Name="carousel"
                        ItemSwiped="Carousel_ItemSwiped"
                        IsCyclical="False"
                        IsAutoNavigatingAnimationEnabled="False"
                        IsVerticalSwipeEnabled="False"
                        RelativeLayout.WidthConstraint="{ConstraintExpression
                            Type=RelativeToParent,Property=Width,Factor=1,Constant=0}"
                        RelativeLayout.HeightConstraint="{ConstraintExpression
                            Type=RelativeToParent,Property=Width,Factor=1,Constant=0}"
                        ItemsSource="{Binding Medias}"
                        SelectedIndex="{ Binding SelectedCarouselIndex, Mode=OneWayToSource, Source={x:Reference Name=view} }"
                        IsVisible="{ Binding IsCardCarouselVisible, Source={x:Reference Name=view} }">
                        <cards:CubeView.ItemTemplate>
                            <DataTemplate>
                                <local:MediaView
                                    ScrollPosition="{Binding Path=ParentContext.ScrollPosition, Source={x:Reference Name=view}}"
                                    CurrentCarouselPostion="{ Binding Source={ x:Reference carousel }, Path=SelectedIndex, Mode=OneWay }"
                                    PageId="{Binding Path=ParentContext.PageId, Source={x:Reference Name=view}}"
                                    PageName="{Binding Path=ParentContext.PageName, Source={x:Reference Name=view}}"
                                    IndexPostion="{ Binding Position }"
                                    MediaUri="{ Binding Uri}"
                                    MediaType="{ Binding Attributes.Type }"/>
                            </DataTemplate>                     
                        </cards:CubeView.ItemTemplate> 
                    </cards:CubeView>
```
I've tried vertical swipe true and false. It wasn't passing vertical scrolls to the scroll view

**Comment by AndreiMisiukevich** [comment]
@kcrandall did you call ```CardsViewRenderer.Preserve()```?

**Comment by kcrandall** [comment]
No I did not, should I do that in the app delegate?

**Comment by AndreiMisiukevich** [comment]
@kcrandall of course :) It's described in Readme

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/68192701-c841bb00-ffc2-11e9-8baf-a116da33c4d0.png)

**Comment by kcrandall** [comment]
Oh damn sorry didn't see that lol. It works not thanks!

**Comment by kcrandall** [comment]
Another cool improvement (that I can do manually with the IsPanEnabled property) would be to add the option to disable panning and movement of the carousel when there is only 1 item in the carousel so users don't have to do it externally by monitoring changes to their ItemSource.
