### ISSUE TITLE
.net standard compatibility

### ISSUE THREAD

**Issue by MaxenceMax** [AndreiMisiukevich/CardView#30]
Ca your cardiview be compatible with .net standard in the future ?

**Comment by AndreiMisiukevich** [comment]
@MaxenceMax Hi
It's compatible now.
Can't you install package?

**Comment by MaxenceMax** [comment]
You got right, sorry for this question, i didn't try to install it, i just read the readme. Nice work on this !

**Comment by AndreiMisiukevich** [comment]
@MaxenceMax thanks for feedback
I will be grateful if you set star on this pepo) it helps me to develop this plugin
