### ISSUE TITLE
Auto play False after initialize

### ISSUE THREAD

**Issue by kerbooo** [AndreiMisiukevich/CardView#301]
Hello Andrei, firstly I would like to many thanks for your good plugin. 

Probably I did not find. My question about "How to stop slides auto animations after carousel initialized". I mean is there any property like Carousel Auto Play? I would like to animate just with arrows or swipe.

Thank you in advance.

**Comment by AndreiMisiukevich** [comment]
Hi mate)

I guess you set SlideShowDuration.
Remove this property)

**Comment by AndreiMisiukevich** [comment]
@kerbooo I hope you fixed your issue
