### ISSUE TITLE
Carousel item is not resizing height when translate to 

### ISSUE THREAD

**Issue by huyjack178** [AndreiMisiukevich/CardView#302]
I have used the carousel view and implement a behavior that is when I scrolling up the listview inside the carousel item, I translate the parent view to top for docking, but the issue is the carousel item height can not be scaled like the image below, there is the pink area at the bottom. Do you have any idea to fix this issue?

![giphy](https://user-images.githubusercontent.com/11793001/67748772-43a0eb00-fa5e-11e9-8c25-e0ffa87dab20.gif)

**Comment by huyjack178** [comment]
@AndreiMisiukevich I used LayoutTo instead of TranslateTo and the issue is resolved. Thank you, I will closed this question

**Comment by AndreiMisiukevich** [comment]
awesome thanks
