### ISSUE TITLE
Not working frature IsUserInteractionRunning

### ISSUE THREAD

**Issue by talmurshidi** [AndreiMisiukevich/CardView#303]
The feature IsUserInteractionRunning on IndicatorsControl in PanCardView to prevent the user from using indicators to move between pages not working when it's value is false.
It is tested on Android OS
Nuget CardsView version 2.3.4

**Comment by AndreiMisiukevich** [comment]
Hi @talmurshidi 
This property doesn't respond to what you described.

Try to set IsEnabled = false.

**Comment by talmurshidi** [comment]
I tried IsEnabled and it is working
I there an Event for indicator clicked?

**Comment by AndreiMisiukevich** [comment]
@talmurshidi no, there is no such event/command.

Do you need it?

**Comment by talmurshidi** [comment]
@AndreiMisiukevich 
Yes, I need it and I am working on a project and it was necessary so I wrote a workaround solution.
I my case the user must complete all input field in the pages then can move using swipe or indicator.
If the second page not completed the the user cannot open third page and so on.
Could you provide some examples in the documentation explain how to use command, please?

int currentIndex = 0;
        private void InsertView_ItemAppeared(PanCardView.CardsView view, PanCardView.EventArgs.ItemAppearedEventArgs args)
        {
            var index = args.Index;
            if (index != currentIndex)
                if ((index - currentIndex) == 1)
                    currentIndex = index;
                else if (currentIndex > index)
                    currentIndex = index;
                else
                {
                    currentIndex = index = currentIndex + 1;
                    Task.Delay(100);
                    InsertView.SelectedIndex = currentIndex;
                }
        }

**Comment by AndreiMisiukevich** [comment]
@talmurshidi currently there is no command property that allows you to manage "indicator tapGestureRecognizer's command)

**Comment by AndreiMisiukevich** [comment]
Also you can try "IsNextItemPanInteractionEnabled" of CarouselView. (Setting it to false will forbid to navigate to next cards)
