### ISSUE TITLE
RTL direction in  v 2.3.5

### ISSUE THREAD

**Issue by talmurshidi** [AndreiMisiukevich/CardView#304]
Nuget version 2.3.5
ContentPage FlowDirection="RightToLeft"
IsRightToLeftFlowDirectionEnabled="True" not working as expected because the list should be reversed and indicator also.

Nuget version 2.3.4
In this version it is working as expected.

Could you enhance the nuget to check flow direction for content page or parent, please?

Kind regards

**Comment by AndreiMisiukevich** [comment]
@talmurshidi try to set FlowDirection="Default" and IsRightToLeftFlowDirectionEnabled="True" for carouselView

**Comment by AndreiMisiukevich** [comment]
But I didn't change anything about FlowDirection from 2.3.4 to 2.3.5
Can you show me an example? What exactly doesn't work?

**Comment by AndreiMisiukevich** [comment]
http://www.giphy.com/gifs/j5iD7iW8f7CzcYTJKl

ContentPage FlowDirection="RightToLeft"
IsRightToLeftFlowDirectionEnabled="True"

works fine for me

**Comment by talmurshidi** [comment]
I set FlowDirection="LeftToRight" and IsRightToLeftFlowDirectionEnabled="True" for carouselView
and when open the page it shows the last page from left instead of first page from right.
I will try to upload an example.

**Comment by AndreiMisiukevich** [comment]
> ContentPage FlowDirection="RightToLeft"
> IsRightToLeftFlowDirectionEnabled="True"

check my GIF and sample.

> when open the page it shows the last page from left 

What is wrong here? The last page from the left side, the first one is from the right?

**Comment by talmurshidi** [comment]
I checked the GIF.
I built a project with v 2.3.4 and in the same project you can update the nuget to 2.4.5
In v 2.3.4 is the expected behavior to start from number 1 but in v 2.4.5 will start from number 5 
Project link:
[https://drive.google.com/open?id=121ocfbEK0FHXr60kqWxgP9oqPRXCZ_UP](url)

**Comment by AndreiMisiukevich** [comment]
> but in v 2.4.5 will start from number 5

You mean it starts from the most right element, correct?
But it's proper behavior! The first element is from right side

**Comment by talmurshidi** [comment]
No, it should works as version 2.3.4 first element must be number 1 and beginning from right not left.

**Comment by AndreiMisiukevich** [comment]
seems related https://github.com/AndreiMisiukevich/CardView/issues/305

**Comment by talmurshidi** [comment]
I think it is related.
Same thing in RTL showing last item before first one and the direction is not correct also.
It must start from right to left in RTL
Version 2.3.4 is correct but 2.3.5 is not correct direction.
Kind regards

**Comment by AndreiMisiukevich** [comment]
2.3.6
