### ISSUE TITLE
Expandable view

### ISSUE THREAD

**Issue by dukeval** [AndreiMisiukevich/CardView#307]
Hi Andrei, thank you for that control.  

Is there a way to create an expandable item within the carouselview?  I'm trying to hide/show a label based on users interaction within the view, so if they click a button or tap the content I want to be able to display a label with more information.

I've created a Observable collection that toggles the visibility property of the selectedItem and hope that it will refresh the view and display the label. I know I can do it with a listview but was wondering if it's possible in the carouselview.  I've tried setting the IsViewReusingEnabled to false but can't get it to refresh.

**Comment by AndreiMisiukevich** [comment]
Hi @dukeval 
Why don't use bindings for achieving that?) I mean refreash it on bindingContext changed or smth like that

if you provide me a sample, I will try to help

**Comment by dukeval** [comment]
I do use binding.  I have a isvisible property in my model that's bound to my label which I'm toggling in my VM but it doesn't seem to render in the view.  So after setting Isvisible to true, the label is still hidden.

I don't currently have access to my code but I will send a code snippet later.

Thanks.

Sent from TypeApp<http://www.typeapp.com/r?b=15729>
On Nov 13, 2019, at 4:12 PM, Andrei <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @dukeval<https://github.com/dukeval>
Why don't use bindings for achieving that?) I mean refreash it on bindingContext changed or smth like that

if you provide me a sample, I will try to help

**Comment by AndreiMisiukevich** [comment]
@dukeval looking forward :)

**Comment by dukeval** [comment]
Hi Andrei, I figured it out.  I updated my model to implement INotifyPropertyChange. Then I was able to read the currently selected item from the carouselview and update the Isvisible property and that refreshed the UI.

I guess the issue was that I was expecting the UI to refresh once my Observable collection updated since it raises the PropertyChanged event.  Below is my original code..

`*******Model********
public class Riddle 
{
        public int ID { get; set; }
        public string Category { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public bool IsVisible { get; set; }
}
*******VM********
public class RiddleVM : INotifyPropertyChanged
    {
//implemented INotifyPropertyChanged for property that handled a different function.
        private ObservableCollection<Riddle> riddles;
        public ObservableCollection<Riddle> Riddles { get {return riddles; } set {riddles=value; } }

public void HideOrShowAnswerAsync(Riddle riddle)
        {
            if (oldRiddle == riddle)
            {
                riddle.IsVisible = !riddle.IsVisible;
                UpdateRiddles(riddle);
                //oldRiddle = riddle;
            }
            else
            {
                if (oldRiddle != null)
                {
                    oldRiddle.IsVisible = false;
                    UpdateRiddles(oldRiddle);


                    riddle.IsVisible = true;
                    UpdateRiddles(riddle);
                }
            }
                oldRiddle = riddle;
        }

        private void UpdateRiddles(Riddle riddle)
        {
            int indexPosition = Riddles.IndexOf(riddle);
            Riddles.Remove(riddle);

            Riddles.Insert(indexPosition, riddle);

           // oldRiddles = riddles;
        }
*******View********
<cards:CarouselView x:Name="carouselViewRiddle" UserInteracted="Interaction" ItemsSource="{Binding Riddles}" HeightRequest="890" IsViewReusingEnabled="False">
            <cards:CarouselView.ItemTemplate>
                <DataTemplate>
                    <StackLayout Padding="10">
                        <StackLayout>
                            <StackLayout>
                                <Label Text="{Binding Question}" LineBreakMode="WordWrap" Style="{DynamicResource ListItemTextStyle}" TextColor="#006BB8" FontSize="Title" />
                            </StackLayout>
                            <StackLayout HeightRequest="150">
                                <Label  Text="{Binding Answer}" VerticalOptions="EndAndExpand" HorizontalOptions="CenterAndExpand" IsVisible="{Binding IsVisible}" LineBreakMode="WordWrap" TextColor="Green" FontSize="Medium" FontAttributes="Bold Italic" />
                            </StackLayout>
                        </StackLayout>                                    
                        <StackLayout VerticalOptions="EndAndExpand">
                            <Button Text="Show Answer" CornerRadius="20" Clicked="OnItemTapped" CommandParameter="{Binding Id}" BackgroundColor="{StaticResource Primary}" TextColor="White"></Button>
                        </StackLayout>
                    </StackLayout>
                </DataTemplate>
            </cards:CarouselView.ItemTemplate>            
        </cards

*******View Code Behind********
void OnItemTapped(object sender, EventArgs e)
        {
            var riddleVM = BindingContext as RiddleVM;

            var r iddle= carouselViewRiddle.SelectedItem as Riddle;
            riddle.IsVisible = true;

            riddleVM.HideOrShowAnswerAsync(riddle);
}
           `
