### ISSUE TITLE
Carousel UWP with Listview items Swipe not working correctly

### ISSUE THREAD

**Issue by bPoller2810** [AndreiMisiukevich/CardView#308]
If i swipe on uwp most times its now working correct. The Carousel hangs in between views.

Is there any undocumented renderer i have to preserve or add to the additional assemblys?

**Comment by AndreiMisiukevich** [comment]
Hi @bPoller2810, unfortunately not
This feature requires writing custom renderer for UWP (like it's done for iOS and Android)

If you wish, you can make PR :)
