### ISSUE TITLE
CoverFlowView with swipegesturerecognizer doesn't work on Android

### ISSUE THREAD

**Issue by andrercarvalho** [AndreiMisiukevich/CardView#309]
Hi Andrei,
First of all thanks for your plugin.

Im trying to implement a coverflowview with swipegesturerecognizers and it does not trigger the events on android.

CardsView library version: 2.3.6
Xamarin.Forms version: 4.3.0.991211

`<StackLayout Spacing="0" HeightRequest="60" MinimumHeightRequest="60" HorizontalOptions="FillAndExpand" IsVisible="{Binding Path=IsSchoolSelectorVisible}">
                            <cards:CoverFlowView
                                HeightRequest="60"
                                PositionShiftValue="60"
                                IsCyclical="true"
                                IsAutoInteractionRunning="{Binding SchoolSlider.IsAutoAnimationRunning}"
                                IsUserInteractionRunning="{Binding SchoolSlider.IsUserInteractionRunning}"
                                VerticalOptions="CenterAndExpand"
                                SelectedIndex="{Binding SchoolSlider.CurrentIndex}"
                                ItemsSource="{Binding SchoolSlider.Schools}">
                                <cards:CoverFlowView.ItemTemplate>
                                    <DataTemplate>
                                        <StackLayout Spacing="0">
                                            <StackLayout.GestureRecognizers>
                                                <SwipeGestureRecognizer Direction="Left" Swiped="Grid_SwipeLeft" />
                                                <SwipeGestureRecognizer Direction="Right" Swiped="Grid_SwipeRight" />
                                            </StackLayout.GestureRecognizers>
                                            <Label FontSize="17" FontAttributes="Bold" TextColor="{Binding ColorToShow}" Margin="15,0,0,0" Text="{Binding NameToShow}" HorizontalOptions="Start" VerticalOptions="CenterAndExpand"></Label>
                                        </StackLayout>
                                    </DataTemplate>
                                </cards:CoverFlowView.ItemTemplate>
                            </cards:CoverFlowView>
                        </StackLayout>`

private void Grid_SwipeLeft(object sender, SwipedEventArgs e)
        {
                viewModel.SchoolSlider.PanPositionChangedCommand.Execute(true.ToString());
        }
private void Grid_SwipeRight(object sender, SwipedEventArgs e)
        {
                viewModel.SchoolSlider.PanPositionChangedCommand.Execute(false.ToString());
        }

Any sugestion to debug such situation?

**Comment by AndreiMisiukevich** [comment]
Hi
No need to add SwipeGestureRecognizer
There is an event ItemSwiped
use it
