### ISSUE TITLE
CoverFlowView pan event syncing with MasterDetailPage

### ISSUE THREAD

**Issue by mr5z** [AndreiMisiukevich/CardView#310]
We have an app with a root view of type MasterDetail. One of its detail page have CoverFlowView on it.
Every time we pan from left or right on Xamarin.iOS, the event propagates to the master's drawer.

Below is how we configure the page:

``` xml
<ContentPage>

    <!-- omitted -->

    <cards:CoverFlowView
        Grid.Row="1"
        PositionShiftPercentage="{OnIdiom Phone='.25', Tablet='.55'}"
        ItemsSource="{Binding ItemsSource}"
        SelectedIndex="{Binding SelectedIndex}">

        <x:Arguments>
            <proc:BaseCoverFlowFrontViewProcessor OpacityFactor="0.25" ScaleFactor="0.70" />
            <proc:BaseCoverFlowBackViewProcessor OpacityFactor="0.25" ScaleFactor="0.70" />
        </x:Arguments>

        <cards:CardsView.ItemTemplate>
            <DataTemplate>
                <ViewCell>
                    <!-- omitted -->
                </ViewCell>
            </DataTemplate>
        </cards:CardsView.ItemTemplate>
        
    </cards:CoverFlowView>

</ContentPage>
```

Take note that this issue doesn't exist on version 2.3.3

**Comment by AndreiMisiukevich** [comment]
Hi,
first of all thanks for the fedback

No need to put ViewCell. you may remove it. 
```xaml
<DataTemplate>
                <ViewCell>
                    <!-- omitted -->
                </ViewCell>
</DataTemplate>
```

**Comment by AndreiMisiukevich** [comment]
Can you please tell me the exact version, where this issue was introduced?

**Comment by AndreiMisiukevich** [comment]
try 2.3.5 pls, then 2.3.6 or 2.3.4 :)

**Comment by mr5z** [comment]
> Can you please tell me the exact version, where this issue was introduced?

We are using 2.3.7

**Comment by AndreiMisiukevich** [comment]
@mr5z yeah, got it. I just wonder what is the latest stable version. It will help me to find the reason )

**Comment by mr5z** [comment]
Hi @AndreiMisiukevich

Unfortunately, I might have been mistaken when I said that it is working on version 2.3.3.

I've tried the following versions: 2.3.**3**, 2.3.**4**, 2.3.**5**, 2.3.**6**, 2.3.**7** and none of them prevents the pan event from propagating up to its parent. The drawer still pans along with the cards when I swipe from left to right.

**Comment by mr5z** [comment]
Maybe it's because how `UISplitViewController` (Master-Detail internal implementation) works and this is a Xamarin Forms issue.

**Comment by AndreiMisiukevich** [comment]
@mr5z thanks for the investigation :)

**Comment by joshykautz** [comment]
Looks like you folks beat me to it - was about to report the same thing!
This  has only started happening recently - I've been able to work around it for the time being by setting MasterDetailPage's _IsGestureEnabled_ to false on iOS, since it's not really an issue on Android.

https://imgur.com/a/jT5OrP7

**Comment by joshykautz** [comment]
This works perfectly now - great work, thank you Andrei!
