### ISSUE TITLE
CardView inside to a CarouselView

### ISSUE THREAD

**Issue by georgemichailou** [AndreiMisiukevich/CardView#311]
I use the new Xamarin Forms CarouselView control with different views. 

I try to add the CardView in one view, but swipe doesn't work (i try the new IsHorizontalOrientation property). 

I believe that the problem is the already swipe effect from Carousel control where block the CardView. 

Here is my sample 

https://github.com/georgemichailou/ShaXam

**Comment by AndreiMisiukevich** [comment]
I don't understand,
cardsView inside carousel view?
How will the app detect what view do you want to interact with?

I believe you should simplify your layout
