### ISSUE TITLE
CardView inside ScrollView

### ISSUE THREAD

**Issue by Char0394** [AndreiMisiukevich/CardView#312]
Hi,
When using the CardView inside a Scrollview when scrolling the carrousel go to the next page. 
What specific configuration should I add to prevent this automatic swipe?
I already set: 
-             IsAutoNavigatingAnimationEnabled = false;
-               IsVerticalSwipeEnabled = false;
-             VerticalSwipeThresholdDistance = 30000;

Thanks in advance

**Comment by AndreiMisiukevich** [comment]
Hi
I guess set MoveThresholdDistance to 20
