### ISSUE TITLE
CarouselView crash on UWP when right or left arrow control is used

### ISSUE THREAD

**Issue by Haapsaari-Juha** [AndreiMisiukevich/CardView#314]
Following is working on Android (probably on iOS also, not tested yet) but in UWP it crashes app (exception is System.NullReferenceException: Object reference not set to an instance of an object):
```xaml
<cards:CarouselView Grid.RowSpan="2" Margin="0" ItemsSource="{Binding CarouselPages}" SelectedIndex="{Binding CarouselPosition, Mode=TwoWay}" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
                    <cards:CarouselView.ItemTemplate>
                        <DataTemplate>
                            <Grid Margin="0" Padding="0">
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="*"/>
                                    <RowDefinition Height="150"/>
                                </Grid.RowDefinitions>
                                <Frame Grid.Row="0" BorderColor="{StaticResource Accent}" CornerRadius="10" BackgroundColor="{StaticResource White90}" Margin="20,0,20,0" HasShadow="True" Padding="10" WidthRequest="500" HorizontalOptions="Center" VerticalOptions="Center">
                                    <Frame.Content>
                                        <StackLayout HorizontalOptions="Center" VerticalOptions="Center">
                                            <Label Text="{Binding Title}" TextColor="{StaticResource Accent}" FontSize="Medium" HorizontalOptions="Center" VerticalTextAlignment="Center"/>
                                            <Label Text="{Binding Text}" HorizontalOptions="Center" VerticalTextAlignment="Center" HorizontalTextAlignment="Center"/>
                                        </StackLayout>
                                    </Frame.Content>
                                </Frame>
                            </Grid>
                        </DataTemplate>
                    </cards:CarouselView.ItemTemplate>
                    <cardscontrols:LeftArrowControl/>
                    <cardscontrols:RightArrowControl/>
                    <cardscontrols:IndicatorsControl SelectedIndicatorStyle="{StaticResource CarouselViewActiveIndicator}" UnselectedIndicatorStyle="{StaticResource CarouselViewInactiveIndicator}"/>
                </cards:CarouselView>
```
Stack trace on UWP:
Xamarin.Forms
AnimationExtensions.DoAction (IAnimatable self, Action action)
Xamarin.Forms
AnimationExtensions.Animate[T] (IAnimatable self, String name, Func`2 transform, Action`1 callback, UInt32 rate, UInt32 length, Easing easing, Action`2 finished, Func`1 repeat)
Xamarin.Forms
AnimationExtensions.Animate (IAnimatable self, String name, Action`1 callback, UInt32 rate, UInt32 length, Easing easing, Action`2 finished, Func`1 repeat)
Xamarin.Forms
AnimationExtensions.Animate (IAnimatable self, String name, Animation animation, UInt32 rate, UInt32 length, Easing easing, Action`2 finished, Func`1 repeat)
PanCardView.Utility
AnimationWrapper.Commit (View view, String name, UInt32 rate, UInt32 length, Easing easing)
PanCardView.Controls.ArrowControl
<ResetVisibility>d__53.MoveNext ()
System.Runtime.ExceptionServices
ExceptionDispatchInfo.Throw ()
System.Runtime.CompilerServices.AsyncMethodBuilderCore
<>c.<ThrowAsync>b__6_0 (Object state)
System.Threading.WinRTSynchronizationContextBase
Invoker.InvokeCore ()
Windows.ApplicationModel.Core
UnhandledError.Propagate ()
Microsoft.AppCenter.Utils
ApplicationLifecycleHelper.<ctor>b__17_1 (Object sender, UnhandledErrorDetectedEventArgs eventArgs)

**Comment by AndreiMisiukevich** [comment]
@Haapsaari-Juha hi
can you build a sample project? It should be reported to XF project

**Comment by AndreiMisiukevich** [comment]
seems dispatcher is null for some reasons

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/AnimationExtensions.cs#L278-L302

But it's part of Xamarin.Forms project.

**Comment by Haapsaari-Juha** [comment]
Sample project found from https://github.com/Haapsaari-Juha/DemoApp

**Comment by AndreiMisiukevich** [comment]
@Haapsaari-Juha and steps for reproducing, please

**Comment by Haapsaari-Juha** [comment]
1. Run UWP project from sample and exception is thrown
2. Run Android project from sample and no exception and arrows are shown on carousel view
3. Comment left and right arrow controls from MainPage.xaml in shared project
4. Running with UWP and Android projects both work

**Comment by AndreiMisiukevich** [comment]
Seems UWP DispatcherProvider causes a crash.

**Comment by AndreiMisiukevich** [comment]
well, it's XF issue, that will be fixed in future releases.
here is the workaround:
```csharp
class LeftArrow: LeftArrowControl {
    protected override void ResetVisibility(uint? appearingTime = null, Easing appearingEasing = null, uint? dissappearingTime = null, Easing disappearingEasing = null) {
        //lave it empty
    }
}

class RightArrow: LeftArrowControl {
    protected override void ResetVisibility(uint? appearingTime = null, Easing appearingEasing = null, uint? dissappearingTime = null, Easing disappearingEasing = null) {
        //lave it empty
    }
}
```
