### ISSUE TITLE
IndicatorsControl TapGesture Disable

### ISSUE THREAD

**Issue by chrisfoulds** [AndreiMisiukevich/CardView#315]
Hi,
I am using a carousel view for a startup sequence.
I keep having people on mobile press the IndicatorsControl which I am using to indicate the stage of the setup process they are in, so they are effectively skipping steps.
How can I disable the tap gesture, I can't see an obvious way.

**Comment by AndreiMisiukevich** [comment]
This is a very good question :)

You can use IsEnabled = false, but much clearer would be adding a new property **IsTapToNavigateEnabled**

**Comment by chrisfoulds** [comment]
Ah ok, I added the isenabled but wondered if I was missing a field.
IsTapToNavigateEnabled would be a good additions

**Comment by AndreiMisiukevich** [comment]
Added :) 2.4.0

**Comment by chrisfoulds** [comment]
thank you sir
