### ISSUE TITLE
Right Arrow does not work in CarouselView

### ISSUE THREAD

**Issue by jendang** [AndreiMisiukevich/CardView#317]
Hi,

I used CarouselView to display images, the left arrow works fine when I tap on that, the picture goes backward but the right arrow does not make picture goes forward. Please help me to check it

```xaml
<cards:CarouselView
                                            ItemsSource="{Binding Images}"
                                            SlideShowDuration="3500"
                                            VerticalOptions="FillAndExpand"
                                            HorizontalOptions="FillAndExpand"
                                            >
                            <cards:CarouselView.ItemTemplate>
                                <DataTemplate>
                                    <ContentView>
                                        <Frame 
                                                VerticalOptions="FillAndExpand"
                                                HorizontalOptions="FillAndExpand"
                                                Padding="0" 
                                                Margin="0"
                                                HasShadow="false"
                                               >
                                            <ffimage:CachedImage Source="{Binding ImageUrl}" Aspect="AspectFill" HeightRequest="200" />
                                            
                                        </Frame>
                                    </ContentView>
                                </DataTemplate>
                            </cards:CarouselView.ItemTemplate>
                            <controls:IndicatorsControl SelectedIndicatorStyle="{StaticResource ActiveIndicator}"
                                                        UnselectedIndicatorStyle="{StaticResource InactiveIndicator}" />
                            <controls:LeftArrowControl  />
                            <controls:RightArrowControl />
                        </cards:CarouselView>
```

**Comment by AndreiMisiukevich** [comment]
Hi @jendang can you provide a sample?

**Comment by jendang** [comment]
> Hi @jendang can you provide a sample?
> or can you reproduce it on my samples?

I attached a gif file here, please check it out! Thanz


![carousel](https://user-images.githubusercontent.com/39712063/70698969-b2619d00-1cc8-11ea-8b9b-6db5f981c54c.gif)

**Comment by AndreiMisiukevich** [comment]
Yes, I see the issue, but I cannot reproduce it.

**Comment by AndreiMisiukevich** [comment]
Can you build a sample please? or just run my samples and tell me if you can reproduce this issue

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/tree/master/PanCardViewSample

**Comment by jendang** [comment]
> Can you build a sample please? or just run my samples and tell me if you can reproduce this issue

Yes, I will do

**Comment by jendang** [comment]
@AndreiMisiukevich  : I figured it out why the arrow does not work in my case while I am reproduce the sample. Basically I have a grid layout of 6 rows and 5 cols
- I placed the content of the page including the carouselview like the code below, then I have FloatButton that overlap the grid with carouselview (because I want to make sure the FAB stay the same position when I am scrolling) thats why the right arrow does not work (just curious why the left one is still working :P ). But thank you! I think I will close the topic. 
` <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="*"/>
                <RowDefinition Height="*"/>
                <RowDefinition Height="*"/>
                <RowDefinition Height="*"/>
                <RowDefinition Height="*"/>
                <RowDefinition Height="*"/>
            </Grid.RowDefinitions>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*"/>
                <ColumnDefinition Width="*"/>
                <ColumnDefinition Width="*"/>
                <ColumnDefinition Width="*"/>
                <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>
 <StackLayout Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="5" Grid.RowSpan="6">
             <cards:CarouselView>

                   ....
             </cards:CarouselView>
// Other content here
</StackLayout>
<c:FloatingMenu Grid.Column="4" Grid.Row="0" Grid.RowSpan="6" Margin="0, 0, 10, 10" BGColor="#89be47" OpenIcon="plussign.png" CloseIcon="crossfab.png">
                <c:FloatingButton x:Name="Email" BGColor="#89be47" IconSrc="email.png"/>
                <c:FloatingButton x:Name="Phone" BGColor="#89be47" IconSrc="phonecall.png"/></c:FloatingMenu>
</Grid>`

**Comment by AndreiMisiukevich** [comment]
@jendang I'm glad to hear that it works now :)
