### ISSUE TITLE
System.TypeLoadException with Xamarin.Forms 3.4

### ISSUE THREAD

**Issue by lightwalker01** [AndreiMisiukevich/CardView#318]
Xamarin.Forms 3.4
CardView  2.3.8
Target Platform: Android Oreo 8.1
VS2019
Basic project with single content page and a carousel view inside.

Same solution with Xamarin.Forms >= 3.5 works fine (but at the moment I cannot migrate).

**Comment by AndreiMisiukevich** [comment]
What's the stacktrace?
Cannot reproduce

are you sure it's related to CardsView nuget?

**Comment by AndreiMisiukevich** [comment]
don't forget to call CardsViewRenderer.Preserve(); in mainactivity

**Comment by lightwalker01** [comment]
Exception:
`System.TypeLoadException: Could not resolve type with token 01000071 from typeref (expected class 'Xamarin.Forms.NavigableElement' in assembly 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null')`

Stacktrace:
`0x77 in App1.MainPage.InitializeComponent at C:\Users\[user]\Documents\GitHub\CardsViewTest\App1\App1\obj\Debug\netstandard2.0\MainPage.xaml.g.cs:22,9
	at C:\Users\[user]\Documents\GitHub\CardsViewTest\App1\App1\obj\Debug\netstandard2.0\MainPage.xaml.g.cs(22)
0x9 in App1.MainPage..ctor at C:\Users\[user]\Documents\GitHub\CardsViewTest\App1\App1\MainPage.xaml.cs:14,13
	at C:\Users\[user]\Documents\GitHub\CardsViewTest\App1\App1\MainPage.xaml.cs(14)
0x10 in App1.App..ctor at C:\Users\[user]\Documents\GitHub\CardsViewTest\App1\App1\App.xaml.cs:14,13
	at C:\Users\[user]\Documents\GitHub\CardsViewTest\App1\App1\App.xaml.cs(14)
0x2E in App1.Droid.MainActivity.OnCreate at C:\Users\[user]\Documents\GitHub\CardsViewTest\App1\App1.Android\MainActivity.cs:23,13
	at C:\Users\[user]\Documents\GitHub\CardsViewTest\App1\App1.Android\MainActivity.cs(23)
`

To reproduce:
https://github.com/lightwalker01/CardsViewTest

@AndreiMisiukevich thank you for you attention.

**Comment by AndreiMisiukevich** [comment]
thx I will take a look

**Comment by AndreiMisiukevich** [comment]
no idea for now. I don't use Xamarin.Forms.NavigableElement

**Comment by lightwalker01** [comment]
Update: 
Referencing PanCardView and PanCardView.Droid from master  (downgraded to Xamarin.Forms 3.4) instead of the nuget package makes the app working again...

**Comment by AndreiMisiukevich** [comment]
@lightwalker01 then I suggest you go ahead with this approach as a workaround :)
Or you can try to build local nuget with this settings
