### ISSUE TITLE
Black blinking / Orientation changed issues

### ISSUE THREAD

**Issue by rraallvv** [AndreiMisiukevich/CardView#32]
[Here](https://www.dropbox.com/s/p5wlwam8bvk4ba6/test.zip?dl=0) is a sample project with the issue.

![video](https://user-images.githubusercontent.com/1840524/41406800-7243073a-6f9b-11e8-84ea-751d44c5532a.gif)

**Comment by AndreiMisiukevich** [comment]
Super!

But why did you write, that carousel doesn't want to update children?
I see only one issue - black color blinking.

**Comment by AndreiMisiukevich** [comment]
So, I've resolved black blinking
Is it your issue?)

**Comment by rraallvv** [comment]
@AndreiMisiukevich Sorry about the lack of specificity on the title, I really didn't have a clue of what could be the problem, except for what it could be some maybe related to CarouselView not "updating" the state of the individual pages, their position maybe!?

There is still something weird going on when the device changes orientation, I've attached a screen-capture  below:

![video2](https://user-images.githubusercontent.com/1840524/41422977-24aa4150-6fc8-11e8-9bc7-b44a838a5ae8.gif)

Thanks for looking into the issue.

**Comment by rraallvv** [comment]
@AndreiMisiukevich , it seems adding a call to `RaiseChild()` immediately after the modification in your last commit solves the problem, but I'm not sure if I'm messing with something else by doing so. Maybe the call should be put in some other place, I don't know.

    if (ItemTemplate != null)
    {
        SetupBackViews();
    }
    RaiseChild(CurrentView); // <--- here

Thanks again for looking into this.

**Comment by AndreiMisiukevich** [comment]
Thank you
I will figure out it a little bit later

**Comment by AndreiMisiukevich** [comment]
Btw, if you like this plugin, star pls this project)

**Comment by rraallvv** [comment]
Ok... just stared your plugin, I almost always forget about the staring system.
btw, is this plugin being merged into Xamarin Forms?

**Comment by AndreiMisiukevich** [comment]
@rraallvv no..
I suggested them it, but they are very busy for review.
__
I create new pack version on weekend. Is it ok for you?

**Comment by rraallvv** [comment]
Awesome! It's very much appreciated. Thanks again!

**Comment by dblookup** [comment]
Strange, I have the same problem. Please, is this resolved?
On android and ios, when I switch from portrait to landscape, the previous page is in the middle of the current one.

**Comment by dblookup** [comment]
Hi Andrei,
Xamarin.Forms 3.1.0.637273
CardsView 1.5.6

**Comment by AndreiMisiukevich** [comment]
Could you confirm that this use reproduces on my test samples ? (Which one)
Or send me please your sample

**Comment by dblookup** [comment]
Sure, I just create a sample. Please find attached.
[PanCardViewApp.zip](https://github.com/AndreiMisiukevich/CardView/files/2251329/PanCardViewApp.zip)

**Comment by AndreiMisiukevich** [comment]
@dblookup  thanks a lot) i will look through it a little bit later (maybe tomorrow, maybe at weekend)

**Comment by AndreiMisiukevich** [comment]
@dblookup why don't you want to user ItemTemplate and any ItemsSource?
A added one extra check/attempt, but don't think, that it will help.

So, as you use Views collection instead of ItemTemplate, there is only one instance of you view at one time, and when you change orientation of you device, sometime app cannot get in time all animations etc. And i think, it can be the reason.

Btw, could you create small video with reproduction on you test sample? I tried with iOS simulator (iPhone X), and didn't catch any black blinking

**Comment by dblookup** [comment]
Hello Andrei,
Ok, but it is occured in both situations (ItemTemplate and ItemsSource). Please, find attached the video.

[cardview_mov.zip](https://github.com/AndreiMisiukevich/CardView/files/2257434/cardview_mov.zip)

Thank you so much!

**Comment by AndreiMisiukevich** [comment]
@dblookup hope these fixes will help you.
You may check reproducing of this issue this in my samples or create local nuget ..
