### ISSUE TITLE
CoverFlowView doesn't render 100%

### ISSUE THREAD

**Issue by dblookup** [AndreiMisiukevich/CardView#321]
Please, there is any method to force CoverFlowView's render? It is happening an intermittent issue when my app start. The CoverFlowView doesn't render 100%, please find attached.
![screenshot-2020-01-03_15 42 21 366](https://user-images.githubusercontent.com/39842294/71759794-33a7ec00-2e91-11ea-9b12-ae62f7220ebd.jpg)

**Comment by AndreiMisiukevich** [comment]
Yes, your image/frame should have the same size.

It's not an issue of this library. You should fix your markup

Can you share it with me? I will help (provide a sample)

**Comment by AndreiMisiukevich** [comment]
set HeightRequest, use FillAndExpand. I cannot help without a sample.
But I am sure you missed anything in your markup
