### ISSUE TITLE
[question] Is it possible to scroll items horizontally in TabsControl?

### ISSUE THREAD

**Issue by kalaiy** [AndreiMisiukevich/CardView#322]
Hi Andrei,
I'm using tab control and CarouselView, I have a requirement to scroll items in horizontally when there are more items

**Code**
```xaml  
<cardViewControl:TabsControl
                StripeColor="Gold"
                SelectedIndex="{Binding CurrentIndex}"
                BindingContext="{x:Reference caseDetailsListView}">
                    <cardViewControl:TabsControl.ItemTemplate>
                        <DataTemplate>
                           
                            <Label HorizontalTextAlignment="Center"
                               VerticalTextAlignment="Center"
                               HorizontalOptions="FillAndExpand"
                               VerticalOptions="CenterAndExpand"
                              TextColor="White" FontSize="15"
                               FontAttributes="Bold"
                               Text="{Binding pname, Converter={StaticResource CasePaneltoLabelConverter}}"/>
                        </DataTemplate>
                    </cardViewControl:TabsControl.ItemTemplate>
                  </cardViewControl:TabsControl>
                </ContentView>
             
            <cardView:CarouselView  Grid.Row="1"   x:Name="caseDetailsListView" IsCyclical="False" IsVerticalSwipeEnabled="False" OppositePanDirectionDisablingThreshold="1"
```

![image](https://user-images.githubusercontent.com/19687551/71955849-6c92e880-3224-11ea-810b-781d757b8da1.png)

Any Idea? 

Regards,
Kalaiy

**Comment by AndreiMisiukevich** [comment]
Try to wrap cardViewControl:TabsControl by ScrollView

**Comment by kalaiy** [comment]
Thanks Andrei, But now it throws another issue. Scroll View is not scrolling when CarouselView items moved. 

![ScrollIssue](https://user-images.githubusercontent.com/19687551/71968510-087e1d80-3240-11ea-97ae-5c9ce44be8ec.gif)

**Comment by AndreiMisiukevich** [comment]
> Thanks Andrei, But now it throws another issue. Scroll View is not scrolling when CarouselView items moved.
> 
> ![ScrollIssue](https://user-images.githubusercontent.com/19687551/71968510-087e1d80-3240-11ea-97ae-5c9ce44be8ec.gif)

Then scroll it yourself when index changing :)

scrollView.ScrollToAsync(...)

**Comment by kalaiy** [comment]
Thanks Andrea, it is working as expected.

**Comment by AndreiMisiukevich** [comment]
@kalaiy if you wish, I can Add autoscrolling in the next release

**Comment by kalaiy** [comment]
> @kalaiy if you wish, I can Add autoscrolling in the next release

@AndreiMisiukevich It would be nice to have the auto-scroll feature.

I created in a customized way like this 

`      private void caseDetailsListView_ItemSwiped(PanCardView.CardsView view, PanCardView.EventArgs.ItemSwipedEventArgs args)
        {
            if (view.BindingContext != null)
            {
                var viewModel = view.BindingContext as MyCaseDetailsViewModel;
                var stackItems = tabCaseDetails.Children.FirstOrDefault(o => o is StackLayout);
                if (stackItems != null)
                {
                    scrollCaseDetails.ScrollToAsync(((StackLayout)stackItems).Children[viewModel.CurrentIndex], ScrollToPosition.Center, true);
                }
            }
        }`
