### ISSUE TITLE
Hi, how do I move the control indicator to the top of the screen? 

### ISSUE THREAD

**Issue by TohWei** [AndreiMisiukevich/CardView#325]
Hi,

Apparently, the 'paging' indicator control is always appear at the bottom of the ItemTemapltes regardless where I had it placed in Xaml.  If I am not mistaken, it has to be located within the '<cards:CarouselView></cards:CarouselView>'.  

I've tried to place the indicator control before the '<cards:CarouselView.ItemTemaplte>', but it doesn't appear on the top of the carousel. 

Just wondering, how possible it is to place the indicator control on the top of item templates (On the top of the screen) ?  

Please provide some solutions, thanks.

**Comment by AndreiMisiukevich** [comment]
```xaml
<IndicatorsControl AbsoluteLayout.LayoutBounds=".5,0,-1,-1" />
```
