### ISSUE TITLE
Unselected indicator is squared

### ISSUE THREAD

**Issue by Pomezny** [AndreiMisiukevich/CardView#327]
Hi, after updating, we started having this weird and subtle issue. It seems that Unselected Indicator on position of Selected Indicator is squared. From the looks of it it has low value of CornerRadius.

This is how indicators loook. When I open page with carousel and swipe to move to 2nd page:
![Screenshot1](https://user-images.githubusercontent.com/4263174/72435468-6e1d5d00-379e-11ea-8326-f7a9f7fdad4a.jpg)

Issue persists if I set SelectedIndex to another number. For instance entering directly to index 2.
![Screenshot3](https://user-images.githubusercontent.com/4263174/72435471-6eb5f380-379e-11ea-85cd-640db7b77bec.jpg)
It looks fine, until I swipe, then square is reveled:
![Screenshot2](https://user-images.githubusercontent.com/4263174/72435469-6eb5f380-379e-11ea-9efd-12fd54d6c9da.jpg)

Do you have any hits what to look for, or how to solve this?

Details:
Xamarin.Forms:4.3.0.991221
CardsView NuGets tested: 2.3.7 and 2.4.0
Android: Present on 9 and 10.

**Comment by AndreiMisiukevich** [comment]
weird... hmm
It looks like Xamarin.Forms issue
The frame starts to occupy more space than before after style updating.

**Comment by AndreiMisiukevich** [comment]
Did you update XF version?

**Comment by Pomezny** [comment]
Not yet. I have a deadline breathing on my neck. Will try soon and report my findings.

**Comment by AndreiMisiukevich** [comment]
Have you found the reason yet?

**Comment by AndreiMisiukevich** [comment]
oh?

**Comment by Pomezny** [comment]
I hope I'll test on latest XF this weekend.
