### ISSUE TITLE
Android - ListView inside Carousel Scrolling issue

### ISSUE THREAD

**Issue by huyjack178** [AndreiMisiukevich/CardView#328]
Hi @AndreiMisiukevich, please take a look at the gif, when I pull down to refresh, the listview will be shaking like that. Can you help checking for me?
 
![untitled](https://user-images.githubusercontent.com/11793001/72865503-b0005300-3d0a-11ea-9d94-12cd2d868898.gif)

**Comment by AndreiMisiukevich** [comment]
Hi, try MoveThresholdDistance = 20 or 10

**Comment by huyjack178** [comment]
@AndreiMisiukevich issue is still happened

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich issue is still happened

okay, with 50 too ?

**Comment by AndreiMisiukevich** [comment]
Try OppositePanDirectionDisablingThreshold = 1

**Comment by huyjack178** [comment]
I use CarouselView sir

**Comment by huyjack178** [comment]
Enable that property makes my listview scroll is hard and too laggy

**Comment by huyjack178** [comment]
I try the new version, and the issue is happening in iOS as well

**Comment by AndreiMisiukevich** [comment]
> Try OppositePanDirectionDisablingThreshold = 1

try tot set 5 or 10

**Comment by huyjack178** [comment]
> Enable that property makes my listview scroll is hard and too laggy

As I told you, enable that property make my listview scroll is hanging and too laggy

**Comment by AndreiMisiukevich** [comment]
Weird. This property just disallow horizontal scrolling, if the gesture is vertical

**Comment by AndreiMisiukevich** [comment]
Are you experienced your initial issue on iOS? or android only?

**Comment by huyjack178** [comment]
https://drive.google.com/file/d/1ZWvZZ-eL47HddAwzm-TbPEdZPPtOjAly/view?usp=sharing
Please help check, let's check the LiveScore.Features -> Scores -> Views -> ScoresView.xaml

**Comment by akamud** [comment]
I just confirmed I have the same issue on Android.

**Comment by AndreiMisiukevich** [comment]
Hmm @akamud @huyjack178
Who knows how to resolve this stupid bug? Does anybody want to debug?

**Comment by huyjack178** [comment]
Hi @AndreiMisiukevich, I had time to debug your code, can you check on CardsViewRenderer in Android, this method 

```

  public override bool OnInterceptTouchEvent(MotionEvent ev)
        {
            DetectEvent(ev);

            if (!Element.IsPanInteractionEnabled || Element.ShouldThrottlePanInteraction)
            {
                base.OnInterceptTouchEvent(ev);
                return false;
            }

            if (ev.ActionMasked == MotionEventActions.Move)
            {
                if (_lastTouchHandlerId.HasValue && _lastTouchHandlerId != _elementId)
                {
                    return false;
                }

                return SetIsTouchHandled(GetTotalX(ev), GetTotalY(ev));
            }

                HandleDownUpEvents(ev); // TODO: check Element.IsVerticalSwipeEnabled then 
         
            return false;
        }


 public override bool OnTouchEvent(MotionEvent e)
        {
            DetectEvent(e);
            if (e.ActionMasked == MotionEventActions.Move)
            {
                var xDelta = GetTotalX(e);
                var yDelta = GetTotalY(e);
                SetIsTouchHandled(xDelta, yDelta);

                if (Abs(yDelta) <= Abs(xDelta))
                {
                    UpdatePan(GestureStatus.Running, xDelta, yDelta);
                }
            }

     
                HandleDownUpEvents(e); // TODO: check Element.IsVerticalSwipeEnabled then HandleDownUpEvent


            return true;
        }
```

**Comment by huyjack178** [comment]
@AndreiMisiukevich , Hi, I had time to debug your code, I see the problem throws in these lines of code in CardsView.cs, in OnPanUpdated line 584, remove the code for Android 

```
[EditorBrowsable(EditorBrowsableState.Never)]
        public void OnPanUpdated(PanUpdatedEventArgs e)
        {
            if (ItemsCount <= 0 || !IsPanInteractionEnabled)
            {
                return;
            }

            var diff = e.TotalX;
            var oppositeDirectionDiff = e.TotalY;
            if (!IsHorizontalOrientation)
            {
                var tempDiff = diff;
                diff = oppositeDirectionDiff;
                oppositeDirectionDiff = tempDiff;
            }
            switch (e.StatusType)
            {
                case GestureStatus.Started:
                    OnTouchStarted();
                    return;
                case GestureStatus.Running:
                    OnTouchChanged(diff, oppositeDirectionDiff);
                    return;
                case GestureStatus.Canceled:
                case GestureStatus.Completed:
                    // I remove these lines then the issue has gone
                    //if (Device.RuntimePlatform == Device.Android)
                    //{
                    //    OnTouchChanged(diff, oppositeDirectionDiff);
                    //}
                    OnTouchEnded();
                    return;
            }
        }
```

**Comment by AndreiMisiukevich** [comment]
If I did that, it was needed.

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/commit/c50897e6b4fbebb72ca09ce90dfc849778330db9

**Comment by huyjack178** [comment]
Thanks, waiting for new version

**Comment by huyjack178** [comment]
Hi @AndreiMisiukevich, I have another issue, I used CarouselView as a ListView Header, when I pull down to refresh, it also affects the CarouselView. Please take a look at the gif below
                                 
![untitled](https://user-images.githubusercontent.com/11793001/74140232-4ac3c180-4c27-11ea-824f-2cea37996db1.gif)

**Comment by AndreiMisiukevich** [comment]
> Hi @AndreiMisiukevich, I have another issue, I used CarouselView as a ListView Header, when I pull down to refresh, it also affects the CarouselView. Please take a look at the gif below
> 
> ![untitled](https://user-images.githubusercontent.com/11793001/74140232-4ac3c180-4c27-11ea-824f-2cea37996db1.gif)

Well, the previous issue is resolved, right?

**Comment by AndreiMisiukevich** [comment]
OppositePanDirectionDisablingThreshold = 1 doesn't help, does it?

**Comment by huyjack178** [comment]
Yes, it doesn't

**Comment by AndreiMisiukevich** [comment]
Can you get rid of headers? Just use datatemplateselector for this

**Comment by huyjack178** [comment]
What do you mean?

**Comment by AndreiMisiukevich** [comment]
> What do you mean?

You said that the carousel view is the header of ListView.
I propose to put carousel view as a separate cell (first cell)
