### ISSUE TITLE
Card stuck when app moved to background while swiping

### ISSUE THREAD

**Issue by stanbav** [AndreiMisiukevich/CardView#329]
1. Tap Home button while swiping items in CarouselView. Do not release your finger when Home button is pressed.
2. Move app to foreground.

Result:
One is card stuck

**Comment by AndreiMisiukevich** [comment]
cannot replicate this issue on the simulator

**Comment by AndreiMisiukevich** [comment]
Also cannot reproduce on my real iPhone XS device

**Comment by AndreiMisiukevich** [comment]
```csharp
            Device.BeginInvokeOnMainThread(() =>
            {
                var setCurrentView = carousel.GetType().GetMethod("SetCurrentView", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
                setCurrentView.Invoke(carousel, new object[] { });
            });
```

Please try this workaround on OnAppearing method of the page that contains carousel.

**Comment by AndreiMisiukevich** [comment]
Hey @stanbav this issue should be fixed ;)
