### ISSUE TITLE
Deleting last element in cards collection causes ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by webmetender** [AndreiMisiukevich/CardView#331]
Hello Andrei,

In the app, I am using CardsView 2.4.0 to display one or more attachments (images or PDFs) to a receipt. Deleting elements of the collection works fine except for when I delete the last element in the list. It causes this exception:
[MonoDroid] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

The execution never reaches the point of testing if the collection is empty in order to return to the previous page. Index of list is -1 after deletion.
I have attached the stack trace.

Thank you,
Adam
[Stack trace.txt](https://github.com/AndreiMisiukevich/CardView/files/4171189/Stack.trace.txt)

**Comment by AndreiMisiukevich** [comment]
Hi, can you please attach a small sample with this issue?
I couldn't reproduce it

**Comment by AndreiMisiukevich** [comment]
2.4.2

**Comment by webmetender** [comment]
Hi Andrei
sorry, I was not able to respond earlier.
I too was not able to reproduce the bug in a small app, I guess it was happening because some binding mish-mash in the app I am working on.
Anyway, the fix you provided fixed the crash, I upgraded to 2.4.4 and all works perfectly, so thanks a lot for it :)
