### ISSUE TITLE
TabsControl IsCyclical not working

### ISSUE THREAD

**Issue by rredoh** [AndreiMisiukevich/CardView#333]
Hi @AndreiMisiukevich . Would you mind check this? Thanks.
I cannot make it non-cyclical on android and ios

**Comment by AndreiMisiukevich** [comment]
Hi) You should disable it on carousel.

carousel.IsCyiclical = false.


Or send me xaml over email or post here

**Comment by rredoh** [comment]
okay. it's working as expected. thanks
