### ISSUE TITLE
How to get the arrow controls event?

### ISSUE THREAD

**Issue by winsonet** [AndreiMisiukevich/CardView#334]
I want to show the difference photo notes when change to others, I can use the `ItemSwiped` event for handle this when swiped a photo, but how to handle when click the left and right arrow controls? I can't find any events about it :(

I just put a separate label for show the notes, please find below screen for my case:

![image](https://user-images.githubusercontent.com/1869995/74785419-3cd80580-52e5-11ea-9d2c-ee1a98e1f779.png)

thanks!

**Comment by AndreiMisiukevich** [comment]
Hi, first of all you should not use ItemSwiped event.
You should use ItemAppearing/ItemAppeared event instead!

**Comment by winsonet** [comment]
hum...I know the  ItemAppearing/ItemAppeared, but for left and right, I need to know the direction, otherwise I can't get the correct index, because the difference direction will be difference index :(

**Comment by AndreiMisiukevich** [comment]
>> I can't get the correct index

But ItemAppearing provides the index

**Comment by AndreiMisiukevich** [comment]
Look

![image](https://user-images.githubusercontent.com/10124814/74815990-4e340880-530b-11ea-9e44-b8767b81f144.png)


Index, Item and IsNextSelected (True - right swipe. False - left)

**Comment by winsonet** [comment]
ok, i will try it again, thanks!

**Comment by AndreiMisiukevich** [comment]
@winsonet feel free to message me with any questions!

**Comment by winsonet** [comment]
ok, I will, thank you so much!

**Comment by winsonet** [comment]
Yes! I tried to use ItemAppeared and it can get the correct index and don't need to handle again, thanks!!
