### ISSUE TITLE
Xamarin Forms - UWP - Item pages do not always render

### ISSUE THREAD

**Issue by mmurfinsimmons** [AndreiMisiukevich/CardView#335]
I am trying to to use this to present a swipeable 'tabbed pages' wizard data-entry pages effect.
ItemSource is set to an observable collection of custom complex contentview types (no template).
On **Android** and **IOS** this works correctly.
On **UWP** sometimes items appear 'blank' when navigated to from the tab-header or in code.
If I touch+drag even a tiny bit then the blank view is rendered, or if I revisit the page 2nd time is fine.

      <cards:CarouselView x:Name="carousel"
                                HorizontalOptions="FillAndExpand"
                                IsCyclical="False"
                                ItemsSource="{Binding ResultWizardValidPages}"
                                IsUserInteractionEnabled="{Binding IsSwipingEnabled}"
                                IsVerticalSwipeEnabled="False"
                                SelectedIndex="{Binding CurrentPageIndex}"
                                SwipeThresholdDistance="25"
                                VerticalOptions="FillAndExpand" />

The 'pages' are created in code (many variations) (build up observable list).
```
addPage(checklistPage, STStyles.Res(Constants.STRING_PAGE_BUILDING_CHECKLISTS));
addPage(correctionPage, STStyles.Res(Constants.STRING_PAGE_BUILDING_CORRECTION));
addPage(attachmentPage, STStyles.Res(Constants.STRING_PAGE_ATTACHMENTS));
addPage(commentPage, STStyles.Res(Constants.STRING_PAGE_COMMENTS));
addPage(resultPage, STStyles.Res(Constants.STRING_PAGE_RESULTS));
addPage(summaryPage, STStyles.Res(Constants.STRING_PAGE_SUMMARY));
```

**Comment by AndreiMisiukevich** [comment]
Try v. 2.4.5

**Comment by AndreiMisiukevich** [comment]
Try it and let me know the result)

**Comment by mmurfinsimmons** [comment]
Thanks - that fixes it perfectly!

**Comment by AndreiMisiukevich** [comment]
> Thanks - that fixes it perfectly!

Please verify that issue doesn't exist on 2.4.6 as well

**Comment by mmurfinsimmons** [comment]
Andrei - 2.4.6 reverted the code fixes and this defect has reappeared.

**Comment by AndreiMisiukevich** [comment]
Ah, thanks.

**Comment by AndreiMisiukevich** [comment]
Please reopen this issue

**Comment by AndreiMisiukevich** [comment]
Don't you mind to try one more version? (I don't have Windows for testing)

**Comment by AndreiMisiukevich** [comment]
Please try 2.4.7 (if it is not working as well, then I will revert changes and put my initial fix :) )

**Comment by mmurfinsimmons** [comment]
Andrei,  v2.4.7 [88f1181](https://github.com/AndreiMisiukevich/CardView/commit/88f1181fb7e03fd160ed2e867bc1cfa14f48c034) does **not** fix my original UWP problem.

**Comment by AndreiMisiukevich** [comment]
2.4.8

**Comment by mmurfinsimmons** [comment]
Thanks! 2.4.8 is rendering programmatic page switches again!
