### ISSUE TITLE
ParentScrollView removed?

### ISSUE THREAD

**Issue by LeoJHarris** [AndreiMisiukevich/CardView#336]
Hi there,

Was ParentScrollView removed on a previous version? If it was is it safe to replace with XF scrollview. We did an update on this project and noticed the ParentScrollView could not be found.

**Comment by AndreiMisiukevich** [comment]
> Hi there,
> 
> Was ParentScrollView removed on a previous version? If it was is it safe to replace with XF scrollview. We did an update on this project and noticed the ParentScrollView could not be found.

Hi )
Yes, ParentScrollView is removed) just replace by ScrollView

**Comment by LeoJHarris** [comment]
Cool thanks for the quick response 👍  thanks for the great work on the projects you provide @AndreiMisiukevich! 🥇 Amazing work!

**Comment by AndreiMisiukevich** [comment]
> Cool thanks for the quick response 👍 thanks for the great work on the projects you provide @AndreiMisiukevich! 🥇 Amazing work!

thanks)
