### ISSUE TITLE
Non-public API usage - iOS Issue

### ISSUE THREAD

**Issue by donovancarthew** [AndreiMisiukevich/CardView#34]
When I try to upload the binary to the app store I get the following message from apple:

"We identified one or more issues with a recent delivery for your app, "<<APP_NAME>>". Please correct the following issues, then upload again.

Non-public API usage:

The app references non-public selectors in <<APP_NAME>>.iOS: applicationWillTerminate, setOrientation:animated:, terminateWithSuccess

If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed."

**Comment by AndreiMisiukevich** [comment]
Why do you think, that this errors is referring to CardsView plugin?

**Comment by AndreiMisiukevich** [comment]
- As for iOS part, this plugin is fully cross-platform and depends on Xamarin.Forms package ONLY.
..
I'm sure, you should look for the reason in your code or other 3rd party packages.
..
Do you use calabash framework? It can be the reason.
And try set linker, if you haven't done it.

**Comment by AndreiMisiukevich** [comment]
You can investigate source code
I don't use such methods.

**Comment by donovancarthew** [comment]
Sorry, I assumed that is was this package because I saw on another forum that someone else had the same issue and said it was this package.

I have done further investigation and found that it was to do with the Xamarin.Forms.TestCloud package that was being included in the release build for some reason. Removing that fixed the issue for me.

Thanks for your help!

**Comment by amirvenus** [comment]
It looks like the issue is back again...

**Comment by AndreiMisiukevich** [comment]
> It looks like the issue is back again...

hi, have you read the conversation ?)

This issue is not related to this nuget package

I don't use those private methods
