### ISSUE TITLE
CoverFlow issue with overlaping views when PositionShiftPercentage is greater then 0.4

### ISSUE THREAD

**Issue by CatOkHero** [AndreiMisiukevich/CardView#341]
Dear Andrei,

I'm trying to achieve something like on the [video](https://imgur.com/a/qjdKdrE), but see the issue with that.
Here is my XAML:

     <cards:CoverFlowView 
		**PositionShiftPercentage="0.5"**
                IsCyclical="false"
                SelectedIndex="{Binding CurrentIndex}"
                ItemsSource="{Binding Items}">
                <x:Arguments>
                    <proc:BaseCoverFlowFrontViewProcessor ScaleFactor="0.75" **OpacityFactor="1"** />
                    <proc:BaseCoverFlowBackViewProcessor  ScaleFactor="0.75" **OpacityFactor="0"** />
                </x:Arguments>
            <cards:CoverFlowView.ItemTemplate>
                <DataTemplate>
                   <Frame
                       Margin="80"
                       VerticalOptions="Center"
                       HorizontalOptions="Fill"
                       Padding="0" 
                       HasShadow="false"
                       IsClippedToBounds="true"
                       CornerRadius="10"
                       BackgroundColor="{Binding Color}">
                            <ffimage:CachedImage Source="{Binding Source}" Aspect="AspectFill"/> 
                        </Frame>
                </DataTemplate>
            </cards:CoverFlowView.ItemTemplate>
            <controls:LeftArrowControl
                AbsoluteLayout.LayoutBounds="0, 1, -1, -1"
                ImageSource="{Static res:ResourcesInfo.BlackLeftArrowImageSource}" />
            <controls:RightArrowControl
                AbsoluteLayout.LayoutBounds="1, 1, -1, -1"
                ImageSource="{Static res:ResourcesInfo.BlackRightArrowImageSource}"/>
        </cards:CoverFlowView>

As we can see, the front view isn't actually the front one and become after I tap on it (after the swipe).
Maybe I missed something in XAML?

**Comment by AndreiMisiukevich** [comment]
Hi @CatOkHero 
Unfortunately, overlapping is not supported by coverflowView. I'd suggest you to redesign your screen to not have overlapping.

**Comment by CatOkHero** [comment]
Thank you)
