### ISSUE TITLE
Возможно ли отключить анимацию при замене картинки.

### ISSUE THREAD

**Issue by igor-niv** [AndreiMisiukevich/CardView#342]
Я использую PanCardView.CarouselView в Xamarin.Forms приложении. 
После того, как фотографии отобразились в PanCardView.CarouselView, я должен, по нажатию кнопки пользователем, выполнить преобразовании фотографии, которая является текущей видимой в PanCardView.CarouselView, к Ч/Б. Затем должен вывести обработанную фотографию заместо старой в PanCardView.CarouselView.
Для хранения массива фотографий я использую ObservableCollection.
Замену картинки произвожу так:  mObservableCollection[index] = new { Source = img },
где img - обработанная фотография, которую я должен вывести.

Во время такой замены картинки я вижу анимацию

![ezgif com-resize](https://user-images.githubusercontent.com/7149306/77919888-8ee65080-72bf-11ea-9b41-f70069678981.gif)

Возможно ли сделать замену картинки без этого анимированного сдвига?
Заранее, спасибо.

P.S. Ниже XAML код с CarouselView (если понадобится).

` <cards:CarouselView 
                ItemsSource="{Binding Items}"
                x:Name="mCarouselView"
                BackgroundColor="{DynamicResource backgroundColor}">
                <cards:CarouselView.ItemTemplate>
                    <DataTemplate>
                        <ContentView>
                            <Frame 
                                VerticalOptions="Center"
                                HorizontalOptions="Center"
                                HeightRequest="1600"
                                WidthRequest="800"
                                Padding="0" 
                                HasShadow="false"
                                IsClippedToBounds="true"
                                CornerRadius="10"
                                BackgroundColor="{DynamicResource backgroundColor}">
                                <Image Source="{Binding Source}" />
                            </Frame>
                        </ContentView>
                    </DataTemplate>
                </cards:CarouselView.ItemTemplate>
                <controls:IndicatorsControl ToFadeDuration="1500"/>
            </cards:CarouselView>`

**Comment by AndreiMisiukevich** [comment]
привет) Да, конечно

выставь IsAutoNavigatingAnimationEnabled = false
