### ISSUE TITLE
CurrentItem doesn't refresh if the ItemsSource collection is edited

### ISSUE THREAD

**Issue by Tommigun1980** [AndreiMisiukevich/CardView#343]
Hi, and thanks for a great component!

I found this issue where the card view's CurrentItem doesn't update if the currently active card is removed from the ItemsSource. I haven't verified but I guess the same thing will happen if a card is added to the collection before the current card.

I added the following workaround to my code for now:
```
        public void HackRefreshCardsViewCurrentItem()
        {
            object selectedItem = null;
            int index = 0;
            foreach (var item in this.cards.ItemsSource)
            {
                if (index++ == this.cards.SelectedIndex)
                {
                    selectedItem = item;
                    break;
                }
            }
            this.cards.SelectedItem = selectedItem;
        }
```
... which I call whenever I change the card view's ItemsSource (ie it forcefully refreshes the SelectedItem).

Would be great if this was fixed so I could remove my hack! My card view is in the PanCardView mode.

Thanks so much!

**Comment by AndreiMisiukevich** [comment]
v.2.5.1

**Comment by Tommigun1980** [comment]
Wow, so fast and it works perfectly now! Thanks so much Andrei 👍

**Comment by AndreiMisiukevich** [comment]
> Wow, so fast and it works perfectly now! Thanks so much Andrei 👍

you are welcome)
