### ISSUE TITLE
Height Issue with CarouselView (Identified on iOS, not tested on Android)

### ISSUE THREAD

**Issue by hamid-shaikh** [AndreiMisiukevich/CardView#344]
Thanking you for writing this wonderful CarouselView Control.

The following is my xaml example
            

> 
>             <ScrollView
>                 x:Name="parentScrollView"
>                 Orientation="Vertical">
>                 <StackLayout
>                     x:Name="parentStackLayout"
>                     Spacing="20">
>                     
>                     <cards:CarouselView
>                         x:Name="mainDataView"
>                         VerticalOptions="StartAndExpand"
>                         IsCyclical="False"
>                         SelectedIndex="{Binding Source={x:Reference thisParentView}, Path=Parent.BindingContext.PageBindingModel.SelectedItemIndex}"
>                         ItemsSource="{Binding Source={x:Reference thisParentView}, Path=Parent.BindingContext.PageBindingModel.ServiceTabs}">
>                         <cards:CardsView.ItemTemplate>
>                             <DataTemplate>
>                                 <StackLayout
>                                     Spacing="0"
>                                     VerticalOptions="StartAndExpand">
> 
>                                     
>                                     <StackLayout
>                                         Spacing="20">
> 
>                                         <appControls:AppExpandCollapseControl
>                                             ParentScrollView="{Binding Source={x:Reference parentStackLayout}, Path='Parent'}"
>                                             HeaderText="{appHelpers:Translate TXM_Hea_014}">
>                                             <appControls:AppExpandCollapseControl.DataViews>
> 
>                                                 
>                                                 <StackLayout
>                                                     Spacing="0">
>                                                     <appControls:AppExpandCollapseItemControl
>                                                         ItemTitle="{appHelpers:Translate TXM_Lab_035}"
>                                                         ItemValue="{Binding someBinding}" />
> 
>                                                     <appControls:AppExpandCollapseItemControl
>                                                         ItemTitle="{appHelpers:Translate TXM_Lab_001}"
>                                                         ItemValue="{Binding someBindinge}" />
>                                                 </StackLayout>
>                                             </appControls:AppExpandCollapseControl.DataViews>
>                                         </appControls:AppExpandCollapseControl>
> 
>                                         <appControls:AppExpandCollapseControl
>                                             ParentScrollView="{Binding Source={x:Reference parentStackLayout}, Path='Parent'}"
>                                             HeaderText="{appHelpers:Translate TXM_Hea_018}">
>                                             <appControls:AppExpandCollapseControl.DataViews>
> 
>                                                 
>                                                 <StackLayout
>                                                     Spacing="0">
> 
>                                                     <appControls:AppExpandCollapseItemControl
>                                                         ItemTitle="{appHelpers:Translate TXM_Lab_008}"
>                                                         ItemValue="{Binding somebinding}" />
> 
>                                                     <appControls:AppExpandCollapseItemControl
>                                                         ShowItemType="AttachmentView"
>                                                         AttachmentCommand="{Binding Source={x:Reference thisParentView}, Path='Parent.BindingContext.AttachmentCommand'}"
>                                                         ItemTitle="{appHelpers:Translate TXM_Lab_066}"
>                                                         ItemValue="{Binding somebinding}" />
>                                                 </StackLayout>
>                                             </appControls:AppExpandCollapseControl.DataViews>
>                                         </appControls:AppExpandCollapseControl>
>                                     </StackLayout>
>                                 </StackLayout>
>                             </DataTemplate>
>                         </cards:CardsView.ItemTemplate>
>                     </cards:CarouselView>
> 
>                     
>                     <appViews:VisitWebSiteView
>                         Margin="30,0" />
>                 </StackLayout>
>             </ScrollView>

The issue occurs in following two scenarios
Note:- Each ItemTemplate are different, each template will 3 to 6 expandcollapsecontrol

1. When changing selectionindex then previous template height is assigned to current selected template
2. when performing expand height is increased but when collapsing some top items are hidden and cannot scroll to them as height got reduced to visible items height only

I will try to create sample solution and share link asap

**Comment by AndreiMisiukevich** [comment]
1. Try to set IsViewReusingEnabled = false

**Comment by AndreiMisiukevich** [comment]
2. Maybe try to call ForceLayout or smth like this
