### ISSUE TITLE
ListView in CarouselView not rendering properly on iPhone 11 or X

### ISSUE THREAD

**Issue by ericallen13** [AndreiMisiukevich/CardView#345]
There seems to be an issue with the phones that have cutouts around space allocation of ListViews within CarouselViews when in landscape mode. When displayed in landscape mode the ListView is getting pushed over to one side or the other by blank space.

The following XAML displays as intended on android and all iOS phones that don't use the cutout but for whatever reason the cutout seems break the listview's width.

`  <cards:CardViewExtended ItemsSource="{Binding BusinessList}"  SelectedIndex="{Binding BusinessHeaderIndex}"   VerticalOptions="CenterAndExpand"  HorizontalOptions="FillAndExpand" IsCyclical="True" IsNextItemPanInteractionEnabled="True" IsPrevItemPanInteractionEnabled="True"  >

                        <cards:CardViewExtended.ItemTemplate>

                            <DataTemplate>
                                <ViewCell>
                                    <StackLayout HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
                                        <ListView HorizontalOptions="FillAndExpand" ItemsSource="{Binding BindingContext.Metrics, Source={x:Reference Main}}" VerticalOptions="FillAndExpand" HasUnevenRows="True" >
                                        <ListView.ItemTemplate>
                                            <DataTemplate>
                                                <ViewCell>

                                                   

                                                        <Grid HorizontalOptions="FillAndExpand" RowSpacing="0" Padding="0,10,0,10">
                                                            <Grid.RowDefinitions>
                                                                <RowDefinition Height="*"/>
                                                            </Grid.RowDefinitions>
                                                            <Grid.ColumnDefinitions>
                                                                <ColumnDefinition Width="2.3*"/>
                                                                <ColumnDefinition Width="*"/>
                                                                <ColumnDefinition Width="*"/>

                                                                <ColumnDefinition Width="{Binding BindingContext.WideScreen, Source={x:Reference Main}, Converter={x:StaticResource WideScreenColumnSizeConverter}}"/>
                                                                <ColumnDefinition Width="{Binding BindingContext.WideScreen, Source={x:Reference Main}, Converter={x:StaticResource WideScreenColumnSizeConverter}}"/>
                                                            </Grid.ColumnDefinitions>

                                                            <StackLayout BackgroundColor="Red" Orientation="Vertical" Grid.Row="0" VerticalOptions="FillAndExpand" Padding="0,0,0,2" HorizontalOptions="FillAndExpand" >
                                                                <Label Text="asd" VerticalTextAlignment="End" HorizontalTextAlignment="Start" TextColor="#0093CA" FontSize="15"  />

                                                                <Label Text="asd" VerticalOptions="FillAndExpand"  VerticalTextAlignment="Start"  FontSize="13" TextColor="#666666" Grid.Column="0" WidthRequest="80" />
                                                            </StackLayout>
                                                            <StackLayout Grid.Column="1" HorizontalOptions="FillAndExpand" BackgroundColor="Pink" VerticalOptions="FillAndExpand">
                                                                <Label Text="asdasd"  Grid.Row="0" TextColor="Black" FontSize="14"  HorizontalTextAlignment="Center" HorizontalOptions="FillAndExpand" VerticalOptions="CenterAndExpand" VerticalTextAlignment="Center" />
                                                            </StackLayout>
                                                            <Label Text="asd" BackgroundColor="Orange" FontSize="14" VerticalOptions="FillAndExpand" TextColor="red"  VerticalTextAlignment="Center"  HorizontalOptions="FillAndExpand" HorizontalTextAlignment="Center" Grid.Column="2"/>
                                                            <Label Text="asd" FontSize="14" BackgroundColor="Blue" VerticalOptions="FillAndExpand" TextColor="red"  VerticalTextAlignment="Center"  HorizontalOptions="FillAndExpand" HorizontalTextAlignment="Center"  Grid.Column="3" IsVisible="{Binding BindingContext.WideScreen, Source={x:Reference Main}}" />
                                                            <Label Text="asd"  FontSize="14" BackgroundColor="Green" VerticalOptions="FillAndExpand" TextColor="red" VerticalTextAlignment="Center"  HorizontalOptions="FillAndExpand" HorizontalTextAlignment="Center"  Grid.Column="4" IsVisible="{Binding BindingContext.WideScreen, Source={x:Reference Main}}" />

                                                        </Grid>
                                                   
                                                </ViewCell>
                                            </DataTemplate>
                                        </ListView.ItemTemplate>
                                            
                                    </ListView>
                                    </StackLayout>
                                </ViewCell>
                            </DataTemplate>
                        </cards:CardViewExtended.ItemTemplate>
                    </cards:CardViewExtended>

                </StackLayout>`

Here's a few screenshots of the issue with and without safe space enabled:

![image](https://user-images.githubusercontent.com/64660177/80833597-44f5d080-8bc5-11ea-9e2b-ba9ca6fd657a.png)

![image](https://user-images.githubusercontent.com/64660177/80833642-5d65eb00-8bc5-11ea-86f9-f05c02777769.png)

![image](https://user-images.githubusercontent.com/64660177/80833702-7ec6d700-8bc5-11ea-9377-76c94a02fc89.png)

Any insight into what might be causing this? Again it works exactly as you would expect on all other platforms.

Xamarin Forms: 4.1.0.778454
CardsView 2.5.1

**Comment by AndreiMisiukevich** [comment]
Can you build a simple sample?
And can you show the expected screenshot? it's difficult to understand what's wrong.
Also, I see you use cards:CardViewExtended

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/80835519-a0db4c00-8bfb-11ea-82fb-0a425e9ad999.png)

Works as expected

**Comment by AndreiMisiukevich** [comment]
I've just tried to put simple cell inside listview WITHOUT carousel

```csharp
Content = new ListView
{
	BackgroundColor = Color.Green,
	ItemsSource = new int[] { 1, 2, 3, 4, 5 },
	ItemTemplate = new DataTemplate(() => new ViewCell { View = new ContentView { BackgroundColor = Color.Red } })
};
```


So, it's Xamarin.Forms issue

![image](https://user-images.githubusercontent.com/10124814/80841021-3d571b80-8c07-11ea-80d8-049590b69495.png)

**Comment by ericallen13** [comment]
I've created a project to reproduce it.

https://github.com/ericallen13/ListViewBug/tree/master/ListViewBugExample

Start app in portrait then rotate to landscape once the main view has loaded, you'll notice black bars on the left and right sides as you scroll.
