### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException

### ISSUE THREAD

**Issue by PaulsonMac** [AndreiMisiukevich/CardView#346]
Hi @AndreiMisiukevich ,
I'm getting this in my crashlytics report for my iOS app (450+ times).. all crashes are from devices running iOS 13 OS (iOS 13.1.3, 13.3.0, 13.3.1).. Looks similar to this issue - https://github.com/AndreiMisiukevich/CardView/issues/295

I've also recently built my app with iOS 13SDK to comply with the latest apple guidelines.

**Did you try in a iOS device having iOS 13?** 

Looks like a fatal crash error

**Logs :**
```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x19bd9096c __exceptionPreprocess
1  libobjc.A.dylib                0x19baa9028 objc_exception_throw
2  Foundation                     0x19c27c5e0 -[NSISEngine tryToOptimizeReturningMutuallyExclusiveConstraints]
3  Foundation                     0x19c0758c4 -[NSISEngine _optimizeWithoutRebuilding]
4  Foundation                     0x19c0757d8 -[NSISEngine optimize]
5  Foundation                     0x19c075448 -[NSISEngine performPendingChangeNotifications]
6  UIKitCore                      0x1a031e824 -[UIView(Hierarchy) layoutSubviews]
7  UIKitCore                      0x1a0331b1c -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
8  libobjc.A.dylib                0x19baa4a4c -[NSObject performSelector:withObject:]
9  QuartzCore                     0x1a2947a9c -[CALayer layoutSublayers]
10 QuartzCore                     0x1a2947eec CA::Layer::layout_if_needed(CA::Transaction*)
11 QuartzCore                     0x1a295a614 CA::Layer::layout_and_display_if_needed(CA::Transaction*)
12 QuartzCore                     0x1a289f1c4 CA::Context::commit_transaction(CA::Transaction*, double)
13 QuartzCore                     0x1a28c9fd0 CA::Transaction::commit()
14 QuartzCore                     0x1a28caba4 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
15 CoreFoundation                 0x19bd0b524 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
16 CoreFoundation                 0x19bd061c4 __CFRunLoopDoObservers
17 CoreFoundation                 0x19bd05f60 CFRunLoopRunSpecific
18 WebCore                        0x1a3ecc8f0 RunWebThread(void*)
19 libsystem_pthread.dylib        0x19ba99840 _pthread_start
20 libsystem_pthread.dylib        0x19baa19f4 thread_start
```

**Error details :**
Fatal Exception: NSInternalInconsistencyException
Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.
-[NSISEngine tryToOptimizeReturningMutuallyExclusiveConstraints]

Hope I have given some helpful details about this issue. Sorry, I can't send my project files as they're confidential.

**Comment by PaulsonMac** [comment]
Referencing #295

**Comment by AndreiMisiukevich** [comment]
> Referencing #295

what version of CardsView does your app have?

**Comment by AndreiMisiukevich** [comment]
@PaulsonMac can you reproduce this issue on your device/simulator? (or it's only stack-trace from crashlytics)

**Comment by PaulsonMac** [comment]
> @PaulsonMac can you reproduce this issue on your device/simulator? (or it's only stack-trace from crashlytics)

We didn't check in a device yet.. It's a stack-trace from crashlytics as of now

**Comment by PaulsonMac** [comment]
I'm using 2.1.3

**Comment by PaulsonMac** [comment]
Was this issue already addressed in any of the recent releases?

**Comment by AndreiMisiukevich** [comment]
> Was this issue already addressed in any of the recent releases?

2.1.3 ??? :)) It's toooooooooo old, man

2.6.1 is the current one. Yes, I fixed such issues ~ 2 months ago

**Comment by PaulsonMac** [comment]
ok, I'll try updating it.. Thanks
