### ISSUE TITLE
Image stream not being displayed in carousel

### ISSUE THREAD

**Issue by sunnyatticsoftware** [AndreiMisiukevich/CardView#348]
I am having an issue, hopefully someone has the answer and lets me know if I'm doing anything wrong or it's a limitation of the carousel.

The idea is that I have several images being generated at runtime (qr barcodes), and I want to display those images along with some text in a carouselview.

## The problem

This is what I see on the first load

![1](https://user-images.githubusercontent.com/57327772/83806429-c99aa980-a6b1-11ea-83ca-ad3941596ca3.JPG)

As you can see the text is displayed, the items within the collection are there, and the same images outside the carousel exist.

The funny thing is that when I save the XAML again (while debugging) forcing a hot reload, it refreshes the page and I can see it working as expected.

![2](https://user-images.githubusercontent.com/57327772/83806533-f353d080-a6b1-11ea-8a6a-8fd40bcdc15d.JPG)

I suspect there must be some kind of race condition here, but **why isn't the carousel displaying the images?**

## My code

For example, my view model has the observable collection of `ImageSource` that I feed when the view model is instantiated:
```
private readonly IQrGeneratorService _qrGeneratorService;
private ObservableCollection<ImageSource> _images = new ObservableCollection<ImageSource>();

public ObservableCollection<ImageSource> Images
{
    get => _images;
    set
    {
        _images = value;
        OnPropertyChanged();
    }
}

public MainViewModel(IQrGeneratorService qrGeneratorService)
{
    _qrGeneratorService = qrGeneratorService;
    _qrGeneratorService = qrGeneratorService;
    var oneBytes = _qrGeneratorService.GetQrCode("foo");
    var twoBytes = _qrGeneratorService.GetQrCode("bar");
    var threeBytes = _qrGeneratorService.GetQrCode("tor");

    var one = ImageSource.FromStream(() => new MemoryStream(oneBytes));
    var two = ImageSource.FromStream(() => new MemoryStream(twoBytes));
    var three = ImageSource.FromStream(() => new MemoryStream(threeBytes));
    Images.Add(one);
    Images.Add(two);
    Images.Add(three);
}
```

Now my Xaml bound to this view model with the following code behind
```
public partial class MainPage : ContentPage
    {
        private readonly MainViewModel _mainViewModel = AppContainer.Resolve<MainViewModel>();
        public MainPage()
        {
            InitializeComponent();
            BindingContext = _mainViewModel;
        }
    }
```

has the following XAML
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:viewModels="clr-namespace:Sasw.AforoPass.ViewModels;assembly=Sasw.AforoPass"
             xmlns:panCardView="clr-namespace:PanCardView;assembly=PanCardView"
             xmlns:controls="clr-namespace:PanCardView.Controls;assembly=PanCardView"
             mc:Ignorable="d"
             x:Class="Sasw.AforoPass.Views.MainPage" 
             x:DataType="viewModels:MainViewModel">
    <ContentPage.Content>
        <StackLayout>
            <StackLayout.Resources>
                <ResourceDictionary>
                    <ResourceDictionary.MergedDictionaries>
                        <ResourceDictionary Source="/Styles/Styles.xaml" />
                    </ResourceDictionary.MergedDictionaries>
                </ResourceDictionary>
            </StackLayout.Resources>

            <panCardView:CarouselView 
                ItemsSource="{Binding Images}"
                BackgroundColor="{StaticResource ColorPrimary}"
                HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand">
                <panCardView:CarouselView.ItemTemplate>
                    <DataTemplate>
                        <StackLayout 
                            HorizontalOptions="CenterAndExpand" 
                            VerticalOptions="CenterAndExpand">
                            <Image Source="{Binding .}"></Image>
                            <Label Text="image should be here"></Label>
                        </StackLayout>
                    </DataTemplate>
                </panCardView:CarouselView.ItemTemplate>

                <controls:LeftArrowControl />
                <controls:RightArrowControl />
                <controls:IndicatorsControl ToFadeDuration="1500"/>
            </panCardView:CarouselView>
            <Image WidthRequest="20" HeightRequest="20" Source ="{Binding Images[0]}"></Image>
            <Image WidthRequest="20" HeightRequest="20"  Source ="{Binding Images[1]}"></Image>
            <Image WidthRequest="20" HeightRequest="20"  Source ="{Binding Images[2]}"></Image>
   
            <Button Text="Close"></Button>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

## Some things to notice
It could be due to the fact that the image is an `ImageSourceStream` and that the stream is not ready by the time the carousel is rendered. Maybe the image source itself should be observable? But I can see the images outside the carousel, so I'm not sure.,

**Comment by AndreiMisiukevich** [comment]
Hi, try to set 
```xaml
<Image Source="{Binding .}" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"/>
```

**Comment by sunnyatticsoftware** [comment]
thanks for your reply. I've tried setting those options but it didn't make any difference. The images are not shown until a hot reload of XAML happens.

**Comment by sunnyatticsoftware** [comment]
I've ran another test with the xamarin CarouselView. Same result as with `CardView`
```
<CarouselView BackgroundColor="White"
              x:Name="Carousel"
              ItemsSource="{Binding Images}">
    <CarouselView.ItemTemplate>
        <DataTemplate>
            <StackLayout 
                HorizontalOptions="CenterAndExpand" 
                VerticalOptions="CenterAndExpand">
                <Image Source="{Binding .}"
                       VerticalOptions="FillAndExpand" 
                       HorizontalOptions="FillAndExpand"></Image>
                <Label Text="image should be here"></Label>
            </StackLayout> 
        </DataTemplate>
    </CarouselView.ItemTemplate>
</CarouselView>
```

First time page is rendered:

![1](https://user-images.githubusercontent.com/57327772/83808599-5bf07c80-a6b5-11ea-8c07-ba2e6906882a.JPG)

After hot reload:

![2](https://user-images.githubusercontent.com/57327772/83808615-63178a80-a6b5-11ea-8dab-0568705a5352.JPG)

Is CardView based on the same mechanism as the Xamarin's out of the box carousel?

**Comment by AndreiMisiukevich** [comment]
> I've ran another test with the xamarin CarouselView. Same result as with `CardView`
> 
> ```
> <CarouselView BackgroundColor="White"
>               x:Name="Carousel"
>               ItemsSource="{Binding Images}">
>     <CarouselView.ItemTemplate>
>         <DataTemplate>
>             <StackLayout 
>                 HorizontalOptions="CenterAndExpand" 
>                 VerticalOptions="CenterAndExpand">
>                 <Image Source="{Binding .}"
>                        VerticalOptions="FillAndExpand" 
>                        HorizontalOptions="FillAndExpand"></Image>
>                 <Label Text="image should be here"></Label>
>             </StackLayout> 
>         </DataTemplate>
>     </CarouselView.ItemTemplate>
> </CarouselView>
> ```
> 
> First time page is rendered:
> 
> ![1](https://user-images.githubusercontent.com/57327772/83808599-5bf07c80-a6b5-11ea-8c07-ba2e6906882a.JPG)
> 
> After hot reload:
> 
> ![2](https://user-images.githubusercontent.com/57327772/83808615-63178a80-a6b5-11ea-8dab-0568705a5352.JPG)
> 
> Is CardView based on the same mechanism as the Xamarin's out of the box carousel?

No, that's different mechanisms

**Comment by AndreiMisiukevich** [comment]
Thanks for the report. I will take a look tomorrow.

Just to make sure that it is not XF bug (can you set WidthRequest and HeightRequest to your Image? 100 and 100 for example

**Comment by sunnyatticsoftware** [comment]
Thanks, I appreciate your help and time.

I've just added with and height request. Same problem
```
<panCardView:CarouselView.ItemTemplate>
    <DataTemplate>
        <StackLayout 
            HorizontalOptions="CenterAndExpand" 
            VerticalOptions="CenterAndExpand"> 
            <Image Source="{Binding .}"
                   HeightRequest="100"
                   WidthRequest="100"
                   VerticalOptions="FillAndExpand" 
                   HorizontalOptions="FillAndExpand"></Image>
            <Label Text="image should be here"></Label>
        </StackLayout>
    </DataTemplate>
</panCardView:CarouselView.ItemTemplate> 
```

**Comment by sunnyatticsoftware** [comment]
In case it helps.. I just ran another experiment with a converter to see if I can find out what's going on. No luck, but there's something interesting.

```
public class ByteToImageConverter
    : IValueConverter, IMarkupExtension
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        var foo = "just to see if it reaches this point. But on the first rendering it doesn't!";
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        throw new NotImplementedException();
    }

    public object ProvideValue(IServiceProvider serviceProvider)
    {
        return this;
    }
}
```

Then in my image within the carousel
```
<Image Source="{Binding ., Converter={converters:ByteToImageConverter}}"
       HeightRequest="100"
       WidthRequest="100"
       VerticalOptions="FillAndExpand" 
       HorizontalOptions="FillAndExpand"></Image>
```

I set a breakpoint in the `Convert` method. On the first load, this converter is not even executed.
After I force the hot reload I can see it the method is finally executed, although the value is null a few times..

I'm afraid I've reached the limits of my knowledge. Fingers crossed your talent helps you find the reason.

**Comment by sunnyatticsoftware** [comment]
I found the issue. It does not make any sense to me, but hopefully it makes to you and can share with me the WHY.

It turns out Re-Sharper was suggesting something risky, to add a `x:DataType`
It's all documented here: https://stackoverflow.com/questions/62200299/images-not-shown-in-carouselview-on-first-load

If you think this does not make sense and it's a Xamarin bug, I would happily open an issue with the Xamarin Forms team. Feel free to close this issue and thanks again for your time!

**Comment by AndreiMisiukevich** [comment]
That's not an image problem
try to change xaml **<Label Text="{Binding .}"></Label>** (And use text instead of stream) You will see that text is not displayed via binding as well

**Comment by AndreiMisiukevich** [comment]
Add x:DataType to your DataTemplate
This will solve your problem
```xaml
<DataTemplate x:DataType="ImageSource">
                        <StackLayout
                            HorizontalOptions="CenterAndExpand" 
                            VerticalOptions="CenterAndExpand">
                            <Image Source="{Binding .}" />
                        </StackLayout>
                    </DataTemplate>
```

**Comment by AndreiMisiukevich** [comment]
@sunnyatticsoftware does it work for you?

**Comment by sunnyatticsoftware** [comment]
yes it does. Thanks!
