### ISSUE TITLE
Giving Command to Items

### ISSUE THREAD

**Issue by alperen-ozdemir** [AndreiMisiukevich/CardView#349]
Hi Andrei,

I'm trying to give command binding to the items, or making images clickable. However, after searching for 2 days I couldn't figure it out. Is there a way to achive this.

Thank you so much.

**Comment by AndreiMisiukevich** [comment]
Hi) Add TapGestureRecognizer to your item template

**Comment by AndreiMisiukevich** [comment]
you can check my samples
How to achieve that via code

https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardViewSample/PanCardViewSample/Views/CardsSampleView.cs

If you have any difficulties, feel free to message me.
