### ISSUE TITLE
[Slideshow | indicators fade] features

### ISSUE THREAD

**Issue by JTOne123** [AndreiMisiukevich/CardView#35]
Do cardview has auto-slide and pause on hover?

**Comment by AndreiMisiukevich** [comment]
What exactly do you mean?
This plugin has got autosliding, just try to change CurrentIndex property from code.

**Comment by JTOne123** [comment]
yep, but I'm looking for in-box solution without handling timer on my side

**Comment by AndreiMisiukevich** [comment]
I think, it can be interesting enhancement. But now - there is no such opportunity

**Comment by AndreiMisiukevich** [comment]
Hey, I thought, that it would be great to have opportunity to fade out indicator if there is no any interactions)

**Comment by AndreiMisiukevich** [comment]
As for slideshow, you can adjust it through setting next property SlideShowDuration (milliseconds of course)

**Comment by JTOne123** [comment]
Oh boy!! it's great, I did it with timer on my side. With pleasure, delete my code :)

**Comment by JTOne123** [comment]
looks like it does not start automatically without pan it once

**Comment by AndreiMisiukevich** [comment]
@JTOne123 what platform do you use?

**Comment by JTOne123** [comment]
tested only on iOS

**Comment by AndreiMisiukevich** [comment]
``` xml
    <cards:CarouselView 
        Items="{Binding Items}"
        SlideShowDuration="3000"
        CurrentIndex="{Binding CurrentIndex}">
        <cards:CarouselView.ItemTemplate>
            <DataTemplate>
                <ContentView>
                    <Frame 
                        VerticalOptions="Center"
                        HorizontalOptions="Center"
                        HeightRequest="300"
                        WidthRequest="300"
                        Padding="0" 
                        HasShadow="false"
                        IsClippedToBounds="true"
                        CornerRadius="10"
                        BackgroundColor="{Binding Color}">
                        
                        <ffimage:CachedImage Source="{Binding Source}"/> 
                        
                    </Frame>
                </ContentView>
            </DataTemplate>
        </cards:CarouselView.ItemTemplate>

        <controls:IndicatorsControl ToFadeDuration="1500"/>
    </cards:CarouselView>
```

Check the sample (CarouselView Xaml)

**Comment by AndreiMisiukevich** [comment]
I've just tested it and it works fine

**Comment by JTOne123** [comment]
maybe magic in at CurrentIndex because I do not set it

**Comment by JTOne123** [comment]
yes, it is! with currentindex it works

**Comment by AndreiMisiukevich** [comment]
no, i see another reason
https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs#L509

ItemsCount can be 0, because you can initialize Slideshow before setting items.. hmm.. or no)

**Comment by AndreiMisiukevich** [comment]
oh.. so, you just set it 0, didn't you?

**Comment by JTOne123** [comment]
yes, you are right, I did it

**Comment by shreyans-wakekar** [comment]
Hello, I just want to know, how to stop slideshow programmatically.
Need Help.

**Comment by AndreiMisiukevich** [comment]
@shreyans-wakekar you can handle index changed (with event or via viewModel) and if your index equals last index, set SlideShowDuration to 0

**Comment by JTOne123** [comment]
Is SlideShowDuration bindable?

**Comment by AndreiMisiukevich** [comment]
@JTOne123 yes, of course
