### ISSUE TITLE
CarouselView with maps

### ISSUE THREAD

**Issue by TSerra-PT** [AndreiMisiukevich/CardView#351]
Hi Andrei!

I am using a CarouselView with many ContentViews and one of many this ContentViews has a Map (Xamarin.Forms.Maps). In ios works well (loads the apple maps and I can navigate with the gestures) but in android the navigation with the gestures doesn't work (the google maps takes a lot of time to renderer). 
Can you help me with this problem?

**Comment by AndreiMisiukevich** [comment]
Hi,

What do you mean "navigation with gesture"? CarouselView navigation or navigation in maps?

**Comment by TSerra-PT** [comment]
> Hi,
> 
> What do you mean "navigation with gesture"? CarouselView navigation or navigation in maps?

Navigation in the maps (with the finger). I disabled the "swipe left and rigth" (in the CarouselView) with the proprety IsUserInteractionEnabled = "false"

**Comment by AndreiMisiukevich** [comment]
> > Hi,
> > What do you mean "navigation with gesture"? CarouselView navigation or navigation in maps?
> 
> Navigation in the maps (with the finger). I disabled the "swipe left and rigth" (in the CarouselView) with the proprety IsUserInteractionEnabled = "false"

Try to add this "ShouldThrottlePanInteraction = true"

**Comment by AndreiMisiukevich** [comment]
Does it work?

**Comment by TSerra-PT** [comment]
> > > Hi,
> > > What do you mean "navigation with gesture"? CarouselView navigation or navigation in maps?
> > 
> > 
> > Navigation in the maps (with the finger). I disabled the "swipe left and rigth" (in the CarouselView) with the proprety IsUserInteractionEnabled = "false"
> 
> Try to add this "ShouldThrottlePanInteraction = true"

It's works!!!
Thank you so much @AndreiMisiukevich ;)
I owe you a beer ^_^

**Comment by AndreiMisiukevich** [comment]
haha, yes
