### ISSUE TITLE
Next/Previous on Carousel View?

### ISSUE THREAD

**Issue by rdurish** [AndreiMisiukevich/CardView#352]
I would like to have a next previous buttons in line with the paging dots in Carousel View.  Can that be an enhancement or am I missing how to accomplish that?  Thank you!

**Comment by AndreiMisiukevich** [comment]
```xaml
<controls:LeftArrowControl AbsoluteLayout.LayoutFlags="0,1,-1,-1" Margin="0, 20" />
<controls:RightArrowControl AbsoluteLayout.LayoutFlags="1,1,-1,-1" Margin="0, 20" />
```

Also, you can try without margin (Or just play with that)

**Comment by rdurish** [comment]
Thank you for the feedback...I am trying to get this effect, not sure I made sense above LOL:
[https://1drv.ms/u/s!AtiXKZF_BIouirRoCDMBPzfUUlk9cQ?e=zQ3gn7](url)

**Comment by AndreiMisiukevich** [comment]
oh, okay then you should use your own buttons or labels
Add ProtectedViewBehavior and put inside carousel view with  AbsoluteLayout.LayoutFlags="0,1,-1,-1" Margin="0, 20" and AbsoluteLayout.LayoutFlags="1,1,-1,-1" Margin="0, 20"

**Comment by AndreiMisiukevich** [comment]
or just show me your xaml

**Comment by rdurish** [comment]
Here is my xaml, I can't see the back, next buttons (I tried even margin'ing (+/-) to try to see them) , I assume I need a bind of some sort as well to tell it to go back and form, is there something I can grab?  Also, another issue I am running into is a can not put a click even on my buttons inside the carousel.ItemSource, is there a work around for that too?  Sory I am a complete XAML newb, been doing c# forever but new to xaml and xamarin.

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             xmlns:cards="clr-namespace:PanCardView;assembly=PanCardView"
             xmlns:controls="clr-namespace:PanCardView.Controls;assembly=PanCardView"
             xmlns:proc="clr-namespace:PanCardView.Processors;assembly=PanCardView"
             xmlns:ef="clr-namespace:AiForms.Effects;assembly=AiForms.Effects"
             x:Class="Physio.MainPage"
             Padding="0">

    <ContentPage.Resources>
        <ResourceDictionary>
            <Style x:Key="ActiveIndicator" TargetType="Frame">
                <Setter Property="OutlineColor" Value="#EE8B22" />
            </Style>
            <Style x:Key="InactiveIndicator" TargetType="Frame">
                <Setter Property="OutlineColor" Value="#EE8B22" />
                <Setter Property="BackgroundColor" Value="#EE8B22" />
            </Style>
        </ResourceDictionary>
    </ContentPage.Resources>

    <StackLayout>
        <cards:CarouselView VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" Margin="0" Padding="0" MaxChildrenCount="3">
            <cards:CarouselView.ItemsSource>
                <x:Array Type="{x:Type View}">
                    <StackLayout WidthRequest="100" BackgroundColor="White">
                        <Image Source="IntroKnee.png" HeightRequest="300" Aspect="AspectFill"/>
                        <Image Source="ribbonWave.png" HeightRequest="300" Aspect="AspectFill" Margin="0,-205,0,0"/>
                        <Image Source="logo.png" HeightRequest="100" Aspect="AspectFit" Margin="70,-30,70,0" />
                        <Label FontFamily="Raleway" FontSize="Medium" Margin="20, 0, 20, 0" HeightRequest="100" HorizontalTextAlignment="Center" Text="Fusce vehicula dolor arcu, sir amet blandit dolor mollis nec. Donec viverra eleifend lacus, vitae ullamcorper."></Label>
                    </StackLayout>
                    <StackLayout WidthRequest="100" BackgroundColor="White">
                        <Label FontFamily="Raleway" FontSize="Large" Text="welcome" HorizontalTextAlignment="Center" Padding="0,20,0,20" BackgroundColor="#E31837" TextColor="White" Margin="0"></Label>
                        <Image Source="IntroKnee.png" HeightRequest="300" Aspect="AspectFill" Margin="0,-9,0, 0"/>
                        <Image Source="ribbonWave2.png" HeightRequest="300" Aspect="AspectFill" Margin="0,-130,0,0"/>
                        <Button Text="WATCH VIDEO" Margin="120,-374,120,0" Padding="0,10,0,10" CornerRadius="50" TextColor="Gray" BackgroundColor="White" Opacity="0.90"></Button>
                        <Label FontFamily="Raleway" FontSize="Medium" Margin="20, 260, 20, 0" HeightRequest="100" HorizontalTextAlignment="Center" Text="Fusce vehicula dolor arcu, sir amet blandit dolor mollis nec. Donec viverra eleifend lacus, vitae ullamcorper."></Label>
                    </StackLayout>
                    <StackLayout WidthRequest="100" BackgroundColor="White">
                        <Image Source="LoginBG.png" HeightRequest="500" Aspect="AspectFill"/>
                        <StackLayout HeightRequest="500" Margin="70,-280,70,0">
                            <Image Source="logo.png" HeightRequest="100" Aspect="AspectFit" />
                            <Entry x:Name="entEmail" Placeholder="email address" TextColor="#E31837" PlaceholderColor="#E31837"></Entry>
                            <Entry x:Name="entPwd" IsPassword="True" Placeholder="password" TextColor="#E31837" PlaceholderColor="#E31837"></Entry>
                            <Button x:Name="btnForgot" Text="forgot password?" FontSize="Micro" BackgroundColor="Transparent" HorizontalOptions="End"  Margin="0,-25">
                                
                            </Button>
                            <Button x:Name="btnLogin" ef:Gradient.Colors="#EE8B22,#E84D2D,#E31837" ef:Gradient.Orientation="RightLeft" Text="Sign In" FontSize="Large" CornerRadius="50" TextColor="White" Margin="0,40,0,0"></Button>                            
                        </StackLayout>
                        <Image Source="ribbonWave.png" Aspect="AspectFill" Margin="0,-280,0,0"/>
                    </StackLayout>
                </x:Array>
            </cards:CarouselView.ItemsSource>

            <Button Text="back" BackgroundColor="Transparent" TextColor="#EE8B22"></Button>
            <controls:IndicatorsControl SelectedIndicatorStyle="{StaticResource ActiveIndicator}" UnselectedIndicatorStyle="{StaticResource InactiveIndicator}" />
            <Button Text="next" BackgroundColor="Transparent" TextColor="#EE8B22"></Button>

        </cards:CarouselView>
    </StackLayout>

</ContentPage>`

**Comment by AndreiMisiukevich** [comment]
Well, look at this stuff

```xaml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:viewModels="clr-namespace:PanCardViewSample.ViewModels"
    xmlns:cards="clr-namespace:PanCardView;assembly=PanCardView"
    xmlns:controls="clr-namespace:PanCardView.Controls;assembly=PanCardView"
    xmlns:beh="clr-namespace:PanCardView.Behaviors;assembly=PanCardView"
    x:Class="PanCardViewSample.Views.CarouselSampleXamlView"
    BackgroundColor="Black"
    x:Name="Page"
    Title="Carousel Xaml">

    <ContentPage.BindingContext>
        <viewModels:CardsSampleViewModel/>
    </ContentPage.BindingContext>

    <ContentPage.Resources>
        <ResourceDictionary>
            <Style x:Key="ActiveIndicator" TargetType="Frame">
                <Setter Property="OutlineColor" Value="#EE8B22" />
            </Style>
            <Style x:Key="InactiveIndicator" TargetType="Frame">
                <Setter Property="OutlineColor" Value="#EE8B22" />
                <Setter Property="BackgroundColor" Value="#EE8B22" />
            </Style>
        </ResourceDictionary>
    </ContentPage.Resources>

    <StackLayout>
        <cards:CarouselView VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
            <cards:CarouselView.ItemsSource>
                <x:Array Type="{x:Type View}">
                    <ContentView BackgroundColor="Blue" />
                    <ContentView BackgroundColor="LightCoral" />
                    <ContentView BackgroundColor="Green" />
                </x:Array>
            </cards:CarouselView.ItemsSource>

            <controls:IndicatorsControl SelectedIndicatorStyle="{StaticResource ActiveIndicator}" UnselectedIndicatorStyle="{StaticResource InactiveIndicator}" />

            <Button Text="back"
                    BackgroundColor="Transparent"
                    TextColor="#EE8B22"
                    AbsoluteLayout.LayoutFlags="PositionProportional"
                    AbsoluteLayout.LayoutBounds="0,1,-1,-1"
                    Margin="15, 0"
                    Command="{Binding BindingContext.BackCommand, Source={x:Reference Page}}">
                <Button.Behaviors>
                    <beh:ProtectedControlBehavior />
                </Button.Behaviors>
            </Button>

            <Button Text="next"
                    BackgroundColor="Transparent"
                    TextColor="#EE8B22"
                    AbsoluteLayout.LayoutFlags="PositionProportional"
                    AbsoluteLayout.LayoutBounds="1,1,-1,-1"
                    Margin="15, 0"
                    Command="{Binding BindingContext.NextCommand, Source={x:Reference Page}}">
                <Button.Behaviors>
                    <beh:ProtectedControlBehavior />
                </Button.Behaviors>
            </Button>

        </cards:CarouselView>
    </StackLayout>
    
</ContentPage>
```

**Comment by AndreiMisiukevich** [comment]
Here is how to make navigations by buttons https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardViewSample/PanCardViewSample/Views/CubeSampleXamlView.xaml
