### ISSUE TITLE
[HowTo] Allow Scrollable Content within items

### ISSUE THREAD

**Issue by InquisitorJax** [AndreiMisiukevich/CardView#356]
See sample: "Andrei" tab:
[CarouselViewSamples.zip](https://github.com/AndreiMisiukevich/CardView/files/5201361/CarouselViewSamples.zip)

How can I get the top CollectionView to scroll, as well as allowing the main Carousel to scroll when the SubItems Carousel has reached the end?
See the "Alex" tab implementation that works out of the box.

Is this possible?

**Comment by AndreiMisiukevich** [comment]
Hi, now that's impossible)
But I guess such feature can be implemented.
We need to "pass" gesture event value to the parent carousel if it exists in case no items to scroll 👍

**Comment by AndreiMisiukevich** [comment]
Would you like to have this feature? Or you find another solution

**Comment by InquisitorJax** [comment]
@AndreiMisiukevich there currently isn't an up to date CarouselView that supports this, so I think it would be tremendously useful to the community as it adds a bunch of new content possibilities to the already very cool control.

Also, I definitely would like to have this feature ;)

**Comment by AndreiMisiukevich** [comment]
Then need to try to implement it

**Comment by InquisitorJax** [comment]
There was an issue logged on the Forms CarouselView in Dec. last year, and it's still not there :(
https://github.com/xamarin/Xamarin.Forms/issues/8960
You can see there's a few people looking for that kind of functionality.

**Comment by AndreiMisiukevich** [comment]
2.6.4
