### ISSUE TITLE
CoverFlowView, Android-only, "Method not found: bool PanCardView.CardsView.get_IsPanControllingdByChild()"

### ISSUE THREAD

**Issue by Martin-4Spaces** [AndreiMisiukevich/CardView#360]
This error occurs when I start scrolling horizontal on ConverFlowView.

View
```
<cards:CoverFlowView 
    PositionShiftValue="145"
    IsCyclical="false"
    ItemsSource="{Binding TestItems}">

    <cards:CoverFlowView.ItemTemplate>
        <DataTemplate>
            <Label
                HeightRequest="100"
                Text="{Binding Title}" />
        </DataTemplate>
    </cards:CoverFlowView.ItemTemplate>

</cards:CoverFlowView>
```

ViewModel
```
public ObservableCollection<object> TestItems { get; }
TestItems = new ObservableCollection<object>
            {
                new { Title = "First" },
                new { Title = "Second" },
                new { Title = "Long Title" },
                new { Title = "4" },
                new { Title = "5th" }
            };
```

The package is installed with nuget in the shared project, android og iOS-project.
MainActivity
```
global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
CardsViewRenderer.Preserve();
LoadApplication(new App());
```

No issues in iOS. I use a Huawei smartphone API 28 as test device.

**Comment by AndreiMisiukevich** [comment]
Hi @Martin-4Spaces

can you try to disable linker (Set to "Do not link") and check whether the issue exists

**Comment by AndreiMisiukevich** [comment]
Also, make sure you installed the same CardsView nuget version to **ALL** your projects

**Comment by Martin-4Spaces** [comment]
It is already set to Do not link for debug mode. 
I cant build my Android app release after installing this library to the android project. It complains about the same error because linker is set to SDK assemblies only,
All projects is updated to version 2.6.7.

**Comment by AndreiMisiukevich** [comment]
Try 2.6.8, please
if it doesn't work, let me know

**Comment by Martin-4Spaces** [comment]
Same issue, new method name :/
```
System.MissingMethodException: Method not found: bool PanCardView.CardsView.get_IsPanControllingByChild()
```
Here is some screenshots showing i'm using the correct version.
![shared](https://user-images.githubusercontent.com/9819124/98155253-3a025c80-1ed6-11eb-9d79-f3dbdb6650c4.png)
![android](https://user-images.githubusercontent.com/9819124/98155261-3c64b680-1ed6-11eb-820f-84d7b7f632a3.png)
![android main](https://user-images.githubusercontent.com/9819124/98155270-3ec71080-1ed6-11eb-920d-1d0af6f0f6ec.png)
![dont link](https://user-images.githubusercontent.com/9819124/98155274-4090d400-1ed6-11eb-9014-4b2fb06b485b.png)

**Comment by AndreiMisiukevich** [comment]
Could you please build a small sample and attach it here? Or put a link to github project with reproduction.

I will take a look

Thanks.

**Comment by AndreiMisiukevich** [comment]
Cannot reproduce

[test.zip](https://github.com/AndreiMisiukevich/CardView/files/5490079/test.zip)

**Comment by Martin-4Spaces** [comment]
@AndreiMisiukevich I tried too and it worked with sample.
So I started applying my own app into the sample. 
The error began when I added the dependency to https://www.nuget.org/packages/PanCardView/.
Removed it and now everything works fine.

Thank you!
