### ISSUE TITLE
PositionChangedEventArgs For CubeView

### ISSUE THREAD

**Issue by hackerjarvis007** [AndreiMisiukevich/CardView#361]
Hi Andrei,
Thanks for the wonderful library and amazing work. I am trying to get the PostitionChanged event for CubeView. 
In my CubeView , I am showing a video player. What I am trying to do is change a value when position of the cubeview item change.

I can achieve this using CarousalView like this : 

```
`   private void Carousal_PositionChanged(object sender, PositionChangedEventArgs e)
 
       {
            MyList[e.PreviousPosition].IsPlaying = false;       
        }`
```

Which event should I consume in cubeview?

**Comment by AndreiMisiukevich** [comment]
Hi @hackerjarvis007 Thanks for your question!

You should use ItemAppearing / ItemAppeared / ItemDisappearing events (or commands)

Please choose the most suitable for you.
Feel free to ask more questions!

**Comment by hackerjarvis007** [comment]
Hi Andrei, How can I get the Previous position or Item using ItemAppearing event? Can you help me on that part?

**Comment by AndreiMisiukevich** [comment]
> Hi Andrei, How can I get the Previous position or Item using ItemAppearing event? Can you help me on that part?

Hi,

Use **OldIndex** property or just use ItemDisappearing event (and check args)
