### ISSUE TITLE
tapped item nested

### ISSUE THREAD

**Issue by hamidish** [AndreiMisiukevich/CardView#363]
hi
i use nested i want to tapp item 
how can do it?
i use  collectionview instead of main carouselview .
i want tapped items but  not worked
can u help me?

**Comment by AndreiMisiukevich** [comment]
Hi, how about adding TapGestureRecognizer or TouchEffect from XamarinCommunityToolkit?

**Comment by hamidish** [comment]
i use tapgesture for carouselview template but not worked.
and use selectionchange for collectionview not worked

**Comment by AndreiMisiukevich** [comment]
Can you build a small sample?

**Comment by hamidish** [comment]
<DataTemplate x:Key="NestedItemTemplate" >
            <AbsoluteLayout  Padding="0" IsClippedToBounds="True">
                <Frame  Margin="80"
                       VerticalOptions="Center"
                       Padding="0" 
                       HasShadow="True" 
                       CornerRadius="10"  
                          AbsoluteLayout.LayoutFlags="All"
                       AbsoluteLayout.LayoutBounds="0, 0, 1, 1">
                    <AbsoluteLayout >

                        <Image Source="{Binding ImageLink}"   
                           Aspect="AspectFill" 
                                AbsoluteLayout.LayoutFlags="All"
                       AbsoluteLayout.LayoutBounds="0, 0, 1, 1"/>

                        <Label Text="{Binding Titr}"
                       TextColor="#81ffff"
                           BackgroundColor="#66000000"
                       FontFamily="entfont"
                           Margin="0,5,10,5" 
                                AbsoluteLayout.LayoutFlags="All"
                       AbsoluteLayout.LayoutBounds="0,1, 1,0.4"
                       FontSize="24"/>
                    </AbsoluteLayout>
                </Frame>
                <Line Y1="0"
                      X2="80"
                      Y2="0"
                      X1="0"
                      HorizontalOptions="Center"
                      Stroke="#e40081"
                      StrokeThickness="9"
                      VerticalOptions="StartAndExpand" 
                      Margin="0,0,0,0"
                        AbsoluteLayout.LayoutFlags="All"
                       AbsoluteLayout.LayoutBounds="0, 1, 1, 0.25"/>

            </AbsoluteLayout>
        </DataTemplate>
        <DataTemplate x:Key="TopItemTemplate">
            <Grid RowSpacing="0" IsClippedToBounds="True" Padding="0" >
                    <Grid.RowDefinitions>
                    <RowDefinition Height="Auto"/>
                    <RowDefinition Height="Auto"/>
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="1*"/>
                        <ColumnDefinition Width="1*"/>
                    </Grid.ColumnDefinitions>
                <Label Text=" viewall &gt;"
                           Grid.Column="0"
                       TextColor="#e40081"
                       FontFamily="entfont"
                       FontSize="20"
                           VerticalTextAlignment="Center"
                           HorizontalTextAlignment="Center" 
                           Margin="10,30,0,0"
                           Grid.Row="0"
                           HorizontalOptions="Start" >
                </Label>
                    <Label Text="{Binding NameGroup}"
                           VerticalTextAlignment="Center"
                           HorizontalTextAlignment="Center" 
                           Margin="0,30,10,0"
                       Padding="0"
                           Grid.Column="1"
                           Grid.Row="0"
                       HorizontalOptions="End" 
                        
                       FontAttributes="Bold" 
                       FontFamily="entfont"
                       FontSize="20"
                       TextColor="Black"  />       
                                   
            <cv:CoverFlowView Grid.RowSpan="2"
                              Grid.ColumnSpan="2"
                              Padding="0" IsClippedToBounds="True"
                                  PositionShiftValue="135"
                              HeightRequest="280"
                              Margin="0,0,0,-60"                              
                                  IsCyclical="True"   
                                    ItemTemplate="{StaticResource NestedItemTemplate}"
                                    ItemsSource="{Binding Items}"
                                  IsRightToLeftFlowDirectionEnabled="True"
                                  SelectedIndex="{Binding Id}"
                                  IsHorizontalOrientation="True">

                    <x:Arguments>
                        <proc:CoverFlowProcessor ScaleFactor="0.75" OpacityFactor="0.25" />
                    </x:Arguments>
                </cv:CoverFlowView>
            </Grid>
        </DataTemplate>

  <CollectionView Grid.Row="1" 
                                    SelectionChanged="collvideo_SelectionChanged"
                                    Margin="5,20,5,0"
                                    x:Name="collvideo"       
                                    SelectionMode="Single">
                        <CollectionView.ItemsLayout>
                            <LinearItemsLayout Orientation="Vertical" ItemSpacing="5"/>
                        </CollectionView.ItemsLayout>
           </CollectionView>


in cs
  ViewModel = new NestedViewModel();
            collvideo.ItemsSource = ViewModel.Items;

**Comment by hamidish** [comment]
and i get data all data dynamically

**Comment by AndreiMisiukevich** [comment]
That's why I asked to build a sample (A small project that I can run and see the problem)

**Comment by hamidish** [comment]
> 
> 
> That's why I asked to build a sample (A small project that I can run and see the problem)

ok

**Comment by hamidish** [comment]
[https://file.io/rwtnBsYp3T2n](url)

**Comment by hamidish** [comment]
https://file.io/rwtnBsYp3T2n

**Comment by AndreiMisiukevich** [comment]
Just move TapGestureRecognizer to NestedItemTemplate

Every item will handle taps (the same as the entire view handles taps)

![image](https://user-images.githubusercontent.com/10124814/103181298-c581e380-48b0-11eb-9cf3-1baa0c11e2c0.png)

**Comment by hamidish** [comment]
> 
> 
> Just move TapGestureRecognizer to NestedItemTemplate
> 
> Every item will handle taps (the same as the entire view handles taps)
> 
> ![image](https://user-images.githubusercontent.com/10124814/103181298-c581e380-48b0-11eb-9cf3-1baa0c11e2c0.png)

thx so much
