### ISSUE TITLE
How can I reduce the space between the cards in CoverFlowView?

### ISSUE THREAD

**Issue by p0dgana** [AndreiMisiukevich/CardView#366]
Is it possible to reduce the space that is between the cards?

**Comment by AndreiMisiukevich** [comment]
Hi, you should play with Margin of your template view and PositionShiftValue of CoverFlowView

![image](https://user-images.githubusercontent.com/10124814/103181018-2ad3d580-48ad-11eb-8ffd-c9221d1650c8.png)

**Comment by AndreiMisiukevich** [comment]
e.g if Margin is "80, 0" it means that all cards have 80 points margin from Left & Right.
So 80 + 80 = 160 (Space that is among all cards is 160 points)
We set PositionShiftValue = 145 (It means that we shift side cards 145 points to the main view)

160 - 145 = 15. So the actual spacing is 15 now.

So, if you wish to reduce the spacing, you should increase PositionShiftValue (e.g. 155)
