### ISSUE TITLE
Different Indicator position on IOS / Android devices

### ISSUE THREAD

**Issue by dirkzp** [AndreiMisiukevich/CardView#367]
Hello,

We are using the plugin to show images f the same size / dimensions on a Content Page. The Indicators should be at the bottom of the image or alternatively under the image. (Bottom of the image is implemented).

We see on our devices that on IOS the Indicators are under the image and on Android devices it is inside the image. Is it a bug or a wrong implementation? Thanks.

IOS View: 
<img width="414" alt="screen1" src="https://user-images.githubusercontent.com/41550363/103401048-b9fc1a00-4b47-11eb-8eea-37b66c71234d.png">

The following XAML is used:
`<cards:CarouselView ItemsSource="{Binding FirmImages}"
                                    SelectedIndex="{Binding image_name}"
                                    BackgroundColor="White">
            <cards:CarouselView.ItemTemplate>
                        <DataTemplate>
                            <ContentView>
                                <Frame VerticalOptions="Start"
                                       HorizontalOptions="FillAndExpand"
                                       Padding="0"
                                       HasShadow="false"
                                       IsClippedToBounds="true"
                                       CornerRadius="0"
                                       Margin="0,0,0,5">
                                    <Image Source="{Binding url}" />
                                </Frame>
                            </ContentView>
                        </DataTemplate>
                    </cards:CarouselView.ItemTemplate>
                    <controls:IndicatorsControl AbsoluteLayout.LayoutBounds="0.5,0.87,-1,-1"
                                                SelectedIndicatorStyle="{StaticResource ActiveIndicator}"
                                                UnselectedIndicatorStyle="{StaticResource InactiveIndicator}" />
                </cards:CarouselView>`

**Comment by AndreiMisiukevich** [comment]
Hello, I don't think it's a bug
Probably images on android and iOS take different space sizes.

**Comment by AndreiMisiukevich** [comment]
Indicators are exactly at that place where you put them)

It seems that Image doesn't expand to take all available card's space

**Comment by AndreiMisiukevich** [comment]
Replace images with colored BoxViews and check if positions are different indeed.
