### ISSUE TITLE
TapGestureRecognizer Tapped create a build error

### ISSUE THREAD

**Issue by grounch** [AndreiMisiukevich/CardView#369]
Hi just noticed an issue with tapgestures.
If i want to assign an event handler to tapped event of tapgesture on an element nested in a CarouselView, it gives the following error at build:

Error: Common Language Runtime detected an invalid program

```
        <CarouselView>
            <CarouselView.ItemsSource>
				<x:Array Type="{x:Type ContentView}">
					<ContentView >
                        <Grid>
                            <Grid.GestureRecognizers>
                                <TapGestureRecognizer Tapped="GestureRecognizer_Tapped"/>
                            </Grid.GestureRecognizers>
                        </Grid>
                    </ContentView>
				</x:Array>
			</CarouselView.ItemsSource>
        </CarouselView>
```

Works well with the Command="..." property to bind a command from the viewmodel, but i need to use an eventhandler in the view's .cs .

**Comment by AndreiMisiukevich** [comment]
I propose you to bind TapGestureRecognizer.Command to your view's command.

```xaml
<ContentPage x:Name="Page"

...

<Grid.GestureRecognizers>
    <TapGestureRecognizer Command="{Binding TapCommand, Source={x:Reference Page}}"/>
</Grid.GestureRecognizers>
```

Then in code-behind add TapCommand and handle click)

**Comment by AndreiMisiukevich** [comment]
Feel free to ask more questions :)
