### ISSUE TITLE
iOS: If the carousel in the scrollview, then there is no possibility of pulling it down or up

### ISSUE THREAD

**Issue by JTOne123** [AndreiMisiukevich/CardView#37]
I don't dig it deeply yet, may be it's an issue in ffimageloading.

I have the ffimageloading in the carousel, and carousel in the scrollview.

For some reason, I can touch and pulling it down in Android, but I can't did the same on iOS(and UWP as well)

Have you come across this?

**Comment by AndreiMisiukevich** [comment]
Hi, have you looked through the workarounds section of Readme file?)
Pay attention at ParentScrollView

**Comment by JTOne123** [comment]
Сорян, провтык

**Comment by AndreiMisiukevich** [comment]
It's ok
