### ISSUE TITLE
nextViews and prevViews not returning proper values after the animation has ended in CardView

### ISSUE THREAD

**Issue by procyon97** [AndreiMisiukevich/CardView#371]
nextViews and prevViews always ouput correct values during swipe (status is running), however the values I get after the swipe seem to be incorrect. 
For example let's say there are 4 cards: A, B, C, D and A is the first card. And swipe is from A to B

During swipe:
```
var nextView = MainCardView.NextViews.First() as CardView;
Debug.WriteLine($"Next view value is: {nextView}");
var prevView = MainCardView.PrevViews.First() as CardView;
Debug.WriteLine($"Prev view value is: {prevView}");
```
Outputs:
```
Next view value is: B
Prev view value is: D
```

So that's correct, however I'm running into a problem when I use this method after the swipe (status ending or ended).

After swipe:
```
var nextView = MainCardView.NextViews.First() as CardView;
Debug.WriteLine($"Next view value is: {nextView}");
var prevView = MainCardView.PrevViews.First() as CardView;
Debug.WriteLine($"Prev view value is: {prevView}");
```
Outputs:
```
Next view value is: D
Prev view value is: A
```

If I swipe 1 more time with the same query outputs:
```
Next view value is: A
Prev view value is: B
```
then B,C and then C,D. The direction of the swipe also matters. It always shows previous two cards instead of previous and next one. Is it a bug or is the a way it should work?

**Comment by AndreiMisiukevich** [comment]
These properties are more for internal use.
And they show actual values only during interaction (because before interaction views can be absent).

CardsView doesn't create views for all items on start.
Also, CardsView reuses views created from DataDemplate.

So, yes. That's impossible to get the view before the movement started.
