### ISSUE TITLE
Carousel View sets selected index to 0 on init even though selected item is not index 0

### ISSUE THREAD

**Issue by Jcook65** [AndreiMisiukevich/CardView#372]
I am in a situation where I am trying to load a page with the `CarouselView` at the position that the user was in when they last left the page (or closed the application). I am doing this by binding the `SelectedItem` to the last selected item in the carousel's bound list. What is happening though is that the `CarouselView` always starts at index 0 regardless of what the `SelectedItem` is bound to and then will change the `SelectedItem` to match the index.

When I put a break point in the property changed event, to observe what is happening, I am noticing that the carousel starts with the correct selected item but with an index of -1, since I am loading a list and the selected item gets bound before the list is done loading. I guess since the Item isnt found in the empty list it sets the index to -1. I am assuming that after the page is done initializing it sets that -1 to 0? and then that updates the `SelectedItem` as a consequence. I have tried to set the binding of `SelectedItem` after the `ItemSource` property changed but this doesnt work either.

I might be wrong in that assessment but I guess my question is: is it possible to drive the carousel from a bound `SelectedItem`? or do I have to bind to the `SelectedIndex` to get the kind of behavior I am wanting?

**Comment by AndreiMisiukevich** [comment]
Hey @Jcook65 try next

1) Set IsAutoNavigatingAnimationEnabled = false
2) Set SelectedItems
3) Set IsAutoNavigatingAnimationEnabled = true

**Comment by AndreiMisiukevich** [comment]
@Jcook65 did it help?

**Comment by Jcook65** [comment]
hey @AndreiMisiukevich, sorry for the delayed response. I actually ended up just converting the selected item to and index and binding to the SelectedIndex instead of the SelectedItem and it works fine now. I haven't had the time to go back and try it the way you suggested here. I must've missed that property on the carousel but it sounds like it would help this situation. Thank you for the swift response!

**Comment by AndreiMisiukevich** [comment]
@InquisitorJax I guess it happens because SelectedItem/SelectedIndex binding is performed before ItemsSource binding.

**Comment by AndreiMisiukevich** [comment]
hmm, or maybe even vice versa (because index binding performed earlier)

**Comment by AndreiMisiukevich** [comment]
@InquisitorJax try to reorder bindings in your xaml.

Or even try to bind ItemsSource in xaml and SelectedIndex in code-behind

**Comment by AndreiMisiukevich** [comment]
@InquisitorJax I think we should open a new ticket for this problem, cuz this one is related to SelectedItem.

Unfortunately, SelectedItem cannot be used for setting initial value (because it just sets selected index)

```csharp
var view = bindable.AsCardsView();
view.SelectedIndex = view.ItemsSource?.FindIndex(newValue) ?? -1;
```

And if ItemsSource is not set before the selected item, then it will be reset to null.

**Comment by AndreiMisiukevich** [comment]
@InquisitorJax maybe you can create a new issue and attach a sample?
Or maybe you have a chance to debug the lib on your main project to see why it resets to 0?

**Comment by AndreiMisiukevich** [comment]
Also, it can happen if you use "null" items or items with the same value (e.g. items are integers or strings with the same value)

**Comment by AndreiMisiukevich** [comment]
Also, it can happen if you set SelectedIndex (e.g. to 3), bind ItemsSource to ObservableCollection (empty). And start to add elements one by one after that.

**Comment by InquisitorJax** [comment]
I'll open a new ticket, thanks Andrei. So we bind ItemSource to generic List<T>, and Selected Index.
Attaching the project ot debug is a good idea - I'll try that, and report what I find.
