### ISSUE TITLE
Bug with TemplateSelector on Android when switching Shell Tabs

### ISSUE THREAD

**Issue by InquisitorJax** [AndreiMisiukevich/CardView#373]
See attached repro project

![cardsview](https://user-images.githubusercontent.com/1822976/110479698-5d405100-80ee-11eb-8ee5-e36981d9139d.gif)

[CardsCarouselSample.zip](https://github.com/AndreiMisiukevich/CardView/files/6108849/CardsCarouselSample.zip)

**Comment by AndreiMisiukevich** [comment]
v2.7.1
