### ISSUE TITLE
Getting error "the given key "xamarin.forms.xaml.elementNode" was not present in the dictionary" 

### ISSUE THREAD

**Issue by wadekarswati** [AndreiMisiukevich/CardView#374]
Took latest CardsView nuget added in all projects. 
Follwoed all steps.
In project added Coverflowview in content view. but getting below error -

the given key "xamarin.forms.xaml.elementNode" was not present in the dictionary
KeyNotFoundException is coming.

Xamarin.Forms - 5.0.0
CardsView - 2.7.1

**Comment by AndreiMisiukevich** [comment]
Hey @wadekarswati could you please build a sample app and add a stack trace of the exception.
I have never seen anything like this before.

**Comment by AndreiMisiukevich** [comment]
CC @wadekarswati )

**Comment by AndreiMisiukevich** [comment]
Feel free to reopen this issue if you have a reproduction sample)
