### ISSUE TITLE
Templates remain in cache

### ISSUE THREAD

**Issue by InquisitorJax** [AndreiMisiukevich/CardView#376]
reloading the collection where data template should be different still loads an old data template.
What's interesting is that it seems to only happen if the CollectionView hosting the template is scrolled.
![carousels](https://user-images.githubusercontent.com/1822976/113269567-dfc8c480-92d8-11eb-9e2c-c580e3e25a25.gif)
[CardsCarouselSample.zip](https://github.com/AndreiMisiukevich/CardView/files/6242325/CardsCarouselSample.zip)

in our main project, the 2 templates actually appear over each other.

**Comment by InquisitorJax** [comment]
The problem is compounded when setting IsAutoNavigatingAnimationEnabled="False":
![carousels2](https://user-images.githubusercontent.com/1822976/113289501-971d0580-92f0-11eb-9efd-ce1b86e2fbb7.gif)

**Comment by AndreiMisiukevich** [comment]
Seems I cannot reproduce it on iOS. Can you?

**Comment by AndreiMisiukevich** [comment]
Wow, it was a hard time debugging this issue.

**Comment by AndreiMisiukevich** [comment]
v2.7.2
