### ISSUE TITLE
When making the window bigger on UWP, you see the card on the right side.

### ISSUE THREAD

**Issue by rheesbeen** [AndreiMisiukevich/CardView#378]
When you make the window bigger on UWP. The card outside the window becomes visible.
Expected behaviour is that it shouldn't become visible.

Thnx for your time and please let me know how i can help.

**Comment by AndreiMisiukevich** [comment]
@rheesbeen do you see the card only during resizing (and once you end resizing it disappears again). Or it is still visible after the end of resizing.

**Comment by rheesbeen** [comment]
It is still visible after the resize. It will rectify when you scroll a little or select a other page.
I just saw that sometimes the item on the left side moves in during resize.

![resize-right](https://user-images.githubusercontent.com/34963849/114142983-db715c80-9913-11eb-833d-8698de68c813.png)
![resize-left](https://user-images.githubusercontent.com/34963849/114142991-ddd3b680-9913-11eb-9c54-6fc29ae372b1.png)

**Comment by AndreiMisiukevich** [comment]
interesting.

**Comment by AndreiMisiukevich** [comment]
Can you override the OnSizeChanged (OnSizeAllocated) of your page that you resize?

And perform a call there

```carousel.ForceRedrawViews();```

**Comment by AndreiMisiukevich** [comment]
Or even better, subclass the carouselView and override the method.

```
class MyCarousel : PanCardView.CarouselView {
        protected override void OnSizeChanged()
        {
            base.OnSizeChanged();
            Device.BeginInvokeInMainThread(() => {
                ForceRedrawViews();
                RemoveUnprocessingChildren();
                LayoutChildren(X, Y, Width, Height);
                ForceLayout();
            });
        }
}

**Comment by rheesbeen** [comment]
Overriding the OnSizeAllocated does the trick. Did not try the subclass option, do you want me to try that also?

**Comment by AndreiMisiukevich** [comment]
> Overriding the OnSizeAllocated does the trick. Did not try the subclass option, do you want me to try that also?

yes please

**Comment by AndreiMisiukevich** [comment]
> Overriding the OnSizeAllocated does the trick. Did not try the subclass option, do you want me to try that also?

how does overridden method look like?

**Comment by AndreiMisiukevich** [comment]
try 2.7.3

**Comment by rheesbeen** [comment]
Yes! That resolved the issue. Thanks for your time,
