### ISSUE TITLE
When swipping back on iOS the menu page opens up

### ISSUE THREAD

**Issue by IeuanWalker** [AndreiMisiukevich/CardView#379]
Is there a way to prevent the menu page from opening up on iOS when swiping back

**Comment by AndreiMisiukevich** [comment]
Hi @IeuanWalker 
What menu page do you mean?

**Comment by IeuanWalker** [comment]
the master-detail/ flyout page

**Comment by AndreiMisiukevich** [comment]
@IeuanWalker does it work fine on Android?

**Comment by AndreiMisiukevich** [comment]
@IeuanWalker I cannot reproduce it with "MasterDetailPage"
Do you use Shell Flyout insted?
Can you build a small sample?

**Comment by AndreiMisiukevich** [comment]
```if (parent is MasterDetailPage && (Element?.IsHorizontalOrientation ?? false))```
Probably we just need to add FlyoutItem check in iOS renderer, but I do prefer to see reproduction before committing. Cuz as I said, I cannot reproduce it on old MasterDetailPage

**Comment by IeuanWalker** [comment]
@AndreiMisiukevic Android seems fine.

Here is a repo (slimmed down version of our app) - 
[Repo.zip](https://github.com/AndreiMisiukevich/CardView/files/6311903/Repo.zip)

Also, I couldn't find any docs to show how you could change the display index from the code behind. There are 2 arrows on that page, that when clicked should go to the next/ previous year.

**Comment by AndreiMisiukevich** [comment]
> Also, I couldn't find any docs to show how you could change the display index from the code behind. There are 2 arrows on that page, that when clicked should go to the next/ previous year

Bind SelectedIndex to ViewModel's property and change it to desired value. Don't forget to trigger PropertyChanged event.

**Comment by AndreiMisiukevich** [comment]
v.2.7.4

**Comment by IeuanWalker** [comment]
Thanks, works like a charm :)
