### ISSUE TITLE
Right/Left arrows feature

### ISSUE THREAD

**Issue by AndreiMisiukevich** [AndreiMisiukevich/CardView#38]
Something like this
![image](https://user-images.githubusercontent.com/10124814/41658268-8803e58c-749e-11e8-8e64-94c92201a6c6.png)

**Comment by AndreiMisiukevich** [comment]
Somebody wants to get in "from box" ?

**Comment by abner86** [comment]
![screenshot_2018-06-28-09-19-33 1](https://user-images.githubusercontent.com/5524692/42047860-5e3e958a-7ab6-11e8-88a5-2e5f88d12e74.png)
Something like this?

**Comment by AndreiMisiukevich** [comment]
@abner86, yep)
Would you like to get this feature in next releases?
Because I don't know, if it would be useful feature or not.

**Comment by abner86** [comment]
Honestly, I don't think this is a useful feature. But we can add this feature in the next releases since I added a boolean property that gives devs an option if they want to display this feature to the user.

**Comment by AndreiMisiukevich** [comment]
Ok, let's close this issue for now.. maybe return to it later

**Comment by benazir0** [comment]
Please implement the feature. It would be nice to have.

**Comment by AndreiMisiukevich** [comment]
I will do it on weekend)
It will be something like indicatorsControl)

**Comment by LeoJHarris** [comment]
This would be really helpful, tbh I was hoping this already had it  which it didnt so was bit disappointed but would be super to have it. Can we have the ability to either get the dots in the middle bottom or the side indicaters.

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris yes, you can put IndicatorsControl, where you want

**Comment by AndreiMisiukevich** [comment]
@benazir0 @LeoJHarris I'm so sorry, guys =( I had no time to implement it on this weekend.
I will try to find time today =)
Thanks for patience )

**Comment by AndreiMisiukevich** [comment]
Hi
Check it on sample project

**Comment by LeoJHarris** [comment]
@AndreiMisiukevich Will check, just as a side question, in the demo gifs, you have first one that has images going to the next with the images tilting over and fade out and the 2nd example gif give they just swipe across. Is there some setting for this?

**Comment by LeoJHarris** [comment]
Mine are fading and tilting when I move between but Im trying to just have it so it just just swipes without the effects

**Comment by LeoJHarris** [comment]
Want this: https://camo.githubusercontent.com/5f26de8f92151b1185d10610a0ae210c5a176c60/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f647530616b5843754f384254487a427561742f67697068792e676966

getting this:
https://camo.githubusercontent.com/a4d6aae8af292dc1db629441f8eefb5c963e0404/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f467a6c563574516846317564447849592f67697068792e676966

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris sorry, i can't see it.
![image](https://user-images.githubusercontent.com/10124814/45671693-c7379b00-bb2e-11e8-8c6b-a6ad11a906a3.png)

**Comment by LeoJHarris** [comment]
![capture](https://user-images.githubusercontent.com/5468757/45717044-d715b480-bbec-11e8-9bca-9948010c5479.PNG)

On your home page for this project you have two gifs the top has a different animation then the below. I would like to get the below animation.

**Comment by LeoJHarris** [comment]
@AndreiMisiukevich but have to compliment you on a really cool library anyhow :)

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris 
>
>
1) if you want to get "Carousel" animation, you should use **CarouselView** instead of CardsView

They are almost the same https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CarouselView.cs#L10
but have different animation processors
>
>
2) Yes, arrows don't response during animation process..
https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Controls/ArrowControl.cs#L181-L184
Do you think I should remove this check?
>
>
3) Thank you so much :)

**Comment by AndreiMisiukevich** [comment]
Hi
1.6.3 is published
https://github.com/AndreiMisiukevich/CardView/blob/master/docs/ArrowControl%20(Left:Right).md
