### ISSUE TITLE
[iOS] OppositePanDirectionDisablingThreshold has adverse effect on swipe performance + missing template

### ISSUE THREAD

**Issue by InquisitorJax** [AndreiMisiukevich/CardView#382]
Test Device: iPad 5th Gen.

related issue?
https://github.com/AndreiMisiukevich/CardView/issues/328

When an item in the CarouselView as scrollable content:
- works great on android (no horizontal scrolling happens when swiping the list)
- iOS: when swiping the list, horizontal scrolling is also activated, and accidental swipes to the next CarouselItem can happen
- tried implementing OppositePanDirectionDisablingThreshold property to fix this, but results in the content listview swipe performance degradation.

Not 100% sure if this is related, but the template also seems to go blank when activating the swipe with the threshold property.

Not using the property: List swipe is super-fast, but accidental horizontal move can happen (only iOS)
![nothreshold](https://user-images.githubusercontent.com/1822976/115390315-6426ad00-a1de-11eb-8109-a700a89942fb.gif)

Adding the property - the accidental swiping is prevented, but the swipe performance is terrible, and it also seems to cause a render problem with the item (becomes blank)

![threshold](https://user-images.githubusercontent.com/1822976/115390814-fdee5a00-a1de-11eb-9a36-6d0a488c6c73.gif)

[CardsCarouselSample.zip](https://github.com/AndreiMisiukevich/CardView/files/6343241/CardsCarouselSample.zip)

**Comment by AndreiMisiukevich** [comment]
Updated code)
v.2.7.6
