### ISSUE TITLE
Having the indicators control external and not in CarouselView body

### ISSUE THREAD

**Issue by LegendaryB** [AndreiMisiukevich/CardView#384]
Hey, 

any way possible to move the indicators control outside of the carousel view body?
Already tried with setting itemssource manually but then the current position is not shown.

**Comment by LegendaryB** [comment]
Can be closed. My workaround is to give the CarouselView a x:Name.
After that I use the IndicatorsControl like this:
```
<indicator:IndicatorsControl
     Grid.Column="1"
     ItemsSource="{Binding Media}"
     SelectedIndex="{Binding Source={x:Reference mediaPresenter}, Path=SelectedIndex}" />
```

**Comment by AndreiMisiukevich** [comment]
Or
```
<indicator:IndicatorsControl
     BindingContext="{Binding Source={x:Reference mediaPresenter}}"
     Grid.Column="1"/>
```
