### ISSUE TITLE
Default constructor not found for type PanCardView.Droid.CardsViewRenderer 

### ISSUE THREAD

**Issue by braulio-oc** [AndreiMisiukevich/CardView#39]
Hi!

I used the CardsView control inside the PullToRefreshLayout from jamesmontemagno control, when the app start throws me the error: 
Default constructor not found for type PanCardView.Droid.CardsViewRenderer 

How could I avoid this error? first I try not link the assemblies in config properties, then I try creating a custom render with default constructor without luck.

I used xamarin forms 2.4
thanks for your help

**Comment by braulio-oc** [comment]
Ok, I resolved implementing the custom render in android without context in the constructor for xamarin 2.4 and deleting the reference PanCardView.Android in Android project

**Comment by AndreiMisiukevich** [comment]
Hm, does compiler say you, that default constructor is obsolete/deprecated?
Or this update came with Xamarin Forms 2.5...

**Comment by AndreiMisiukevich** [comment]
This is cool work around.
I think, we needn't add it to the project, because Forms 2.4 is rather old

**Comment by AndreiMisiukevich** [comment]
I didn't want to update this plugin to excepting XF versions less then 2.5..

https://forums.xamarin.com/discussion/106796/avoiding-obsolete-default-constructor-with-android-custom-renderers-in-2-5

So, I think, this issue can be closed.. =)

**Comment by AndreiMisiukevich** [comment]
Hi @braulio-oc 
I pushed new version of package with Forms 2.4 fix
So, you can try to remove you duplicated code and install droid part again =)
