### ISSUE TITLE
CoverFlowView strange behaviour

### ISSUE THREAD

**Issue by morpheusweb** [AndreiMisiukevich/CardView#390]
Hello. randomly, the coverflowview instead of scrolling horizontally smoothly produces an effect as shown in the figure.
the code used is placed at the bottom. See attached image for behaviour

Thank you
Carmelo

Code:

<panCardView:CoverFlowView ItemsSource="{Binding MonthlyPicks, Mode=OneWay}"
                           PositionShiftValue="90"
                           IsCyclical="True"
                           Padding="30, 0,30,0"  
                           BackgroundColor="{StaticResource White}"
                           ItemSwiped="CardsView_OnItemSwiped"
                           OppositePanDirectionDisablingThreshold="1">
    <panCardView:CoverFlowView.ItemTemplate>
        <DataTemplate  x:DataType="itinerary:ItineraryModel">
            <Frame 
                Padding="10" 
                Margin="14" 
                HasShadow="False" 
                IsClippedToBounds="True" 
                HorizontalOptions="FillAndExpand"
                BackgroundColor="White" >

                <Frame.GestureRecognizers>
                    <TapGestureRecognizer NumberOfTapsRequired="1"
                                  Command="{Binding BindingContext.ItinerarySelected, Source={x:Reference mainpage} }"
                                  CommandParameter="{Binding .}" />
                </Frame.GestureRecognizers>

                <Grid>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="Auto"></RowDefinition>
                        <RowDefinition Height="Auto"></RowDefinition>
                        <RowDefinition Height="Auto"></RowDefinition>
                        <RowDefinition Height="Auto"></RowDefinition>
                    </Grid.RowDefinitions>

                    <materialFrame:MaterialFrame  Grid.Row="0"
                                     Grid.Column="0"
                                     CornerRadius="20" 
                                     Elevation="10"
                                     Padding="0" 
                                     Margin="0" 
                                     IsClippedToBounds="True" 
                                     HorizontalOptions="FillAndExpand"
                                     BackgroundColor="{StaticResource White}" >
                        <Frame IsClippedToBounds="True" CornerRadius="20" Margin="0" Padding="0" HasShadow="False">
                            <Grid>
                                <ffimageloading:CachedImage HorizontalOptions="FillAndExpand" 
                                    VerticalOptions="Start"
                                    Aspect="AspectFill"
                                    HeightRequest="220"
                                    DownsampleToViewSize="true"
                                    Source = "{Binding FrontImageFileName, Converter={StaticResource ToImageWebsite}}" />
                                <Frame IsVisible="False">
                                    <abstractions:CircleButton
                                        ImageSource="{Binding IsFavorite, Converter={StaticResource ToFont}}" 
                                        FontSize="10" 
                                        TextColor="{StaticResource NigthBlue}" 
                                        HeightRequest="30" 
                                        WidthRequest="30" 
                                        BorderThickness="0"
                                        BackgroundColor="{StaticResource White}" 
                                        Command="{Binding BindingContext.SetFavorites, Source={x:Reference mainpage}}" CommandParameter="{Binding .}" />
                                </Frame>
                            </Grid>
                        </Frame>
                    </materialFrame:MaterialFrame>

                    <Label Grid.Row="1" 
                           Grid.Column="0"
                           Padding="4" Margin="10, 0" Text="{Binding Title}" FontSize="{OnPlatform iOS=Small, Android=Micro}" FontAttributes="Bold"/>

                    <Grid Grid.Row="2" Grid.Column="0">
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="*"></ColumnDefinition>
                            <ColumnDefinition Width="*"></ColumnDefinition>
                        </Grid.ColumnDefinitions>

                        <rating:SfRating Grid.Row="0"
                             Grid.Column="0"
                             ItemSize="20"
                             Margin="10,0"
                             ReadOnly="true"
                             Value="{Binding AverageRating}">
                            <rating:SfRating.RatingSettings>
                                <rating:SfRatingSettings RatedFill="{StaticResource WorldyOrange}" UnRatedFill="{StaticResource GrayDark}" RatedStrokeWidth="0" UnRatedStrokeWidth="0"/>
                            </rating:SfRating.RatingSettings>
                        </rating:SfRating>
                        <Label Grid.Row="0"
                               Grid.Column="1"
                               Text="{Binding DiscountPrice, StringFormat='{}{0:N0}€'}" 
                               FontSize="{OnPlatform iOS=Small, Android=Micro}"
                               FontAttributes="Bold"
                               HorizontalOptions="EndAndExpand"
                               Margin="10,0"></Label>
                    </Grid>

                    <Grid Grid.Row="3" Grid.Column="0" Margin="0,0">
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="auto"></ColumnDefinition>
                            <ColumnDefinition Width="*"></ColumnDefinition>
                        </Grid.ColumnDefinitions>

                        <ffimageloading:CachedImage  
                            Margin="10,0"
                            Grid.Row="0"
                            Grid.Column="0"
                            HorizontalOptions="FillAndExpand" 
                            VerticalOptions="Center"
                            Aspect="AspectFill"
                            DownsampleToViewSize="true"
                            HeightRequest="30"
                            WidthRequest="30"
                            Source = "{Binding InterestIcon, Converter={StaticResource ToImageWebsite}}" 
                        />
                        <Label Grid.Row="0"
                               Grid.Column="1"
                           Text="{Binding InterestDescription}" 
                           FontSize="{OnPlatform iOS=Small, Android=Micro}"
                           FontAttributes="Bold"
                           HorizontalOptions="Start"
                           VerticalOptions="Center"
                           TextColor="{StaticResource GrayDark}"
                           Margin="0,0"></Label>
                    </Grid>

                </Grid>

            </Frame>
        </DataTemplate>
    </panCardView:CoverFlowView.ItemTemplate>

</panCardView:CoverFlowView>

![coverflowview](https://user-images.githubusercontent.com/76620588/120765468-8881e300-c519-11eb-8dac-44d2d2f9e3f1.png)

**Comment by AndreiMisiukevich** [comment]
Maybe try to remove OppositePanDirectionDisablingThreshold="1"
Also, ItemSwiped that's not what you think. You should use ItemAppearing

**Comment by AndreiMisiukevich** [comment]
I can't reproduce it without a sample.
I guess there is an issue somewhere on your side.
