### ISSUE TITLE
Android: Nested CourselView Swipe performance

### ISSUE THREAD

**Issue by InquisitorJax** [AndreiMisiukevich/CardView#392]
Nested CarouselView for iOS works fantastically, but on Android, the **child carousel** will often reject the swipe gesture :(

![nestedCarousel](https://user-images.githubusercontent.com/1822976/122061968-4ac16c00-cdef-11eb-909e-1aa3018a0f9d.gif)

by the looks of it, it will only happen if the swipe should register to the parent (child has reached the end of it's items)

**Comment by AndreiMisiukevich** [comment]
it is not easy not to fix( I spent hours trying that - no luck (

But it works fine if you not fast swiping but just drag and move, right?

**Comment by InquisitorJax** [comment]
yeah, slow swiping works. 
I also tried digging into the code a bit - didn't spot anything obvious.
The only alternative is to perhaps implement ViewPager for android 
https://www.journaldev.com/19336/android-nested-viewpager-vertical-viewpager
or perhaps there's some handy code in there that could help.

**Comment by AndreiMisiukevich** [comment]
Sorry man, I doubt it would be implemented. Probably I should drop support of nested carousels :(

**Comment by InquisitorJax** [comment]
... or known issue on android ;)
