### ISSUE TITLE
Android: CarouselView - Allow scrollable content

### ISSUE THREAD

**Issue by InquisitorJax** [AndreiMisiukevich/CardView#393]
Perhaps this is already possible with a property?
iOS: If I add a horizontal ScrollView with content, iOS allows the content to be scrolled:
![iosChildScroll](https://user-images.githubusercontent.com/1822976/122365453-f9ce8680-cf5a-11eb-8dfb-916418d0ba2e.gif)

.. but for Android, I'm not able to scroll the header ScrollView:
![droidChildScroll](https://user-images.githubusercontent.com/1822976/122365718-34d0ba00-cf5b-11eb-86ba-e95d89759f0e.gif)

Sample repro repo here using the Nested CarouselView page:
https://github.com/InquisitorJax/CardView

**Comment by AndreiMisiukevich** [comment]
Hm, try to set ShouldThrottlePanInrwraction to True

**Comment by InquisitorJax** [comment]
that allows the header scrollview to scroll, but then the nested CarouselView can only pan within itself - the parent carousel cannot swipe to item 2.

**Comment by AndreiMisiukevich** [comment]
Got it) I think such kind of layout is quite complex, I am not sure it will be possible to implement that (at least I don't know for now)

**Comment by InquisitorJax** [comment]
yeah - I'm thinking these types of scenarios is where one should lean more on the native controls like the ViewPager + Adapter that support this kind of thing more easily (at least I think they do  🤷‍♀️).

**Comment by AndreiMisiukevich** [comment]
Sorry, I don't think it will be ever implemented
