### ISSUE TITLE
Support for .NET Maui

### ISSUE THREAD

**Issue by DoubleDBE** [AndreiMisiukevich/CardView#399]
Will this library be ported to .NET Maui?

**Comment by AndreiMisiukevich** [comment]
@DoubleDBE I think, Yes.

**Comment by AndreiMisiukevich** [comment]
@DoubleDBE do you want to volunteer on this?

**Comment by sixpeteunder** [comment]
@AndreiMisiukevich what would need to be done?

**Comment by DoubleDBE** [comment]
Maui has an option for XF compatibility which can be used to gradually port XF libraries to maui with minimal changes.

I think that's the best option for now because documentation for maui is very slim at the moment, and things can still change due to the fact that it's still in development.

@AndreiMisiukevich @sixpeteunder What are your opinions?

**Comment by sixpeteunder** [comment]
@DoubleDBE I'm willing to help. It would be my first contribution of this kind but I think with some help can get it done. 

Not a professional opinion, but I think MAUI is nearing RC so things might stabilize soon.

**Comment by ederbond** [comment]
MAUI is currently on RC2 and very close to GA (My personal guess is that they will announce GA on Build Conference this year).
Do you guys have any clue of when and "if" this will be ported to MAUI?

**Comment by AndreiMisiukevich** [comment]
@ederbond I believe you will be able to use all Xamarin packages in your MAUI application by adding the XamarinCompat package.

Or am I missing something?

**Comment by ederbond** [comment]
According to the MAUI team there will be some required changes on the package itself to make it compatible with MAUI
https://twitter.com/ederbond/status/1522630420101218304?s=20&t=1M4IXZNaYjTCWENj9YJQow

**Comment by developer9969** [comment]
Hi Big fan of this nuget - is there any chance of this being moved to Maui? Is it on the cards on no at all. 
It would be nice to know so that we can plan accordingly.

Again @AndreiMisiukevich  thank you for this control .

**Comment by AndreiMisiukevich** [comment]
@developer9969 hi :) and thanks for your support, I appreciate it.
I want to be honest with you, currently I don't have time for that and I'm not sure that it will have it in near future :(

**Comment by AndreiMisiukevich** [comment]
@developer9969 maybe you want to help with porting it to maui? at least as "compat" package?

**Comment by developer9969** [comment]
@AndreiMisiukevich  I will have a look - but I am getting familiar with the all handlers etcs way of doing things..

**Comment by maexsp** [comment]
@AndreiMisiukevich @developer9969 hi :) i started with some investigations and found out the compatibility mode seems not to work (InvalidCastException) as long as the custom control does derive from AbsoluteLayout. Exact this is done in CardsView. I filed a issue to the MAUI team: https://github.com/dotnet/maui/issues/9936

As an alternative I tryed to use the handlers approach and same issue there. As long as the CardsView derives from AbsoluteLayout a InvalidCastException is thrown. Only to derive from ContentView or View/IView solves the problem but those types cannot have multiple children.

Also the _hasRenderer needs to be removed cause MAUI does not throw anymore "Renderer" NotifyPropertyChanges.
 
On my current solution Items are rendered again but the renderer I needed to remove for now and so swipe/touch/fling is not working right now.

**Comment by xleon** [comment]
Our app is based heavily on this library and we are thinking about migrating to MAUI. 
When the moment comes I will need this library migrated so if nobody does it before then I'll do it. 
I don't think the compatibility hack will be enough. However I wanted to ask you in case I consider making a PR in the future: how would you organise folders in this solution to keep both XF and MAUI separated?

**Comment by AndreiMisiukevich** [comment]
@xleon thanks for your feedback and for your readiness to help!

I think it should be completely separate github project.
I can create it

**Comment by xleon** [comment]
Nice. First I wanted to play around an hypothetical migration. 
I'm pretty new to MAUI and it has more changes in Layouts that I expected. 
For instance I'm currently investigating how to solve this issue https://github.com/xleon/CardView.MAUI/blob/main/PanCardView/CardsView.cs#L822

**Comment by AndreiMisiukevich** [comment]
@xleon probaby you can ignore that. It was added as workaround afaik

**Comment by naweed** [comment]
Hi @AndreiMisiukevich,
Any idea when we can expect Maui port of this great library? We are all deeply missing this wonderful package for our Maui apps.

**Comment by AndreiMisiukevich** [comment]
Hello @naweed thanks for your warm words. But unfortunately I don't think I have time for this :(

**Comment by FreakyAli** [comment]
@AndreiMisiukevich I love your work here, I really wish this was ported to Maui :(

**Comment by AndreiMisiukevich** [comment]
@FreakyAli thanks dude

Here we go https://github.com/AndreiMisiukevich/CardView.MAUI

The quality is not as good as you might expect though :(

**Comment by FreakyAli** [comment]
@AndreiMisiukevich  Awesome i will check it out later, Also why do you say the quality might not be as I expect?

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich  Awesome i will check it out later, Also why do you say the quality might not be as I expect?

Because Maui is still raw :( and for example CubeView is broken, also I had to disable IsClippedToBounds for carousel view because of some weird bug. Overall it works but not as good as XF version

**Comment by FreakyAli** [comment]
@AndreiMisiukevich Yeah I can relate to this, I had some existing controls that I created in XF and then moved to MAUI quite recently and many of them broke, Properties didn't work anymore & other such issues. In any case, I will check it out hopefully bugs will get solved. You can check out my controls if you're interested by the way, Nothing fancy but still decent API extensions in my opinion : https://github.com/FreakyAli/Maui.FreakyControls

**Comment by AndreiMisiukevich** [comment]
@FreakyAli thanks!

**Comment by IeuanWalker** [comment]
@FreakyAli lol same experience for me too, still working through my NuGet's but every single one has something that used to work but now has some sort of bug that I have to spend hours researching to find a way around it.

**Comment by FreakyAli** [comment]
> @FreakyAli lol same experience for me too, still working through my NuGet's but every single one has something that used to work but now has some sort of bug that I have to spend hours researching to find a way around it.

I have my fingers crossed that the Maui team will fix them eventually, Anyway as far as I see as of right now. Maui is not stable enough for production apps. (Just my humble opinion.)

**Comment by AndreiMisiukevich** [comment]
@FreakyAli I absolutely agree with this statement
