### ISSUE TITLE
Updatable Carousel with lazy loading?

### ISSUE THREAD

**Issue by K232** [AndreiMisiukevich/CardView#4]
Hi Andrei,
I have the following problem: I need a full-page carousel. It should contain dozens (or hundreds) of pages, so it should render the pages only when needed, not all at the start. Additionally each page has a button where a popup opens. On this popup, user could make changes (increase a counter) which should be updated on the current carousel page as soon as the user closes the tab.
I've tried several plugins (including yours), using observables or lists, but with every plugin (or official CarouselPage) I somewhere face problems :-( Do you think that would be possible to do with your Carousel?
Many thanks and have a nice weekend!

**Comment by AndreiMisiukevich** [comment]
@K232 Hi Kai
I think, yes. Because my plugin has got cache for views and you are able to manage it!
If you want, i can add sample special for you :)

Could you explain, what issue exactly did you face with my plugin?

**Comment by K232** [comment]
Hi Andrei,
that sounds great! Unfortunately I deleted my tests yesterday as I tried so many plugins that I don't know exactly where the problem appeared :-( I've your plugin downloaded last thursday, but my tests are deleted. If you are able to do such a sample that would be awesome!

**Comment by AndreiMisiukevich** [comment]
@K232 Kai, now you can look at samples. I've just added new one for 1000 views in carousel view (4th sample)

Also you can look at 2nd sample (With custom context)
It's sample for CardsView, but it's easy to setup it as carousel view. Just change CardsView to CarouselView. This sample shows, how you can manage prev/next/current views by yourself.

**Comment by AndreiMisiukevich** [comment]
I sure, it's not a problem to show popup and change BindingContext of current card =)

**Comment by AndreiMisiukevich** [comment]
@K232 Is it you need?

**Comment by K232** [comment]
Thanks a lot Andrei, I'm still testing so I did not give a feedback yet but it looks very cool! I'll contact you via email later on. Thanks a lot so far!!

**Comment by AndreiMisiukevich** [comment]
@K232 You are welcome!
I'm glad to help you.

**Comment by K232** [comment]
I've now changed the content of the items to be in a scrollview instead of just a label. While everything works fine in iOS, the carousel effect on Android is gone... I could scroll up down, but not left right anymore...?
This is what I've changed in GetCardItem:
```
            var scroller = new ScrollView
            {
                Content = label
            };

            var content = new ContentView
            {
                BackgroundColor = Color.Black,
                Content = scroller
            };
```

**Comment by AndreiMisiukevich** [comment]
@K232 Ok, I see.
ScrollView steals touch events from superview..

So, it need to create custom renderer for scrollview and try to resolve touches..

**Comment by AndreiMisiukevich** [comment]
@K232 
I'm able to create ability for workaround, if you want.

You will have to set IsEnabled = false in ScrollView and CarouselView will scroll content.
But it doesn't look like native scroll animation.

What do you think?

**Comment by AndreiMisiukevich** [comment]
@K232 Validate it now, i've just implemented this workaround
I can pack new version, if you need :)

**Comment by K232** [comment]
Great! Yes, if you do a new version i'll wait for it. I fear to forget something somewhere ... ;-)

**Comment by AndreiMisiukevich** [comment]
@K232 
Don't forget to star this repository haha xD

So, Can I create new pack, or you want to test it much more time?

**Comment by AndreiMisiukevich** [comment]
@K232 1.2.8 version will be available on nuget in about 10 minutes, i've just pushed it

**Comment by MaxenceMax** [comment]
@AndreiMisiukevich I don't understand your sample with factory and I don't find it in sample ! Does't it work now ?

**Comment by AndreiMisiukevich** [comment]
Hi @MaxenceMax yes, factory was marked as deprecated and removed a few month ago)
Now you should use ItemTemplate (DateTemplate/DataTemplateSelector).


https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardViewSample/PanCardViewSample/Views/CarouselSampleXamlView.xaml
