### ISSUE TITLE
Binding issue

### ISSUE THREAD

**Issue by robertmiles3** [AndreiMisiukevich/CardView#40]
When I attempt to bind to a property on the main page's view model, it doesn't work. I have created an example here...

https://github.com/robertmiles3/CardsViewBindingIssue

I have your CardsView library as the top example on the MainPage, and I have a CarouselView example below it. I like how your CardsView properly lays out in design mode while CarouselView doesn't layout properly. However, CarouselView properly binds to `Stats.Count1` (etc) while I can't get your CardsView to bind like that.

Am I missing something in getting it to bind properly to the `Stats` property?

**Comment by AndreiMisiukevich** [comment]
I this case I suggest you to use ItemTemplate property for creating card template. All your cards are the same, but have got different bindingContext

Set ItemTemplate - your view, and Items - Stats collection.
And bind what you want))

**Comment by robertmiles3** [comment]
`Stats` isn't a collection. It's a single object with properties on it. How would that work?

**Comment by AndreiMisiukevich** [comment]
Redesign it to collection of int
new List<int>()

**Comment by robertmiles3** [comment]
I'm pulling a few counts as stats from a DB, so it doesn't make sense for it to be a list of ints.

**Comment by AndreiMisiukevich** [comment]
By the way, make this class as IPropertyChanged 

    public class DashboardStats
    {
        public int Count1 { get; set; }
        public int Count2 { get; set; }
        public int Count3 { get; set; }
        public int Count4 { get; set; }

        public int Count5 { get; set; }
        public int Count6 { get; set; }
        public int Count7 { get; set; }
        public int Count8 { get; set; }
    }

**Comment by AndreiMisiukevich** [comment]
And try to call this method first of all 

https://github.com/robertmiles3/CardsViewBindingIssue/blob/master/TestCarousel/MainPage.xaml.cs#L32

**Comment by robertmiles3** [comment]
I had that first at the beginning of my testing. Didn't work, so I moved it around testing different things.

**Comment by AndreiMisiukevich** [comment]
So, your issue is clear for me, I'll try to help you =) I will look through your code/xaml this weekend

Thank you for feedback

**Comment by AndreiMisiukevich** [comment]
I think, I know the reason...
Look here https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs#L1068-L1103

if you doesn't use itemTemplate, your view has itself as bindingContext..
It seems like a bug, what do you think, colleague?

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs#L1031

if view == context, we needn't set it as context.. maybe it's the reason of our headache)

**Comment by AndreiMisiukevich** [comment]
Probably, you want to test this case and contribute to this project? Or you can wait until I fix it myself

**Comment by robertmiles3** [comment]
Hmm, yes possibly so. So, what would be the fix? Can it somehow just use the parent/page binding context?

**Comment by AndreiMisiukevich** [comment]
I believe if we leave BindingContext as null the view will get parent's context

**Comment by robertmiles3** [comment]
Gotcha. I'll try that in a bit.

**Comment by AndreiMisiukevich** [comment]
And it must be here https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs#L526
We should to extend this check

			if (CurrentView.BindingContext == context || CurrentView == context)
			{
				return false;
			}

**Comment by AndreiMisiukevich** [comment]
So, only two check (the first is above) and the second is below

https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs#L1029

			if (view != null && view != context)
			{
				view.BindingContext = context;
			}

**Comment by robertmiles3** [comment]
Those 2 changes (L526 and L1029) worked. You want to put those in or want me to submit a PR?

**Comment by AndreiMisiukevich** [comment]
Create PR please

**Comment by AndreiMisiukevich** [comment]
I will create new pack on weekend

**Comment by ryanherman** [comment]
I just ran into this issue where I set the BindingContext to my main view.  When I load the CarouselView, it sets it to the main view, then overrides it to the view set.

**Comment by AndreiMisiukevich** [comment]
Sorry, I didn't understand your matter.

**Comment by AndreiMisiukevich** [comment]
But it doesn't seem to be the same issue

**Comment by AndreiMisiukevich** [comment]
https://www.nuget.org/packages/CardsView/1.4.7
pack with fix

**Comment by robertmiles3** [comment]
Awesome, thanks. Just updated in my main app and it resolved my issue.
