### ISSUE TITLE
[iOS] IsPanInteractionEnabled interaction not honored when SelectedIndex binding added

### ISSUE THREAD

**Issue by InquisitorJax** [AndreiMisiukevich/CardView#401]
When using SelectedIndex binding, and setting IsPanInteractionEnabled = false, the CarouselView is still picking up a swipe action and setting the SelectedIndex property, which triggers a pan.
![lockpan](https://user-images.githubusercontent.com/1822976/146008853-d90ba370-5535-4498-ae56-031fa636c840.gif)

The lock works as expected on android.
![lockpandroid](https://user-images.githubusercontent.com/1822976/146009266-af9c093b-1efa-4a6b-9536-c4072293239b.gif)

find attached repro
[CardsCarouselSample.zip](https://github.com/AndreiMisiukevich/CardView/files/7712004/CardsCarouselSample.zip)

**Comment by AndreiMisiukevich** [comment]
Hi)
Please use IsUserInteractionEnabled instead.

**Comment by AndreiMisiukevich** [comment]
Or try to set IsPanSwipeEnabled to False

**Comment by InquisitorJax** [comment]
Hey Andrei,

We need user interaction, as the reason we're locking the swipe is to allow other touch interactions in the content.

Setting IsPanSwipeEnabled=False still sets the SelectedIndex, which makes it swipe.

**Comment by InquisitorJax** [comment]
Actually - scratch that :)

using IsUserInteractionEnabled does the trick - both on iOS and Android :)

Thanks!

**Comment by AndreiMisiukevich** [comment]
Great)
