### ISSUE TITLE
XAML hot-reload not working when Carousel is in a page of a TabbedPage 

### ISSUE THREAD

**Issue by xleon** [AndreiMisiukevich/CardView#402]
This is making development harder. 
Any other tab in my app works with HotReload just fine. 
Whenever I change something in XAML, the page goes blank. 

Is there any know workaround?

**Comment by AndreiMisiukevich** [comment]
Hi, I don't think so.
Does it work fine with Xamarin Carousel or another carousel plugin?

**Comment by xleon** [comment]
Yes, XF CarouselView works fine in the same scenario.

**Comment by AndreiMisiukevich** [comment]
I'd propose to set "reload entire page" Xaml Hot Reload option and see if it helps)
