### ISSUE TITLE
IsCyclical="false" is causing the content to be blank/not show up

### ISSUE THREAD

**Issue by brettnguyen** [AndreiMisiukevich/CardView#403]

**Comment by AndreiMisiukevich** [comment]
Could you please provide a sample?

**Comment by brettnguyen** [comment]
seems to only be blank with iscyclical = false when I bind something to the selectedItem. But isn't blank on iscyclical = true with a binding to a selectedItem. I have the card view in the aboutpage.xaml. 
https://github.com/brettnguyen/TestPanView

**Comment by brettnguyen** [comment]
Could just be the way I am binding but I was confused when it worked for true but not false. Thank you for any help or feedback.

**Comment by AndreiMisiukevich** [comment]
Hi, could you please try to use selectedIndex instead of selectedItem? Maybe it will solve the problem

**Comment by brettnguyen** [comment]
Will try when I’m home

**Comment by brettnguyen** [comment]
> Hi, could you please try to use selectedIndex instead of selectedItem? Maybe it will solve the problem

this change worked thank you for the help
