### ISSUE TITLE
ItemDisappearing giving me this error "Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index"

### ISSUE THREAD

**Issue by brettnguyen** [AndreiMisiukevich/CardView#405]
ItemDisappearing giving me this error "Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index"
specifically using the mediaelement from the community toolkit like this in my .cs page "mediaElements[args.Index].Pause();".

links to my xaml and xaml.cs

https://github.com/brettnguyen/CollegeVSDemo/blob/master/CollegeVS/CollegeVS/Views/HomePages/CLGVSHome.xaml

https://github.com/brettnguyen/CollegeVSDemo/blob/master/CollegeVS/CollegeVS/Views/HomePages/CLGVSHome.xaml.cs

**Comment by AndreiMisiukevich** [comment]
I see that ItemsSource is bound to `highlights`
```ItemsSource="{Binding highlights}"```

But you call pause on `mediaElements`.

It is most probably an error in your code.
