### ISSUE TITLE
Pull to refresh not working while swiping down on top of Carousal View

### ISSUE THREAD

**Issue by anoopv** [AndreiMisiukevich/CardView#407]
Hi,

We have implemented carousal view in my project and it's working fine.

But if we try to put Carousal View inside RefreshView then Pull to refresh is not happening if we try to swipe down on top of Carousal View.   

Is there any possible solution for this?
```
<Grid>
   <RefreshView>
      <CollectionView>
         <CollectionView.HeaderTemplate>
           <DataTemplate>
               <cards:CarouselView/>
          </DataTemplate>
      </CollectionView.HeaderTemplate>
   </CollectionView>
  </RefreshView>
</Grid>
```
Thanks

**Comment by anoopv** [comment]
Hi @AndreiMisiukevich,Issue exists in iOS

**Comment by AndreiMisiukevich** [comment]
probably the issue is somewhere here
https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView.iOS/CardsViewRenderer.cs#L142-L166

But I am not sure when/if I have time to look through it
