### ISSUE TITLE
Carouselview Indicator Position Top

### ISSUE THREAD

**Issue by Tally2014** [AndreiMisiukevich/CardView#410]
I want my Carousel View Indicators to be on Top instead of being at the bottom by Default. 
I tried setting my <controls:IndicatorsControl VerticalOptions="Start"/> but nothing happens. (When I use the same technique on the default xamarin carousel view it works)

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/issues/263
