### ISSUE TITLE
Carousel Item Wrongly showed other Section of Carousel While Swipe down on RefreshView

### ISSUE THREAD

**Issue by UdayaDevConsole** [AndreiMisiukevich/CardView#411]
Hi .. I am Uday
Carousel View Working Fine on Both device 
i just Display the Section Based Content in Carousel inner of CollectionView
When try to Refresh the Collection View it content wrongly showed other section of carousel view 
it updated Proper content  after Few Second

<StackLayout>
   <RefreshView>
      <CollectionView>
         <CollectionView.ItemTemplate>
           <DataTemplate>
               <cards:CarouselView/>
          </DataTemplate>
      </CollectionView.ItemTemplate>
   </CollectionView>
  </RefreshView>
</StackLayout>

**Comment by UdayaDevConsole** [comment]
<Stacklayout>
   <RefreshView>
      <CollectionView>
         <CollectionView.ItemTemplate>
           <DataTemplate>
               <cards:CarouselView/>
          </DataTemplate>
      </CollectionView.ItemTemplate>
   </CollectionView>
  </RefreshView>
</Grid>

**Comment by AndreiMisiukevich** [comment]
Hello Uday, unfortunately, I can't help you without a reproduction sample and video.

**Comment by UdayaDevConsole** [comment]
Hi @AndreiMisiukevich ... Here i Attached Reference Image .
i showed Multiple Carousel in Single Page. It Properly Showed Under Section But Frame Content Wrongly Showed Other Section Content When i Refresh the Collection View
![CarouselCacheRefreshIssue](https://user-images.githubusercontent.com/105741993/168983272-fccd2266-41d7-4b6c-b49d-0ad6f8174d1d.png)

**Comment by UdayaDevConsole** [comment]
@AndreiMisiukevich Also It Working Fine on Emulator and simulator But Issue on Deployment

**Comment by AndreiMisiukevich** [comment]
Hm, that's weird. If it works fine on iOS simulator then it should on real Device.

Can it be some Xamarin bug?
Can you try to run the app on real device with linter disabled?

**Comment by AndreiMisiukevich** [comment]
Looks like collection view reorders items for a while.
We don't control this process from collection view

**Comment by UdayaDevConsole** [comment]
so how to cache clear on collectionView

**Comment by AndreiMisiukevich** [comment]
I propose to fully recreate items source

**Comment by UdayaDevConsole** [comment]
Sorry .i couldn't understood . Can u explain briefly?

**Comment by UdayaDevConsole** [comment]
While Refresh the View What i do to ?
i am Using Observable Collection for DataBinding
CollView.ItemSource = RefreshData.ToList()

**Comment by AndreiMisiukevich** [comment]
What is inside RefreshData?
Views or just items?

I mean, do you use ItemTemplate? Or add views directly to itemssource?


Also, you can try something so hacky.

Using code behind, remove your collection view from page and then add it again (on refresh). Or optionally recreate a new instance of collection view

**Comment by UdayaDevConsole** [comment]
i am using item Template and Data assign Using itemsource directly from c# Like below Mentioned
XAML : 
<StackLayout>
   <RefreshView>
      <CollectionView x:Name="CollView">
         <CollectionView.ItemTemplate>
           <DataTemplate>
               <cards:CarouselView/>
          </DataTemplate>
      </CollectionView.ItemTemplate>
   </CollectionView>
  </RefreshView>
</StackLayout>
C# :
CollView.ItemSource = RefreshData.ToList()

**Comment by UdayaDevConsole** [comment]
@AndreiMisiukevich can u have sample for **",remove your collection view from page and then add it again (on refresh). Or optionally recreate a new instance of collection view"** ?

**Comment by UdayaDevConsole** [comment]
Hi @AndreiMisiukevich 
i think its not collection view problem because Issue When i Scrolldown to bottom these way also occur same issue 
something wrong on carousel

**Comment by AndreiMisiukevich** [comment]
@UdayaDevConsole https://github.com/xamarin/Xamarin.Forms/issues/13045
it can be collectionview recycling issue
Try to change collectionview to listview and set strategy to retain element instead recycling
