### ISSUE TITLE
Add ItemTemplateSelector functionalty

### ISSUE THREAD

**Issue by Alex-Dobrynin** [AndreiMisiukevich/CardView#413]
In my case I need to show different templates for each item in your's carouselview, but unfortunately it does not allow me to do that when im trying to put template selector into ItemTemplate property, as it could be done in collectionview or listview.

OR I dont understand why my DataTemplateSelectro's SelectTemplate is not being called, I just replaced Xamarin.Forms's carouselview by your's one

**Comment by AndreiMisiukevich** [comment]
Can you build a sample?

It should be working

https://github.com/AndreiMisiukevich/CardView/blob/ac346c302b92e09e2f7ca098dca9de3cd5c8be29/PanCardViewSample/PanCardViewSample/Views/CarouselSampleListView.cs

**Comment by AndreiMisiukevich** [comment]
Here is the code https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs#L1627-L1631

At least it was working previously. I would be surprised if it's not working now

**Comment by Alex-Dobrynin** [comment]
Yeah, It was my fault, sorry :(
