### ISSUE TITLE
not dismissing keyboard

### ISSUE THREAD

**Issue by sbxamdev** [AndreiMisiukevich/CardView#418]
Hi,

I have a Xamarin.Forms application and is using the PanCardView.CarouseView. The ItemTemplate contains editor and entry controls. My issue is that the keyboard is not dismissing when I swipe the carousel on the next carousel item. For example, If I'm on the first index of the carousel then taps on the Entry, the keyboard shows but if I swipe to the second index while the keyboard is still active, its still there which I suppose should be dismissed?

Is there any solution/work-around for this?
Thanks in advance!

**Comment by AndreiMisiukevich** [comment]
Hi @sbxamdev you should dismiss keyboard on your own.
Probably ItemDisappearing event / ItemDisappearingCommand should help you.

You need to perform unfocus when a correpsonding view goes away.

**Comment by sbxamdev** [comment]
thank you! that solves it
