### ISSUE TITLE
Carouselview does not rerender when device wakes from sleep on Android

### ISSUE THREAD

**Issue by daltzctr** [AndreiMisiukevich/CardView#419]
OS: Android 11
Hardware: Lenovo Tablet

Summary: Whenever the device is woken up from sleep (`OnStop` -> `OnStart`), CarouselView elements are blank. Swiping restores the elements, but is not an intuitive user experience.

**Comment by AndreiMisiukevich** [comment]
Closing this issue since I haven't received any response from the author.
