### ISSUE TITLE
CarouselView IsAutoNavigating Does not work?

### ISSUE THREAD

**Issue by mzhukovs** [AndreiMisiukevich/CardView#42]
Hi there,

THanks for this package.

I have a CarouselView and i set IsAutoNavigating to True, but in the view, the carousel does not move from item to item automatically (without user interaction) as expected. Am I supposed to set something else for this to work or am I misunderstanding the point of IsAutoNavigating?

Please let me know, thanks.

**Comment by AndreiMisiukevich** [comment]
Hi) 
Thanks for feedback.. I think, i need to make some properties as internal or add comment, that they are only for Internal use =)

So, this porperty just demonstrate, that carousel view is autoNavigating now. It means, that now one card changes another one without user interaction.

If you want to make slideshow, please, see SlideShowDuration property (Set milliseconds delay)

Enjoy it! =)

**Comment by AndreiMisiukevich** [comment]
Let me know, if you have any troubles with setting up slideshow

**Comment by mzhukovs** [comment]
Ah got it, yes using SlideShowDuration gets me what I was after. Yes it may help prevent confusion if some comments were provided for the properties. Спасибо за помощь!

**Comment by shreyans-wakekar** [comment]
Hello, I just want to know, how to stop slideshow programmatically, after last element has been swiped.
Need Help.

**Comment by AndreiMisiukevich** [comment]
@shreyans-wakekar Replied you in another issue =)

"if current index == last index then slideshowduration = 0 " =) it's just pseudocode
