### ISSUE TITLE
Data Wrongly Replicate to other Section when Scroll the multiple Carouselview in CollectionView on Xamarin IOS

### ISSUE THREAD

**Issue by UdayaDevConsole** [AndreiMisiukevich/CardView#421]
Hi ...
i have issue on **Xamarin IOS**
CarouselView Data Replicate to other Section When i Scroll the CollectionView 
i mean ... I Display the Section Based CarouselView ..So i Just Added multiple Template for that View and Display the multiple carousel in single collection view ..
The Display Data Wrongly few second Display in other section and it was disappear 
My Question why it occur fast scroll on collectionview and it only issue on IOS

**Comment by AndreiMisiukevich** [comment]
Try to set IsViewReusingEnabled="False"
