### ISSUE TITLE
Is .NET 1 Standard Support a joke?

### ISSUE THREAD

**Issue by mediaexplorer74** [AndreiMisiukevich/CardView#422]
Hi, Andrei.

I explored your PanCardView module. I detected that you link Xamarin Forms 5. But Xamarin Forms 5 is not compatible with .NET 1/ 1.2 / 1.3/ 1.4. It is for 2.0 only. So, .NET 1 Standard support is only joke :(
Heh, I want to use PanCardView for old sweet Win10Mobile (last Win 15063 SDK don't support .NET 2 Standard). Too bad that your multi-platform samples is not universal solution as I dream...

**Comment by AndreiMisiukevich** [comment]
Yes, it was a joke.
If you wish, you can download this project, downgrade forms version to needed one, then either create a local package or add the project as dependency, use it and enjoy)

**Comment by mediaexplorer74** [comment]
> Yes, it was a joke. If you wish, you can download this project, downgrade forms version to needed one, then either create a local package or add the project as dependency, use it and enjoy)

Nice idea. Good plan!
Ok, I forked your solution for PanCardView adaptation to W10M UWP :)

Cheers up!
Have a nice day / Best wishes ,
mediaexplorer74 aka Andrey

**Comment by AndreiMisiukevich** [comment]
@mediaexplorer74 nice :)
