### ISSUE TITLE
I put the carousel view in a horizontal scrollview and since the horizontalorientation is false on the carousel view it won't let me scroll left and right

### ISSUE THREAD

**Issue by brettnguyen** [AndreiMisiukevich/CardView#423]
how can I fix this. it seems to only be on iOS

**Comment by AndreiMisiukevich** [comment]
Hi Brett
Sorry to hear that you are running into an issue with the package.
Honestly speaking, this control was never designed to work with so complex scenarios.
I really don't know what can help you.

Maybe try to set OppositePanDirectionDisablingThreshold to 0

**Comment by brettnguyen** [comment]
I’ll try this out but is there any chance you can point me in the direction
of the logic you have for itemappearing and itemdisappearing so I can
attempt to create my own custom carouselview for my project?

**Comment by AndreiMisiukevich** [comment]
@brettnguyen since this is an open-source library. The entire code is open :)
Everything you need is in this file https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs

**Comment by AndreiMisiukevich** [comment]
I don't think this will be ever fixed unless someone wants to contribute
