### ISSUE TITLE
Carousel content overlaps bounds - second card only, iOS

### ISSUE THREAD

**Issue by garnelsoftware** [AndreiMisiukevich/CardView#424]
Hi Andrei, thank you so much for your fantastic plugin - I'd be lost without it and I've benefited hugely from it since launching my first app in 2020.

I have an app regression occurring whereby the layout for my carousel view is overlapping its bounds but only when:
- the device is iOS
- the second card is displayed (1st and Nth card display fine)

I setup the template layout when the constructor is called and also when the carousel view size is changed (upon rotate).
No noticeable layout events fire when we show the second card and forcing the layout to redraw upon each card appearing does not work.

Android is rock solid across platforms.

Please help!

Tom

**Comment by AndreiMisiukevich** [comment]
Hi Tom, thanks for your warm words! 

Can you try calling it `carousel.ForceRedrawViews()`.
Also, can you build a small sample?

**Comment by garnelsoftware** [comment]
Hi Andrei,

Great to hear from you, I shall try to get an example prepared.

Many thanks,

Tom

**Comment by garnelsoftware** [comment]
Andrei,

For a minute there I thought that had fixed it but I have at least narrowed
it down to a more specific scenario.
It's only happening when I use the "next" button which does only one thing:
update the carousel selected index.
If I swipe the control instead then the layout is correct!

Sorry I've still not had time to prepare an example.

Tom

**Comment by garnelsoftware** [comment]
I forgot to add that it's actually not restricted to landscape either.

I hadn't realised that on a phone  where I tended to use portrait I would
swipe but on tablet, I'd use landscape and tended to use the buttons!

**Comment by AndreiMisiukevich** [comment]
@garnelsoftware hmm, interesting. You can try to implement your own arrows and use SelectedItem instead of SelectedIndex.

**Comment by garnelsoftware** [comment]
Thanks Andrei,

After looking at the implementation of SelectedItem I feel that it will do
the same as SelectedIndex.

I have just tried calling carousel.OnSwiped(PanDirection) in place of the
index modification and the same display glitch occurs...

ForceRedrawViews caused the app to crash and so I abandoned that idea.

**Comment by AndreiMisiukevich** [comment]
@garnelsoftware try to call ForceRedrawViews in Main thread

**Comment by garnelsoftware** [comment]
I gave it a go but it made no difference. I best get that sample ready for
you!

Thanks for your help thus far!

**Comment by garnelsoftware** [comment]
Andrei,

I decided to take a step back and grab all of my view model bound height
and widths in the constructor and store them in fields. Then when the
layout method was invoked later in the constructor or upon rotate I could
guarantee the only thing that would change would be the width/height of the
page.

This seems to have fixed my issue! I think what was happening is that the
view model values were not always set when I expected them to and so
sometimes the sizes would differ and throw the layout out of kilter.

Sorry about all of that.

Once again thank you for your excellent plugin AND thank you so much for
providing me with support.

Many thanks,

Tom

**Comment by AndreiMisiukevich** [comment]
Thanks Tom!
