### ISSUE TITLE
[iOS] Unable to convert Microsoft.Maui.Handlers.ContentViewHandler to UIKit.UIView

### ISSUE THREAD

**Issue by eyeveye** [AndreiMisiukevich/CardView#425]
Main page contain CarouselView which has a collection of ContentView on it.
No problem on displaying and swiping it.

However, when navigating to other page Shell.Current.GoToAsync(xxx), it will throw error:
"Unable to convert Microsoft.Maui.Handlers.ContentViewHandler to UIKit.UIView"

When I commented out the CarouselView, and it will allow me to navigate without error.

This only occur in iOS.

<img width="597" alt="Screenshot 2023-10-17 at 1 40 47 AM" src="https://github.com/AndreiMisiukevich/CardView/assets/63999994/4cb9005a-f0a8-4ecc-8b7d-4a5029290d46">

<img width="1153" alt="Screenshot 2023-10-17 at 1 38 54 AM" src="https://github.com/AndreiMisiukevich/CardView/assets/63999994/ab507eb4-cdec-4106-b68d-252d91c80231">

**Comment by AndreiMisiukevich** [comment]
hi
This library is for XamarinForms
For .NET MUI you should use that one https://github.com/AndreiMisiukevich/CardView.MAUI
