### ISSUE TITLE
IndicatorsControl item size

### ISSUE THREAD

**Issue by garnelsoftware** [AndreiMisiukevich/CardView#426]
Hi Andrei,

As I always say, great plugin it's made all the difference to my app but I'd like to know how to shrink the size of the items in the indicators control. 

Sometimes I'll have as few as 8 items and as much as 26 so to stand a chance of it fitting I'd either need smaller circles displayed or some sort of progress bar style.

Do you have any advice for me?

Thanks!

**Comment by AndreiMisiukevich** [comment]
Hi @garnelsoftware 

`IndicatorsControl` has a property ItemTemplate.
`IndicatorItemView` has a few props also.

```xaml
<controls:IndicatorsControl>
  <controls:IndicatorsControl.ItemTemplate>
    <DataTemplate>
      <controls:IndicatorItemView Size="2" />
    </DataTemplate>
  </controls:IndicatorsControl.ItemTemplate>
</controls:IndicatorsControl>
```

Also, you can consider putting IndicatorsControl into ScrollView or maybe even building your own  IndicatorsControl

**Comment by garnelsoftware** [comment]
Excellent as always, thank you so much!
