### ISSUE TITLE
After migrating in NET 8 carousel view is not working

### ISSUE THREAD

**Issue by ketakidevendra** [AndreiMisiukevich/CardView#427]
In iOS it is not vertically scrolling and in android it is not visible at all.
Used latest nuget package - 0.0.5 that has .net8 support.
Controls inside carousel view are not clickable

**Comment by AndreiMisiukevich** [comment]
Have you tried 0.0.4?

**Comment by ketakidevendra** [comment]
0.0.4 was working well with .net7
After moving to .net 8 it stopped working so I moved to 0.0.5 and it is still not working.

**Comment by AndreiMisiukevich** [comment]
it's a wrong repo :) This plugin is for Xamarin.Forms

https://github.com/AndreiMisiukevich/CardView.maui
