### ISSUE TITLE
 IndicatorsControl Navigation Issue

### ISSUE THREAD

**Issue by mikkdev** [AndreiMisiukevich/CardView#428]
**Description:**
When either IsPrevItemPanInteractionEnabled or IsNextItemPanInteractionEnabled is set to false, the expectation is that navigation to previous or next items should be disabled. However, even with these properties set to false, it is still possible to navigate through the IndicatorsControl , which should not be allowed.

This behavior contradicts the intended design of disabling user navigation when pan interaction is turned off.

Steps to Reproduce:
- Set up a project using the CardView control with an associated IndicatorsControl.
- In the properties of CardView, set:
IsPrevItemPanInteractionEnabled = false
OR/AND IsNextItemPanInteractionEnabled = false
- Try to swipe or pan to the next or previous items (as expected, panning is disabled).
- Attempt navigation using the IndicatorView (the navigation remains possible, which is unintended).

.net MAUI (.net 8)

**Comment by AndreiMisiukevich** [comment]
Oh, wow
why is it closed?
