### ISSUE TITLE
Sizing carousel view to full width without weird margins

### ISSUE THREAD

**Issue by 2092015** [AndreiMisiukevich/CardView#43]
For example 
In Iphone emulator 2436x1125 i need to specify a height of ~250px
In Android device 782x480 i need to specify a height of ~215px

Something weird in iphone emulator for example, with 1125px width, for the image to fully cover horizontally no way the carousel should have less than ~500px height while testing it needs ~250px height.

**Comment by AndreiMisiukevich** [comment]
Did you try to change aspect of image?
Aspect.Fill etc

**Comment by AndreiMisiukevich** [comment]
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.aspect?view=xamarin-forms
--

I hope, it will help you.
Point is that isn't CardsView issue.. this is something with image settings

**Comment by AndreiMisiukevich** [comment]
Contact me pls after trying this way
