### ISSUE TITLE
CardsViewRenderer ObjectDisposed crash

### ISSUE THREAD

**Issue by JTOne123** [AndreiMisiukevich/CardView#49]
The same, I cannot reproduce

Maybe you have ideas...

CardsViewRenderer.OnTouchEvent (Android.Views.MotionEvent e)
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Android.Views.GestureDetector'.
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeVirtualBooleanMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
GestureDetector.OnTouchEvent (Android.Views.MotionEvent ev)
CardsViewRenderer.OnTouchEvent (Android.Views.MotionEvent e)
View.n_OnTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e)
(wrapper dynamic-method) System.Object.269ac379-00f3-45e2-9cb9-b16ea4332fe7(intptr,intptr,intptr)

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView.Droid/CardsViewRenderer.cs#L57

This is the line of code, where crash occurs.
Well, this is Xamarin.Forms bug, i believe, but we can catch this exception and recreate gestureDetector.
What do you think?

**Comment by JTOne123** [comment]
Yep, it looks the android part and the fix does not affect other platforms.
We differently should try

**Comment by AndreiMisiukevich** [comment]
Hope it will be enough
This fix will appear in next release
For now, you can copy this renderer to your project)

**Comment by JTOne123** [comment]
thank you!
