### ISSUE TITLE
View indicator

### ISSUE THREAD

**Issue by grantwardle** [AndreiMisiukevich/CardView#5]
Is there anyway to add a view indicator to this to see what page you're on?
I can't find any code for it however all other views have them included

**Comment by AndreiMisiukevich** [comment]
@grantwardle Hi
I thought that it was redundant feature, because everybody are able to add it himself
Because there are a lot of types of indicator (circle, square, some image... etc.)

But if you want, I can implement it =) It will be circles only

**Comment by grantwardle** [comment]
Circles are perfect, I can’t find any implementation fit them any where.


Grant Wardle
Chief Executive Officer
Newcastle-Under-Lyme • Staffordshire, United Kingdom 
AWSCO
  +44 78273 44868
  +44 74022 77106
  grantwardle@awsco.co.uk
  www.awsco.co.uk

**Comment by AndreiMisiukevich** [comment]
@grantwardle Okay) I see
I will implement it soon, i hope. Then I contact you for getting feedback

Thanks for your reaction!

**Comment by grantwardle** [comment]
That’s great!

Thank you very much 


Grant Wardle
Chief Executive Officer
Newcastle-Under-Lyme • Staffordshire, United Kingdom 
AWSCO
  +44 78273 44868
  +44 74022 77106
  grantwardle@awsco.co.uk
  www.awsco.co.uk

**Comment by AndreiMisiukevich** [comment]
@grantwardle Hi)
I will push new version soon) You can check sample now, there is an update by your issue :)

**Comment by grantwardle** [comment]
Thank you very much! 


Grant Wardle
Chief Executive Officer
Newcastle-Under-Lyme • Staffordshire, United Kingdom 
AWSCO
  +44 78273 44868
  +44 74022 77106
  grantwardle@awsco.co.uk
  www.awsco.co.uk

**Comment by AndreiMisiukevich** [comment]
@grantwardle 
I updated package. Check version 1.3.0) Also look through [Readme](https://github.com/AndreiMisiukevich/CardView/blob/master/README.md) 

if you like this package, please, set star on this repository) I will be grateful!
