### ISSUE TITLE
Xamarin.Forms.Xaml.XamlParseException: Position 189:26. Type cards:CarouselView not found in xmlns clr-namespace:PanCardView;assembly=PanCardView

### ISSUE THREAD

**Issue by rexconcepcion** [AndreiMisiukevich/CardView#50]
Hi, 

It is ok during designing but when I run the application I am getting this error. 
Xamarin.Forms.Xaml.XamlParseException: Position 189:26. Type cards:CarouselView not found in xmlns clr-namespace:PanCardView;assembly=PanCardView

btw I am using Xamarin.Forms.3.1.0.583944

**Comment by AndreiMisiukevich** [comment]
Show please whole xaml markup

**Comment by AndreiMisiukevich** [comment]
I think, this is something with your visual studio..(

**Comment by thedjnova** [comment]
Have you added cards as a xmlns on the page/views root element?

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/42517310-11977ce0-8468-11e8-9680-4f5cb11c39dd.png)

oh) but you declare Items property two times..

**Comment by rexconcepcion** [comment]
I clean the xaml file and set the Sample as the main page, clean, rebuild, and  still getting the error.
I already restarded vstudio. 

Type cards:CarouselView not found in xmlns clr-namespace:PanCardView;assembly=PanCardView

```
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             xmlns:cards="clr-namespace:PanCardView;assembly=PanCardView" 
             x:Class="ExceedMobile.Sample">
    <ContentPage.Content>
        <StackLayout>
            <cards:CarouselView 
                SlideShowDuration="3000" >
                 <cards:CarouselView.Items>
                        <x:Array Type="{x:Type View}">
                            <ContentView>
                                <Image Source="approve.png"/>
                            </ContentView>
                            <RelativeLayout>
                                <Button Text="Click" />
                            </RelativeLayout>
                            <StackLayout>
                                <Label Text="any text"/>
                            </StackLayout>
                        </x:Array>
                </cards:CarouselView.Items>
            </cards:CarouselView>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

**Comment by AndreiMisiukevich** [comment]
hmm, try to remove package from the solution
Remove all bin and obj folders
install package again (into all projects)

**Comment by rexconcepcion** [comment]
Removed Package
Removed Bin and Obj folders
Install CardsView Package 

I am still getting the same error.

Theres no problem during design time. Usually the IDE will detect if the Type is not found during design time and there is no error there. It is only during the run time that error shows up.

**Comment by AndreiMisiukevich** [comment]
@rexconcepcion could you try with code?
I'm sure, it's VS error.. because I have no such error on VS for Mac

**Comment by AndreiMisiukevich** [comment]
Send me small sample with this error, please. I will try it on my VS for mac

**Comment by AndreiMisiukevich** [comment]
Probably, this is the reason of our headache

```xml
    <!--Net Standard-->
    <file src="PanCardView\bin\Release\PanCardView.dll" target="lib\netstandard1.0\PanCardView.dll" />

    <!--Core PCL-->
    <file src="PanCardView\bin\Release\PanCardView.dll" target="lib\portable-win+net45+wp80+win81+wpa81\PanCardView.dll" />
``

**Comment by AndreiMisiukevich** [comment]
@rexconcepcion  Did you resolve this issue?

**Comment by AndreiMisiukevich** [comment]
try latest PRE-release version https://www.nuget.org/packages/CardsView/1.5.0-netstandard2.0-possible-fix

if issue is still reproducing, reopen this issue please

**Comment by thedjnova** [comment]
I use .Net Standard 2 already and everything is fine.

**Comment by AndreiMisiukevich** [comment]
@thedjnova very-very strange issue..

**Comment by requenaxii** [comment]
I'm facing the same issue right now, I tried with latest release and 1.5.0-netstandard2.0-possible-fix and still happens. 

Was working until I updated Visual Studio for Mac elements to the latest version due requirement this noon... any clue?

**Comment by AndreiMisiukevich** [comment]
Try to create it from code

**Comment by Eldin66** [comment]
For some reason I had this problem as well, just on iOS. I 'fixed' it by calling CardsViewRenderer.Preserve() in AppDelegate.

**Comment by AndreiMisiukevich** [comment]
@Eldin66 yeah, i added this step to setup section :)

**Comment by Unlonlyness** [comment]
This is amazing !
 I had the problem on iOS.  When I call the CardsViewRenderer.Preserve() in AppDelegate.
The problem has gone.

**Comment by AndreiMisiukevich** [comment]
@Unlonlyness cool
