### ISSUE TITLE
How to use this ??

### ISSUE THREAD

**Issue by marcelinhovt** [AndreiMisiukevich/CardView#51]
I added the Nuget and trying to use on XAML. But i am not getting where is the "cards:CarouselView". What do i have to declair to get this assembly ?

<cards:CarouselView  >

**Comment by marcelinhovt** [comment]
Sorry !! Now, its working...the Nuget didn´t install on the main project. Now, its working.

**Comment by marcelinhovt** [comment]
Sorry guys... my images are not appearing.
I need to set some images to a list and show them on carouselview. 1 sec wich one, scrolling automatic. How to do this ?

Thanks

**Comment by AndreiMisiukevich** [comment]
Hi, did you look through the samples?

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardViewSample/PanCardViewSample/Views/CarouselSampleXamlView.xaml

I suggest you to use FFImageLoading plugin for images instead of native xamarin Image

**Comment by marcelinhovt** [comment]
Yes...and i did exactly...but instead of ffimage i used the native image.
Its showing blank.
I will try with the ffimage

Em quinta-feira, 12 de julho de 2018, Andrei <notifications@github.com>
escreveu:

**Comment by AndreiMisiukevich** [comment]
reopen this issue, if you face with troubles =)
