### ISSUE TITLE
Size only settles after first SizeChanged event

### ISSUE THREAD

**Issue by deakjahn** [AndreiMisiukevich/CardView#55]
Well, I don't know where the problem is. :-) I received both updates at the same time, yours (1.4.9) and the latest Xamarin Forms (3.1.0.637273). On UWP, all pages that have a CardView on them are a bit oversize, meaning that the bottom 40-50 pixel high strip isn't visible at first (for instance, where we usually put the indicator control). As soon as I move the main window size a little bit, everything snaps into place and works all right.

I know this is pretty vague but before I try to go any further, you might have a hunch based on what you changed in the last upgrade. :-)

**Comment by AndreiMisiukevich** [comment]
Hi)
So, on 1.4.8 you didn't see this issue, right?
---
If it is true, I will validate my changes for sure, but unfortunately I have only Mac in my own and won't be able to make sure in resolving the problem :(

**Comment by AndreiMisiukevich** [comment]
Could you please check the problem with previous version of Xamarin?

**Comment by AndreiMisiukevich** [comment]
Three commits between 1.4.8 and 1.4.9

https://github.com/AndreiMisiukevich/CardView/commit/24334b7619a2f215be6c9c5f7fd72c5a9b2e05db

https://github.com/AndreiMisiukevich/CardView/commit/113fc07f795ad7cca3d1a2920d57dbfb57856d24

https://github.com/AndreiMisiukevich/CardView/commit/e0ed6437dd0249d3d6754d8108dde172767cca7c

So, I'm sure, that it is Xamarin.Forms issue. Validate this case with previous version of Xamarin.Forms

Guys, i need help with this issue, because I haven't got windows PC/Laptop :(

**Comment by AndreiMisiukevich** [comment]
I would be grateful, if you are able to check this case.. or debug my project
Probably, you can suggest any workaround for the time being ? :)
I will appreciate any help )

**Comment by AndreiMisiukevich** [comment]
@deakjahn did the trick help?

**Comment by deakjahn** [comment]
Sorry, I didn't get notification.

Yes, I'm suspecting XF, too, but for some reason I only found the problem on pages that have cards as well. But this must be a coincidence somehow.

**Comment by AndreiMisiukevich** [comment]
try this please >> Maybe it will be enough to set HeightRequest for CarouselView and for each card.. ?

**Comment by AndreiMisiukevich** [comment]
well, try to work around with setting HeightRequest, calling ForceLayout etc.. obviously it's XF issue =(
I will close this issue, but if you find work around, leave it here for other guys =)

**Comment by deakjahn** [comment]
Yes, sure that helps but in normal life, I don't know how high it would need to be. :-)

I reported it on the XF issue queue, we'll see. And I returned to the previous XF while I bumped up yours to 1.5.0 so it's definitely a XF issue now.
