### ISSUE TITLE
Very slow and infinite cycle. Use it in xaml

### ISSUE THREAD

**Issue by VadyaVL** [AndreiMisiukevich/CardView#6]
Hello. I'm using a not very complicated template. However, your component is running slowly with it.
I would like to see the possibility of easy use in xaml (without CardViewItemFactory, use DataTemplate).
Also, when we initialize an empty list, we have an infinite loop (see CardsView.cs line 1066).
if index = 0 and _itemsCount = 0
0 >= 0
0 -= 0
........ infinite

**Comment by AndreiMisiukevich** [comment]
As for first remark.. DataTemplate just creates Views, with this, we will lose ability to cache views

As for second - I will check it

**Comment by AndreiMisiukevich** [comment]
@VadyaVL haha) it's my bad, that I haven't implemented view creator via DataTemplate)
I overthought in this case, but you opened my eyes)

Thanks!

**Comment by AndreiMisiukevich** [comment]
Check 1.2.9 version pls

**Comment by AndreiMisiukevich** [comment]
@VadyaVL Have you checked it yet?)

**Comment by AndreiMisiukevich** [comment]
@VadyaVL if you like this package, please, set star on this repository) I will be grateful!
