### ISSUE TITLE
How to get the Tap gesture on the Cards image?

### ISSUE THREAD

**Issue by marcelinhovt** [AndreiMisiukevich/CardView#60]
I tried the code above and didn´t work. I have a class and the image is a property of the class. I need to get it. 
Can you help me ?

```
<cards:CarouselView.GestureRecognizers>
                    <TapGestureRecognizer Tapped="OnTapGestureRecognizerTapped" NumberOfTapsRequired="1" />
                </cards:CarouselView.GestureRecognizers>
```

When using this, i just get the image obviouslly!!

**Comment by AndreiMisiukevich** [comment]
Hi @marcelinhovt. You should add tapGesture to each your CARD, but you tried to add it into the main carousel view. Check the code below =)


```xml
    <cards:CarouselView 
        <cards:CarouselView.ItemTemplate>
            <DataTemplate>
                <ContentView> //YOUR CARD
                    <ContentView.GestureRecognizers>
                        <TapGestureRecognizer Tapped="Handle_Tapped"/>
                    </ContentView.GestureRecognizers>
                </ContentView>
            </DataTemplate>
        </cards:CarouselView.ItemTemplate>
    </cards:CarouselView>
```
and code behind

```csharp
void Handle_Tapped(object sender, System.EventArgs e)
		{
			
		}
```

It works fine for me)

P.S. I will appreciate, if you STAR this repository )

**Comment by marcelinhovt** [comment]
Thaaaaankss bosssss ! I gave a star...

**Comment by marcelinhovt** [comment]
![sem titulo](https://user-images.githubusercontent.com/17338668/42974719-c864b046-8b8e-11e8-812a-fa94954a1a56.png)

**Comment by AndreiMisiukevich** [comment]
@marcelinhovt yes, because you need to get BindingContext of your sender

```csharp
var view = sender as View;
var context = view as Slides;
```

**Comment by AndreiMisiukevich** [comment]
Hi, I just release 1.5.3 version (I refactored names and added one useful event)

So, now you can use ItemTapped event =)

**Comment by marcelinhovt** [comment]
Thanks bosssss.

**Comment by marcelinhovt** [comment]
My friend. The tap gesture is not recognizing 100%. Some times I tap, but no action happens on debug.

So, i tried to update to the new stable release, but its crashing my app. 
I changed the Items for ItemSource and CurrentIndex for SelectedIndex, but its crashing. Appeared the message "System.MissingMethodException: void PanCardView.CardsView.set_SelectedIndex(int)"
I am trying to put the index when the page initialize, but is not making any difference.

**Comment by AndreiMisiukevich** [comment]
- remove package from all projects
- delete all bin and obj folders
- close VS
- open VS
- install package again

**Comment by AndreiMisiukevich** [comment]
@amrkamal1993 did you check BindingContext of TapGesture holder?
I think, you missed something. Probably, you needed to set x:Reference binding

**Comment by amrkamal1993** [comment]
It works fine if i implement this in cs .. otherwise if i implement the same using mvvm Bindning it doesn't work

**Comment by AndreiMisiukevich** [comment]
@amrkamal1993 show your xaml/code

**Comment by amrkamal1993** [comment]
<cards:CarouselView  Grid.Row="0" IsViewCacheEnabled="True" Grid.Column="0" Padding="0" HorizontalOptions="FillAndExpand" Margin="0" 
        ItemsSource="{Binding Imageslst}"
        SlideShowDuration="3000">
                                    <cards:CarouselView.ItemTemplate>
                                        <DataTemplate>
                                            <ContentView>
                                                <ContentView.GestureRecognizers>
                                                    <TapGestureRecognizer Command="{Binding GoToItem}"/>
                                                </ContentView.GestureRecognizers>
                                                <ffimageloading:CachedImage  Aspect="Fill" HeightRequest="350"  Margin="0" VerticalOptions="Fill" HorizontalOptions="Fill" Source="{Binding ImageUrl}">
                                                  
                                                </ffimageloading:CachedImage>
                                            </ContentView>
                                        </DataTemplate>
                                    </cards:CarouselView.ItemTemplate>

                                    <controls:IndicatorsControl ToFadeDuration="1500"/>
                                </cards:CarouselView>
