### ISSUE TITLE
XA0106 warnings in Adroid project

### ISSUE THREAD

**Issue by deakjahn** [AndreiMisiukevich/CardView#62]
Right now I have 38 warnings: "Skipping .... Please check that your Nuget Package versions are compatible". These are supposed to be XA0106 warnings but VS fails to show a code and, consequently, they can't be disabled, either. But all items mentioned in the warnings come from CardView. You should bump up the support package versions, I suppose.

CardsView: 1.5.5
XF: 3.1.0.583944 (I know there is a newer one but it breaks important things so it can't be installed. Anyway, this has no bearing on this particular issue).
XA support libraries: 27.0.2.1

**Comment by deakjahn** [comment]
Warning		Skipping XXX.Droid.Resource.Id.withText. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Styleable.ActionMenuView. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.useLogo. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.SYM. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.snap. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.showTitle. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.showHome. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.showCustom. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.SHIFT. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.scroll. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.never. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.middle. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.META. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.ifRoom. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.homeAsUp. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.FUNCTION. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.fill_vertical. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.fill_horizontal. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.exitUntilCollapsed. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.enterAlwaysCollapsed. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.enterAlways. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.disableHome. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.CTRL. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.collapseActionView. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.clip_vertical. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.clip_horizontal. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.center_vertical. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.center_horizontal. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.beginning. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.always. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.ALT. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Id.all. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Drawable.avd_show_password_3. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Drawable.avd_show_password_2. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Drawable.avd_show_password_1. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Drawable.avd_hide_password_3. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Drawable.avd_hide_password_2. Please check that your Nuget Package versions are compatible.	XXX.Android			
Warning		Skipping XXX.Droid.Resource.Drawable.avd_hide_password_1. Please check that your Nuget Package versions are compatible.	XXX.Android

**Comment by AndreiMisiukevich** [comment]
So, do you want to create PR with fix ?)

**Comment by deakjahn** [comment]
Never created a nugget in me life. Do you think it would be wise to wait for it now? ;-))

**Comment by AndreiMisiukevich** [comment]
Any ideas?

**Comment by deakjahn** [comment]
I'm trying to identify what commit solved the issue for other packages (these warning are to be found everywhere, many other packages complained about it). As far as I can tell, but I'm not yet finished investigating, the XF version number should be changed to something up-to-date.

**Comment by deakjahn** [comment]
This seems to be a relevant comment: https://forums.xamarin.com/discussion/comment/272488/#Comment_272488

In .Droid/packages.config the support packages seem to be rather new but the XF is terribly old. Is this necessary for some reason?

**Comment by AndreiMisiukevich** [comment]
backwards compatibility

So, what do you suggest? Update XF to latest version?

**Comment by AndreiMisiukevich** [comment]
I read that comment, and there we knew, that the reason can be XA support packages, but cardsView package has got latest XA.. Do you think, that we should update XF package too?

**Comment by deakjahn** [comment]
Huh, that's why I said I never built a Nuget package for Xamarin. :-) I grabbed a package now just to see, FFImageLoading, just to look into it and XF versions are up-to-date. So, I'm not sure backwards compatibility really depends on this. But I really don't want to be reponsible for ruining this. :-)

If you might be able to make a test, bring everything up to-date and put it up as a prerelease, not a real one so that I can try it without causing problems for people using it out there? I don't know of other ways to really try it, do you?

**Comment by AndreiMisiukevich** [comment]
Hm, sure, I can create prerelease package (You will be able to updated it via local nuget storage.. or you want to receive it from alpha channel?

**Comment by deakjahn** [comment]
I found one SO reference to a local Nuget store but I never tried it out before. Might be worth a try.

**Comment by AndreiMisiukevich** [comment]
Yes, exactly
I will create the package for you today's evening

**Comment by deakjahn** [comment]
OK, thanks, I'll try to look back from time to time. GitHub doesn't seem to send out notifications, although I have them enabled for sure.

**Comment by AndreiMisiukevich** [comment]
@deakjahn forgive me please =( I will do it today ( i was very busy yesterday

**Comment by AndreiMisiukevich** [comment]
@deakjahn hi

https://drive.google.com/open?id=1EnD1LvwpwkpIn2TU78xWyuyj2XqOaXFI

**Comment by deakjahn** [comment]
Well, I don't, know, the same warnings. :-(

I can't check what gets compiled into the DLL but the .nuspec still references XF 2.4. If that has got anything to do with it at all, I don't know...

**Comment by deakjahn** [comment]
Oops, now they disappeared after the third build. This IntelliSense is really a pain. Let's see if it stays that way.

**Comment by AndreiMisiukevich** [comment]
I think, it's something with you visual studio =(

**Comment by deakjahn** [comment]
Everything's possible. Still, currently, CardsView is the only Nuget package that shows this behavior. :-)

It became much better, just not perfect (and that's the strangest part of it). I don't have the warnings most of the time, still, sometimes they reappear and linger on until about the first full Android rebuild. Yes, I cleared the .vs folder, more than once.

So, in the end, I can't see anything going wrong because of this modification, so you might keep it as a prerelease and if it doesn't harm other people, I suggest you leave it this way. Thanks.

**Comment by AndreiMisiukevich** [comment]
Cool, i will create prerelease package at weekend, i think

**Comment by AndreiMisiukevich** [comment]
Latest XF breaks one of my sample) EmbeddedViewSample
But it isn't matter, i'm sure, that updating packages in sample doesn't affect your project.
Because the plugin uses that version of forms, which is used by your code =)

I'm not going to update forms in my samples now.. maybe later

-- .nuspec still references XF 2.4

It means, that XF 2.4 is lowest supported version =)

**Comment by deakjahn** [comment]
The latest XF breaks more than one thing, apparently. :-) I'm waiting for that navigation trouble to be fixed, too. The one we were not sure whether it's Card or XF initially but it's XF all right.

**Comment by AndreiMisiukevich** [comment]
@deakjahn btw, if you like this plugin, you may set star on the project)

**Comment by MarkTRooney** [comment]
I added a 'throw-away' resource to my resources folder, recompiled, and the warning went away.  Apparently Android needed to rebuild the Resource designer to bring in the updated packages.

**Comment by AndreiMisiukevich** [comment]
@MarkTRooney thanks :)
