### ISSUE TITLE
Error	XLS0503 Error in CarouselSampleEmbeddedView

### ISSUE THREAD

**Issue by AlfredoSolisFrausto** [AndreiMisiukevich/CardView#63]
When open CarouselSampleEmbeddedView.xaml appear the error XLS0503: A value of type 'ArrayExtension' cannot be added to a collection or dictionary of type 'IList'. It does not prevent the execution, however it's problematic to work with de xaml code looking at the whole page underlined.

**Comment by AndreiMisiukevich** [comment]
Hi @AlfredoSolisFrausto 
It's good point, i think.
I will have to change type of ItemsSource property to IEnumerable and create additional private property for internal needs =)

**Comment by AndreiMisiukevich** [comment]
@AlfredoSolisFrausto try it now please

**Comment by AndreiMisiukevich** [comment]
I don't know, why this issue appears at your machine. Probably, you use Win PC/Laptop.. because on Mac it works fine

**Comment by AndreiMisiukevich** [comment]
if you like this plugin, you can set star on the project)

**Comment by AlfredoSolisFrausto** [comment]
Yeah, you have my star!
