### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by IgorPopov56** [AndreiMisiukevich/CardView#65]
Hi. Are you going to implement RTL support in CarouselView in nearest future?
For example, I set "FlowDirection" to "RightToLeft" and in this way items in carousel will revert theirs positions. "SelectedIndex == 0" would be the rightest item in Carousel. Also it would be first shown. Thanks for response =)

**Comment by AndreiMisiukevich** [comment]
Hi @IgorPopov56 
Good question, I haven't thought of it yet

**Comment by AndreiMisiukevich** [comment]
How does  this plugin behave now if you set FD to RTL ?)

**Comment by IgorPopov56** [comment]
@AndreiMisiukevich The property affects the content of each slide, but doesn't affect the actual Carousel.

**Comment by AndreiMisiukevich** [comment]
@IgorPopov56 there is one small trouble
Now this package support XF from 2.4, but RTL appeared at 3.0, as I know..
Any ideas, how can we work around?.. only one idea - to use reflection for determining, whether control contain FD property and is's RTL..

**Comment by IgorPopov56** [comment]
@AndreiMisiukevich Yeah... Can't come up now with the good solution. Indeed, on my mind only reflection.

**Comment by AndreiMisiukevich** [comment]
hmm, maybe OnPropertyChanged can help us too =)

**Comment by AndreiMisiukevich** [comment]
Yes, I will try, but only at weekend

**Comment by AndreiMisiukevich** [comment]
Maybe, anybody wants to assist me according to this issue?

**Comment by IgorPopov56** [comment]
Ok. Thanks ;)

**Comment by IgorPopov56** [comment]
@AndreiMisiukevich "Maybe, anybody wants to assist me according to this issue?"
I can. Which type of help you need?

**Comment by AndreiMisiukevich** [comment]
How should we implement this feature?)

So, first items is on the right side and it still has 0 index
by swiping left cardsView should increment its index..
How can we do it without dozens of checks / tricks etc. I want to find pretty way)

**Comment by IgorPopov56** [comment]
@AndreiMisiukevich I didn't see source code of plugin. I need time to investigate your current implementation. Maybe after that I can propose some way.

**Comment by AndreiMisiukevich** [comment]
**IsRightToLeftFlowDirectionEnabled** - use this property for achieving such feature)

**Comment by IgorPopov56** [comment]
@AndreiMisiukevich Hi =) Thanks for enhancement. But there is a bug with indicators. Selected indicator is left when IsRightToLeftFlowDirectionEnabled=true. But should be the right one.

**Comment by AndreiMisiukevich** [comment]
@IgorPopov56 great point ) I forgot about it..
create bug please
