### ISSUE TITLE
Improvement proposal

### ISSUE THREAD

**Issue by AlfredoSolisFrausto** [AndreiMisiukevich/CardView#67]
Hi again, I have a proposal for you, using the cardview, I find it very useful be able to use IsCurrent (TabView) as BindableProperty to bind his value to a ViewModel. Also, it would be very useful include a IsVisible property to can control the flow in the interaction. I hope you understand my english.

**Comment by AndreiMisiukevich** [comment]
IsCurrest - is a property for determining, whether card is selected now, right?
And IsVisible - is a property for determining, whether we need to display this card or should skip..

If i understood you, i think, it's redundant / specific logic, which you are able to realize if you need =)
So, let's skip it for now
