### ISSUE TITLE
Memory accumulation or memory leak (FFImageLoading + PanCardView)

### ISSUE THREAD

**Issue by dblookup** [AndreiMisiukevich/CardView#68]
Hi everybody,

I am trying to use PanCardView and FFImageLoading (Xamarin Forms) to display pictures fullscreen.
Usually one image weighs about 1MB (format jpg) in 1920px.

I tried 100+ photos images but the app suddenly closes when it reaches the third image (Message Failed to Stop app: IDB410101).

By the way, this is only occurs on iOS (used an iPad). I tried CarouselView and CardsView.

I noticed that there is an accumulated memory consumption in the device, maybe some memory leak. When I put the images in low resolution (480px) the carousel runs longer (until tenth photos) and when I use 1920px, it does not reach the third image.

Thank you so much!

**Comment by AndreiMisiukevich** [comment]
Hi
This is very interesting

Did you try to use regular Xamarin Forms image instead of FFImage ?

**Comment by dblookup** [comment]
Hi Andrei,

Thank you for your prompt reply. I did not try it with simulator yet.

I just tried now with your suggest for insert 4 in MaxChildrenCount and DisiredMaxChildrenCount properties. It worked perfectly, I tried with +120 photos. I think that it was resolved.

Thank you so much for your assistance and congratulations for cardview.

**Comment by AndreiMisiukevich** [comment]
awesome :)
If you like this plugin, you may set 🌟 star on the repository)

**Comment by dblookup** [comment]
Sure, I did it.
Tks!
