### ISSUE TITLE
[Android]: FFImageLoading image appears too wide

### ISSUE THREAD

**Issue by deakjahn** [AndreiMisiukevich/CardView#69]
I have the following very simple layout. If I use a stock XF `Image`, everything is all right. If I use an FFImageLoading `CachedImage`, the image display will be wider than the carousel page, on both sides. This extra image strip will stay there when I swipe to another page, and won't go away until the next swipe touch.

    <cards:CarouselView Items="{Binding Categories}" VerticalOptions="FillAndExpand" IsViewCacheEnabled="True" MaxChildrenCount="4" DesiredMaxChildrenCount="4" IsCyclical="True" IsClippedToBounds="True">
      <cards:CarouselView.ItemTemplate>
        <DataTemplate>
          <ContentView>
            <Grid>
              <ff:CachedImage Source="{Binding imagePath}" Aspect="AspectFill" />
              or
              <Image Source="{Binding imagePath}" Aspect="AspectFill" />

The bitmap has a different aspect ratio than the page, so that's the bitmap that I can see to the left and right, no problem with that, but in the `Image` case it's cropped as normal using AspectFill.

**Comment by AndreiMisiukevich** [comment]
Hi, it seems to be Ffimageloading bug  https://github.com/luberda-molinet/FFImageLoading/issues/1086

@Daniel-luberda

**Comment by AndreiMisiukevich** [comment]
https://github.com/luberda-molinet/FFImageLoading/releases

Check release notes of 2.3.6
Perhaps, it can be useful to try to set FixOnMesureBehavior to false or try to enable/disable fast renderer

**Comment by deakjahn** [comment]
I tried another trick that seems to work: I put the FF image inside an extra Grid that has its dimensions bound to the page width and height. But this means that the bug should have been fixed already, we're at 2.4.3 now.

**Comment by AndreiMisiukevich** [comment]
Got it.. strange issue..

**Comment by deakjahn** [comment]
OK, the fast renderer seems to be the final culprit. Without it, there is no need for either the FixWhatever static field nor the extra Grid. Did you try without the fast one? I'll note it in Daniel's issue if that's the case.

**Comment by deakjahn** [comment]
I'm only allowed by GitHub to do that once. ;-))

**Comment by AndreiMisiukevich** [comment]
What a pity !)) Haha

**Comment by deakjahn** [comment]
Anyway, thanks for the help and nice catch, I wrote about it there (as I mentioned you, GH had to notify you by now).

**Comment by AndreiMisiukevich** [comment]
Very well!
