### ISSUE TITLE
[iOS] Swipe Crash CarouselView 1.5.6

### ISSUE THREAD

**Issue by BlackRamsis** [AndreiMisiukevich/CardView#74]
Hy, 

i used the Carousel with webviews in 1.5.0 and everything was fine. But in 1.5.6 i get a crash in iOS after about 10 swipes. (if i switch back to 1.5.0 everything is fine again)

I catched the bug with Hockeyapp  -> Collection <CALayerArray: 0x61000024c660> was mutated while being enumerated.'

**Comment by AndreiMisiukevich** [comment]
Hi @BlackRamsis thank you very much for your feedback
Could you please create small sample with this issue?

It means, that i need to lock something in additional palace..

**Comment by BlackRamsis** [comment]
i tried to reproduce this with an simple app, but the error is not showing. seems like  a race condition only happening while heavy load

**Comment by MaxenceMax** [comment]
since the new update, I have some lag and crashes to

**Comment by AndreiMisiukevich** [comment]
hmmm, how can we emulate it?

Maybe, you can download source code and debug it with your heavy project.
Probably, we can retrieve more info..

**Comment by AndreiMisiukevich** [comment]
and this issue too =)

**Comment by AndreiMisiukevich** [comment]
could you please update package step by step and tell me, what version breaks your app =)
It isn't very difficult, use binary search for it)

firstly check version 1.5.3, and 
if it's fine, check 1.5.2 - 1.5.1,
else check version 1.5.4 - 1.5.5

**Comment by AndreiMisiukevich** [comment]
@BlackRamsis any updates?)

**Comment by AndreiMisiukevich** [comment]
@BlackRamsis  upd.

**Comment by AndreiMisiukevich** [comment]
@BlackRamsis  upd.

**Comment by AndreiMisiukevich** [comment]
closed for now) i will reopen it, if you send me reproduction)
thx
