### ISSUE TITLE
Items are not disposed

### ISSUE THREAD

**Issue by BlackRamsis** [AndreiMisiukevich/CardView#75]
Hy,

i use the Carousselview with webviews. After someone swipes to the next page i use javascript to get the filter settings of the user. next time he comes back i set them again.

I use Safari/Chrome to test the javascript directly on the device via debugging. While doing this i have seen a strange behavior with the first items in the Caroussel

iOS:
When i open the Caroussel on position 0. i see the page from position 0 and 1.
if i swipe to position 1, i see the page from position 0 and twice position 1!
swipe to pos 2-> i see 0, 0, 1, 1, 2
swipe to pos 3-> i see 0, 0 ,1, 1, 2, 3
swipe to pos 4 ->i see 0, 0, 1, 2, 3 ,4
swipe to pos 5-> i see 0, 0, 1, 3 ,4, 5
swipe to pos 6-> i see 0, 0, 1, 4 ,5, 6
swipe to pos 7-> i see 0, 0, 1, 5 ,6, 7

little bit different for Android, but the first 2 pages stay always in memory
same in 1.5.0 and 1.5.6

btw good work with this control

**Comment by AndreiMisiukevich** [comment]
Could you try to set IsViewCacheEnabled = false ?

**Comment by BlackRamsis** [comment]
still the same

**Comment by BlackRamsis** [comment]
i set backviewdepth=1 and DesiredMaxChildrenCount = 1, now its working much better. Maybe after 20 swipes i see one page twice

**Comment by AndreiMisiukevich** [comment]
could you send me reproduction project?

**Comment by AndreiMisiukevich** [comment]
@BlackRamsis ?

**Comment by BlackRamsis** [comment]
Hy Andrei, sry i have alot to do at the moment. I hope i can create something next week

**Comment by AndreiMisiukevich** [comment]
@BlackRamsis i'm waiting )

**Comment by AndreiMisiukevich** [comment]
Video/Screenshots at least...

**Comment by AndreiMisiukevich** [comment]
@BlackRamsis any updates?

**Comment by AndreiMisiukevich** [comment]
closed for now) i will reopen it, if you send me reproduction)
thx
