### ISSUE TITLE
IndicatorsControl color?

### ISSUE THREAD

**Issue by reense** [AndreiMisiukevich/CardView#76]
Hello all,

Is there a way to make the color of the indicatorscontrol black?

**Comment by braulio-oc** [comment]
Hi you can define the style in the constructor, this is my sample

`var indicators = new IndicatorsControl
            {
                SelectedIndicatorStyle = new Style(typeof(Frame))
                {
                    Setters = {
                        new Setter { Property = BackgroundColorProperty, Value = Color.DarkGray.MultiplyAlpha(.8)},
                        new Setter { Property = WidthRequestProperty, Value = 3}
                    }
                },
                UnselectedIndicatorStyle = new Style(typeof(Frame))
                {
                    Setters = {
                        new Setter { Property = BackgroundColorProperty, Value = Color.LightGray.MultiplyAlpha(.5) },
                        new Setter {Property = WidthRequestProperty, Value = 2}
                    }
                },
                Margin = new Thickness(10, 0, 10, 7)
            };`

**Comment by AndreiMisiukevich** [comment]
@reense hi
Yes, for sure
https://github.com/AndreiMisiukevich/CardView/issues/54

**Comment by reense** [comment]
Thanks!!

**Comment by AndreiMisiukevich** [comment]
@reense if you like this plugin, you can support it by setting star on this repo ;)
