### ISSUE TITLE
[iOS] CarouselView inside PullToRefresh control

### ISSUE THREAD

**Issue by br-oc** [AndreiMisiukevich/CardView#77]
Hi, 

I use the carouselview inside of pulltorefresh control, in Android work as expected but on iOS don't!
I hope  some one can help me to find a solution.

Greatings!

**Comment by AndreiMisiukevich** [comment]
Hi @braulio-oc 
I will help you, for sure, if you provide me small sample, please )

**Comment by braulio-oc** [comment]
Thanks Andrei
Here is the repro, also use ParentScrollView inside 
 
[https://github.com/braulio-oc/CardViewInsidePullToRefresh](url)

Greatings

**Comment by AndreiMisiukevich** [comment]
Indeed, there is such issue.
It seems, PanGesture steals gestures from PullToRefreshLayout

I think, we should end with SwipeGesture, and it would be great work around https://github.com/AndreiMisiukevich/CardView/issues/72

**Comment by AndreiMisiukevich** [comment]
also, you can ask developers of that plugin, how can we solve this issue =)

**Comment by AndreiMisiukevich** [comment]
@braulio-oc does it work for iOS at all?
I tried with such markup

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:PruebaCarrucel"
             x:Class="PruebaCarrucel.MainPage"
             xmlns:controls="clr-namespace:PanCardView.Controls;assembly=PanCardView"
             xmlns:cards="clr-namespace:PanCardView;assembly=PanCardView"
             xmlns:controls2="clr-namespace:Refractored.XamForms.PullToRefresh;assembly=Refractored.XamForms.PullToRefresh">
    <controls2:PullToRefreshLayout
          IsPullToRefreshEnabled="True"
          RefreshCommand="{Binding RefreshCommand}"
          IsRefreshing="{Binding IsBusy}"
          RefreshColor="Blue">
            <StackLayout BackgroundColor="Red">
        </StackLayout>
    </controls2:PullToRefreshLayout>
</ContentPage>
```

And it didn't work

**Comment by AndreiMisiukevich** [comment]
Can you make it working without carouselView.
_
I added IsPanInteractionEnabled property (true by default).
If you make it working WITHOUT carouselView, try next steps

1) Instal latest pre-release package (1.5.8-pre1)
2) In AppDelegate call CardsViewRenderer.Preserve()
3) Set IsPanInteractionEnabled to false

**Comment by braulio-oc** [comment]
Yes, its work without CarouselView, I'll try repro yours steps and I'll report you my results 
Thansk Andrei
Greatings!

**Comment by br-oc** [comment]
Hi Andrei,

In the latest builds there is no PositionChanged and  OnCardCarouselAutoNavigationEnded, this events are very useful for me, How can I achieve the same behavior? 
I'm trying to implement your solution with IsPanInteractionEnabled 

Thanks Again!

Greatings!

**Comment by AndreiMisiukevich** [comment]
@br-oc yes, they were marked as obsolete some builds ago and recently were removed.

Now you should use these ones

public event CardsViewItemDisappearingHandler ItemDisappearing;
public event CardsViewItemAppearingHandler ItemAppearing;

**Comment by br-oc** [comment]
Hi, just reporting my results.

It Works!!!!

Here the sample:
[https://github.com/br-oc/CardViewInsidePullToRefresh](url)

Needs use a scrollview inside the pulltorefreshlayaout and the steps that you mention before

Greatings!!!

**Comment by AndreiMisiukevich** [comment]
@br-oc very well!
I will close this issue, it will be available as stable version soon

**Comment by AndreiMisiukevich** [comment]
you may use 1.5.8 version
