### ISSUE TITLE
RTL indicators bug

### ISSUE THREAD

**Issue by IgorPopov56** [AndreiMisiukevich/CardView#78]
There is a bug with indicators. Selected indicator is left when IsRightToLeftFlowDirectionEnabled=true. But should be the right one.

**Comment by AndreiMisiukevich** [comment]
Cool, i will fix it asap

**Comment by IgorPopov56** [comment]
Big thanks =)

**Comment by AndreiMisiukevich** [comment]
@IgorPopov56 you are welcome) you may star this repo)) it helps to support it)

**Comment by IgorPopov56** [comment]
Done =)
