### ISSUE TITLE
ParentScrollView doesn't work properly on the version 1.5.8 on iOS

### ISSUE THREAD

**Issue by grammatnMcK** [AndreiMisiukevich/CardView#79]
The scrolling function is working but not the swiping

**Comment by grammatnMcK** [comment]
The IsPanInteractionEnabled was blocking the swiping. Sorry :)

**Comment by AndreiMisiukevich** [comment]
@grammatnMcK no problem) enjoy it)

**Comment by AndreiMisiukevich** [comment]
@grammatnMcK hi
Could you please explain, what version was ok for you, and what version broke it?
Also, if it's possible, create small sample please

**Comment by grammatnMcK** [comment]
Hello Andrei,

in the 1.5.8 was ok and in 1.6.3 doesn't work anymore.
All what I have is a listview and the itemssource is getting filled with an ObservableCollection<IList<ImageSource>> . 

Is it a little more clear now?

**Comment by grammatnMcK** [comment]
I just created a new issue/question in a new thread because I think this was irrelevant. 

Thank you very much for the good work.
