### ISSUE TITLE
Crash on iOS: Name: NSInternalInconsistencyException Reason: Invalid parameter not satisfying: [views count] == 3

### ISSUE THREAD

**Issue by shoeIT** [AndreiMisiukevich/CardView#80]
Hello,
I'm evaluating your control and I'm using it more and more but I get this error sometimes:
Unhandled Exception:

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Invalid parameter not satisfying: [views count] == 3
Native stack trace:
	0   CoreFoundation                      0x0000000113f131e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000114ead031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000113f18472 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000110121652 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x000000010e978529 -[_UIQueuingScrollView _replaceViews:updatingContents:adjustContentInsets:animated:] + 1018
	5   UIKit                               0x000000010e97bec8 -[_UIQueuingScrollView _didScrollWithAnimation:force:] + 1157
	6   UIKit                               0x000000010e9773ff -[_UIQueuingScrollView layoutSubviews] + 179
	7   UIKit                               0x000000010df927a8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1515
	8   QuartzCore                          0x000000010c2bf456 -[CALayer layoutSublayers] + 177
	9   QuartzCore                          0x000000010c2c3667 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 395
	10  QuartzCore                          0x000000010c24a0fb _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 343
	11  QuartzCore                          0x000000010c27779c _ZN2CA11Transaction6commitEv + 568
	12  QuartzCore                          0x000000010c1c2613 _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 261
	13  QuartzCore                          0x000000010c304a12 _ZL22display_timer_callbackP12__CFMachPortPvlS1_ + 248
	14  CoreFoundation                      0x0000000113ea24b9 __CFMachPortPerform + 169
	15  CoreFoundation                      0x0000000113ea23f9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	16  CoreFoundation                      0x0000000113ea2361 __CFRunLoopDoSource1 + 465
	17  CoreFoundation                      0x0000000113e99f64 __CFRunLoopRun + 2532
	18  CoreFoundation                      0x0000000113e9930b CFRunLoopRunSpecific + 635
	19  GraphicsServices                    0x00000001195b8a73 GSEventRunModal + 62
	20  UIKit                               0x000000010dec3057 UIApplicationMain + 159
	21  ???                                 0x000000013479bfd7 0x0 + 5175361495
	22  ???                                 0x000000013479bd33 0x0 + 5175360819

I have three pages each containing your CarouselView, this only happend on one page until now when I add the last page (Page 4, Index 3), my output:

2018-08-10 17:31:26.056 PathfinderMobileiOS[12692:5208781] ChildViewControllers count = 1
2018-08-10 17:31:26.104 PathfinderMobileiOS[12692:5208781] ChildViewControllers count = 1
2018-08-10 17:31:27.290 PathfinderMobileiOS[12692:5208781] ChildViewControllers count = 2
2018-08-10 17:31:27.739 PathfinderMobileiOS[12692:5208781] ChildViewControllers count = 3
2018-08-10 17:31:29.235 PathfinderMobileiOS[12692:5208781] *** Assertion failure in -[_UIQueuingScrollView _replaceViews:updatingContents:adjustContentInsets:animated:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3698.54.4/_UIQueuingScrollView.m:395

**Comment by AndreiMisiukevich** [comment]
Hi, could you show me your xaml/csharp ?

**Comment by AndreiMisiukevich** [comment]
It seems like Xamarin
It's native crash otherwise CardsView is almost fully cross platform..
Also tell me please your Xamarin Forms version

**Comment by hameedibrahim** [comment]
How to get scroll direction??

**Comment by AndreiMisiukevich** [comment]
@hameedibrahim what exactly do you mean?

**Comment by hameedibrahim** [comment]
I want to get right and left scroll direction listner of carousel view

**Comment by AndreiMisiukevich** [comment]
@hameedibrahim what do you try to achieve?)
Could you describe an example?

**Comment by hameedibrahim** [comment]
In my code If I hit the button first time it will get first two item from sqlite db and it will be store  in the list. and first time list count will be 2 and i will set the list to the 
                      **carousel.ItemsSource = list;**	
If I am swiping to right direction i will clear the list and I will fetch the items from sqlite db and now it will be store in the list. and now the list count will be 3. and now I will set the list to the carousel.ItemsSource.
	
For this scenario I want to get left and right direction.so please help how to get the scroll direction.

**Comment by AndreiMisiukevich** [comment]
Check ItemAppearing event..
But if you have only one element at your CardsView, you can't swipe, because there are no more element.
As you have 2 items and try to swipe right, nothing will happen..
Do I understand you correctly? You want always to have ability to handle swipe, right?

**Comment by AndreiMisiukevich** [comment]
@hameedibrahim Ok, you may use ItemAppearing event

**Comment by AndreiMisiukevich** [comment]
@shoeIT sample please

**Comment by AndreiMisiukevich** [comment]
https://github.com/ermalkaleci/CarbonKit/issues/177

it seems, you calling something not it UI thread.
Probably, you update ObservableCollection ?

btw, the same issue had alexrainman carouselView (check link below)  https://github.com/alexrainman/CarouselView/issues/226

**Comment by shoeIT** [comment]
"Probably, you update ObservableCollection ?"

jep that's possible I try this...unfortunately its not easy to reproduce. Thanks

**Comment by alexmartinezm** [comment]
Thanks to this issue I have solved a big crash in GoogleAds plugin implementation. Thank you so much!

**Comment by shoeIT** [comment]
The issue hasnot occured anymore over the last month, I think it works right now

**Comment by AndreiMisiukevich** [comment]
@shoeIT thanks a lot for update :)
