### ISSUE TITLE
condition never true, because of wrong comparison

### ISSUE THREAD

**Issue by shoeIT** [AndreiMisiukevich/CardView#82]
that's the line I'm talking about:
https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs#L1226
 if (ItemsSource[i] == CurrentView.BindingContext)

In my case the BindingContext of a view is the ViewModel since I'm using MVVM and therefore the condition is never true and the selected index always 0.

I think this addition would help, it fixes my issues atm:

ItemsSource[i] == CurrentView.BindingContext || ItemsSource[i] == CurrentView

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/issues/81

btw, i think, i will remove ItemTapped event.. )
