### ISSUE TITLE
IsPanInteractionEnabled doesn't work

### ISSUE THREAD

**Issue by LeoJHarris** [AndreiMisiukevich/CardView#83]
I just updated the nuget package and when I launch my page with the CardView in it with the field:

IsPanInteractionEnabled = false

I am getting an exception:

System.MissingMethodException: void PanCardView.CardsView.set_IsPanInteractionEnabled(bool)

I am trying to enable the pinching / zoom of images and read somewhere else this was the way to do it in the new version but am now getting an exception. When I remove IsPanInteractionEnabled the excetpion goes away.

Any ideas..?

**Comment by AndreiMisiukevich** [comment]
Hi Leo
I saw similar issue.. I suggest you to try next approach:
1) Remove nuget package fro
m all projects
2) Close Visual Studio
3) remove all bin / obj folders
4) Open VS again
5) install CardsView package again

If exception doesn't go away, try to set this property from code (if you used to work with xaml)

**Comment by LeoJHarris** [comment]
Ill give it a go now. As a side note the property was initially being set in from code.

**Comment by LeoJHarris** [comment]
sure.. one moment

**Comment by LeoJHarris** [comment]
[SampleCardView.zip](https://github.com/AndreiMisiukevich/CardView/files/2285429/SampleCardView.zip)

Sample attached

**Comment by LeoJHarris** [comment]
Okay so its one or the other cannot have both?

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris you may have both if set IsPanInteractionEnabled = false (and only if set this property to false).

But as I noticed, you haven't used them PanGestureRecognizer / PinchGestureRecognizer

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris did you decide to leave this plugin and switch to Alex's one? :)

**Comment by LeoJHarris** [comment]
@AndreiMisiukevich Hi sorry I forgot to get back on this, I actually ended up using this library: https://github.com/stormlion227/PhotoBrowser.Forms
