### ISSUE TITLE
Add ItemSwiped event and command

### ISSUE THREAD

**Issue by acidbless** [AndreiMisiukevich/CardView#84]
Hi,
First of all I want to say thank you for your nice library. I have a specific task to enable vertical swipe gestures on a currently visible card. For example top swipe will remove the current item from the items collection and the bottom swipe will perform a certain business task. So the question is how to implement this functionality?

**Comment by AndreiMisiukevich** [comment]
Hi, thanks for feedback

You can check platform-specific code and make vertical swipes regarding to existing implementation.
Or probably it can an enhancement for next release

**Comment by AndreiMisiukevich** [comment]
@acidbless what do you think?
Will you implement it by yourself? Or want to get "from box" ?

**Comment by acidbless** [comment]
I think it would be a good addition to your component. Thanks!

**Comment by acidbless** [comment]
Can you tell when it's ready? I'm currently trying to get workaround through implementation of IOrdinateHandlerParentView, but it looks like this option works only for iOS, CardsView.cs: 1385.

**Comment by AndreiMisiukevich** [comment]
@acidbless i will do it on weekend, i think

**Comment by AndreiMisiukevich** [comment]
iOS: https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView.iOS/CardsViewRenderer.cs#L24-L31

Need add Up and Down gestures

Android: https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView.Droid/CardsViewRenderer.cs#L188-L204

Handle vertical swipes as well I've already implemented it..

**Comment by AndreiMisiukevich** [comment]
Hi @acidbless 
Do you want to test pre-release package?

**Comment by AndreiMisiukevich** [comment]
1.6.0 version

**Comment by AndreiMisiukevich** [comment]
ItemSwiped and ItemSwipedCommand
