### ISSUE TITLE
Vertical scroll doesn't work properly on iOS

### ISSUE THREAD

**Issue by ernestoyaquello** [AndreiMisiukevich/CardView#85]
Hi, I am using the control `CarouselView` (version 1.5.5) in a Xamarin Forms app this way:

```xml
<cvc:ParentScrollView
    HorizontalOptions="FillAndExpand"
    VerticalOptions="FillAndExpand"
    Orientation="Vertical">
    <cv:CarouselView
        IsCyclical="false"
        SelectedIndex="{Binding CarouselPagePosition}"
        Items="{Binding CarouselPages}">
        <cv:CarouselView.ItemTemplate>
            <DataTemplate>
                <ScrollView
                    HorizontalOptions="FillAndExpand"
                    VerticalOptions="FillAndExpand">
                    <VerticalStackLayoutWithStuff />
                </ScrollView>
            </DataTemplate>
        </cv:CarouselView.ItemTemplate>
    </cv:CarouselView>
</cvc:ParentScrollView>
```

This works fine on Android, but the vertical scrolling doesn't seem to work properly on iOS (I can scroll up and down, but it is very hard and wonky because the view stops scrolling as soon as I put my finger up). Interestingly enough, it seems to scroll perfectly when using two fingers.

Is there any known solution to this problem?

Thanks in advance!

**Comment by AndreiMisiukevich** [comment]
Hi @ernestoyaquello 
Only one workaround
Set **IsPanInteractionEnabled** to **False**

In this case you will lose possibility to pan cards, but you will preserve possibility to swipe them and ScrollView, i hope, will work well.

**Comment by ernestoyaquello** [comment]
Hi @AndreiMisiukevich, thanks for the response. Would it be possible to pan cards while also having vertical scrolling working properly on iOS? I need the ability to pan cards...

**Comment by AndreiMisiukevich** [comment]
@ernestoyaquello unfortunately, no. I didn't find a solution, how to handle this case.
if you know, i will appreciate you suggestions PR's.

**Comment by ernestoyaquello** [comment]
I will take a look. Thanks for the quick response anyway!

**Comment by ernestoyaquello** [comment]
@AndreiMisiukevich I removed the outer `ParentScrollView`, implemented a normal `ScrollView` as the parent of my carousel item template view... and now everything seems to be working fine on both platforms.

**Comment by AndreiMisiukevich** [comment]
Thanks for your investigation.
That's fine to read , but it is a little bit strange.. what version of Xamarin Forms do you use?

**Comment by ernestoyaquello** [comment]
@AndreiMisiukevich My Xamarin Forms version is `2.5.0.91635`. I forgot to mention that I updated the plugin to the version `1.5.9`, but the vertical scroll still didn't work properly until I changed the layout.

**Comment by AndreiMisiukevich** [comment]
@ernestoyaquello so, regular ScrollView is fine for both platforms?

```xml
<ScrollView>
    <cv:CarouselView
     ...
    </cv:CarouselView>
<ScrollView>
```
?

**Comment by ernestoyaquello** [comment]
@AndreiMisiukevich No, sorry if I didn't explain it correctly. I wanted to be able to swipe between pages horizontally while also being able to scroll vertically inside each one of the pages. My final layout, which seems to be working fine on both platforms, looks like this:

```xml
<cv:CarouselView
    IsCyclical="false"
    SelectedIndex="{Binding CarouselPagePosition}"
    Items="{Binding CarouselPages}">
    <cv:CarouselView.ItemTemplate>
        <DataTemplate>
            <ContentView>
                <ScrollView>
                    <VerticalStackLayoutWithStuff />
                </ScrollView>
            </ContentView>
        </DataTemplate>
    </cv:CarouselView.ItemTemplate>
</cv:CarouselView>
```

As you can see, I got rid of the `ParentScrollView`, and so far I haven't seen any errors.

I hope this can be of help. Cheers!
