### ISSUE TITLE
IndicatorsControl overflow

### ISSUE THREAD

**Issue by ronaldosena** [AndreiMisiukevich/CardView#86]
First, thanks for the tool!

I want to put the Indicators Control between the cards and the colored button group, but when I try to TranslateY it is being cut by the end of the CarouselView.

![screenshot_20180814-172527](https://user-images.githubusercontent.com/23301665/44116955-4bd1c988-9fe8-11e8-8f9b-42065810b52c.png)

I tried making the CarouselView bigger and the Card smaller, so there would be a spare space to the Controls, but this way I was not able to set the sizes according to the screen size (I use Grids to achieve it right now).

Any help?

Thanks!

**Comment by eamreyes** [comment]
I to need to control the location of the IndicatorsControl. I defined an IndicatorsControl outside of the Carousel/Cardview which allowed me to move it wherever I needed to in a layout. Then the IndicatorsControl properties need to be bound to the Carousel/CardView.

```
	<panIndicators:IndicatorsControl 
                UseParentAsBindingContext="False"
                HorizontalOptions="Center"
                BindingContext="{x:Reference PanCardView}"
                Margin="5"
                SelectedIndex="{Binding SelectedIndex}"
                ItemsCount="{Binding ItemsCount}"
                IndicatorsContexts="{Binding ItemsSource}"
                IsUserInteractionRunning="{Binding IsUserInteractionRunning}"
                IsAutoInteractionRunning="{Binding IsAutoInteractionRunning}"/>
```

Its important to assign false to the UseParentAsBindingContext property. The current implementation of the control assumes you're using it as a child of Carousel/Cardview and then sets the BindingContext to the parent.

**Comment by AndreiMisiukevich** [comment]
Hi all
@ronaldosena yes, as @eamreyes said, it's possible.

But as I remember, you needn't have to bind every property, next lines would be enough:

```xml
<StackLayout>
    <cards:CarouselView x:Name="Carousel" />
    <panIndicators:IndicatorsControl 
                UseParentAsBindingContext="False"
                BindingContext="{x:Reference PanCardView}"
</StackLayout>
```

Because all bindings are defined at constructor. Indeed, as @eamreyes noted, you should set **UseParentAsBindingContext** to **False** and bind indicators bindingContext to your Carousel/Cards control.
