### ISSUE TITLE
System.InvalidOperationException: Cannot change ObservableCollection during a CollectionChanged event.

### ISSUE THREAD

**Issue by rkotulan** [AndreiMisiukevich/CardView#88]
We occasionally experience this error.
Android, MvvmCross.

CardsView.AddChild (Xamarin.Forms.View topView, Xamarin.Forms.View[] views)
System.InvalidOperationException: Cannot change ObservableCollection during a CollectionChanged event.
ObservableCollection`1[T].CheckReentrancy ()
ObservableCollection`1[T].InsertItem (System.Int32 index, T item)
Collection`1[T].Insert (System.Int32 index, T item)
ObservableWrapper`2[TTrack,TRestrict].Insert (System.Int32 index, TRestrict item)
CardsView.AddChild (Xamarin.Forms.View topView, Xamarin.Forms.View[] views)
CardsView.GetViews (PanCardView.Enums.AnimationDirection animationDirection, PanCardView.Processors.ICardProcessor processor, System.Int32[] indeces)
CardsView.SetupNextView ()
CardsView.SetupBackViews ()
CardsView+<SetCurrentView>d__202.MoveNext ()
ExceptionDispatchInfo.Throw ()

Unfortunately we do not have repro sample.

**Comment by AndreiMisiukevich** [comment]
Hi and thanks for feedback
Was your changing any collection , when crash appeared ?

Could you please provide repro sample latter?

**Comment by rkotulan** [comment]
I have quite simple setup

View with CachedImage
```
 <panCardView:CarouselView
                ItemsSource="{Binding Items"
                SelectedIndex="{Binding CurrentIndex"
                HeightRequest="{Binding CarouselHeight">
                <panCardView:CarouselView.ItemTemplate>
                    <DataTemplate>
                        <StackLayout BackgroundColor="White" Margin="0" Padding="0">
                            <forms:CachedImage Source="{Binding }" Margin="0" />
                        </StackLayout>
                    </DataTemplate>
                </panCardView:CarouselView.ItemTemplate>

                <controls1:IndicatorsControl SelectedIndicatorStyle="{StaticResource SelectedIndicatorItemStyle}" UnselectedIndicatorStyle="{StaticResource UnSelectedIndicatorItemStyle}" />
 </panCardView:CarouselView>
```

ViewModel
```
public override async Task Initialize()
{
            await base.Initialize();
            
            if (authenticationService.IsUserAuthenticated())
            {
                var userInfo = await authenticationService.GetAuthenticatedUser();
                IsVip = userInfo.IsVip;
            }

            if (IsVip)
            {
                TescoDoubleCardItems = new ObservableCollection<string>
                                           {
                                               "VIP_TMCZ_KUPON.png",
                                               "VIP_PECIVO.png",
                                               "VIP_OVOCE.png",
                                               "VIP_MLEKO.png",
                                               "VIP_MASO.png",
                                               "VIP_DROGERIE.png"
                                           };
            }
            else
            {
                TescoDoubleCardItems = new ObservableCollection<string> { "VIP_TMCZ_KUPON.png", };
            }
}
```

I will try to prepare repro sample later, but problem is that app crash occasionally.

**Comment by AndreiMisiukevich** [comment]
Ok, i'm waiting your sample =) let's figure out

**Comment by AndreiMisiukevich** [comment]
Also I suggest you to try set your items in main thread

**Comment by rkotulan** [comment]
It seems to be ok. Thanks.
