### ISSUE TITLE
Carousel with virtual pages

### ISSUE THREAD

**Issue by deakjahn** [AndreiMisiukevich/CardView#89]
It's more like a question but I wonder if, judging how the carousel works internally, you could suggest something. Let's suppose a carousel of virtual pages. Virtual in the sense that I'm unable to give you a list up front containing all items. However, at any time, I can provide the current page and I can answer whether there is a previous and a next page. And if there is, I can provide that previous or next page any time. But I don't know how many pages there are and I don't want (or can't) fill a complete ItemsSource with them at the beginning. Do you think something like that could be accommodated somehow? And if so, is this something you should consider worth doing?

**Comment by AndreiMisiukevich** [comment]
Hi) haha, I removed this feature in one of the past releases )
Because, thought, that nobody needs it.

Ok, you may create observable collection of your binding contexts (3 items)
And after every swipe remove redundant item and add new one

**Comment by deakjahn** [comment]
Now, that's a nice idea. I'll try that but I have a few other hurdles now before that. XF is so enamored of MVVM that it's awfully hard to do things that are not as clear cut as the MVVM crowd thinks... :-)

**Comment by AndreiMisiukevich** [comment]
Let me know if you have any troubles
