### ISSUE TITLE
[Android] Don't scroll item in list view

### ISSUE THREAD

**Issue by morhung** [AndreiMisiukevich/CardView#90]
Hy,

I use the CarouselView with DataTemplate is listview. On iOS, it 's working. But on Android, it not scroll the item in listview?

**Comment by AndreiMisiukevich** [comment]
Hi
Show your xaml please

**Comment by morhung** [comment]
Hi bro,
`    <cards:CarouselView
        VerticalOptions="FillAndExpand"
        HorizontalOptions="FillAndExpand"
        ItemsSource="{Binding ItemMenuLists}">
        <cards:CarouselView.ItemTemplate>
            <DataTemplate>
                <ListView
                    ItemsSource="{Binding TestList}">
                    <ListView.ItemTemplate>
                        <DataTemplate>
                            <ViewCell>
                                <StackLayout>
                                    <Image
                                        Source="{Binding ImgUrl}" />
                                    <Label
                                        Text="{Binding Intro}" />
                                </StackLayout>
                            </ViewCell>
                        </DataTemplate>
                    </ListView.ItemTemplate>
                </ListView>
            </DataTemplate>
        </cards:CarouselView.ItemTemplate>
    </cards:CarouselView>`

**Comment by morhung** [comment]
Yes..set VerticalSwipeThresholdDistance = 1000...It 's working.. Tks bro :)

**Comment by AndreiMisiukevich** [comment]
@morhung if you like this plugin, you can star it)
