### ISSUE TITLE
CarouselView affecting ScrollView

### ISSUE THREAD

**Issue by stevenchingch** [AndreiMisiukevich/CardView#94]
Hi AndreiMisuikevich,

I encountered an issue using CardView (CarouselView), explained below. 
I am using CarouselView at the top of my page.
The CarouselView is within a ScrollView, capable of scrolling up/down.

When I'm at the top of the page, scrolling left/right seems to interfere with ScrollView wanting to scroll up and down. How can I make it where once I start swiping left/right on the CarouselView, the scrollview immediately disables itself and prevent itself from scrolling up/down? Or a way to keep the user's touch input on the CarouselView.

In more simple terms, I do not want my scroll view to take over the swipe gesture input away from CarouselView.

I tried using CarouselView by AlexRainman. I was able to workaround this issue by using the Scrolled event and disabling my scrollview and pull to refresh layout. And on PositionSelected, I enable back the pull to refresh layout and my scrolling. I'm unable to do that with CardView (CarouselView). 

I'm also having some issues where putting a CachedImageRenderer in the CarouselView and switching between tabs using BottomBarPage is causing the CachedImageRenderer within CarouselView to resize by itself. 

Thank you so much for your help. Hopefully you have some suggestions for me or anything I might have missed.

**Comment by AndreiMisiukevich** [comment]
Hi
Have you read https://github.com/AndreiMisiukevich/CardView#workarounds yet?)

**Comment by stevenchingch** [comment]
Hi Andrei, thank you so much for your response. Yes. I’ve read and added the necessary workarounds. Even with that, it doesn’t fix the issue I’m experiencing. 

I also do have pull to refresh layout too (sorry forgot to mention this, and I think this is the reason) and it is triggering with or without the workarounds in place. Any idea if I can add an onscrolled event so that I can disable the pull to refresh layout when scrolling the carousel view? 

Thank you once again!

**Comment by AndreiMisiukevich** [comment]
Sorry, i really don't know
You can try to add IsPanInteractionEnabled = false.
