### ISSUE TITLE
Card Ghosting effect

### ISSUE THREAD

**Issue by nawidy** [AndreiMisiukevich/CardView#97]
Hi @AndreiMisiukevich,

I'm using the carousel view controller and notice that sometimes, there's an ghosting effect with my swipes. I'm not sure if this is for any reason because of padding within my carousel view or if this could be something else? I think I was able to reproduce this also if cyclical mode is turned off. Not sure if this could be for swiping too fast, or from the edge or something. If you've seen this before, any suggestions are greatly appreciated.
Thanks,
-Nawid

**Comment by AndreiMisiukevich** [comment]
@nawidy Hi
Could you provide a video with reproduction? 
Perhaps, this effect occurs, because you doesn't use ItemTemplate and pass view to ItemsSource directly

**Comment by nawidy** [comment]
Hi @AndreiMisiukevich,
Thanks I will look into creating a repro. I've created sample code for the other ticket and trying to reproduce it there as well. I think I also noticed this happen when cyclical mode is turned off

**Comment by nawidy** [comment]
I have not reproduced this recently, it seems to be a result of doing a quick swipe. If I don't reproduce it soon, I'll go ahead and close this out

**Comment by nawidy** [comment]
I have not reproduced this recently, if I do. I'll reopen the ticket/let you know what I did.
